import { declarativeRestConnector } from './declarative-rest.js'

const appointmentId = { type: 'integer', minimum: 1, description: 'Acuity appointment id.' } as const

export const acuitySchedulingConnector = declarativeRestConnector({
  kind: 'acuity-scheduling',
  displayName: 'Acuity Scheduling',
  description:
    'Read availability and manage Acuity Scheduling appointments, calendars, appointment types, and clients.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://acuityscheduling.com/oauth2/authorize',
    tokenUrl: 'https://acuityscheduling.com/oauth2/token',
    scopes: ['api-v1'],
    clientIdEnv: 'ACUITY_OAUTH_CLIENT_ID',
    clientSecretEnv: 'ACUITY_OAUTH_CLIENT_SECRET',
  },
  category: 'calendar',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://acuityscheduling.com/api/v1',
  credentialPlacement: { kind: 'bearer' },
  test: { method: 'GET', path: '/me' },
  capabilities: [
    {
      name: 'appointments.list',
      class: 'read',
      description: 'List appointments with date, calendar, type, client, and cancellation filters.',
      parameters: {
        type: 'object',
        properties: {
          minDate: { type: 'string', description: 'YYYY-MM-DD lower date bound.' },
          maxDate: { type: 'string', description: 'YYYY-MM-DD upper date bound.' },
          calendarID: { type: 'integer' },
          appointmentTypeID: { type: 'integer' },
          canceled: { type: 'boolean' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          phone: { type: 'string' },
          email: { type: 'string' },
          addonID: { type: 'integer' },
          excludeForms: { type: 'boolean' },
          max: { type: 'integer', minimum: 1, maximum: 100 },
        },
      },
      request: {
        method: 'GET',
        path: '/appointments',
        query: {
          minDate: '{minDate}', maxDate: '{maxDate}', calendarID: '{calendarID}',
          appointmentTypeID: '{appointmentTypeID}', canceled: '{canceled}',
          firstName: '{firstName}', lastName: '{lastName}', phone: '{phone}',
          email: '{email}', addonID: '{addonID}', excludeForms: '{excludeForms}', max: '{max}',
        },
      },
    },
    {
      name: 'appointments.get',
      class: 'read',
      description: 'Read one appointment by id.',
      parameters: {
        type: 'object',
        properties: { appointmentId },
        required: ['appointmentId'],
      },
      request: { method: 'GET', path: '/appointments/{appointmentId}' },
    },
    {
      name: 'appointments.create',
      class: 'mutation',
      description: 'Book a new appointment for a client.',
      parameters: {
        type: 'object',
        properties: {
          appointmentTypeID: { type: 'integer' },
          datetime: { type: 'string', description: 'Provider-formatted appointment start time.' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          calendarID: { type: 'integer' },
          phone: { type: 'string' },
          timezone: { type: 'string' },
          certificate: { type: 'string' },
          notes: { type: 'string' },
          fields: { type: 'array', items: { type: 'object' } },
          addonIDs: { type: 'array', items: { type: 'integer' } },
          labels: { type: 'array', maxItems: 1, items: { type: 'object' } },
          smsOptIn: { type: 'boolean' },
          noEmail: { type: 'boolean' },
          admin: { type: 'boolean', description: 'Book as an administrator, bypassing availability checks.' },
        },
        required: ['appointmentTypeID', 'datetime', 'firstName', 'lastName', 'email'],
      },
      request: {
        method: 'POST',
        path: '/appointments',
        query: { admin: '{admin}', noEmail: '{noEmail}' },
        body: {
          appointmentTypeID: '{appointmentTypeID}',
          datetime: '{datetime}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          calendarID: '{calendarID}',
          phone: '{phone}',
          timezone: '{timezone}',
          certificate: '{certificate}',
          notes: '{notes}',
          fields: '{fields}',
          addonIDs: '{addonIDs}',
          labels: '{labels}',
          smsOptIn: '{smsOptIn}',
        },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'appointments.reschedule',
      class: 'mutation',
      description: 'Move an appointment to a new date, time, or calendar.',
      parameters: {
        type: 'object',
        properties: {
          appointmentId,
          datetime: { type: 'string' },
          calendarID: { type: 'integer' },
          timezone: { type: 'string' },
          admin: { type: 'boolean', description: 'Reschedule as an administrator.' },
          noEmail: { type: 'boolean', description: 'Suppress rescheduling email and SMS.' },
        },
        required: ['appointmentId', 'datetime'],
      },
      request: {
        method: 'PUT',
        path: '/appointments/{appointmentId}/reschedule',
        query: { admin: '{admin}', noEmail: '{noEmail}' },
        body: { datetime: '{datetime}', calendarID: '{calendarID}', timezone: '{timezone}' },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'appointments.cancel',
      class: 'mutation',
      description: 'Cancel an appointment and optionally mark it as a no-show.',
      parameters: {
        type: 'object',
        properties: {
          appointmentId,
          cancelNote: { type: 'string', description: 'Message sent with cancellation notifications.' },
          noShow: { type: 'boolean' },
          admin: { type: 'boolean', description: 'Cancel as an administrator.' },
          noEmail: { type: 'boolean', description: 'Suppress cancellation email and SMS.' },
        },
        required: ['appointmentId'],
      },
      request: {
        method: 'PUT',
        path: '/appointments/{appointmentId}/cancel',
        query: { admin: '{admin}', noEmail: '{noEmail}' },
        body: { cancelNote: '{cancelNote}', noShow: '{noShow}' },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'appointment-types.list',
      class: 'read',
      description: 'List appointment types and their durations, prices, and availability settings.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/appointment-types' },
    },
    {
      name: 'calendars.list',
      class: 'read',
      description: 'List booking calendars and their owners/locations.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/calendars' },
    },
    {
      name: 'availability.dates',
      class: 'read',
      description: 'List dates with availability for an appointment type in a month.',
      parameters: {
        type: 'object',
        properties: {
          month: { type: 'string', description: 'Month in YYYY-MM format.' },
          appointmentTypeID: { type: 'integer' },
          calendarID: { type: 'integer' },
          timezone: { type: 'string' },
        },
        required: ['month', 'appointmentTypeID'],
      },
      request: {
        method: 'GET',
        path: '/availability/dates',
        query: {
          month: '{month}', appointmentTypeID: '{appointmentTypeID}',
          calendarID: '{calendarID}', timezone: '{timezone}',
        },
      },
    },
    {
      name: 'availability.times',
      class: 'read',
      description: 'List bookable times on one date for an appointment type.',
      parameters: {
        type: 'object',
        properties: {
          date: { type: 'string', description: 'Date in YYYY-MM-DD format.' },
          appointmentTypeID: { type: 'integer' },
          calendarID: { type: 'integer' },
          timezone: { type: 'string' },
          ignoreAppointment: { type: 'integer' },
        },
        required: ['date', 'appointmentTypeID'],
      },
      request: {
        method: 'GET',
        path: '/availability/times',
        query: {
          date: '{date}', appointmentTypeID: '{appointmentTypeID}', calendarID: '{calendarID}',
          timezone: '{timezone}', ignoreAppointment: '{ignoreAppointment}',
        },
      },
    },
    {
      name: 'clients.list',
      class: 'read',
      description: 'List clients with optional search and pagination.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'string' },
          offset: { type: 'integer', minimum: 0 },
          max: { type: 'integer', minimum: 1, maximum: 100 },
        },
      },
      request: {
        method: 'GET',
        path: '/clients',
        query: { search: '{search}', offset: '{offset}', max: '{max}' },
      },
    },
    {
      name: 'blocks.list',
      class: 'read',
      description: 'List blocked-off calendar time with optional date/calendar filters.',
      parameters: {
        type: 'object',
        properties: {
          minDate: { type: 'string' },
          maxDate: { type: 'string' },
          calendarID: { type: 'integer' },
        },
      },
      request: {
        method: 'GET',
        path: '/blocks',
        query: { minDate: '{minDate}', maxDate: '{maxDate}', calendarID: '{calendarID}' },
      },
    },
  ],
})
