import { declarativeRestConnector } from './declarative-rest.js'

const awsCredentialHint =
  'AWS credentials as JSON: {"accessKeyId":"AKIA…","secretAccessKey":"…","region":"us-east-1"}. Optional "sessionToken" and "endpoint" support temporary credentials and local AWS-compatible endpoints.'

export const amazonLambdaConnector = declarativeRestConnector({
  kind: 'aws-lambda',
  displayName: 'AWS Lambda',
  description:
    'Inspect, invoke, create, update, version, alias, and delete AWS Lambda functions.',
  auth: { kind: 'api-key', hint: awsCredentialHint },
  category: 'other',
  // Lambda invocation is at-least-once and can cause arbitrary downstream
  // effects. The connection cannot promise authoritative mutation replay.
  defaultConsistencyModel: 'advisory',
  credentialPlacement: { kind: 'aws-sigv4', service: 'lambda' },
  baseUrl: {
    metadataKey: 'endpoint',
    fallback: 'https://lambda.{region}.amazonaws.com',
  },
  test: {
    method: 'GET',
    path: '/2015-03-31/functions',
    query: { MaxItems: '1' },
  },
  capabilities: [
    {
      name: 'functions.list',
      class: 'read',
      description: 'List Lambda functions in the configured AWS region.',
      parameters: {
        type: 'object',
        properties: {
          marker: { type: 'string', description: 'Pagination marker.' },
          maxItems: { type: 'integer', description: 'Maximum functions to return (1-50).' },
          functionVersion: {
            type: 'string',
            enum: ['ALL'],
            description: 'Include published versions when set to ALL.',
          },
          masterRegion: { type: 'string', description: 'Filter Lambda@Edge replicas by region.' },
        },
      },
      request: {
        method: 'GET',
        path: '/2015-03-31/functions',
        query: {
          Marker: '{marker}',
          MaxItems: '{maxItems}',
          FunctionVersion: '{functionVersion}',
          MasterRegion: '{masterRegion}',
        },
      },
    },
    {
      name: 'functions.get',
      class: 'read',
      description: 'Get one function configuration and its temporary deployment-package URL.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string', description: 'Function name or ARN.' },
          qualifier: { type: 'string', description: 'Version number or alias.' },
        },
        required: ['functionName'],
      },
      request: {
        method: 'GET',
        path: '/2015-03-31/functions/{functionName}',
        query: { Qualifier: '{qualifier}' },
      },
    },
    {
      name: 'aliases.list',
      class: 'read',
      description: 'List aliases for a Lambda function.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          functionVersion: { type: 'string' },
          marker: { type: 'string' },
          maxItems: { type: 'integer' },
        },
        required: ['functionName'],
      },
      request: {
        method: 'GET',
        path: '/2015-03-31/functions/{functionName}/aliases',
        query: {
          FunctionVersion: '{functionVersion}',
          Marker: '{marker}',
          MaxItems: '{maxItems}',
        },
      },
    },
    {
      name: 'functions.invoke',
      class: 'mutation',
      description:
        'Invoke a Lambda function synchronously, asynchronously, or as a dry-run permission check.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string', description: 'Function name or ARN.' },
          qualifier: { type: 'string', description: 'Version number or alias.' },
          invocationType: {
            type: 'string',
            enum: ['RequestResponse', 'Event', 'DryRun'],
          },
          logType: { type: 'string', enum: ['None', 'Tail'] },
          clientContext: {
            type: 'string',
            description: 'Base64-encoded client context for synchronous invocation.',
          },
          payload: {
            description: 'JSON payload passed directly to the function.',
          },
        },
        required: ['functionName', 'payload'],
      },
      request: {
        method: 'POST',
        path: '/2015-03-31/functions/{functionName}/invocations',
        query: { Qualifier: '{qualifier}' },
        headers: {
          'X-Amz-Invocation-Type': '{invocationType}',
          'X-Amz-Log-Type': '{logType}',
          'X-Amz-Client-Context': '{clientContext}',
        },
        body: '{payload}',
      },
      cas: 'none',
      externalEffect: true,
    },
    {
      name: 'functions.create',
      class: 'mutation',
      description: 'Create a Lambda function from an S3 object, inline zip, or ECR image.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          role: { type: 'string', description: 'Execution-role ARN.' },
          code: {
            type: 'object',
            description: 'AWS FunctionCode shape: S3Bucket/S3Key/S3ObjectVersion, ZipFile, or ImageUri.',
          },
          runtime: { type: 'string' },
          handler: { type: 'string' },
          description: { type: 'string' },
          timeout: { type: 'integer' },
          memorySize: { type: 'integer' },
          publish: { type: 'boolean' },
          packageType: { type: 'string', enum: ['Zip', 'Image'] },
          architectures: { type: 'array', items: { type: 'string' } },
          environment: { type: 'object', description: 'AWS Environment shape.' },
          vpcConfig: { type: 'object', description: 'AWS VpcConfig shape.' },
          layers: { type: 'array', items: { type: 'string' } },
          tags: { type: 'object' },
          ephemeralStorage: { type: 'object' },
          loggingConfig: { type: 'object' },
        },
        required: ['functionName', 'role', 'code'],
      },
      request: {
        method: 'POST',
        path: '/2015-03-31/functions',
        body: {
          FunctionName: '{functionName}',
          Role: '{role}',
          Code: '{code}',
          Runtime: '{runtime}',
          Handler: '{handler}',
          Description: '{description}',
          Timeout: '{timeout}',
          MemorySize: '{memorySize}',
          Publish: '{publish}',
          PackageType: '{packageType}',
          Architectures: '{architectures}',
          Environment: '{environment}',
          VpcConfig: '{vpcConfig}',
          Layers: '{layers}',
          Tags: '{tags}',
          EphemeralStorage: '{ephemeralStorage}',
          LoggingConfig: '{loggingConfig}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'functions.code.update',
      class: 'mutation',
      description: 'Replace the unpublished code for a Lambda function.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          s3Bucket: { type: 'string' },
          s3Key: { type: 'string' },
          s3ObjectVersion: { type: 'string' },
          imageUri: { type: 'string' },
          zipFile: { type: 'string', description: 'Base64-encoded zip bytes.' },
          publish: { type: 'boolean' },
          dryRun: { type: 'boolean' },
          revisionId: { type: 'string' },
          architectures: { type: 'array', items: { type: 'string' } },
        },
        required: ['functionName'],
      },
      request: {
        method: 'PUT',
        path: '/2015-03-31/functions/{functionName}/code',
        body: {
          S3Bucket: '{s3Bucket}',
          S3Key: '{s3Key}',
          S3ObjectVersion: '{s3ObjectVersion}',
          ImageUri: '{imageUri}',
          ZipFile: '{zipFile}',
          Publish: '{publish}',
          DryRun: '{dryRun}',
          RevisionId: '{revisionId}',
          Architectures: '{architectures}',
        },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'functions.configuration.update',
      class: 'mutation',
      description: 'Update the unpublished configuration for a Lambda function.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          role: { type: 'string' },
          handler: { type: 'string' },
          description: { type: 'string' },
          timeout: { type: 'integer' },
          memorySize: { type: 'integer' },
          runtime: { type: 'string' },
          environment: { type: 'object' },
          layers: { type: 'array', items: { type: 'string' } },
          vpcConfig: { type: 'object' },
          revisionId: { type: 'string' },
          ephemeralStorage: { type: 'object' },
          loggingConfig: { type: 'object' },
        },
        required: ['functionName'],
      },
      request: {
        method: 'PUT',
        path: '/2015-03-31/functions/{functionName}/configuration',
        body: {
          Role: '{role}',
          Handler: '{handler}',
          Description: '{description}',
          Timeout: '{timeout}',
          MemorySize: '{memorySize}',
          Runtime: '{runtime}',
          Environment: '{environment}',
          Layers: '{layers}',
          VpcConfig: '{vpcConfig}',
          RevisionId: '{revisionId}',
          EphemeralStorage: '{ephemeralStorage}',
          LoggingConfig: '{loggingConfig}',
        },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'versions.publish',
      class: 'mutation',
      description: 'Publish an immutable version from the current function code and configuration.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          codeSha256: { type: 'string' },
          description: { type: 'string' },
          revisionId: { type: 'string' },
        },
        required: ['functionName'],
      },
      request: {
        method: 'POST',
        path: '/2015-03-31/functions/{functionName}/versions',
        body: {
          CodeSha256: '{codeSha256}',
          Description: '{description}',
          RevisionId: '{revisionId}',
        },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'aliases.create',
      class: 'mutation',
      description: 'Create an alias that points to a published function version.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          name: { type: 'string' },
          functionVersion: { type: 'string' },
          description: { type: 'string' },
          routingConfig: { type: 'object' },
        },
        required: ['functionName', 'name', 'functionVersion'],
      },
      request: {
        method: 'POST',
        path: '/2015-03-31/functions/{functionName}/aliases',
        body: {
          Name: '{name}',
          FunctionVersion: '{functionVersion}',
          Description: '{description}',
          RoutingConfig: '{routingConfig}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'aliases.update',
      class: 'mutation',
      description: 'Move or reconfigure an existing function alias.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          name: { type: 'string' },
          functionVersion: { type: 'string' },
          description: { type: 'string' },
          routingConfig: { type: 'object' },
          revisionId: { type: 'string' },
        },
        required: ['functionName', 'name'],
      },
      request: {
        method: 'PUT',
        path: '/2015-03-31/functions/{functionName}/aliases/{name}',
        body: {
          FunctionVersion: '{functionVersion}',
          Description: '{description}',
          RoutingConfig: '{routingConfig}',
          RevisionId: '{revisionId}',
        },
      },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'aliases.delete',
      class: 'mutation',
      description: 'Delete a function alias without deleting the function version.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          name: { type: 'string' },
        },
        required: ['functionName', 'name'],
      },
      request: {
        method: 'DELETE',
        path: '/2015-03-31/functions/{functionName}/aliases/{name}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'functions.delete',
      class: 'mutation',
      description: 'Permanently delete a Lambda function or one published version.',
      parameters: {
        type: 'object',
        properties: {
          functionName: { type: 'string' },
          qualifier: { type: 'string', description: 'Version to delete. Omit to delete all versions.' },
        },
        required: ['functionName'],
      },
      request: {
        method: 'DELETE',
        path: '/2015-03-31/functions/{functionName}',
        query: { Qualifier: '{qualifier}' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
