import { declarativeRestConnector } from './declarative-rest.js'

export const apitemplateIoConnector = declarativeRestConnector({
  kind: 'apitemplate-io',
  displayName: 'APITemplate.io',
  description:
    'Generate PDFs and images from APITemplate.io templates or raw HTML/URLs, list generated objects, and manage account artifacts.',
  auth: { kind: 'api-key', hint: 'APITemplate.io API key issued from the dashboard.' },
  category: 'storage',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://rest.apitemplate.io/v2',
  credentialPlacement: { kind: 'header', header: 'X-API-KEY' },
  test: { method: 'GET', path: '/account-information' },
  capabilities: [
    {
      name: 'account.get',
      class: 'read',
      description: 'Get APITemplate.io account information, including plan and usage counters.',
      parameters: {
        type: 'object',
        properties: {},
      },
      request: { method: 'GET', path: '/account-information' },
    },
    {
      name: 'objects.list',
      class: 'read',
      description:
        'List generated PDF/image objects, optionally filtered by template, transaction reference, or date range.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 300 },
          offset: { type: 'integer', minimum: 0 },
          templateId: { type: 'string' },
          transactionRef: { type: 'string' },
          dateFrom: { type: 'string', description: 'YYYY-MM-DD' },
          dateTo: { type: 'string', description: 'YYYY-MM-DD' },
        },
      },
      request: {
        method: 'GET',
        path: '/list-objects',
        query: {
          limit: '{limit}',
          offset: '{offset}',
          template_id: '{templateId}',
          transaction_ref: '{transactionRef}',
          date_from: '{dateFrom}',
          date_to: '{dateTo}',
        },
      },
    },
    {
      name: 'image.create',
      class: 'mutation',
      description:
        'Render an image from an APITemplate.io image template by template ID, supplying an overrides payload.',
      parameters: {
        type: 'object',
        properties: {
          templateId: { type: 'string' },
          data: {
            type: 'object',
            description:
              'Template overrides payload, e.g. { "overrides": [ { "name": "field", "text": "value" } ] }.',
          },
          meta: { type: 'string', description: 'External reference ID echoed back on the response.' },
        },
        required: ['templateId', 'data'],
      },
      request: {
        method: 'POST',
        path: '/create-image',
        query: { template_id: '{templateId}', meta: '{meta}' },
        body: '{data}',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'pdf.create',
      class: 'mutation',
      description:
        'Render a PDF from an APITemplate.io PDF template by template ID, supplying an overrides payload.',
      parameters: {
        type: 'object',
        properties: {
          templateId: { type: 'string' },
          data: {
            type: 'object',
            description: 'Template overrides payload consumed by the PDF template.',
          },
          expiration: {
            type: 'integer',
            minimum: 0,
            maximum: 10080,
            description: '0 = permanent, 1-10080 minutes (7 days max) otherwise.',
          },
          meta: { type: 'string' },
          generationDelay: { type: 'integer', description: 'Delay in milliseconds before PDF generation.' },
        },
        required: ['templateId', 'data'],
      },
      request: {
        method: 'POST',
        path: '/create-pdf',
        query: {
          template_id: '{templateId}',
          expiration: '{expiration}',
          meta: '{meta}',
          generation_delay: '{generationDelay}',
        },
        body: '{data}',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'pdf.createFromHtml',
      class: 'mutation',
      description:
        'Render a PDF from raw HTML (and optional CSS) without an APITemplate.io template, with full page layout controls.',
      parameters: {
        type: 'object',
        properties: {
          html: { type: 'string', description: 'HTML body to render.' },
          css: { type: 'string', description: 'Optional CSS applied to the HTML body.' },
          expiration: { type: 'integer', minimum: 0, maximum: 10080 },
          meta: { type: 'string' },
          pageSize: { type: 'string', description: 'e.g. A4, Letter, Legal.' },
          orientation: { type: 'string', enum: ['portrait', 'landscape'] },
          marginTop: { type: 'number' },
          marginBottom: { type: 'number' },
          marginLeft: { type: 'number' },
          marginRight: { type: 'number' },
          printBackground: { type: 'boolean' },
          displayHeaderFooter: { type: 'boolean' },
          customHeader: { type: 'string' },
          customFooter: { type: 'string' },
          headerFontSize: { type: 'string' },
          scale: { type: 'number', minimum: 0.1, maximum: 2.0 },
          waitForTimeout: { type: 'integer' },
        },
        required: ['html'],
      },
      request: {
        method: 'POST',
        path: '/create-pdf-from-html',
        query: {
          expiration: '{expiration}',
          meta: '{meta}',
          page_size: '{pageSize}',
          orientation: '{orientation}',
          margin_top: '{marginTop}',
          margin_bottom: '{marginBottom}',
          margin_left: '{marginLeft}',
          margin_right: '{marginRight}',
          print_background: '{printBackground}',
          display_header_footer: '{displayHeaderFooter}',
          custom_header: '{customHeader}',
          custom_footer: '{customFooter}',
          header_font_size: '{headerFontSize}',
          scale: '{scale}',
          wait_for_timeout: '{waitForTimeout}',
        },
        body: {
          body: '{html}',
          css: '{css}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'pdf.createFromUrl',
      class: 'mutation',
      description:
        'Render a PDF by loading a remote URL in a headless browser, with viewport, scroll, and selector controls.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', format: 'uri' },
          expiration: { type: 'integer', minimum: 0, maximum: 10080 },
          meta: { type: 'string' },
          pageSize: { type: 'string' },
          orientation: { type: 'string', enum: ['portrait', 'landscape'] },
          marginTop: { type: 'number' },
          marginBottom: { type: 'number' },
          marginLeft: { type: 'number' },
          marginRight: { type: 'number' },
          printBackground: { type: 'boolean' },
          scale: { type: 'number', minimum: 0.1, maximum: 2.0 },
          waitForTimeout: { type: 'integer' },
          waitForSelector: { type: 'string' },
          viewportWidth: { type: 'integer' },
          viewportHeight: { type: 'integer' },
          fullPage: { type: 'boolean' },
        },
        required: ['url'],
      },
      request: {
        method: 'POST',
        path: '/create-pdf-from-url',
        query: {
          url: '{url}',
          expiration: '{expiration}',
          meta: '{meta}',
          page_size: '{pageSize}',
          orientation: '{orientation}',
          margin_top: '{marginTop}',
          margin_bottom: '{marginBottom}',
          margin_left: '{marginLeft}',
          margin_right: '{marginRight}',
          print_background: '{printBackground}',
          scale: '{scale}',
          wait_for_timeout: '{waitForTimeout}',
          wait_for_selector: '{waitForSelector}',
          viewport_width: '{viewportWidth}',
          viewport_height: '{viewportHeight}',
          full_page: '{fullPage}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'object.delete',
      class: 'mutation',
      description: 'Permanently delete a previously generated PDF or image object by transaction reference.',
      parameters: {
        type: 'object',
        properties: {
          transactionRef: { type: 'string' },
        },
        required: ['transactionRef'],
      },
      request: {
        method: 'DELETE',
        path: '/delete-object',
        query: { transaction_ref: '{transactionRef}' },
      },
      cas: 'native-idempotency',
    },
  ],
})
