import { declarativeRestConnector } from './declarative-rest.js'

export const asknewsConnector = declarativeRestConnector({
  kind: 'asknews',
  displayName: 'AskNews',
  description:
    'Search and retrieve enriched real-time and historical news articles, run news-aware chat completions, and manage AskNews newsletters and alerts.',
  auth: { kind: 'api-key', hint: 'AskNews API key (client_id + client_secret minted in the AskNews console).' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.asknews.app',
  test: { method: 'GET', path: '/v1/health' },
  capabilities: [
    {
      name: 'search.news',
      class: 'read',
      description: 'Search recent or historical news articles by natural-language query.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          nArticles: { type: 'integer' },
          hoursBack: { type: 'integer' },
          historical: { type: 'boolean' },
          method: { type: 'string', enum: ['nl', 'kw', 'both'] },
          categories: { type: 'array', items: { type: 'string' } },
          returnType: { type: 'string', enum: ['string', 'dicts', 'both'] },
          similarityScoreThreshold: { type: 'number' },
        },
        required: ['query'],
      },
      request: {
        method: 'GET',
        path: '/v1/news/search',
        query: {
          query: '{query}',
          n_articles: '{nArticles}',
          hours_back: '{hoursBack}',
          historical: '{historical}',
          method: '{method}',
          categories: '{categories}',
          return_type: '{returnType}',
          similarity_score_threshold: '{similarityScoreThreshold}',
        },
      },
    },
    {
      name: 'generate.news.knowledge.graph',
      class: 'mutation',
      description: 'Build a knowledge graph from a news query, optionally rendering a visualization.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          nArticles: { type: 'integer' },
          visualizeWith: { type: 'string' },
          minClusterProbability: { type: 'number' },
          geoDiambiguation: { type: 'boolean' },
          queryMethod: { type: 'string', enum: ['nl', 'kw', 'both'] },
          hoursBack: { type: 'integer' },
          historical: { type: 'boolean' },
          categories: { type: 'array', items: { type: 'string' } },
        },
        required: ['query'],
      },
      request: {
        method: 'POST',
        path: '/v1/news/graph',
        body: {
          query: '{query}',
          n_articles: '{nArticles}',
          visualize_with: '{visualizeWith}',
          min_cluster_probability: '{minClusterProbability}',
          geo_disambiguation: '{geoDiambiguation}',
          query_method: '{queryMethod}',
          hours_back: '{hoursBack}',
          historical: '{historical}',
          categories: '{categories}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'get.article.by.id',
      class: 'read',
      description: 'Fetch one or more articles by their AskNews UUID.',
      parameters: {
        type: 'object',
        properties: {
          articleIds: { type: 'array', items: { type: 'string' } },
          returnType: { type: 'string', enum: ['string', 'dicts', 'both'] },
        },
        required: ['articleIds'],
      },
      request: {
        method: 'GET',
        path: '/v1/news/article',
        query: {
          article_ids: '{articleIds}',
          return_type: '{returnType}',
        },
      },
    },
    {
      name: 'asknews.chat.completion',
      class: 'mutation',
      description: 'Run a news-aware chat completion grounded in AskNews retrieval.',
      parameters: {
        type: 'object',
        properties: {
          userMessage: { type: 'string' },
          model: { type: 'string' },
          temperature: { type: 'number' },
          maxTokens: { type: 'integer' },
          journalistMode: { type: 'boolean' },
          inlineCitations: { type: 'string', enum: ['none', 'numbered', 'markdown', 'hyperlinks'] },
          appendReferences: { type: 'boolean' },
          asknewsWatermark: { type: 'boolean' },
          conversationalAwareness: { type: 'boolean' },
          systemPrompt: { type: 'string' },
        },
        required: ['userMessage'],
      },
      request: {
        method: 'POST',
        path: '/v1/openai/chat/completions',
        body: {
          messages: [{ role: 'user', content: '{userMessage}' }],
          model: '{model}',
          temperature: '{temperature}',
          max_tokens: '{maxTokens}',
          journalist_mode: '{journalistMode}',
          inline_citations: '{inlineCitations}',
          append_references: '{appendReferences}',
          asknews_watermark: '{asknewsWatermark}',
          conversational_awareness: '{conversationalAwareness}',
          system_prompt: '{systemPrompt}',
        },
      },
      cas: 'none',
      externalEffect: true,
    },
    {
      name: 'search.stories',
      class: 'read',
      description: 'Search AskNews stories (clusters of related articles) by query.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          categories: { type: 'array', items: { type: 'string' } },
          expand_updates: { type: 'boolean' },
          sort_by: { type: 'string', enum: ['relevance', 'recency', 'coverage'] },
          returnArticles: { type: 'boolean' },
          hoursBack: { type: 'integer' },
        },
        required: ['query'],
      },
      request: {
        method: 'GET',
        path: '/v1/stories',
        query: {
          query: '{query}',
          categories: '{categories}',
          expand_updates: '{expand_updates}',
          sort_by: '{sort_by}',
          return_articles: '{returnArticles}',
          hours_back: '{hoursBack}',
        },
      },
    },
    {
      name: 'create.anewsletter',
      class: 'mutation',
      description: 'Create a new scheduled AskNews newsletter from a natural-language query.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          query: { type: 'string' },
          cron: { type: 'string' },
          sender: { type: 'string' },
          subject: { type: 'string' },
          logoUrl: { type: 'string' },
          replyTo: { type: 'string' },
          audienceId: { type: 'string' },
          resendApiKey: { type: 'string' },
          isPublic: { type: 'boolean' },
          isActive: { type: 'boolean' },
          expiresAt: { type: 'string' },
        },
        required: ['name', 'query', 'cron', 'sender'],
      },
      request: {
        method: 'POST',
        path: '/v1/newsletters',
        body: {
          name: '{name}',
          query: '{query}',
          cron: '{cron}',
          sender: '{sender}',
          subject: '{subject}',
          logo_url: '{logoUrl}',
          reply_to: '{replyTo}',
          audience_id: '{audienceId}',
          resend_api_key: '{resendApiKey}',
          is_public: '{isPublic}',
          is_active: '{isActive}',
          expires_at: '{expiresAt}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.anewsletter',
      class: 'mutation',
      description: 'Update an existing AskNews newsletter by ID.',
      parameters: {
        type: 'object',
        properties: {
          newsletterId: { type: 'string' },
          name: { type: 'string' },
          query: { type: 'string' },
          cron: { type: 'string' },
          subject: { type: 'string' },
          logoUrl: { type: 'string' },
          replyTo: { type: 'string' },
          isPublic: { type: 'boolean' },
          isActive: { type: 'boolean' },
          expiresAt: { type: 'string' },
        },
        required: ['newsletterId'],
      },
      request: {
        method: 'PATCH',
        path: '/v1/newsletters/{newsletterId}',
        body: {
          name: '{name}',
          query: '{query}',
          cron: '{cron}',
          subject: '{subject}',
          logo_url: '{logoUrl}',
          reply_to: '{replyTo}',
          is_public: '{isPublic}',
          is_active: '{isActive}',
          expires_at: '{expiresAt}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'alert.for.query',
      class: 'mutation',
      description: 'Register a scheduled alert that fires when a query matches new coverage.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          cron: { type: 'string' },
          title: { type: 'string' },
          alwaysTrigger: { type: 'boolean' },
          repeat: { type: 'boolean' },
          categories: { type: 'array', items: { type: 'string' } },
        },
        required: ['query', 'cron'],
      },
      request: {
        method: 'POST',
        path: '/v1/alerts',
        body: {
          query: '{query}',
          cron: '{cron}',
          title: '{title}',
          always_trigger: '{alwaysTrigger}',
          repeat: '{repeat}',
          categories: '{categories}',
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
