import { declarativeRestConnector } from './declarative-rest.js'

export const beehiivConnector = declarativeRestConnector({
  kind: 'beehiiv',
  displayName: 'Beehiiv',
  description: 'Manage subscriptions, automations, and posts in Beehiiv.',
  auth: { kind: 'api-key', hint: 'Beehiiv API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.beehiiv.com/v1',
  test: { method: 'GET', path: '/publications' },
  capabilities: [
    {
      name: 'subscriptions.create',
      class: 'mutation',
      description: 'Create a subscription in Beehiiv.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          email: { type: 'string' },
          double_opt_override: { type: 'boolean' },
          reactivate_existing: { type: 'boolean' },
          send_welcome_email: { type: 'boolean' },
          utm_source: { type: 'string' },
          utm_medium: { type: 'string' },
          utm_campaign: { type: 'string' },
          referring_site: { type: 'string' },
          referral_code: { type: 'string' },
          tier: { type: 'string' },
          stripe_customer_id: { type: 'string' },
        },
        required: ['publication_id', 'email'],
      },
      request: {
        method: 'POST',
        path: '/subscriptions',
        body: {
          publication_id: '{publication_id}',
          email: '{email}',
          double_opt_override: '{double_opt_override}',
          reactivate_existing: '{reactivate_existing}',
          send_welcome_email: '{send_welcome_email}',
          utm_source: '{utm_source}',
          utm_medium: '{utm_medium}',
          utm_campaign: '{utm_campaign}',
          referring_site: '{referring_site}',
          referral_code: '{referral_code}',
          tier: '{tier}',
          stripe_customer_id: '{stripe_customer_id}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.update',
      class: 'mutation',
      description: 'Update a subscription in Beehiiv.',
      parameters: {
        type: 'object',
        properties: {
          subscription_id: { type: 'string' },
          email: { type: 'string' },
          tier: { type: 'string' },
          unsubscribe: { type: 'boolean' },
          stripe_customer_id: { type: 'string' },
        },
        required: ['subscription_id'],
      },
      request: {
        method: 'PATCH',
        path: '/subscriptions/{subscription_id}',
        body: {
          email: '{email}',
          tier: '{tier}',
          unsubscribe: '{unsubscribe}',
          stripe_customer_id: '{stripe_customer_id}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'automations.list',
      class: 'read',
      description: 'List automations in a publication.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          limit: { type: 'integer' },
          page: { type: 'integer' },
          expand: { type: 'string' },
        },
        required: ['publication_id'],
      },
      request: {
        method: 'GET',
        path: '/automations',
        query: { publication_id: '{publication_id}', limit: '{limit}', page: '{page}', expand: '{expand}' },
      },
    },
    {
      name: 'subscriptions.add.to.automation',
      class: 'mutation',
      description: 'Add a subscription to an automation.',
      parameters: {
        type: 'object',
        properties: { automation_id: { type: 'string' }, subscription_id: { type: 'string' } },
        required: ['automation_id', 'subscription_id'],
      },
      request: {
        method: 'POST',
        path: '/automations/{automation_id}/subscriptions',
        body: { subscription_id: '{subscription_id}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'posts.list',
      class: 'read',
      description: 'List posts in a publication.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          platform: { type: 'string' },
          status: { type: 'string' },
          limit: { type: 'integer' },
          page: { type: 'integer' },
          content_tags: { type: 'object' },
        },
        required: ['publication_id'],
      },
      request: {
        method: 'GET',
        path: '/posts',
        query: { publication_id: '{publication_id}', platform: '{platform}', status: '{status}', limit: '{limit}', page: '{page}' },
      },
    },
    {
      name: 'subscriptions.delete',
      class: 'mutation',
      description:
        'Unsubscribe and remove a subscriber from a publication. Hard-deletes the subscription record.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          subscription_id: { type: 'string' },
        },
        required: ['publication_id', 'subscription_id'],
      },
      request: {
        method: 'DELETE',
        path: '/publications/{publication_id}/subscriptions/{subscription_id}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'posts.create',
      class: 'mutation',
      description: 'Draft a new post in a Beehiiv publication.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          title: { type: 'string' },
          subtitle: { type: 'string' },
          body_content: {
            type: 'string',
            description: 'HTML or markdown body, depending on publication configuration.',
          },
          status: {
            type: 'string',
            description: 'draft | scheduled | confirmed (default: draft).',
          },
          audience: { type: 'string', description: 'free | premium | all' },
          platform: { type: 'string', description: 'web | email | both' },
        },
        required: ['publication_id', 'title', 'body_content'],
      },
      request: {
        method: 'POST',
        path: '/publications/{publication_id}/posts',
        body: {
          title: '{title}',
          subtitle: '{subtitle}',
          body_content: '{body_content}',
          status: '{status}',
          audience: '{audience}',
          platform: '{platform}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'posts.publish',
      class: 'mutation',
      description: 'Publish a previously drafted Beehiiv post.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          post_id: { type: 'string' },
        },
        required: ['publication_id', 'post_id'],
      },
      request: {
        method: 'POST',
        path: '/publications/{publication_id}/posts/{post_id}/publish',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'segments.create',
      class: 'mutation',
      description: 'Create a subscriber segment under a publication.',
      parameters: {
        type: 'object',
        properties: {
          publication_id: { type: 'string' },
          name: { type: 'string' },
          type: {
            type: 'string',
            description: 'dynamic | static — controls whether the segment is recomputed.',
          },
          filters: {
            type: 'object',
            description: 'Beehiiv segment filter expression.',
          },
        },
        required: ['publication_id', 'name'],
      },
      request: {
        method: 'POST',
        path: '/publications/{publication_id}/segments',
        body: {
          name: '{name}',
          type: '{type}',
          filters: '{filters}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
