import { declarativeRestConnector } from './declarative-rest.js'

// Bexio is a Swiss business-software suite (accounting, invoicing, contacts,
// projects, time tracking). Its public REST API is split across major versions
// per resource family: contacts (`/2.0/contact`, `/2.0/contact_relation`),
// products (`/2.0/article`), accounting manual entries (`/3.0/accounting/manual_entries`),
// invoices/orders/quotes (`/2.0/kb_invoice`, `/2.0/kb_order`, `/2.0/kb_offer`),
// files (`/3.0/files`), projects (`/2.0/pr_project`), timesheets
// (`/2.0/timesheet`), and read-only refs (`/2.0/accounts`, `/2.0/country`).
// All endpoints are bearer-token authenticated against api.bexio.com via the
// OAuth2 authorization-code flow at idp.bexio.com.
export const bexioConnector = declarativeRestConnector({
  kind: 'bexio',
  displayName: 'Bexio',
  description:
    'Swiss business software for accounting, invoicing, contacts, products, projects, and time tracking.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://idp.bexio.com/authorize',
    tokenUrl: 'https://idp.bexio.com/token',
    scopes: [
      'openid',
      'profile',
      'offline_access',
      'accounting',
      'contact_show',
      'contact_edit',
      'article_show',
      'article_edit',
      'kb_invoice_show',
      'kb_invoice_edit',
      'kb_order_show',
      'kb_order_edit',
      'kb_offer_show',
      'kb_offer_edit',
      'project_show',
      'project_edit',
      'monitoring_show',
      'monitoring_edit',
      'file_show',
      'file_edit',
    ],
    clientIdEnv: 'BEXIO_OAUTH_CLIENT_ID',
    clientSecretEnv: 'BEXIO_OAUTH_CLIENT_SECRET',
  },
  category: 'database',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.bexio.com',
  test: { method: 'GET', path: '/2.0/company_profile' },
  capabilities: [
    {
      name: 'create.manual.entry',
      class: 'mutation',
      description:
        'Post a manual accounting entry (journal voucher) with one or more debit/credit lines.',
      parameters: {
        type: 'object',
        properties: {
          type: { type: 'string', description: 'Entry type, e.g. "manual_single_entry".' },
          date: { type: 'string', description: 'ISO-8601 booking date.' },
          reference_nr: { type: 'string' },
          entries: {
            type: 'array',
            description: 'Array of voucher lines (debit_account_id, credit_account_id, amount, tax_id, description, currency_id).',
            items: { type: 'object' },
          },
        },
        required: ['type', 'date', 'entries'],
      },
      request: {
        method: 'POST',
        path: '/3.0/accounting/manual_entries',
        body: {
          type: '{type}',
          date: '{date}',
          reference_nr: '{reference_nr}',
          entries: '{entries}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['accounting'],
      externalEffect: true,
    },
    {
      name: 'create.company',
      class: 'mutation',
      description: 'Create a company contact (contact_type_id=2).',
      parameters: {
        type: 'object',
        properties: {
          name_1: { type: 'string', description: 'Company name.' },
          name_2: { type: 'string' },
          address: { type: 'string' },
          postcode: { type: 'string' },
          city: { type: 'string' },
          country_id: { type: 'integer' },
          mail: { type: 'string' },
          phone_fixed: { type: 'string' },
          user_id: { type: 'integer' },
          owner_id: { type: 'integer' },
        },
        required: ['name_1', 'user_id', 'owner_id'],
      },
      request: {
        method: 'POST',
        path: '/2.0/contact',
        body: {
          contact_type_id: 2,
          name_1: '{name_1}',
          name_2: '{name_2}',
          address: '{address}',
          postcode: '{postcode}',
          city: '{city}',
          country_id: '{country_id}',
          mail: '{mail}',
          phone_fixed: '{phone_fixed}',
          user_id: '{user_id}',
          owner_id: '{owner_id}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contact_edit'],
      externalEffect: true,
    },
    {
      name: 'update.company',
      class: 'mutation',
      description: 'Partially update a company contact by id.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          patch: { type: 'object', description: 'Subset of contact fields to overwrite.' },
        },
        required: ['contactId', 'patch'],
      },
      request: {
        method: 'POST',
        path: '/2.0/contact/{contactId}',
        body: '{patch}',
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['contact_edit'],
      externalEffect: true,
    },
    {
      name: 'create.person',
      class: 'mutation',
      description: 'Create a person contact (contact_type_id=1).',
      parameters: {
        type: 'object',
        properties: {
          name_1: { type: 'string', description: 'Last name.' },
          name_2: { type: 'string', description: 'First name.' },
          salutation_id: { type: 'integer' },
          mail: { type: 'string' },
          phone_fixed: { type: 'string' },
          phone_mobile: { type: 'string' },
          address: { type: 'string' },
          postcode: { type: 'string' },
          city: { type: 'string' },
          country_id: { type: 'integer' },
          contact_group_ids: { type: 'string' },
          user_id: { type: 'integer' },
          owner_id: { type: 'integer' },
        },
        required: ['name_1', 'user_id', 'owner_id'],
      },
      request: {
        method: 'POST',
        path: '/2.0/contact',
        body: {
          contact_type_id: 1,
          name_1: '{name_1}',
          name_2: '{name_2}',
          salutation_id: '{salutation_id}',
          mail: '{mail}',
          phone_fixed: '{phone_fixed}',
          phone_mobile: '{phone_mobile}',
          address: '{address}',
          postcode: '{postcode}',
          city: '{city}',
          country_id: '{country_id}',
          contact_group_ids: '{contact_group_ids}',
          user_id: '{user_id}',
          owner_id: '{owner_id}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contact_edit'],
      externalEffect: true,
    },
    {
      name: 'update.person',
      class: 'mutation',
      description: 'Partially update a person contact by id.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          patch: { type: 'object' },
        },
        required: ['contactId', 'patch'],
      },
      request: {
        method: 'POST',
        path: '/2.0/contact/{contactId}',
        body: '{patch}',
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['contact_edit'],
      externalEffect: true,
    },
    {
      name: 'create.file',
      class: 'mutation',
      description: 'Upload a file to the Bexio file store. Body should be a multipart payload reference.',
      parameters: {
        type: 'object',
        properties: {
          file: { type: 'object', description: 'Multipart file payload (name, content).' },
        },
        required: ['file'],
      },
      request: {
        method: 'POST',
        path: '/3.0/files',
        body: '{file}',
      },
      cas: 'native-idempotency',
      requiredScopes: ['file_edit'],
      externalEffect: true,
    },
    {
      name: 'create.sales.invoice',
      class: 'mutation',
      description: 'Create a sales invoice (kb_invoice) with one or more positions.',
      parameters: {
        type: 'object',
        properties: {
          contact_id: { type: 'integer' },
          user_id: { type: 'integer' },
          logopaper_id: { type: 'integer' },
          language_id: { type: 'integer' },
          bank_account_id: { type: 'integer' },
          currency_id: { type: 'integer' },
          payment_type_id: { type: 'integer' },
          header: { type: 'string' },
          footer: { type: 'string' },
          mwst_type: { type: 'integer' },
          mwst_is_net: { type: 'boolean' },
          positions: { type: 'array', items: { type: 'object' } },
        },
        required: ['contact_id', 'user_id', 'positions'],
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_invoice',
        body: {
          contact_id: '{contact_id}',
          user_id: '{user_id}',
          logopaper_id: '{logopaper_id}',
          language_id: '{language_id}',
          bank_account_id: '{bank_account_id}',
          currency_id: '{currency_id}',
          payment_type_id: '{payment_type_id}',
          header: '{header}',
          footer: '{footer}',
          mwst_type: '{mwst_type}',
          mwst_is_net: '{mwst_is_net}',
          positions: '{positions}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['kb_invoice_edit'],
      externalEffect: true,
    },
    {
      name: 'export.invoice.pdf',
      class: 'mutation',
      description: 'Render a sales invoice as PDF.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'integer' } },
        required: ['invoiceId'],
      },
      request: { method: 'GET', path: '/2.0/kb_invoice/{invoiceId}/pdf' },
      cas: 'native-idempotency',
      requiredScopes: ['kb_invoice_show'],
    },
    {
      name: 'send.sales.invoice',
      class: 'mutation',
      description: 'Send a sales invoice by email.',
      parameters: {
        type: 'object',
        properties: {
          invoiceId: { type: 'integer' },
          recipient_email: { type: 'string' },
          subject: { type: 'string' },
          message: { type: 'string' },
          mark_as_open: { type: 'boolean' },
          attach_pdf: { type: 'boolean' },
        },
        required: ['invoiceId', 'recipient_email'],
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_invoice/{invoiceId}/send',
        body: {
          recipient_email: '{recipient_email}',
          subject: '{subject}',
          message: '{message}',
          mark_as_open: '{mark_as_open}',
          attach_pdf: '{attach_pdf}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['kb_invoice_edit'],
      externalEffect: true,
    },
    {
      name: 'create.product',
      class: 'mutation',
      description: 'Create an article (product) in Bexio.',
      parameters: {
        type: 'object',
        properties: {
          intern_name: { type: 'string' },
          intern_code: { type: 'string' },
          intern_description: { type: 'string' },
          purchase_price: { type: 'string' },
          sale_price: { type: 'string' },
          purchase_total: { type: 'string' },
          sale_total: { type: 'string' },
          currency_id: { type: 'integer' },
          tax_income_id: { type: 'integer' },
          tax_id: { type: 'integer' },
          tax_consideration: { type: 'boolean' },
          user_id: { type: 'integer' },
          article_type_id: { type: 'integer' },
        },
        required: ['intern_name', 'user_id'],
      },
      request: {
        method: 'POST',
        path: '/2.0/article',
        body: {
          intern_name: '{intern_name}',
          intern_code: '{intern_code}',
          intern_description: '{intern_description}',
          purchase_price: '{purchase_price}',
          sale_price: '{sale_price}',
          purchase_total: '{purchase_total}',
          sale_total: '{sale_total}',
          currency_id: '{currency_id}',
          tax_income_id: '{tax_income_id}',
          tax_id: '{tax_id}',
          tax_consideration: '{tax_consideration}',
          user_id: '{user_id}',
          article_type_id: '{article_type_id}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['article_edit'],
      externalEffect: true,
    },
    {
      name: 'update.product',
      class: 'mutation',
      description: 'Partially update an article by id.',
      parameters: {
        type: 'object',
        properties: {
          articleId: { type: 'integer' },
          patch: { type: 'object' },
        },
        required: ['articleId', 'patch'],
      },
      request: {
        method: 'POST',
        path: '/2.0/article/{articleId}',
        body: '{patch}',
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['article_edit'],
      externalEffect: true,
    },
    {
      name: 'create.sales.order',
      class: 'mutation',
      description: 'Create a sales order (kb_order).',
      parameters: {
        type: 'object',
        properties: {
          contact_id: { type: 'integer' },
          user_id: { type: 'integer' },
          logopaper_id: { type: 'integer' },
          language_id: { type: 'integer' },
          currency_id: { type: 'integer' },
          header: { type: 'string' },
          footer: { type: 'string' },
          mwst_type: { type: 'integer' },
          mwst_is_net: { type: 'boolean' },
          positions: { type: 'array', items: { type: 'object' } },
        },
        required: ['contact_id', 'user_id', 'positions'],
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_order',
        body: {
          contact_id: '{contact_id}',
          user_id: '{user_id}',
          logopaper_id: '{logopaper_id}',
          language_id: '{language_id}',
          currency_id: '{currency_id}',
          header: '{header}',
          footer: '{footer}',
          mwst_type: '{mwst_type}',
          mwst_is_net: '{mwst_is_net}',
          positions: '{positions}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['kb_order_edit'],
      externalEffect: true,
    },
    {
      name: 'create.project',
      class: 'mutation',
      description: 'Create a project.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          contact_id: { type: 'integer' },
          user_id: { type: 'integer' },
          pr_state_id: { type: 'integer' },
          pr_project_type_id: { type: 'integer' },
          pr_invoice_type_id: { type: 'integer' },
          start_date: { type: 'string' },
          end_date: { type: 'string' },
          comment: { type: 'string' },
        },
        required: ['name', 'user_id'],
      },
      request: {
        method: 'POST',
        path: '/2.0/pr_project',
        body: {
          name: '{name}',
          contact_id: '{contact_id}',
          user_id: '{user_id}',
          pr_state_id: '{pr_state_id}',
          pr_project_type_id: '{pr_project_type_id}',
          pr_invoice_type_id: '{pr_invoice_type_id}',
          start_date: '{start_date}',
          end_date: '{end_date}',
          comment: '{comment}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['project_edit'],
      externalEffect: true,
    },
    {
      name: 'create.sales.quote',
      class: 'mutation',
      description: 'Create a sales quote / offer (kb_offer).',
      parameters: {
        type: 'object',
        properties: {
          contact_id: { type: 'integer' },
          user_id: { type: 'integer' },
          logopaper_id: { type: 'integer' },
          language_id: { type: 'integer' },
          currency_id: { type: 'integer' },
          header: { type: 'string' },
          footer: { type: 'string' },
          mwst_type: { type: 'integer' },
          mwst_is_net: { type: 'boolean' },
          positions: { type: 'array', items: { type: 'object' } },
        },
        required: ['contact_id', 'user_id', 'positions'],
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_offer',
        body: {
          contact_id: '{contact_id}',
          user_id: '{user_id}',
          logopaper_id: '{logopaper_id}',
          language_id: '{language_id}',
          currency_id: '{currency_id}',
          header: '{header}',
          footer: '{footer}',
          mwst_type: '{mwst_type}',
          mwst_is_net: '{mwst_is_net}',
          positions: '{positions}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['kb_offer_edit'],
      externalEffect: true,
    },
    {
      name: 'create.time.tracking',
      class: 'mutation',
      description: 'Create a timesheet entry.',
      parameters: {
        type: 'object',
        properties: {
          user_id: { type: 'integer' },
          status_id: { type: 'integer' },
          client_service_id: { type: 'integer' },
          contact_id: { type: 'integer' },
          pr_project_id: { type: 'integer' },
          text: { type: 'string' },
          allowable_bill: { type: 'boolean' },
          tracking: {
            type: 'object',
            description: 'Tracking range or duration (type=duration|range with date/duration or date_start/date_end).',
          },
        },
        required: ['user_id', 'tracking'],
      },
      request: {
        method: 'POST',
        path: '/2.0/timesheet',
        body: {
          user_id: '{user_id}',
          status_id: '{status_id}',
          client_service_id: '{client_service_id}',
          contact_id: '{contact_id}',
          pr_project_id: '{pr_project_id}',
          text: '{text}',
          allowable_bill: '{allowable_bill}',
          tracking: '{tracking}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['monitoring_edit'],
      externalEffect: true,
    },
    {
      name: 'find.account',
      class: 'read',
      description: 'List ledger accounts; supports server-side search via the search payload.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' }, description: 'Bexio search expressions on field/value/criteria.' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/accounts/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['accounting'],
    },
    {
      name: 'find.company',
      class: 'read',
      description: 'Search contacts filtered to companies (contact_type_id=2).',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/contact/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['contact_show'],
    },
    {
      name: 'find.person',
      class: 'read',
      description: 'Search contacts filtered to persons (contact_type_id=1).',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/contact/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['contact_show'],
    },
    {
      name: 'find.product',
      class: 'read',
      description: 'Search articles (products) by intern_code, intern_name, or other fields.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/article/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['article_show'],
    },
    {
      name: 'find.country',
      class: 'read',
      description: 'List or search countries by name or ISO code.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/country/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
    },
    {
      name: 'search.invoice',
      class: 'read',
      description: 'Search sales invoices (kb_invoice) by document_nr, title, contact_id, etc.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_invoice/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['kb_invoice_show'],
    },
    {
      name: 'search.order',
      class: 'read',
      description: 'Search sales orders (kb_order).',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_order/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['kb_order_show'],
    },
    {
      name: 'search.quote',
      class: 'read',
      description: 'Search sales quotes / offers (kb_offer).',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'array', items: { type: 'object' } },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
        },
      },
      request: {
        method: 'POST',
        path: '/2.0/kb_offer/search',
        query: { limit: '{limit}', offset: '{offset}' },
        body: '{search}',
      },
      requiredScopes: ['kb_offer_show'],
    },
  ],
})
