import { declarativeRestConnector } from './declarative-rest.js'

export const bookedinConnector = declarativeRestConnector({
  kind: 'bookedin',
  displayName: 'Bookedin',
  description: 'AI agents for lead conversion and appointment booking — manage Bookedin leads.',
  auth: { kind: 'api-key', hint: 'Bookedin API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.bookedin.com',
  test: { method: 'GET', path: '/v1/leads', query: { limit: '1' } },
  capabilities: [
    {
      name: 'leads.list',
      class: 'read',
      description: 'List or search Bookedin leads with optional filters.',
      parameters: {
        type: 'object',
        properties: {
          search: { type: 'string', description: 'Search text in name, email, or phone number.' },
          source: { type: 'string', description: 'Filter by lead source.' },
          handling_status: { type: 'string' },
          limit: { type: 'integer' },
          skip: { type: 'integer' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/leads',
        query: {
          search: '{search}',
          source: '{source}',
          handling_status: '{handling_status}',
          limit: '{limit}',
          skip: '{skip}',
        },
      },
    },
    {
      name: 'leads.get',
      class: 'read',
      description: 'Read a single Bookedin lead by id.',
      parameters: {
        type: 'object',
        properties: { leadId: { type: 'string' } },
        required: ['leadId'],
      },
      request: { method: 'GET', path: '/v1/leads/{leadId}' },
    },
    {
      name: 'leads.stats',
      class: 'read',
      description: 'Get aggregate Bookedin lead statistics.',
      parameters: {
        type: 'object',
        properties: { source: { type: 'string' } },
      },
      request: { method: 'GET', path: '/v1/leads/stats', query: { source: '{source}' } },
    },
    {
      name: 'leads.create',
      class: 'mutation',
      description: 'Create a Bookedin lead.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          source: { type: 'string' },
        },
        required: ['firstName', 'lastName', 'email', 'phone'],
      },
      request: {
        method: 'POST',
        path: '/v1/leads',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          source: '{source}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.update',
      class: 'mutation',
      description: 'Update an existing Bookedin lead. Individual fields merge with the optional update_json payload.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          handling_status: { type: 'string' },
          update_json: { type: 'object', description: 'Optional JSON body for complex updates. Merges with individual fields.' },
        },
        required: ['leadId'],
      },
      request: {
        method: 'PATCH',
        path: '/v1/leads/{leadId}',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          handling_status: '{handling_status}',
          update_json: '{update_json}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.delete',
      class: 'mutation',
      description: 'Delete a Bookedin lead.',
      parameters: {
        type: 'object',
        properties: { leadId: { type: 'string' } },
        required: ['leadId'],
      },
      request: { method: 'DELETE', path: '/v1/leads/{leadId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'appointments.create',
      class: 'mutation',
      description: 'Book a new Bookedin appointment for a lead or customer.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string', description: 'Optional lead id to attach the appointment to.' },
          serviceId: { type: 'string', description: 'Service or appointment type id.' },
          staffId: { type: 'string', description: 'Staff member to assign to the appointment.' },
          startTime: { type: 'string', description: 'ISO 8601 start time for the appointment.' },
          endTime: { type: 'string', description: 'ISO 8601 end time for the appointment.' },
          notes: { type: 'string', description: 'Optional notes attached to the appointment.' },
        },
        required: ['serviceId', 'startTime'],
      },
      request: {
        method: 'POST',
        path: '/v1/appointments',
        body: {
          leadId: '{leadId}',
          serviceId: '{serviceId}',
          staffId: '{staffId}',
          startTime: '{startTime}',
          endTime: '{endTime}',
          notes: '{notes}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'appointments.cancel',
      class: 'mutation',
      description: 'Cancel an existing Bookedin appointment.',
      parameters: {
        type: 'object',
        properties: {
          appointmentId: { type: 'string', description: 'Bookedin appointment id to cancel.' },
          reason: { type: 'string', description: 'Optional cancellation reason.' },
        },
        required: ['appointmentId'],
      },
      request: {
        method: 'POST',
        path: '/v1/appointments/{appointmentId}/cancel',
        body: { reason: '{reason}' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'appointments.reschedule',
      class: 'mutation',
      description: 'Reschedule an existing Bookedin appointment to a new start/end time.',
      parameters: {
        type: 'object',
        properties: {
          appointmentId: { type: 'string', description: 'Bookedin appointment id to reschedule.' },
          startTime: { type: 'string', description: 'New ISO 8601 start time.' },
          endTime: { type: 'string', description: 'New ISO 8601 end time.' },
          staffId: { type: 'string', description: 'Optional new staff member id.' },
        },
        required: ['appointmentId', 'startTime'],
      },
      request: {
        method: 'POST',
        path: '/v1/appointments/{appointmentId}/reschedule',
        body: {
          startTime: '{startTime}',
          endTime: '{endTime}',
          staffId: '{staffId}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
