import { declarativeRestConnector } from './declarative-rest.js'

export const campaignMonitorConnector = declarativeRestConnector({
  kind: 'campaign-monitor',
  displayName: 'Campaign Monitor',
  description:
    'Manage Campaign Monitor subscribers across lists: add, update details, unsubscribe, and lookup.',
  auth: { kind: 'api-key', hint: 'Campaign Monitor API key from Account Settings > API keys.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.createsend.com/api/v3.3',
  test: { method: 'GET', path: '/clients.json' },
  capabilities: [
    {
      name: 'subscriber.add',
      class: 'mutation',
      description: 'Add a subscriber to a list (matches Campaign Monitor "Add subscriber to list").',
      parameters: {
        type: 'object',
        properties: {
          listId: { type: 'string' },
          emailAddress: { type: 'string' },
          name: { type: 'string' },
          mobileNumber: { type: 'string' },
          customFields: { type: 'array' },
          consentToTrack: { type: 'string', enum: ['Yes', 'No', 'Unchanged'] },
          consentToSendSms: { type: 'string', enum: ['Yes', 'No', 'Unchanged'] },
          resubscribe: { type: 'boolean' },
          restartSubscriptionBasedAutoresponders: { type: 'boolean' },
        },
        required: ['listId', 'emailAddress', 'consentToTrack'],
      },
      request: {
        method: 'POST',
        path: '/subscribers/{listId}.json',
        body: {
          EmailAddress: '{emailAddress}',
          Name: '{name}',
          MobileNumber: '{mobileNumber}',
          CustomFields: '{customFields}',
          ConsentToTrack: '{consentToTrack}',
          ConsentToSendSms: '{consentToSendSms}',
          Resubscribe: '{resubscribe}',
          RestartSubscriptionBasedAutoresponders: '{restartSubscriptionBasedAutoresponders}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriber.update',
      class: 'mutation',
      description: 'Update an existing subscriber on a list.',
      parameters: {
        type: 'object',
        properties: {
          listId: { type: 'string' },
          email: { type: 'string' },
          newEmailAddress: { type: 'string' },
          name: { type: 'string' },
          mobileNumber: { type: 'string' },
          customFields: { type: 'array' },
          consentToTrack: { type: 'string', enum: ['Yes', 'No', 'Unchanged'] },
          consentToSendSms: { type: 'string', enum: ['Yes', 'No', 'Unchanged'] },
          resubscribe: { type: 'boolean' },
          restartSubscriptionBasedAutoresponders: { type: 'boolean' },
        },
        required: ['listId', 'email', 'consentToTrack'],
      },
      request: {
        method: 'PUT',
        path: '/subscribers/{listId}.json',
        query: { email: '{email}' },
        body: {
          EmailAddress: '{newEmailAddress}',
          Name: '{name}',
          MobileNumber: '{mobileNumber}',
          CustomFields: '{customFields}',
          ConsentToTrack: '{consentToTrack}',
          ConsentToSendSms: '{consentToSendSms}',
          Resubscribe: '{resubscribe}',
          RestartSubscriptionBasedAutoresponders: '{restartSubscriptionBasedAutoresponders}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'subscriber.unsubscribe',
      class: 'mutation',
      description: 'Unsubscribe a subscriber from a list.',
      parameters: {
        type: 'object',
        properties: {
          listId: { type: 'string' },
          emailAddress: { type: 'string' },
        },
        required: ['listId', 'emailAddress'],
      },
      request: {
        method: 'POST',
        path: '/subscribers/{listId}/unsubscribe.json',
        body: { EmailAddress: '{emailAddress}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'campaign.create',
      class: 'mutation',
      description: 'Draft a new campaign for a Campaign Monitor client.',
      parameters: {
        type: 'object',
        properties: {
          clientId: { type: 'string', description: 'Campaign Monitor client id that owns the campaign.' },
          name: { type: 'string' },
          subject: { type: 'string' },
          fromName: { type: 'string' },
          fromEmail: { type: 'string' },
          replyTo: { type: 'string' },
          htmlUrl: { type: 'string' },
          textUrl: { type: 'string' },
          listIDs: { type: 'array', items: { type: 'string' } },
          segmentIDs: { type: 'array', items: { type: 'string' } },
        },
        required: ['clientId', 'name', 'subject', 'fromName', 'fromEmail', 'replyTo', 'htmlUrl', 'listIDs'],
      },
      request: {
        method: 'POST',
        path: '/campaigns/{clientId}.json',
        body: {
          Name: '{name}',
          Subject: '{subject}',
          FromName: '{fromName}',
          FromEmail: '{fromEmail}',
          ReplyTo: '{replyTo}',
          HtmlUrl: '{htmlUrl}',
          TextUrl: '{textUrl}',
          ListIDs: '{listIDs}',
          SegmentIDs: '{segmentIDs}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'campaign.send',
      class: 'mutation',
      description: 'Send a previously-drafted Campaign Monitor campaign.',
      parameters: {
        type: 'object',
        properties: {
          campaignId: { type: 'string' },
          confirmationEmail: { type: 'string', description: 'Email address to receive the send confirmation.' },
          sendDate: { type: 'string', description: 'ISO-8601 date to schedule the send (or "immediately").' },
        },
        required: ['campaignId', 'confirmationEmail'],
      },
      request: {
        method: 'POST',
        path: '/campaigns/{campaignId}/send.json',
        body: {
          ConfirmationEmail: '{confirmationEmail}',
          SendDate: '{sendDate}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'list.create',
      class: 'mutation',
      description: 'Create a subscriber list under a Campaign Monitor client.',
      parameters: {
        type: 'object',
        properties: {
          clientId: { type: 'string' },
          title: { type: 'string' },
          unsubscribePage: { type: 'string' },
          unsubscribeSetting: { type: 'string', enum: ['AllClientLists', 'OnlyThisList'] },
          confirmedOptIn: { type: 'boolean' },
          confirmationSuccessPage: { type: 'string' },
        },
        required: ['clientId', 'title'],
      },
      request: {
        method: 'POST',
        path: '/lists/{clientId}.json',
        body: {
          Title: '{title}',
          UnsubscribePage: '{unsubscribePage}',
          UnsubscribeSetting: '{unsubscribeSetting}',
          ConfirmedOptIn: '{confirmedOptIn}',
          ConfirmationSuccessPage: '{confirmationSuccessPage}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'list.delete',
      class: 'mutation',
      description: 'Delete a Campaign Monitor subscriber list.',
      parameters: {
        type: 'object',
        properties: { listId: { type: 'string' } },
        required: ['listId'],
      },
      request: { method: 'DELETE', path: '/lists/{listId}.json' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'subscriber.find',
      class: 'read',
      description: 'Look up a subscriber by email address on a list.',
      parameters: {
        type: 'object',
        properties: {
          listId: { type: 'string' },
          email: { type: 'string' },
          includeTrackingPreference: { type: 'boolean' },
        },
        required: ['listId', 'email'],
      },
      request: {
        method: 'GET',
        path: '/subscribers/{listId}.json',
        query: {
          email: '{email}',
          includetrackingpreference: '{includeTrackingPreference}',
        },
      },
    },
  ],
})
