import { declarativeRestConnector } from './declarative-rest.js'

// ChargeKeep is a Sperse recurring + one-time payments product that wraps
// Stripe / PayPal. The public REST API is rooted at https://api.chargekeep.com
// and authenticates with an account API key passed via the X-API-Key header.
export const chargekeepConnector = declarativeRestConnector({
  kind: 'chargekeep',
  displayName: 'ChargeKeep',
  description:
    'Manage ChargeKeep (Sperse) contacts, subscriptions, invoices, and products for recurring and one-time payments via Stripe / PayPal.',
  auth: {
    kind: 'api-key',
    hint: 'ChargeKeep account API key. Sent as the X-API-Key request header.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.chargekeep.com',
  credentialPlacement: { kind: 'header', header: 'X-API-Key' },
  test: { method: 'GET', path: '/api/v1/contacts' },
  capabilities: [
    {
      name: 'contacts.upsert',
      class: 'mutation',
      description:
        'Add or update a ChargeKeep contact. The contactXref string acts as an external idempotency reference: passing the same xref updates the existing record.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          contactXref: { type: 'string' },
          matchExisting: { type: 'boolean' },
          ignoreInvalidValues: { type: 'boolean' },
          importType: {
            type: 'string',
            description: 'Contact type. e.g. Client, Lead, Vendor.',
          },
          createUser: { type: 'boolean' },
          sendWelcomeEmail: { type: 'boolean' },
          userPassword: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          companyName: { type: 'string' },
        },
        required: ['importType'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/contacts/upsert',
        body: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
          matchExisting: '{matchExisting}',
          ignoreInvalidValues: '{ignoreInvalidValues}',
          importType: '{importType}',
          createUser: '{createUser}',
          sendWelcomeEmail: '{sendWelcomeEmail}',
          userPassword: '{userPassword}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          companyName: '{companyName}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.upsert.extended',
      class: 'mutation',
      description:
        'Extended contact upsert that accepts the full ChargeKeep contact profile (name parts, address, demographic fields, lists, custom fields).',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          contactXref: { type: 'string' },
          matchExisting: { type: 'boolean' },
          overrideLists: { type: 'boolean' },
          ignoreInvalidValues: { type: 'boolean' },
          importType: { type: 'string' },
          createUser: { type: 'boolean' },
          sendWelcomeEmail: { type: 'boolean' },
          userPassword: { type: 'string' },
          namePrefix: { type: 'string' },
          firstName: { type: 'string' },
          middleName: { type: 'string' },
          lastName: { type: 'string' },
          nickName: { type: 'string' },
          nameSuffix: { type: 'string' },
          gender: { type: 'string' },
          dob: { type: 'string', description: 'YYYY-MM-DD or MM-DD-YYYY.' },
          ssn: { type: 'string' },
          drivingLicense: { type: 'string' },
          drivingLicenseState: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          companyName: { type: 'string' },
          address: {
            type: 'object',
            properties: {
              line1: { type: 'string' },
              line2: { type: 'string' },
              city: { type: 'string' },
              state: { type: 'string' },
              zip: { type: 'string' },
              country: { type: 'string' },
            },
          },
          customFields: { type: 'object' },
        },
        required: ['importType'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/contacts/upsert/extended',
        body: 'args',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.upsert',
      class: 'mutation',
      description:
        'Create or update a subscription for a ChargeKeep contact. Subscriptions are billed through the connected Stripe or PayPal account.',
      parameters: {
        type: 'object',
        properties: {
          subscriptionId: { type: 'integer' },
          subscriptionXref: { type: 'string' },
          contactId: { type: 'integer' },
          contactXref: { type: 'string' },
          productCode: { type: 'string' },
          planCode: { type: 'string' },
          amount: { type: 'number' },
          currency: { type: 'string' },
          billingInterval: { type: 'string', enum: ['day', 'week', 'month', 'year'] },
          intervalCount: { type: 'integer', minimum: 1 },
          startDate: { type: 'string' },
          trialDays: { type: 'integer', minimum: 0 },
          status: { type: 'string' },
        },
        required: ['productCode'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/subscriptions/upsert',
        body: 'args',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create an invoice in ChargeKeep for an existing contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          contactXref: { type: 'string' },
          invoiceXref: { type: 'string' },
          currency: { type: 'string' },
          dueDate: { type: 'string', description: 'YYYY-MM-DD' },
          memo: { type: 'string' },
          items: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                productCode: { type: 'string' },
                description: { type: 'string' },
                quantity: { type: 'number' },
                unitPrice: { type: 'number' },
                taxRate: { type: 'number' },
              },
              required: ['description', 'quantity', 'unitPrice'],
            },
          },
        },
        required: ['items'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/invoices',
        body: 'args',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a product (offer) in the ChargeKeep catalog.',
      parameters: {
        type: 'object',
        properties: {
          productCode: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          price: { type: 'number' },
          currency: { type: 'string' },
          recurring: { type: 'boolean' },
          billingInterval: { type: 'string', enum: ['day', 'week', 'month', 'year'] },
          intervalCount: { type: 'integer', minimum: 1 },
          trialDays: { type: 'integer', minimum: 0 },
          taxable: { type: 'boolean' },
        },
        required: ['name', 'price'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/products',
        body: 'args',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.get',
      class: 'read',
      description:
        'Read full ChargeKeep contact details. Look up by internal contactId or external contactXref.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'integer' },
          contactXref: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/api/v1/contacts/details',
        query: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
        },
      },
    },
  ],
})
