import { declarativeRestConnector } from './declarative-rest.js'

export const clockodoConnector = declarativeRestConnector({
  kind: 'clockodo',
  displayName: 'Clockodo',
  description:
    'Read and manage Clockodo time entries, customers, projects, services, users, and absences for time-tracking automation.',
  auth: {
    kind: 'api-key',
    hint: 'Clockodo API user email and API key, sent as X-ClockodoApiUser and X-ClockodoApiKey headers.',
  },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://my.clockodo.com/api',
  test: { method: 'GET', path: '/users' },
  capabilities: [
    {
      name: 'entries.find',
      class: 'read',
      description: 'List time entries within a date range, optionally filtered by user, customer, project, service, billable, or billed flags.',
      parameters: {
        type: 'object',
        properties: {
          time_since: { type: 'string' },
          time_until: { type: 'string' },
          users_id: { type: 'integer' },
          customers_id: { type: 'integer' },
          projects_id: { type: 'integer' },
          services_id: { type: 'integer' },
          billable: { type: 'integer' },
          billed: { type: 'boolean' },
          page: { type: 'integer' },
        },
        required: ['time_since', 'time_until'],
      },
      request: {
        method: 'GET',
        path: '/v2/entries',
        query: {
          time_since: '{time_since}',
          time_until: '{time_until}',
          'filter[users_id]': '{users_id}',
          'filter[customers_id]': '{customers_id}',
          'filter[projects_id]': '{projects_id}',
          'filter[services_id]': '{services_id}',
          'filter[billable]': '{billable}',
          'filter[billed]': '{billed}',
          page: '{page}',
        },
      },
    },
    {
      name: 'entries.get',
      class: 'read',
      description: 'Fetch a single Clockodo time entry by id.',
      parameters: {
        type: 'object',
        properties: { entryId: { type: 'integer' } },
        required: ['entryId'],
      },
      request: { method: 'GET', path: '/v2/entries/{entryId}' },
    },
    {
      name: 'entries.create',
      class: 'mutation',
      description: 'Create a Clockodo time entry for a customer/project/service.',
      parameters: {
        type: 'object',
        properties: {
          customers_id: { type: 'integer' },
          projects_id: { type: 'integer' },
          services_id: { type: 'integer' },
          users_id: { type: 'integer' },
          billable: { type: 'integer' },
          time_since: { type: 'string' },
          time_until: { type: 'string' },
          text: { type: 'string' },
          hourly_rate: { type: 'number' },
        },
        required: ['customers_id', 'services_id', 'billable', 'time_since', 'time_until'],
      },
      request: {
        method: 'POST',
        path: '/v2/entries',
        body: {
          customers_id: '{customers_id}',
          projects_id: '{projects_id}',
          services_id: '{services_id}',
          users_id: '{users_id}',
          billable: '{billable}',
          time_since: '{time_since}',
          time_until: '{time_until}',
          text: '{text}',
          hourly_rate: '{hourly_rate}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'entries.update',
      class: 'mutation',
      description: 'Update a Clockodo time entry.',
      parameters: {
        type: 'object',
        properties: {
          entryId: { type: 'integer' },
          customers_id: { type: 'integer' },
          projects_id: { type: 'integer' },
          services_id: { type: 'integer' },
          billable: { type: 'integer' },
          time_since: { type: 'string' },
          time_until: { type: 'string' },
          text: { type: 'string' },
          hourly_rate: { type: 'number' },
        },
        required: ['entryId'],
      },
      request: {
        method: 'PUT',
        path: '/v2/entries/{entryId}',
        body: {
          customers_id: '{customers_id}',
          projects_id: '{projects_id}',
          services_id: '{services_id}',
          billable: '{billable}',
          time_since: '{time_since}',
          time_until: '{time_until}',
          text: '{text}',
          hourly_rate: '{hourly_rate}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'entries.delete',
      class: 'mutation',
      description: 'Delete a Clockodo time entry by id.',
      parameters: {
        type: 'object',
        properties: { entryId: { type: 'integer' } },
        required: ['entryId'],
      },
      request: { method: 'DELETE', path: '/v2/entries/{entryId}' },
      cas: 'native-idempotency',
    },
    {
      name: 'customers.find',
      class: 'read',
      description: 'List Clockodo customers, optionally filtered by active status.',
      parameters: {
        type: 'object',
        properties: {
          active: { type: 'boolean' },
          page: { type: 'integer' },
        },
      },
      request: {
        method: 'GET',
        path: '/v2/customers',
        query: {
          'filter[active]': '{active}',
          page: '{page}',
        },
      },
    },
    {
      name: 'customers.get',
      class: 'read',
      description: 'Fetch a single Clockodo customer by id.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'integer' } },
        required: ['customerId'],
      },
      request: { method: 'GET', path: '/v2/customers/{customerId}' },
    },
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a Clockodo customer.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          number: { type: 'string' },
          active: { type: 'boolean' },
          billable_default: { type: 'boolean' },
          note: { type: 'string' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/v2/customers',
        body: {
          name: '{name}',
          number: '{number}',
          active: '{active}',
          billable_default: '{billable_default}',
          note: '{note}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'projects.find',
      class: 'read',
      description: 'List Clockodo projects, optionally scoped to a customer.',
      parameters: {
        type: 'object',
        properties: {
          customers_id: { type: 'integer' },
          active: { type: 'boolean' },
          page: { type: 'integer' },
        },
      },
      request: {
        method: 'GET',
        path: '/v2/projects',
        query: {
          'filter[customers_id]': '{customers_id}',
          'filter[active]': '{active}',
          page: '{page}',
        },
      },
    },
    {
      name: 'projects.create',
      class: 'mutation',
      description: 'Create a Clockodo project under a customer.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          customers_id: { type: 'integer' },
          active: { type: 'boolean' },
          billable_default: { type: 'boolean' },
          note: { type: 'string' },
        },
        required: ['name', 'customers_id'],
      },
      request: {
        method: 'POST',
        path: '/v2/projects',
        body: {
          name: '{name}',
          customers_id: '{customers_id}',
          active: '{active}',
          billable_default: '{billable_default}',
          note: '{note}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'services.find',
      class: 'read',
      description: 'List Clockodo services.',
      parameters: {
        type: 'object',
        properties: {
          active: { type: 'boolean' },
        },
      },
      request: {
        method: 'GET',
        path: '/v2/services',
        query: { 'filter[active]': '{active}' },
      },
    },
    {
      name: 'users.find',
      class: 'read',
      description: 'List Clockodo users (co-workers) in the account.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/users' },
    },
    {
      name: 'absences.find',
      class: 'read',
      description: 'List Clockodo absences in a given year, optionally filtered by user.',
      parameters: {
        type: 'object',
        properties: {
          year: { type: 'integer' },
          users_id: { type: 'integer' },
        },
        required: ['year'],
      },
      request: {
        method: 'GET',
        path: '/absences',
        query: {
          year: '{year}',
          users_id: '{users_id}',
        },
      },
    },
    {
      name: 'absences.create',
      class: 'mutation',
      description: 'Create a Clockodo absence (vacation, sick day, etc.) for a user.',
      parameters: {
        type: 'object',
        properties: {
          date_since: { type: 'string' },
          date_until: { type: 'string' },
          type: { type: 'integer' },
          users_id: { type: 'integer' },
          status: { type: 'integer' },
          note: { type: 'string' },
          half_days: { type: 'boolean' },
          sick_note: { type: 'boolean' },
        },
        required: ['date_since', 'date_until', 'type'],
      },
      request: {
        method: 'POST',
        path: '/absences',
        body: {
          date_since: '{date_since}',
          date_until: '{date_until}',
          type: '{type}',
          users_id: '{users_id}',
          status: '{status}',
          note: '{note}',
          half_days: '{half_days}',
          sick_note: '{sick_note}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'absences.delete',
      class: 'mutation',
      description: 'Delete a Clockodo absence by id.',
      parameters: {
        type: 'object',
        properties: { absenceId: { type: 'integer' } },
        required: ['absenceId'],
      },
      request: { method: 'DELETE', path: '/absences/{absenceId}' },
      cas: 'native-idempotency',
    },
  ],
})
