import { declarativeRestConnector } from './declarative-rest.js'

export const convertkitConnector = declarativeRestConnector({
  kind: 'convertkit',
  displayName: 'ConvertKit',
  description: 'Manage ConvertKit subscribers, tags, forms, sequences, broadcasts, and purchases via the v3 API.',
  auth: { kind: 'api-key', hint: 'ConvertKit API Secret (from Account → Advanced).' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.convertkit.com/v3',
  credentialPlacement: { kind: 'query', parameter: 'api_secret' },
  test: { method: 'GET', path: '/account' },
  capabilities: [
    {
      name: 'fields.create',
      class: 'mutation',
      description: 'Create a custom field on a subscriber profile.',
      parameters: {
        type: 'object',
        properties: { label: { type: 'string' } },
        required: ['label'],
      },
      request: { method: 'POST', path: '/custom_fields', body: { label: '{label}' } },
    },
    {
      name: 'fields.delete',
      class: 'mutation',
      description: 'Delete a custom field.',
      parameters: {
        type: 'object',
        properties: { fieldId: { type: 'string' } },
        required: ['fieldId'],
      },
      request: { method: 'DELETE', path: '/custom_fields/{fieldId}' },
    },
    {
      name: 'fields.list',
      class: 'read',
      description: 'List all custom fields.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/custom_fields' },
    },
    {
      name: 'fields.update',
      class: 'mutation',
      description: 'Update a custom field label.',
      parameters: {
        type: 'object',
        properties: { fieldId: { type: 'string' }, label: { type: 'string' } },
        required: ['fieldId', 'label'],
      },
      request: { method: 'PUT', path: '/custom_fields/{fieldId}', body: { label: '{label}' } },
    },
    {
      name: 'subscribers.getByEmail',
      class: 'read',
      description: 'Look up a subscriber by email address.',
      parameters: {
        type: 'object',
        properties: { emailAddress: { type: 'string' } },
        required: ['emailAddress'],
      },
      request: { method: 'GET', path: '/subscribers', query: { email_address: '{emailAddress}' } },
    },
    {
      name: 'subscribers.getById',
      class: 'read',
      description: 'Fetch a subscriber by id.',
      parameters: {
        type: 'object',
        properties: { subscriberId: { type: 'string' } },
        required: ['subscriberId'],
      },
      request: { method: 'GET', path: '/subscribers/{subscriberId}' },
    },
    {
      name: 'subscribers.list',
      class: 'read',
      description: 'List subscribers with optional status filter and pagination.',
      parameters: {
        type: 'object',
        properties: {
          page: { type: 'integer' },
          from: { type: 'string' },
          to: { type: 'string' },
          updatedFrom: { type: 'string' },
          updatedTo: { type: 'string' },
          sortOrder: { type: 'string' },
          sortField: { type: 'string' },
          emailAddress: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/subscribers',
        query: {
          page: '{page}',
          from: '{from}',
          to: '{to}',
          updated_from: '{updatedFrom}',
          updated_to: '{updatedTo}',
          sort_order: '{sortOrder}',
          sort_field: '{sortField}',
          email_address: '{emailAddress}',
        },
      },
    },
    {
      name: 'subscribers.tags.listByEmail',
      class: 'read',
      description: 'List tags applied to a subscriber by email address.',
      parameters: {
        type: 'object',
        properties: { emailAddress: { type: 'string' } },
        required: ['emailAddress'],
      },
      request: {
        method: 'GET',
        path: '/subscribers/tags',
        query: { email_address: '{emailAddress}' },
      },
    },
    {
      name: 'subscribers.tags.listById',
      class: 'read',
      description: 'List tags applied to a subscriber by id.',
      parameters: {
        type: 'object',
        properties: { subscriberId: { type: 'string' } },
        required: ['subscriberId'],
      },
      request: { method: 'GET', path: '/subscribers/{subscriberId}/tags' },
    },
    {
      name: 'subscribers.unsubscribe',
      class: 'mutation',
      description: 'Unsubscribe a subscriber by email address.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'PUT', path: '/unsubscribe', body: { email: '{email}' } },
    },
    {
      name: 'subscribers.update',
      class: 'mutation',
      description: 'Update subscriber profile fields.',
      parameters: {
        type: 'object',
        properties: {
          subscriberId: { type: 'string' },
          firstName: { type: 'string' },
          emailAddress: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['subscriberId'],
      },
      request: {
        method: 'PUT',
        path: '/subscribers/{subscriberId}',
        body: {
          first_name: '{firstName}',
          email_address: '{emailAddress}',
          fields: '{fields}',
        },
      },
    },
    {
      name: 'webhooks.create',
      class: 'mutation',
      description: 'Create an automation webhook (outbound notification).',
      parameters: {
        type: 'object',
        properties: { targetUrl: { type: 'string' }, event: { type: 'object' } },
        required: ['targetUrl', 'event'],
      },
      request: {
        method: 'POST',
        path: '/automations/hooks',
        body: { target_url: '{targetUrl}', event: '{event}' },
      },
    },
    {
      name: 'webhooks.delete',
      class: 'mutation',
      description: 'Delete an automation webhook.',
      parameters: {
        type: 'object',
        properties: { ruleId: { type: 'string' } },
        required: ['ruleId'],
      },
      request: { method: 'DELETE', path: '/automations/hooks/{ruleId}' },
    },
    {
      name: 'broadcasts.stats',
      class: 'read',
      description: 'Get open and click stats for a broadcast.',
      parameters: {
        type: 'object',
        properties: { broadcastId: { type: 'string' } },
        required: ['broadcastId'],
      },
      request: { method: 'GET', path: '/broadcasts/{broadcastId}/stats' },
    },
    {
      name: 'broadcasts.create',
      class: 'mutation',
      description: 'Create a new broadcast.',
      parameters: {
        type: 'object',
        properties: {
          subject: { type: 'string' },
          content: { type: 'string' },
          description: { type: 'string' },
          public: { type: 'boolean' },
          publishedAt: { type: 'string' },
          sendAt: { type: 'string' },
          emailAddress: { type: 'string' },
          emailLayoutTemplate: { type: 'string' },
          thumbnailAlt: { type: 'string' },
          thumbnailUrl: { type: 'string' },
        },
        required: ['subject', 'content'],
      },
      request: {
        method: 'POST',
        path: '/broadcasts',
        body: {
          subject: '{subject}',
          content: '{content}',
          description: '{description}',
          public: '{public}',
          published_at: '{publishedAt}',
          send_at: '{sendAt}',
          email_address: '{emailAddress}',
          email_layout_template: '{emailLayoutTemplate}',
          thumbnail_alt: '{thumbnailAlt}',
          thumbnail_url: '{thumbnailUrl}',
        },
      },
    },
    {
      name: 'broadcasts.delete',
      class: 'mutation',
      description: 'Delete a broadcast.',
      parameters: {
        type: 'object',
        properties: { broadcastId: { type: 'string' } },
        required: ['broadcastId'],
      },
      request: { method: 'DELETE', path: '/broadcasts/{broadcastId}' },
    },
    {
      name: 'broadcasts.getById',
      class: 'read',
      description: 'Fetch a single broadcast by id.',
      parameters: {
        type: 'object',
        properties: { broadcastId: { type: 'string' } },
        required: ['broadcastId'],
      },
      request: { method: 'GET', path: '/broadcasts/{broadcastId}' },
    },
    {
      name: 'broadcasts.list',
      class: 'read',
      description: 'List broadcasts.',
      parameters: { type: 'object', properties: { page: { type: 'integer' } } },
      request: { method: 'GET', path: '/broadcasts', query: { page: '{page}' } },
    },
    {
      name: 'broadcasts.update',
      class: 'mutation',
      description: 'Update an existing broadcast.',
      parameters: {
        type: 'object',
        properties: {
          broadcastId: { type: 'string' },
          subject: { type: 'string' },
          content: { type: 'string' },
          description: { type: 'string' },
          public: { type: 'boolean' },
          publishedAt: { type: 'string' },
          sendAt: { type: 'string' },
          emailAddress: { type: 'string' },
          emailLayoutTemplate: { type: 'string' },
          thumbnailAlt: { type: 'string' },
          thumbnailUrl: { type: 'string' },
        },
        required: ['broadcastId'],
      },
      request: {
        method: 'PUT',
        path: '/broadcasts/{broadcastId}',
        body: {
          subject: '{subject}',
          content: '{content}',
          description: '{description}',
          public: '{public}',
          published_at: '{publishedAt}',
          send_at: '{sendAt}',
          email_address: '{emailAddress}',
          email_layout_template: '{emailLayoutTemplate}',
          thumbnail_alt: '{thumbnailAlt}',
          thumbnail_url: '{thumbnailUrl}',
        },
      },
    },
    {
      name: 'forms.subscribers.add',
      class: 'mutation',
      description: 'Subscribe an email to a form.',
      parameters: {
        type: 'object',
        properties: {
          formId: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string' },
          fields: { type: 'object' },
          tags: { type: 'array' },
        },
        required: ['formId', 'email'],
      },
      request: {
        method: 'POST',
        path: '/forms/{formId}/subscribe',
        body: {
          email: '{email}',
          first_name: '{firstName}',
          fields: '{fields}',
          tags: '{tags}',
        },
      },
    },
    {
      name: 'forms.list',
      class: 'read',
      description: 'List all forms on the account.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/forms' },
    },
    {
      name: 'forms.subscriptions.list',
      class: 'read',
      description: 'List subscriptions to a form.',
      parameters: {
        type: 'object',
        properties: {
          formId: { type: 'string' },
          page: { type: 'integer' },
          subscriberState: { type: 'string' },
          sortOrder: { type: 'string' },
        },
        required: ['formId'],
      },
      request: {
        method: 'GET',
        path: '/forms/{formId}/subscriptions',
        query: {
          page: '{page}',
          subscriber_state: '{subscriberState}',
          sort_order: '{sortOrder}',
        },
      },
    },
    {
      name: 'sequences.subscribers.add',
      class: 'mutation',
      description: 'Subscribe an email to a sequence.',
      parameters: {
        type: 'object',
        properties: {
          sequenceId: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string' },
          fields: { type: 'object' },
          tags: { type: 'array' },
        },
        required: ['sequenceId', 'email'],
      },
      request: {
        method: 'POST',
        path: '/sequences/{sequenceId}/subscribe',
        body: {
          email: '{email}',
          first_name: '{firstName}',
          fields: '{fields}',
          tags: '{tags}',
        },
      },
    },
    {
      name: 'sequences.list',
      class: 'read',
      description: 'List all sequences on the account.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/sequences' },
    },
    {
      name: 'sequences.subscriptions.list',
      class: 'read',
      description: 'List subscriptions to a sequence.',
      parameters: {
        type: 'object',
        properties: {
          sequenceId: { type: 'string' },
          page: { type: 'integer' },
          subscriberState: { type: 'string' },
          sortOrder: { type: 'string' },
        },
        required: ['sequenceId'],
      },
      request: {
        method: 'GET',
        path: '/sequences/{sequenceId}/subscriptions',
        query: {
          page: '{page}',
          subscriber_state: '{subscriberState}',
          sort_order: '{sortOrder}',
        },
      },
    },
    {
      name: 'tags.create',
      class: 'mutation',
      description: 'Create a new tag.',
      parameters: {
        type: 'object',
        properties: { name: { type: 'string' } },
        required: ['name'],
      },
      request: { method: 'POST', path: '/tags', body: { tag: { name: '{name}' } } },
    },
    {
      name: 'tags.subscriptions.list',
      class: 'read',
      description: 'List subscriptions tagged with the given tag.',
      parameters: {
        type: 'object',
        properties: {
          tagId: { type: 'string' },
          page: { type: 'integer' },
          subscriberState: { type: 'string' },
          sortOrder: { type: 'string' },
        },
        required: ['tagId'],
      },
      request: {
        method: 'GET',
        path: '/tags/{tagId}/subscriptions',
        query: {
          page: '{page}',
          subscriber_state: '{subscriberState}',
          sort_order: '{sortOrder}',
        },
      },
    },
    {
      name: 'tags.list',
      class: 'read',
      description: 'List all tags on the account.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/tags' },
    },
    {
      name: 'tags.removeBySubscriberEmail',
      class: 'mutation',
      description: 'Remove a tag from a subscriber identified by email address.',
      parameters: {
        type: 'object',
        properties: { tagId: { type: 'string' }, email: { type: 'string' } },
        required: ['tagId', 'email'],
      },
      request: {
        method: 'POST',
        path: '/tags/{tagId}/unsubscribe',
        body: { email: '{email}' },
      },
    },
    {
      name: 'tags.removeBySubscriberId',
      class: 'mutation',
      description: 'Remove a tag from a subscriber identified by id.',
      parameters: {
        type: 'object',
        properties: { tagId: { type: 'string' }, subscriberId: { type: 'string' } },
        required: ['tagId', 'subscriberId'],
      },
      request: { method: 'DELETE', path: '/subscribers/{subscriberId}/tags/{tagId}' },
    },
    {
      name: 'tags.apply',
      class: 'mutation',
      description: 'Tag a subscriber by email address.',
      parameters: {
        type: 'object',
        properties: {
          tagId: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['tagId', 'email'],
      },
      request: {
        method: 'POST',
        path: '/tags/{tagId}/subscribe',
        body: { email: '{email}', first_name: '{firstName}', fields: '{fields}' },
      },
    },
    {
      name: 'purchases.createBatch',
      class: 'mutation',
      description: 'Create or upsert a batch of purchases.',
      parameters: {
        type: 'object',
        properties: { purchases: { type: 'array' } },
        required: ['purchases'],
      },
      request: { method: 'POST', path: '/purchases', body: { purchases: '{purchases}' } },
    },
    {
      name: 'purchases.create',
      class: 'mutation',
      description: 'Create or upsert a single purchase.',
      parameters: {
        type: 'object',
        properties: { purchase: { type: 'object' } },
        required: ['purchase'],
      },
      request: { method: 'POST', path: '/purchases', body: { purchase: '{purchase}' } },
    },
    {
      name: 'purchases.getById',
      class: 'read',
      description: 'Fetch a purchase by id.',
      parameters: {
        type: 'object',
        properties: { purchaseId: { type: 'string' } },
        required: ['purchaseId'],
      },
      request: { method: 'GET', path: '/purchases/{purchaseId}' },
    },
    {
      name: 'purchases.list',
      class: 'read',
      description: 'List purchases.',
      parameters: {
        type: 'object',
        properties: { page: { type: 'integer' } },
      },
      request: { method: 'GET', path: '/purchases', query: { page: '{page}' } },
    },
  ],
})
