import { declarativeRestConnector } from './declarative-rest.js'

// Copper CRM (formerly ProsperWorks) developer API. Base path is
// /developer_api/v1, every request takes three account-scoped headers:
//   X-PW-AccessToken   - the API key from Settings → Integrations → API Keys
//   X-PW-Application   - always "developer_api"
//   X-PW-UserEmail     - the email address tied to the API key
//
// The activepieces piece (@activepieces/piece-copper) only models the
// access-token field directly; the user-email + application headers are
// constants per Copper's docs, so they live in defaultHeaders. Hosts that
// want to override the email per-connection can do so by post-processing
// the manifest.defaultHeaders before invocation.
export const copperConnector = declarativeRestConnector({
  kind: 'copper',
  displayName: 'Copper',
  description:
    'Copper CRM: create and update people, leads, companies, opportunities, projects, tasks, and activities; search across the full entity set.',
  auth: {
    kind: 'api-key',
    hint: 'Copper API key from Settings → Integrations → API Keys. Sent as the X-PW-AccessToken header.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.copper.com/developer_api/v1',
  credentialPlacement: { kind: 'header', header: 'X-PW-AccessToken' },
  defaultHeaders: {
    accept: 'application/json',
    'content-type': 'application/json',
    'x-pw-application': 'developer_api',
  },
  test: { method: 'GET', path: '/account' },
  capabilities: [
    {
      name: 'create.person',
      class: 'mutation',
      description: 'Create a person record in Copper.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Full name of the person.' },
          email: { type: 'string' },
          emails: { type: 'array', items: { type: 'object' } },
          phone_numbers: { type: 'array', items: { type: 'object' } },
          tags: { type: 'array', items: { type: 'string' } },
          details: { type: 'string' },
          fields: { type: 'object', description: 'Additional / custom fields.' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/people',
        body: {
          name: '{name}',
          email: '{email}',
          emails: '{emails}',
          phone_numbers: '{phone_numbers}',
          tags: '{tags}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.person',
      class: 'mutation',
      description: 'Update an existing person record.',
      parameters: {
        type: 'object',
        properties: {
          personId: { type: 'string', description: 'Copper person ID.' },
          updateFields: { type: 'object', description: 'Fields to update.' },
        },
        required: ['personId', 'updateFields'],
      },
      request: {
        method: 'PUT',
        path: '/people/{personId}',
        body: '{updateFields}',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'create.lead',
      class: 'mutation',
      description: 'Create a lead in Copper.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          email: { type: 'string' },
          phone_numbers: { type: 'array', items: { type: 'object' } },
          details: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/leads',
        body: {
          name: '{name}',
          email: '{email}',
          phone_numbers: '{phone_numbers}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.lead',
      class: 'mutation',
      description: 'Update an existing lead.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          updateFields: { type: 'object' },
        },
        required: ['leadId', 'updateFields'],
      },
      request: {
        method: 'PUT',
        path: '/leads/{leadId}',
        body: '{updateFields}',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'convert.lead',
      class: 'mutation',
      description: 'Convert a lead into a person, company, and/or opportunity.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          details: { type: 'object', description: 'Conversion options payload.' },
        },
        required: ['leadId'],
      },
      request: {
        method: 'POST',
        path: '/leads/{leadId}/convert',
        body: '{details}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'create.company',
      class: 'mutation',
      description: 'Create a company record.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          email_domain: { type: 'string' },
          phone_numbers: { type: 'array', items: { type: 'object' } },
          details: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/companies',
        body: {
          name: '{name}',
          email_domain: '{email_domain}',
          phone_numbers: '{phone_numbers}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.company',
      class: 'mutation',
      description: 'Update a company record.',
      parameters: {
        type: 'object',
        properties: {
          companyId: { type: 'string' },
          updateFields: { type: 'object' },
        },
        required: ['companyId', 'updateFields'],
      },
      request: {
        method: 'PUT',
        path: '/companies/{companyId}',
        body: '{updateFields}',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'create.opportunity',
      class: 'mutation',
      description: 'Create an opportunity.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          primary_contact_id: { type: 'string' },
          pipelineStageId: { type: 'string' },
          priority: { type: 'string' },
          details: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['name', 'primary_contact_id'],
      },
      request: {
        method: 'POST',
        path: '/opportunities',
        body: {
          name: '{name}',
          primary_contact_id: '{primary_contact_id}',
          pipeline_stage_id: '{pipelineStageId}',
          priority: '{priority}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.opportunity',
      class: 'mutation',
      description: 'Update an opportunity.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          updateFields: { type: 'object' },
        },
        required: ['opportunityId', 'updateFields'],
      },
      request: {
        method: 'PUT',
        path: '/opportunities/{opportunityId}',
        body: '{updateFields}',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'create.project',
      class: 'mutation',
      description: 'Create a project.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          details: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/projects',
        body: {
          name: '{name}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'update.project',
      class: 'mutation',
      description: 'Update a project.',
      parameters: {
        type: 'object',
        properties: {
          projectId: { type: 'string' },
          updateFields: { type: 'object' },
        },
        required: ['projectId', 'updateFields'],
      },
      request: {
        method: 'PUT',
        path: '/projects/{projectId}',
        body: '{updateFields}',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'create.task',
      class: 'mutation',
      description: 'Create a task. Optionally attach to a parent entity (person, lead, opportunity, ...).',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          entity: {
            type: 'string',
            description: 'Parent entity type (person, lead, company, opportunity, project).',
          },
          entityItemId: { type: 'string', description: 'Parent entity resource ID.' },
          due_date: { type: 'string', description: 'Unix epoch seconds.' },
          reminder_date: { type: 'string', description: 'Unix epoch seconds.' },
          priority: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          details: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/tasks',
        body: {
          name: '{name}',
          related_resource: { type: '{entity}', id: '{entityItemId}' },
          due_date: '{due_date}',
          reminder_date: '{reminder_date}',
          priority: '{priority}',
          tags: '{tags}',
          details: '{details}',
          custom_fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'create.activity',
      class: 'mutation',
      description:
        'Log an activity (note, call, meeting, etc.) against a Copper entity (parent resource).',
      parameters: {
        type: 'object',
        properties: {
          entity: {
            type: 'string',
            description: 'Parent entity type (person, lead, company, opportunity, project).',
          },
          entityItemId: { type: 'string', description: 'Parent entity resource ID.' },
          activity_type: {
            type: 'object',
            description: 'Activity type { category, id } per Copper activity_types.',
          },
          details: { type: 'string', description: 'Activity body.' },
          activity_date: { type: 'string', description: 'Unix epoch seconds.' },
        },
        required: ['entity', 'entityItemId', 'activity_type'],
      },
      request: {
        method: 'POST',
        path: '/activities',
        body: {
          parent: { type: '{entity}', id: '{entityItemId}' },
          type: '{activity_type}',
          details: '{details}',
          activity_date: '{activity_date}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'search.for.an.activity',
      class: 'read',
      description: 'Search activities, with optional parent + date-range filters.',
      parameters: {
        type: 'object',
        properties: {
          parent: {
            type: 'object',
            description: 'Optional parent entity reference { type, id }.',
          },
          minimum_activity_date: { type: 'integer', description: 'Unix epoch seconds.' },
          maximum_activity_date: { type: 'integer', description: 'Unix epoch seconds.' },
          full_result: { type: 'boolean' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/activities/search',
        body: {
          parent: '{parent}',
          minimum_activity_date: '{minimum_activity_date}',
          maximum_activity_date: '{maximum_activity_date}',
          full_result: '{full_result}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
    {
      name: 'search.for.aperson',
      class: 'read',
      description: 'Search for people by name, email, phone, address, or interaction filters.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          emails: { type: 'array', items: { type: 'string' } },
          phone_number: { type: 'string' },
          email_domains: { type: 'array', items: { type: 'string' } },
          city: { type: 'string' },
          state: { type: 'string' },
          postal_code: { type: 'string' },
          country: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          followed: { type: 'string' },
          age: { type: 'integer' },
          minimum_interaction_count: { type: 'integer' },
          maximum_interaction_count: { type: 'integer' },
          minimum_interaction_date: { type: 'integer' },
          maximum_interaction_date: { type: 'integer' },
          minimum_created_date: { type: 'integer' },
          maximum_created_date: { type: 'integer' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/people/search',
        body: {
          name: '{name}',
          emails: '{emails}',
          phone_number: '{phone_number}',
          email_domains: '{email_domains}',
          city: '{city}',
          state: '{state}',
          postal_code: '{postal_code}',
          country: '{country}',
          tags: '{tags}',
          followed: '{followed}',
          age: '{age}',
          minimum_interaction_count: '{minimum_interaction_count}',
          maximum_interaction_count: '{maximum_interaction_count}',
          minimum_interaction_date: '{minimum_interaction_date}',
          maximum_interaction_date: '{maximum_interaction_date}',
          minimum_created_date: '{minimum_created_date}',
          maximum_created_date: '{maximum_created_date}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
    {
      name: 'search.for.alead',
      class: 'read',
      description: 'Search leads by status, monetary value, modified date, or other filters.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          emails: { type: 'array', items: { type: 'string' } },
          phone_number: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          postal_code: { type: 'string' },
          country: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          include_converted_leads: { type: 'boolean' },
          minimum_monetary_value: { type: 'number' },
          maximum_monetary_value: { type: 'number' },
          minimum_modified_date: { type: 'integer' },
          maximum_modified_date: { type: 'integer' },
          minimum_interaction_count: { type: 'integer' },
          maximum_interaction_count: { type: 'integer' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/leads/search',
        body: {
          name: '{name}',
          emails: '{emails}',
          phone_number: '{phone_number}',
          city: '{city}',
          state: '{state}',
          postal_code: '{postal_code}',
          country: '{country}',
          tags: '{tags}',
          include_converted_leads: '{include_converted_leads}',
          minimum_monetary_value: '{minimum_monetary_value}',
          maximum_monetary_value: '{maximum_monetary_value}',
          minimum_modified_date: '{minimum_modified_date}',
          maximum_modified_date: '{maximum_modified_date}',
          minimum_interaction_count: '{minimum_interaction_count}',
          maximum_interaction_count: '{maximum_interaction_count}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
    {
      name: 'search.for.acompany',
      class: 'read',
      description: 'Search companies by name, domain, location, socials, or interaction filters.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          phone_number: { type: 'string' },
          email_domains: { type: 'array', items: { type: 'string' } },
          city: { type: 'string' },
          state: { type: 'string' },
          postal_code: { type: 'string' },
          country: { type: 'string' },
          socials: { type: 'array', items: { type: 'object' } },
          tags: { type: 'array', items: { type: 'string' } },
          followed: { type: 'string' },
          age: { type: 'integer' },
          minimum_interaction_count: { type: 'integer' },
          maximum_interaction_count: { type: 'integer' },
          minimum_interaction_date: { type: 'integer' },
          maximum_interaction_date: { type: 'integer' },
          minimum_created_date: { type: 'integer' },
          maximum_created_date: { type: 'integer' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/companies/search',
        body: {
          name: '{name}',
          phone_number: '{phone_number}',
          email_domains: '{email_domains}',
          city: '{city}',
          state: '{state}',
          postal_code: '{postal_code}',
          country: '{country}',
          socials: '{socials}',
          tags: '{tags}',
          followed: '{followed}',
          age: '{age}',
          minimum_interaction_count: '{minimum_interaction_count}',
          maximum_interaction_count: '{maximum_interaction_count}',
          minimum_interaction_date: '{minimum_interaction_date}',
          maximum_interaction_date: '{maximum_interaction_date}',
          minimum_created_date: '{minimum_created_date}',
          maximum_created_date: '{maximum_created_date}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
    {
      name: 'search.for.an.opportunity',
      class: 'read',
      description: 'Search opportunities by status, priority, stage, close-date, or other filters.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          status_ids: { type: 'array', items: { type: 'string' } },
          priorities: { type: 'array', items: { type: 'string' } },
          pipeline_stage_ids: { type: 'array', items: { type: 'string' } },
          tags: { type: 'array', items: { type: 'string' } },
          followed: { type: 'string' },
          minimum_monetary_value: { type: 'number' },
          maximum_monetary_value: { type: 'number' },
          minimum_close_date: { type: 'integer' },
          maximum_close_date: { type: 'integer' },
          minimum_stage_change_date: { type: 'integer' },
          maximum_stage_change_date: { type: 'integer' },
          minimum_interaction_count: { type: 'integer' },
          maximum_interaction_count: { type: 'integer' },
          minimum_interaction_date: { type: 'integer' },
          maximum_interaction_date: { type: 'integer' },
          minimum_created_date: { type: 'integer' },
          maximum_created_date: { type: 'integer' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/opportunities/search',
        body: {
          name: '{name}',
          status_ids: '{status_ids}',
          priorities: '{priorities}',
          pipeline_stage_ids: '{pipeline_stage_ids}',
          tags: '{tags}',
          followed: '{followed}',
          minimum_monetary_value: '{minimum_monetary_value}',
          maximum_monetary_value: '{maximum_monetary_value}',
          minimum_close_date: '{minimum_close_date}',
          maximum_close_date: '{maximum_close_date}',
          minimum_stage_change_date: '{minimum_stage_change_date}',
          maximum_stage_change_date: '{maximum_stage_change_date}',
          minimum_interaction_count: '{minimum_interaction_count}',
          maximum_interaction_count: '{maximum_interaction_count}',
          minimum_interaction_date: '{minimum_interaction_date}',
          maximum_interaction_date: '{maximum_interaction_date}',
          minimum_created_date: '{minimum_created_date}',
          maximum_created_date: '{maximum_created_date}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
    {
      name: 'search.for.aproject',
      class: 'read',
      description: 'Search projects by name, status, or tag filters.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          status: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          followed: { type: 'string' },
          minimum_interaction_count: { type: 'integer' },
          maximum_interaction_count: { type: 'integer' },
          minimum_interaction_date: { type: 'integer' },
          maximum_interaction_date: { type: 'integer' },
          minimum_created_date: { type: 'integer' },
          maximum_created_date: { type: 'integer' },
          page_size: { type: 'integer', minimum: 1, maximum: 200 },
          page_number: { type: 'integer', minimum: 1 },
          sort_by: { type: 'string' },
          sort_direction: { type: 'string' },
        },
      },
      request: {
        method: 'POST',
        path: '/projects/search',
        body: {
          name: '{name}',
          status: '{status}',
          tags: '{tags}',
          followed: '{followed}',
          minimum_interaction_count: '{minimum_interaction_count}',
          maximum_interaction_count: '{maximum_interaction_count}',
          minimum_interaction_date: '{minimum_interaction_date}',
          maximum_interaction_date: '{maximum_interaction_date}',
          minimum_created_date: '{minimum_created_date}',
          maximum_created_date: '{maximum_created_date}',
          page_size: '{page_size}',
          page_number: '{page_number}',
          sort_by: '{sort_by}',
          sort_direction: '{sort_direction}',
        },
      },
    },
  ],
})
