import { declarativeRestConnector } from './declarative-rest.js'

export const dubConnector = declarativeRestConnector({
  kind: 'dub',
  displayName: 'Dub',
  description:
    'Create, manage, and analyse short links on Dub — the modern link attribution platform for tracking conversions and running affiliate programmes.',
  auth: { kind: 'api-key', hint: 'Dub workspace API key (Bearer token).' },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.dub.co',
  test: { method: 'GET', path: '/links', query: { pageSize: '1' } },
  capabilities: [
    {
      name: 'links.create',
      class: 'mutation',
      description: 'Create a short link.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string' },
          domain: { type: 'string' },
          key: { type: 'string' },
          externalId: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          image: { type: 'string' },
          video: { type: 'string' },
          tagNames: { type: 'array', items: { type: 'string' } },
          folderId: { type: 'string' },
          expiresAt: { type: 'string' },
          expiredUrl: { type: 'string' },
          password: { type: 'string' },
          trackConversion: { type: 'boolean' },
          proxy: { type: 'boolean' },
          rewrite: { type: 'boolean' },
          doIndex: { type: 'boolean' },
          archived: { type: 'boolean' },
          ios: { type: 'string' },
          android: { type: 'string' },
          comments: { type: 'string' },
          utm_source: { type: 'string' },
          utm_medium: { type: 'string' },
          utm_campaign: { type: 'string' },
          utm_term: { type: 'string' },
          utm_content: { type: 'string' },
        },
        required: ['url'],
      },
      request: {
        method: 'POST',
        path: '/links',
        body: {
          url: '{url}',
          domain: '{domain}',
          key: '{key}',
          externalId: '{externalId}',
          title: '{title}',
          description: '{description}',
          image: '{image}',
          video: '{video}',
          tagNames: '{tagNames}',
          folderId: '{folderId}',
          expiresAt: '{expiresAt}',
          expiredUrl: '{expiredUrl}',
          password: '{password}',
          trackConversion: '{trackConversion}',
          proxy: '{proxy}',
          rewrite: '{rewrite}',
          doIndex: '{doIndex}',
          archived: '{archived}',
          ios: '{ios}',
          android: '{android}',
          comments: '{comments}',
          utm_source: '{utm_source}',
          utm_medium: '{utm_medium}',
          utm_campaign: '{utm_campaign}',
          utm_term: '{utm_term}',
          utm_content: '{utm_content}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'links.get',
      class: 'read',
      description: 'Retrieve a short link by link ID, external ID, or domain+key slug.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          externalId: { type: 'string' },
          domain: { type: 'string' },
          key: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/links/info',
        query: {
          linkId: '{linkId}',
          externalId: '{externalId}',
          domain: '{domain}',
          key: '{key}',
        },
      },
    },
    {
      name: 'links.list',
      class: 'read',
      description: 'List or search short links in the workspace.',
      parameters: {
        type: 'object',
        properties: {
          domain: { type: 'string' },
          tagNames: { type: 'array', items: { type: 'string' } },
          search: { type: 'string' },
          userId: { type: 'string' },
          showArchived: { type: 'boolean' },
          page: { type: 'integer' },
          pageSize: { type: 'integer' },
          sort: { type: 'string', enum: ['createdAt', 'clicks', 'lastClicked'] },
        },
      },
      request: {
        method: 'GET',
        path: '/links',
        query: {
          domain: '{domain}',
          tagNames: '{tagNames}',
          search: '{search}',
          userId: '{userId}',
          showArchived: '{showArchived}',
          page: '{page}',
          pageSize: '{pageSize}',
          sort: '{sort}',
        },
      },
    },
    {
      name: 'links.update',
      class: 'mutation',
      description: 'Update an existing short link.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          url: { type: 'string' },
          domain: { type: 'string' },
          key: { type: 'string' },
          externalId: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          image: { type: 'string' },
          video: { type: 'string' },
          tagNames: { type: 'array', items: { type: 'string' } },
          folderId: { type: 'string' },
          expiresAt: { type: 'string' },
          expiredUrl: { type: 'string' },
          password: { type: 'string' },
          trackConversion: { type: 'boolean' },
          proxy: { type: 'boolean' },
          rewrite: { type: 'boolean' },
          doIndex: { type: 'boolean' },
          archived: { type: 'boolean' },
          ios: { type: 'string' },
          android: { type: 'string' },
          comments: { type: 'string' },
          utm_source: { type: 'string' },
          utm_medium: { type: 'string' },
          utm_campaign: { type: 'string' },
          utm_term: { type: 'string' },
          utm_content: { type: 'string' },
        },
        required: ['linkId'],
      },
      request: {
        method: 'PATCH',
        path: '/links/{linkId}',
        body: {
          url: '{url}',
          domain: '{domain}',
          key: '{key}',
          externalId: '{externalId}',
          title: '{title}',
          description: '{description}',
          image: '{image}',
          video: '{video}',
          tagNames: '{tagNames}',
          folderId: '{folderId}',
          expiresAt: '{expiresAt}',
          expiredUrl: '{expiredUrl}',
          password: '{password}',
          trackConversion: '{trackConversion}',
          proxy: '{proxy}',
          rewrite: '{rewrite}',
          doIndex: '{doIndex}',
          archived: '{archived}',
          ios: '{ios}',
          android: '{android}',
          comments: '{comments}',
          utm_source: '{utm_source}',
          utm_medium: '{utm_medium}',
          utm_campaign: '{utm_campaign}',
          utm_term: '{utm_term}',
          utm_content: '{utm_content}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'links.delete',
      class: 'mutation',
      description: 'Delete a short link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'DELETE', path: '/links/{linkId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'tags.create',
      class: 'mutation',
      description: 'Create a tag in the Dub workspace.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Tag name.' },
          color: {
            type: 'string',
            enum: ['red', 'yellow', 'green', 'blue', 'purple', 'pink', 'brown'],
            description: 'Tag colour (Dub palette).',
          },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/tags',
        body: {
          name: '{name}',
          color: '{color}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
