import { declarativeRestConnector } from './declarative-rest.js'

// Enrich Layer is a LinkedIn-data enrichment API (people, companies, schools,
// jobs, reverse-contact lookups). The activepieces piece (@activepieces/piece-
// enrichlayer) is built on top of the v2 REST API at enrichlayer.com. Auth is
// an account API key sent as a bearer token in the Authorization header.
export const enrichlayerConnector = declarativeRestConnector({
  kind: 'enrichlayer',
  displayName: 'Enrich Layer',
  description:
    'LinkedIn-style profile, company, school, and job enrichment. Reverse-lookup contacts by email or phone, search employees, and check disposable email addresses.',
  auth: {
    kind: 'api-key',
    hint: 'Enrich Layer API key from the dashboard. Sent as a bearer token in the Authorization header.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://enrichlayer.com/api/v2',
  credentialPlacement: { kind: 'header', header: 'Authorization', prefix: 'Bearer ' },
  defaultHeaders: {
    accept: 'application/json',
  },
  test: { method: 'GET', path: '/credit-balance' },
  capabilities: [
    {
      name: 'school.profile.get',
      class: 'read',
      description: 'Fetch a LinkedIn school profile by public URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn school profile URL.' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/profile/school',
        query: { url: '{url}', use_cache: '{use_cache}' },
      },
    },
    {
      name: 'company.profile.get',
      class: 'read',
      description: 'Fetch a LinkedIn company profile by public URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn company URL.' },
          categories: { type: 'string', description: 'include | exclude' },
          funding_data: { type: 'string', description: 'include | exclude' },
          exit_data: { type: 'string', description: 'include | exclude' },
          acquisitions: { type: 'string', description: 'include | exclude' },
          extra: { type: 'string', description: 'include | exclude' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/company',
        query: {
          url: '{url}',
          categories: '{categories}',
          funding_data: '{funding_data}',
          exit_data: '{exit_data}',
          acquisitions: '{acquisitions}',
          extra: '{extra}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'person.profile.get',
      class: 'read',
      description: 'Fetch a LinkedIn person profile by public URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn profile URL.' },
          skills: { type: 'string', description: 'include | exclude' },
          inferred_salary: { type: 'string', description: 'include | exclude' },
          personal_email: { type: 'string', description: 'include | exclude' },
          personal_contact_number: { type: 'string', description: 'include | exclude' },
          twitter_profile_id: { type: 'string' },
          facebook_profile_id: { type: 'string' },
          github_profile_id: { type: 'string' },
          extra: { type: 'string', description: 'include | exclude' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/profile',
        query: {
          url: '{url}',
          skills: '{skills}',
          inferred_salary: '{inferred_salary}',
          personal_email: '{personal_email}',
          personal_contact_number: '{personal_contact_number}',
          twitter_profile_id: '{twitter_profile_id}',
          facebook_profile_id: '{facebook_profile_id}',
          github_profile_id: '{github_profile_id}',
          extra: '{extra}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'company.lookup',
      class: 'read',
      description: 'Lookup a company by name, domain, or LinkedIn slug.',
      parameters: {
        type: 'object',
        properties: {
          company_domain: { type: 'string' },
          company_name: { type: 'string' },
          company_location: { type: 'string' },
          enrich_profile: { type: 'string', description: 'enrich | skip' },
        },
      },
      request: {
        method: 'GET',
        path: '/company/resolve',
        query: {
          company_domain: '{company_domain}',
          company_name: '{company_name}',
          company_location: '{company_location}',
          enrich_profile: '{enrich_profile}',
        },
      },
    },
    {
      name: 'company.id.lookup',
      class: 'read',
      description: 'Resolve a LinkedIn internal company id from a company URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn company URL.' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/company/profile-id',
        query: { url: '{url}' },
      },
    },
    {
      name: 'company.picture.get',
      class: 'read',
      description: 'Get a temporary URL to a company profile picture.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_company_profile_url: { type: 'string' },
        },
        required: ['linkedin_company_profile_url'],
      },
      request: {
        method: 'GET',
        path: '/company/profile-picture',
        query: { linkedin_company_profile_url: '{linkedin_company_profile_url}' },
      },
    },
    {
      name: 'person.picture.get',
      class: 'read',
      description: 'Get a temporary URL to a person profile picture.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_person_profile_url: { type: 'string' },
        },
        required: ['linkedin_person_profile_url'],
      },
      request: {
        method: 'GET',
        path: '/profile/profile-picture',
        query: { linkedin_person_profile_url: '{linkedin_person_profile_url}' },
      },
    },
    {
      name: 'employee.listing',
      class: 'read',
      description: 'List employees of a company by LinkedIn URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn company URL.' },
          country: { type: 'string' },
          enrich_profiles: { type: 'string', description: 'enrich | skip' },
          role_search: { type: 'string', description: 'Regex of role titles to match.' },
          page_size: { type: 'integer', minimum: 1, maximum: 200000 },
          employment_status: { type: 'string', description: 'current | past | all' },
          sort_by: { type: 'string', description: 'recently-joined | recently-left | oldest | none' },
          resolve_numeric_id: { type: 'boolean' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/company/employees',
        query: {
          url: '{url}',
          country: '{country}',
          enrich_profiles: '{enrich_profiles}',
          role_search: '{role_search}',
          page_size: '{page_size}',
          employment_status: '{employment_status}',
          sort_by: '{sort_by}',
          resolve_numeric_id: '{resolve_numeric_id}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'employee.count',
      class: 'read',
      description: 'Get employee headcount estimate for a company.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn company URL.' },
          linkedin_employee_count: { type: 'string', description: 'include | exclude' },
          employment_status: { type: 'string', description: 'current | past | all' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/company/employees/count',
        query: {
          url: '{url}',
          linkedin_employee_count: '{linkedin_employee_count}',
          employment_status: '{employment_status}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'employee.search',
      class: 'read',
      description: 'Search a company\'s employee list by keyword/role.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_company_profile_url: { type: 'string' },
          keyword_regex: { type: 'string' },
          page_size: { type: 'integer', minimum: 1, maximum: 200000 },
          country: { type: 'string' },
          enrich_profiles: { type: 'string', description: 'enrich | skip' },
          resolve_numeric_id: { type: 'boolean' },
        },
        required: ['linkedin_company_profile_url', 'keyword_regex'],
      },
      request: {
        method: 'GET',
        path: '/company/employees/search',
        query: {
          linkedin_company_profile_url: '{linkedin_company_profile_url}',
          keyword_regex: '{keyword_regex}',
          page_size: '{page_size}',
          country: '{country}',
          enrich_profiles: '{enrich_profiles}',
          resolve_numeric_id: '{resolve_numeric_id}',
        },
      },
    },
    {
      name: 'person.lookup',
      class: 'read',
      description: 'Resolve a person by name + company hints to a LinkedIn profile.',
      parameters: {
        type: 'object',
        properties: {
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          company_domain: { type: 'string' },
          location: { type: 'string' },
          title: { type: 'string' },
          enrich_profile: { type: 'string', description: 'enrich | skip' },
        },
        required: ['first_name', 'company_domain'],
      },
      request: {
        method: 'GET',
        path: '/profile/resolve',
        query: {
          first_name: '{first_name}',
          last_name: '{last_name}',
          company_domain: '{company_domain}',
          location: '{location}',
          title: '{title}',
          enrich_profile: '{enrich_profile}',
        },
      },
    },
    {
      name: 'role.lookup',
      class: 'read',
      description: 'Find a person currently holding a given role at a company.',
      parameters: {
        type: 'object',
        properties: {
          role: { type: 'string', description: 'Role/title to search for.' },
          company_name: { type: 'string' },
          enrich_profile: { type: 'string', description: 'enrich | skip' },
        },
        required: ['role', 'company_name'],
      },
      request: {
        method: 'GET',
        path: '/find/company/role',
        query: {
          role: '{role}',
          company_name: '{company_name}',
          enrich_profile: '{enrich_profile}',
        },
      },
    },
    {
      name: 'reverse.email.lookup',
      class: 'read',
      description: 'Reverse-lookup a LinkedIn profile from a work or personal email.',
      parameters: {
        type: 'object',
        properties: {
          work_email: { type: 'string' },
          enrich_profile: { type: 'string', description: 'enrich | skip' },
          lookup_depth: { type: 'string', description: 'superficial | deep' },
        },
        required: ['work_email'],
      },
      request: {
        method: 'GET',
        path: '/profile/resolve/email',
        query: {
          work_email: '{work_email}',
          enrich_profile: '{enrich_profile}',
          lookup_depth: '{lookup_depth}',
        },
      },
    },
    {
      name: 'reverse.phone.lookup',
      class: 'read',
      description: 'Reverse-lookup public profiles (LinkedIn, Twitter, Facebook) from a phone number.',
      parameters: {
        type: 'object',
        properties: {
          phone_number: { type: 'string', description: 'E.164-formatted phone number.' },
        },
        required: ['phone_number'],
      },
      request: {
        method: 'GET',
        path: '/resolve/phone',
        query: { phone_number: '{phone_number}' },
      },
    },
    {
      name: 'work.email.lookup',
      class: 'read',
      description: 'Find a work email address for a LinkedIn person profile.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_profile_url: { type: 'string' },
          callback_url: { type: 'string', description: 'Webhook URL for async result delivery.' },
        },
        required: ['linkedin_profile_url'],
      },
      request: {
        method: 'GET',
        path: '/profile/email',
        query: {
          linkedin_profile_url: '{linkedin_profile_url}',
          callback_url: '{callback_url}',
        },
      },
    },
    {
      name: 'personal.contact.lookup',
      class: 'read',
      description: 'Find personal contact numbers for a LinkedIn person profile.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_profile_url: { type: 'string' },
          page_size: { type: 'integer', minimum: 1, maximum: 10 },
        },
        required: ['linkedin_profile_url'],
      },
      request: {
        method: 'GET',
        path: '/contact-api/personal-contact',
        query: {
          linkedin_profile_url: '{linkedin_profile_url}',
          page_size: '{page_size}',
        },
      },
    },
    {
      name: 'personal.email.lookup',
      class: 'read',
      description: 'Find personal email addresses for a LinkedIn person profile.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_profile_url: { type: 'string' },
          email_validation: { type: 'string', description: 'include | exclude' },
          page_size: { type: 'integer', minimum: 1, maximum: 10 },
        },
        required: ['linkedin_profile_url'],
      },
      request: {
        method: 'GET',
        path: '/contact-api/personal-email',
        query: {
          linkedin_profile_url: '{linkedin_profile_url}',
          email_validation: '{email_validation}',
          page_size: '{page_size}',
        },
      },
    },
    {
      name: 'disposable.email.check',
      class: 'read',
      description: 'Check whether an email address belongs to a disposable provider.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
        },
        required: ['email'],
      },
      request: {
        method: 'GET',
        path: '/disposable-email',
        query: { email: '{email}' },
      },
    },
    {
      name: 'student.listing',
      class: 'read',
      description: 'List alumni/students for a LinkedIn school profile.',
      parameters: {
        type: 'object',
        properties: {
          linkedin_school_url: { type: 'string' },
          country: { type: 'string' },
          enrich_profiles: { type: 'string', description: 'enrich | skip' },
          search_keyword: { type: 'string' },
          page_size: { type: 'integer', minimum: 1, maximum: 15000 },
          student_status: { type: 'string', description: 'current | past | all' },
          sort_by: { type: 'string', description: 'recently-started | recently-finished | none' },
          resolve_numeric_id: { type: 'boolean' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
        required: ['linkedin_school_url'],
      },
      request: {
        method: 'GET',
        path: '/school/students',
        query: {
          linkedin_school_url: '{linkedin_school_url}',
          country: '{country}',
          enrich_profiles: '{enrich_profiles}',
          search_keyword: '{search_keyword}',
          page_size: '{page_size}',
          student_status: '{student_status}',
          sort_by: '{sort_by}',
          resolve_numeric_id: '{resolve_numeric_id}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'job.profile.get',
      class: 'read',
      description: 'Fetch a single LinkedIn job posting by URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'LinkedIn job posting URL.' },
        },
        required: ['url'],
      },
      request: {
        method: 'GET',
        path: '/job',
        query: { url: '{url}' },
      },
    },
    {
      name: 'job.search',
      class: 'read',
      description: 'Search job postings for a LinkedIn company by job type, region, and experience.',
      parameters: {
        type: 'object',
        properties: {
          search_id: { type: 'string', description: 'LinkedIn company numeric id.' },
          job_type: { type: 'string', description: 'full-time | part-time | contract | internship | temporary | volunteer | other' },
          experience_level: { type: 'string', description: 'internship | entry_level | associate | mid_senior_level | director' },
          when: { type: 'string', description: 'yesterday | past-week | past-month | anytime' },
          flexibility: { type: 'string', description: 'remote | on-site | hybrid' },
          geo_id: { type: 'string', description: 'LinkedIn geo URN identifier.' },
          keyword: { type: 'string' },
        },
        required: ['search_id'],
      },
      request: {
        method: 'GET',
        path: '/company/job',
        query: {
          search_id: '{search_id}',
          job_type: '{job_type}',
          experience_level: '{experience_level}',
          when: '{when}',
          flexibility: '{flexibility}',
          geo_id: '{geo_id}',
          keyword: '{keyword}',
        },
      },
    },
    {
      name: 'job.count',
      class: 'read',
      description: 'Get the count of job postings for a LinkedIn company.',
      parameters: {
        type: 'object',
        properties: {
          search_id: { type: 'string' },
          job_type: { type: 'string' },
          experience_level: { type: 'string' },
          when: { type: 'string' },
          flexibility: { type: 'string' },
          geo_id: { type: 'string' },
          keyword: { type: 'string' },
        },
        required: ['search_id'],
      },
      request: {
        method: 'GET',
        path: '/company/job/count',
        query: {
          search_id: '{search_id}',
          job_type: '{job_type}',
          experience_level: '{experience_level}',
          when: '{when}',
          flexibility: '{flexibility}',
          geo_id: '{geo_id}',
          keyword: '{keyword}',
        },
      },
    },
    {
      name: 'company.search',
      class: 'read',
      description: 'Search the company database by industry, headcount, country, or follower range.',
      parameters: {
        type: 'object',
        properties: {
          country: { type: 'string' },
          region: { type: 'string' },
          city: { type: 'string' },
          name: { type: 'string' },
          industry: { type: 'string' },
          employee_count_min: { type: 'integer', minimum: 0 },
          employee_count_max: { type: 'integer', minimum: 0 },
          follower_count_min: { type: 'integer', minimum: 0 },
          follower_count_max: { type: 'integer', minimum: 0 },
          founded_after_year: { type: 'integer' },
          founded_before_year: { type: 'integer' },
          funding_amount_max: { type: 'integer', minimum: 0 },
          funding_amount_min: { type: 'integer', minimum: 0 },
          funding_raised_after: { type: 'string', description: 'YYYY-MM-DD' },
          funding_raised_before: { type: 'string', description: 'YYYY-MM-DD' },
          public_identifier_in_list: { type: 'string' },
          public_identifier_not_in_list: { type: 'string' },
          page_size: { type: 'integer', minimum: 1, maximum: 100 },
          enrich_profiles: { type: 'string', description: 'enrich | skip' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
      },
      request: {
        method: 'GET',
        path: '/search/company',
        query: {
          country: '{country}',
          region: '{region}',
          city: '{city}',
          name: '{name}',
          industry: '{industry}',
          employee_count_min: '{employee_count_min}',
          employee_count_max: '{employee_count_max}',
          follower_count_min: '{follower_count_min}',
          follower_count_max: '{follower_count_max}',
          founded_after_year: '{founded_after_year}',
          founded_before_year: '{founded_before_year}',
          funding_amount_max: '{funding_amount_max}',
          funding_amount_min: '{funding_amount_min}',
          funding_raised_after: '{funding_raised_after}',
          funding_raised_before: '{funding_raised_before}',
          public_identifier_in_list: '{public_identifier_in_list}',
          public_identifier_not_in_list: '{public_identifier_not_in_list}',
          page_size: '{page_size}',
          enrich_profiles: '{enrich_profiles}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'person.search',
      class: 'read',
      description: 'Search the people database by current role, education, industry, or skills.',
      parameters: {
        type: 'object',
        properties: {
          country: { type: 'string' },
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          education_field_of_study: { type: 'string' },
          education_degree_name: { type: 'string' },
          education_school_name: { type: 'string' },
          education_school_linkedin_profile_url: { type: 'string' },
          current_role_title: { type: 'string' },
          past_role_title: { type: 'string' },
          current_role_before: { type: 'string', description: 'YYYY-MM-DD' },
          current_role_after: { type: 'string', description: 'YYYY-MM-DD' },
          current_company_linkedin_profile_url: { type: 'string' },
          past_company_linkedin_profile_url: { type: 'string' },
          current_job_description: { type: 'string' },
          past_job_description: { type: 'string' },
          current_company_name: { type: 'string' },
          past_company_name: { type: 'string' },
          linkedin_groups: { type: 'string' },
          languages: { type: 'string' },
          region: { type: 'string' },
          city: { type: 'string' },
          headline: { type: 'string' },
          summary: { type: 'string' },
          industries: { type: 'string' },
          interests: { type: 'string' },
          skills: { type: 'string' },
          current_company_country: { type: 'string' },
          current_company_region: { type: 'string' },
          current_company_city: { type: 'string' },
          current_company_type: { type: 'string' },
          current_company_follower_count_min: { type: 'integer', minimum: 0 },
          current_company_follower_count_max: { type: 'integer', minimum: 0 },
          current_company_industry: { type: 'string' },
          current_company_employee_count_min: { type: 'integer', minimum: 0 },
          current_company_employee_count_max: { type: 'integer', minimum: 0 },
          current_company_description: { type: 'string' },
          current_company_founded_after_year: { type: 'integer' },
          current_company_founded_before_year: { type: 'integer' },
          current_company_funding_amount_min: { type: 'integer', minimum: 0 },
          current_company_funding_amount_max: { type: 'integer', minimum: 0 },
          current_company_funding_raised_after: { type: 'string' },
          current_company_funding_raised_before: { type: 'string' },
          public_identifier_in_list: { type: 'string' },
          public_identifier_not_in_list: { type: 'string' },
          page_size: { type: 'integer', minimum: 1, maximum: 100 },
          enrich_profiles: { type: 'string', description: 'enrich | skip' },
          use_cache: { type: 'string', description: 'if-present | if-recent' },
        },
      },
      request: {
        method: 'GET',
        path: '/search/person',
        query: {
          country: '{country}',
          first_name: '{first_name}',
          last_name: '{last_name}',
          education_field_of_study: '{education_field_of_study}',
          education_degree_name: '{education_degree_name}',
          education_school_name: '{education_school_name}',
          education_school_linkedin_profile_url: '{education_school_linkedin_profile_url}',
          current_role_title: '{current_role_title}',
          past_role_title: '{past_role_title}',
          current_role_before: '{current_role_before}',
          current_role_after: '{current_role_after}',
          current_company_linkedin_profile_url: '{current_company_linkedin_profile_url}',
          past_company_linkedin_profile_url: '{past_company_linkedin_profile_url}',
          current_job_description: '{current_job_description}',
          past_job_description: '{past_job_description}',
          current_company_name: '{current_company_name}',
          past_company_name: '{past_company_name}',
          linkedin_groups: '{linkedin_groups}',
          languages: '{languages}',
          region: '{region}',
          city: '{city}',
          headline: '{headline}',
          summary: '{summary}',
          industries: '{industries}',
          interests: '{interests}',
          skills: '{skills}',
          current_company_country: '{current_company_country}',
          current_company_region: '{current_company_region}',
          current_company_city: '{current_company_city}',
          current_company_type: '{current_company_type}',
          current_company_follower_count_min: '{current_company_follower_count_min}',
          current_company_follower_count_max: '{current_company_follower_count_max}',
          current_company_industry: '{current_company_industry}',
          current_company_employee_count_min: '{current_company_employee_count_min}',
          current_company_employee_count_max: '{current_company_employee_count_max}',
          current_company_description: '{current_company_description}',
          current_company_founded_after_year: '{current_company_founded_after_year}',
          current_company_founded_before_year: '{current_company_founded_before_year}',
          current_company_funding_amount_min: '{current_company_funding_amount_min}',
          current_company_funding_amount_max: '{current_company_funding_amount_max}',
          current_company_funding_raised_after: '{current_company_funding_raised_after}',
          current_company_funding_raised_before: '{current_company_funding_raised_before}',
          public_identifier_in_list: '{public_identifier_in_list}',
          public_identifier_not_in_list: '{public_identifier_not_in_list}',
          page_size: '{page_size}',
          enrich_profiles: '{enrich_profiles}',
          use_cache: '{use_cache}',
        },
      },
    },
    {
      name: 'credit.balance.get',
      class: 'read',
      description: 'Get the remaining API credit balance for the account.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/credit-balance' },
    },
  ],
})
