import { declarativeRestConnector } from './declarative-rest.js'

export const exaConnector = declarativeRestConnector({
  kind: 'exa',
  displayName: 'Exa',
  description: 'AI-powered search and content extraction from the web.',
  auth: { kind: 'api-key', hint: 'Exa API key.' },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.exa.ai',
  test: { method: 'POST', path: '/search', body: { query: 'test', numResults: 1 } },
  capabilities: [
    {
      name: 'search.perform',
      class: 'read',
      description: 'Perform a semantic or keyword search.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'Search query' },
          numResults: { type: 'integer', description: 'Number of results to return (max 100)' },
          includeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to include' },
          excludeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to exclude' },
          startCrawlDate: { type: 'string', description: 'Start crawl date (ISO format)' },
          endCrawlDate: { type: 'string', description: 'End crawl date (ISO format)' },
          startPublishedDate: { type: 'string', description: 'Start published date (ISO format)' },
          endPublishedDate: { type: 'string', description: 'End published date (ISO format)' },
          includeText: { type: 'string', description: 'Strings that must be present in webpage text' },
          excludeText: { type: 'string', description: 'Strings that must not be present in webpage text' },
          type: { type: 'string', enum: ['keyword', 'neural'], description: 'Type of search to perform' },
          category: { type: 'string', description: 'Category of data to focus the search on' },
        },
        required: ['query'],
      },
      request: {
        method: 'POST',
        path: '/search',
        body: {
          query: '{query}',
          numResults: '{numResults}',
          includeDomains: '{includeDomains}',
          excludeDomains: '{excludeDomains}',
          startCrawlDate: '{startCrawlDate}',
          endCrawlDate: '{endCrawlDate}',
          startPublishedDate: '{startPublishedDate}',
          endPublishedDate: '{endPublishedDate}',
          includeText: '{includeText}',
          excludeText: '{excludeText}',
          type: '{type}',
          category: '{category}',
        },
      },
    },
    {
      name: 'search.similar',
      class: 'read',
      description: 'Find semantically similar links based on a URL.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'Reference URL to find semantically similar links' },
          numResults: { type: 'integer', description: 'Number of results to return (max 100)' },
          includeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to include' },
          excludeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to exclude' },
          startCrawlDate: { type: 'string', description: 'Start crawl date (ISO format)' },
          endCrawlDate: { type: 'string', description: 'End crawl date (ISO format)' },
          startPublishedDate: { type: 'string', description: 'Start published date (ISO format)' },
          endPublishedDate: { type: 'string', description: 'End published date (ISO format)' },
        },
        required: ['url'],
      },
      request: {
        method: 'POST',
        path: '/findSimilar',
        body: {
          url: '{url}',
          numResults: '{numResults}',
          includeDomains: '{includeDomains}',
          excludeDomains: '{excludeDomains}',
          startCrawlDate: '{startCrawlDate}',
          endCrawlDate: '{endCrawlDate}',
          startPublishedDate: '{startPublishedDate}',
          endPublishedDate: '{endPublishedDate}',
        },
      },
    },
    {
      name: 'contents.get',
      class: 'read',
      description: 'Get the full text contents from URLs.',
      parameters: {
        type: 'object',
        properties: {
          urls: { type: 'array', items: { type: 'string' }, description: 'Array of URLs to crawl' },
          livecrawl: { type: 'string', enum: ['always', 'never', 'fallback'], description: 'Livecrawl option' },
          livecrawlTimeout: { type: 'integer', description: 'Timeout for livecrawling in milliseconds' },
          subpages: { type: 'integer', description: 'Number of subpages to crawl' },
          subpageTarget: { type: 'string', description: 'Keyword(s) to find specific subpages' },
        },
        required: ['urls'],
      },
      request: {
        method: 'POST',
        path: '/contents',
        body: {
          urls: '{urls}',
          livecrawl: '{livecrawl}',
          livecrawlTimeout: '{livecrawlTimeout}',
          subpages: '{subpages}',
          subpageTarget: '{subpageTarget}',
        },
      },
    },
    {
      name: 'answer.generate',
      class: 'read',
      description: 'Generate a summarized answer from the web based on a query.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string', description: 'Question to answer from the web' },
          model: { type: 'string', enum: ['claude-3-5-sonnet', 'gpt-4o'], description: 'Model to use for the answer' },
          numResults: { type: 'integer', description: 'Number of web results to base the answer on' },
          includeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to include' },
          excludeDomains: { type: 'array', items: { type: 'string' }, description: 'List of domains to exclude' },
          text: { type: 'boolean', description: 'If true, includes full text content from search results' },
        },
        required: ['query', 'model'],
      },
      request: {
        method: 'POST',
        path: '/generateAnswer',
        body: {
          query: '{query}',
          model: '{model}',
          numResults: '{numResults}',
          includeDomains: '{includeDomains}',
          excludeDomains: '{excludeDomains}',
          text: '{text}',
        },
      },
    },
  ],
})
