import { declarativeRestConnector } from './declarative-rest.js'

// Flowlu exposes a per-account REST host of the form
// https://{account}.flowlu.com/api/v1 — the connection-time `baseUrl` metadata
// field holds the resolved host root, and the API key is appended as the
// `api_key` query parameter on every call.
export const flowluConnector = declarativeRestConnector({
  kind: 'flowlu',
  displayName: 'Flowlu',
  description:
    'Manage Flowlu CRM contacts, organizations, opportunities, and tasks in the business management platform.',
  auth: {
    kind: 'api-key',
    hint: 'Flowlu API key from Portal Settings → API. The connection must also store the per-account baseUrl (e.g. https://youraccount.flowlu.com/api/v1).',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'baseUrl' },
  credentialPlacement: { kind: 'query', parameter: 'api_key' },
  test: { method: 'GET', path: '/module/crm/account/list' },
  capabilities: [
    {
      name: 'contact.create',
      class: 'mutation',
      description: 'Create a contact (individual account) in Flowlu CRM.',
      parameters: {
        type: 'object',
        properties: {
          first_name: { type: 'string' },
          middle_name: { type: 'string' },
          last_name: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          web: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'integer', enum: [0, 1] },
        },
        required: ['first_name'],
      },
      request: {
        method: 'POST',
        path: '/module/crm/account/create',
        body: {
          first_name: '{first_name}',
          middle_name: '{middle_name}',
          last_name: '{last_name}',
          email: '{email}',
          phone: '{phone}',
          web: '{web}',
          description: '{description}',
          active: '{active}',
          type: 1,
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contact.update',
      class: 'mutation',
      description: 'Update an existing contact by id.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'integer' },
          first_name: { type: 'string' },
          middle_name: { type: 'string' },
          last_name: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          web: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'integer', enum: [0, 1] },
        },
        required: ['id'],
      },
      request: {
        method: 'POST',
        path: '/module/crm/account/update/{id}',
        body: {
          first_name: '{first_name}',
          middle_name: '{middle_name}',
          last_name: '{last_name}',
          email: '{email}',
          phone: '{phone}',
          web: '{web}',
          description: '{description}',
          active: '{active}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'contact.delete',
      class: 'mutation',
      description: 'Delete a contact by id.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'integer' } },
        required: ['id'],
      },
      request: { method: 'POST', path: '/module/crm/account/delete/{id}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'organization.create',
      class: 'mutation',
      description: 'Create an organization (company account) in Flowlu CRM.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          name_legal_full: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          web: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'integer', enum: [0, 1] },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/module/crm/account/create',
        body: {
          name: '{name}',
          name_legal_full: '{name_legal_full}',
          email: '{email}',
          phone: '{phone}',
          web: '{web}',
          description: '{description}',
          active: '{active}',
          type: 2,
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'opportunity.create',
      class: 'mutation',
      description: 'Create an opportunity (CRM lead) in Flowlu.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          customer_id: { type: 'integer' },
          budget: { type: 'number' },
          pipeline_id: { type: 'integer' },
          pipeline_stage_id: { type: 'integer' },
          source_id: { type: 'integer' },
          description: { type: 'string' },
          responsible_id: { type: 'integer' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/module/crm/lead/create',
        body: {
          name: '{name}',
          customer_id: '{customer_id}',
          budget: '{budget}',
          pipeline_id: '{pipeline_id}',
          pipeline_stage_id: '{pipeline_stage_id}',
          source_id: '{source_id}',
          description: '{description}',
          responsible_id: '{responsible_id}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'opportunity.update',
      class: 'mutation',
      description: 'Update an existing opportunity by id.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'integer' },
          name: { type: 'string' },
          customer_id: { type: 'integer' },
          budget: { type: 'number' },
          pipeline_id: { type: 'integer' },
          pipeline_stage_id: { type: 'integer' },
          source_id: { type: 'integer' },
          description: { type: 'string' },
          responsible_id: { type: 'integer' },
        },
        required: ['id'],
      },
      request: {
        method: 'POST',
        path: '/module/crm/lead/update/{id}',
        body: {
          name: '{name}',
          customer_id: '{customer_id}',
          budget: '{budget}',
          pipeline_id: '{pipeline_id}',
          pipeline_stage_id: '{pipeline_stage_id}',
          source_id: '{source_id}',
          description: '{description}',
          responsible_id: '{responsible_id}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'opportunity.delete',
      class: 'mutation',
      description: 'Delete an opportunity by id.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'integer' } },
        required: ['id'],
      },
      request: { method: 'POST', path: '/module/crm/lead/delete/{id}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'task.create',
      class: 'mutation',
      description: 'Create a task in Flowlu.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          deadline: { type: 'string' },
          priority: { type: 'integer' },
          responsible_id: { type: 'integer' },
          owner_id: { type: 'integer' },
          workflow_id: { type: 'integer' },
          workflow_stage_id: { type: 'integer' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/module/task/tasks/create',
        body: {
          name: '{name}',
          description: '{description}',
          deadline: '{deadline}',
          priority: '{priority}',
          responsible_id: '{responsible_id}',
          owner_id: '{owner_id}',
          workflow_id: '{workflow_id}',
          workflow_stage_id: '{workflow_stage_id}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'task.update',
      class: 'mutation',
      description: 'Update an existing task by id.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'integer' },
          name: { type: 'string' },
          description: { type: 'string' },
          deadline: { type: 'string' },
          priority: { type: 'integer' },
          responsible_id: { type: 'integer' },
          owner_id: { type: 'integer' },
          workflow_id: { type: 'integer' },
          workflow_stage_id: { type: 'integer' },
        },
        required: ['id'],
      },
      request: {
        method: 'POST',
        path: '/module/task/tasks/update/{id}',
        body: {
          name: '{name}',
          description: '{description}',
          deadline: '{deadline}',
          priority: '{priority}',
          responsible_id: '{responsible_id}',
          owner_id: '{owner_id}',
          workflow_id: '{workflow_id}',
          workflow_stage_id: '{workflow_stage_id}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'task.delete',
      class: 'mutation',
      description: 'Delete a task by id.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'integer' } },
        required: ['id'],
      },
      request: { method: 'POST', path: '/module/task/tasks/delete/{id}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'task.get',
      class: 'read',
      description: 'Read a single task by id.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'integer' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/module/task/tasks/get/{id}' },
    },
  ],
})
