import { declarativeRestConnector } from './declarative-rest.js'

// Freshsales (Freshworks CRM) REST API is scoped to a per-tenant bundle
// subdomain (https://{bundleAlias}.myfreshworks.com/crm/sales/api). The
// orchestrator stores the resolved host under connection metadata key
// `bundleUrl` so the executor can substitute it at call time. Auth is a
// per-tenant API token sent as `Authorization: Token token=<key>`; the
// declarative-rest runtime handles api-key header binding.

export const freshsalesConnector = declarativeRestConnector({
  kind: 'freshsales',
  displayName: 'Freshsales',
  description:
    'Search, read, create, and update Freshsales (Freshworks CRM) contacts, accounts, leads, and deals.',
  auth: {
    kind: 'api-key',
    hint: 'Freshsales API token from Settings > API Settings. Used as `Authorization: Token token=<key>`.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'bundleUrl' },
  test: { method: 'GET', path: '/crm/sales/api/selector/owners' },
  capabilities: [
    {
      name: 'contacts.create',
      class: 'mutation',
      description:
        'Create a Freshsales contact. Maps to the activepieces `fresh.sales.create.contact` action. Pass any subset of contact fields (first_name, last_name, email, job_title, work_number, mobile_number, address, city, state, zipcode, country, territory_id, owner_id, subscription_status, medium, campaign_id, keyword, time_zone, facebook, twitter, linkedin, contact_status_id, sales_account_id).',
      parameters: {
        type: 'object',
        properties: {
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          job_title: { type: 'string' },
          email: { type: 'string' },
          work_number: { type: 'string' },
          mobile_number: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          country: { type: 'string' },
          territory_id: { type: 'string' },
          owner_id: { type: 'string' },
          subscription_status: { type: 'string' },
          medium: { type: 'string' },
          campaign_id: { type: 'string' },
          keyword: { type: 'string' },
          time_zone: { type: 'string' },
          facebook: { type: 'string' },
          twitter: { type: 'string' },
          linkedin: { type: 'string' },
          contact_status_id: { type: 'string' },
          sales_account_id: { type: 'string' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/crm/sales/api/contacts',
        body: { contact: 'args' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.get',
      class: 'read',
      description: 'Read a single Freshsales contact by id.',
      parameters: {
        type: 'object',
        properties: { contactId: { type: 'string' } },
        required: ['contactId'],
      },
      request: { method: 'GET', path: '/crm/sales/api/contacts/{contactId}' },
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description:
        'Update a Freshsales contact. Pass any subset of mutable contact fields plus contactId.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          job_title: { type: 'string' },
          email: { type: 'string' },
          work_number: { type: 'string' },
          mobile_number: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          country: { type: 'string' },
          territory_id: { type: 'string' },
          owner_id: { type: 'string' },
          subscription_status: { type: 'string' },
          medium: { type: 'string' },
          campaign_id: { type: 'string' },
          keyword: { type: 'string' },
          time_zone: { type: 'string' },
          facebook: { type: 'string' },
          twitter: { type: 'string' },
          linkedin: { type: 'string' },
          contact_status_id: { type: 'string' },
          sales_account_id: { type: 'string' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'PUT',
        path: '/crm/sales/api/contacts/{contactId}',
        body: { contact: 'args' },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'contacts.search',
      class: 'read',
      description:
        'Search Freshsales contacts using the lookup endpoint (typically by email, phone, or mobile_number).',
      parameters: {
        type: 'object',
        properties: {
          q: { type: 'string' },
          f: { type: 'string', description: 'Field to lookup against (email, phone, mobile_number, etc.).' },
          entities: { type: 'string', description: 'Comma-separated entity types to search; defaults to contact.' },
        },
        required: ['q', 'f'],
      },
      request: {
        method: 'GET',
        path: '/crm/sales/api/lookup',
        query: { q: '{q}', f: '{f}', entities: '{entities}' },
      },
    },
    {
      name: 'accounts.create',
      class: 'mutation',
      description: 'Create a Freshsales sales account.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          website: { type: 'string' },
          phone: { type: 'string' },
          industry_type_id: { type: 'string' },
          business_type_id: { type: 'string' },
          number_of_employees: { type: 'integer' },
          annual_revenue: { type: 'number' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          country: { type: 'string' },
          owner_id: { type: 'string' },
          territory_id: { type: 'string' },
          parent_sales_account_id: { type: 'string' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/crm/sales/api/sales_accounts',
        body: { sales_account: 'args' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'accounts.get',
      class: 'read',
      description: 'Read a single Freshsales sales account by id.',
      parameters: {
        type: 'object',
        properties: { accountId: { type: 'string' } },
        required: ['accountId'],
      },
      request: { method: 'GET', path: '/crm/sales/api/sales_accounts/{accountId}' },
    },
    {
      name: 'accounts.update',
      class: 'mutation',
      description: 'Update a Freshsales sales account.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          name: { type: 'string' },
          website: { type: 'string' },
          phone: { type: 'string' },
          industry_type_id: { type: 'string' },
          business_type_id: { type: 'string' },
          number_of_employees: { type: 'integer' },
          annual_revenue: { type: 'number' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          country: { type: 'string' },
          owner_id: { type: 'string' },
          territory_id: { type: 'string' },
        },
        required: ['accountId'],
      },
      request: {
        method: 'PUT',
        path: '/crm/sales/api/sales_accounts/{accountId}',
        body: { sales_account: 'args' },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.create',
      class: 'mutation',
      description: 'Create a Freshsales lead.',
      parameters: {
        type: 'object',
        properties: {
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          email: { type: 'string' },
          job_title: { type: 'string' },
          company: { type: 'string' },
          work_number: { type: 'string' },
          mobile_number: { type: 'string' },
          owner_id: { type: 'string' },
          source_id: { type: 'string' },
          lead_stage_id: { type: 'string' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/crm/sales/api/leads',
        body: { lead: 'args' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.get',
      class: 'read',
      description: 'Read a single Freshsales lead by id.',
      parameters: {
        type: 'object',
        properties: { leadId: { type: 'string' } },
        required: ['leadId'],
      },
      request: { method: 'GET', path: '/crm/sales/api/leads/{leadId}' },
    },
    {
      name: 'deals.create',
      class: 'mutation',
      description: 'Create a Freshsales deal.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          amount: { type: 'number' },
          base_currency_amount: { type: 'number' },
          expected_close: { type: 'string', description: 'ISO date.' },
          closed_date: { type: 'string' },
          probability: { type: 'integer' },
          deal_stage_id: { type: 'string' },
          deal_pipeline_id: { type: 'string' },
          owner_id: { type: 'string' },
          contacts_added_list: { type: 'array', items: { type: 'string' } },
          sales_account_id: { type: 'string' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/crm/sales/api/deals',
        body: { deal: 'args' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'deals.get',
      class: 'read',
      description: 'Read a single Freshsales deal by id.',
      parameters: {
        type: 'object',
        properties: { dealId: { type: 'string' } },
        required: ['dealId'],
      },
      request: { method: 'GET', path: '/crm/sales/api/deals/{dealId}' },
    },
    {
      name: 'deals.update',
      class: 'mutation',
      description: 'Update a Freshsales deal (stage, amount, expected_close, owner, etc.).',
      parameters: {
        type: 'object',
        properties: {
          dealId: { type: 'string' },
          name: { type: 'string' },
          amount: { type: 'number' },
          expected_close: { type: 'string' },
          closed_date: { type: 'string' },
          probability: { type: 'integer' },
          deal_stage_id: { type: 'string' },
          deal_pipeline_id: { type: 'string' },
          owner_id: { type: 'string' },
          sales_account_id: { type: 'string' },
        },
        required: ['dealId'],
      },
      request: {
        method: 'PUT',
        path: '/crm/sales/api/deals/{dealId}',
        body: { deal: 'args' },
      },
      cas: 'optimistic-read-verify',
    },
  ],
})
