import { declarativeRestConnector } from './declarative-rest.js'

// Gorgias OAuth and REST endpoints are scoped to a per-merchant subdomain
// (https://{subdomain}.gorgias.com). The OAuth orchestrator substitutes
// `{subdomain}` from connection metadata before building the authorize
// redirect; the executor reads the same metadata key (`subdomainUrl`) to
// resolve baseUrl. Same per-tenant-host pattern as Zendesk/Salesforce.

export const gorgiasConnector = declarativeRestConnector({
  kind: 'gorgias',
  displayName: 'Gorgias',
  description: 'Search, read, create, and update Gorgias support tickets, messages, and customers for ecommerce help desks.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://{subdomain}.gorgias.com/oauth2/authorize',
    tokenUrl: 'https://{subdomain}.gorgias.com/oauth2/token',
    scopes: [
      'openid',
      'profile',
      'offline',
      'tickets:read',
      'tickets:write',
      'customers:read',
      'customers:write',
      'messages:read',
      'messages:write',
    ],
    clientIdEnv: 'GORGIAS_OAUTH_CLIENT_ID',
    clientSecretEnv: 'GORGIAS_OAUTH_CLIENT_SECRET',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'subdomainUrl' },
  test: { method: 'GET', path: '/api/users/0' },
  capabilities: [
    {
      name: 'tickets.search',
      class: 'read',
      description: 'List tickets, optionally filtered by status/channel/assignee/customer. Pass any Gorgias ticket-list query parameter.',
      parameters: {
        type: 'object',
        properties: {
          status: { type: 'string' },
          channel: { type: 'string' },
          assignee_user: { type: 'integer' },
          customer_id: { type: 'integer' },
          order_by: { type: 'string' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          cursor: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/api/tickets',
        query: {
          status: '{status}',
          channel: '{channel}',
          assignee_user: '{assignee_user}',
          customer_id: '{customer_id}',
          order_by: '{order_by}',
          limit: '{limit}',
          cursor: '{cursor}',
        },
      },
      requiredScopes: ['tickets:read'],
    },
    {
      name: 'tickets.get',
      class: 'read',
      description: 'Read a single Gorgias ticket by id.',
      parameters: {
        type: 'object',
        properties: { ticketId: { type: 'integer' } },
        required: ['ticketId'],
      },
      request: { method: 'GET', path: '/api/tickets/{ticketId}' },
      requiredScopes: ['tickets:read'],
    },
    {
      name: 'tickets.create',
      class: 'mutation',
      description: 'Create a Gorgias ticket. Pass the full ticket payload as defined by Gorgias (channel, customer, messages, etc.).',
      parameters: {
        type: 'object',
        properties: {
          channel: { type: 'string' },
          via: { type: 'string' },
          subject: { type: 'string' },
          customer: { type: 'object' },
          messages: { type: 'array', items: { type: 'object' } },
          status: { type: 'string' },
          priority: { type: 'string' },
          tags: { type: 'array', items: { type: 'object' } },
          assignee_user: { type: 'object' },
          assignee_team: { type: 'object' },
        },
        required: ['channel', 'via', 'customer', 'messages'],
      },
      request: { method: 'POST', path: '/api/tickets', body: 'args' },
      cas: 'native-idempotency',
      requiredScopes: ['tickets:write'],
    },
    {
      name: 'tickets.update',
      class: 'mutation',
      description: 'Update a Gorgias ticket. Pass any subset of mutable ticket fields (status, priority, assignee_user, tags, etc.).',
      parameters: {
        type: 'object',
        properties: {
          ticketId: { type: 'integer' },
          status: { type: 'string' },
          priority: { type: 'string' },
          assignee_user: { type: 'object' },
          assignee_team: { type: 'object' },
          tags: { type: 'array', items: { type: 'object' } },
          subject: { type: 'string' },
          meta: { type: 'object' },
        },
        required: ['ticketId'],
      },
      request: { method: 'PUT', path: '/api/tickets/{ticketId}', body: 'args' },
      cas: 'optimistic-read-verify',
      requiredScopes: ['tickets:write'],
    },
    {
      name: 'messages.create',
      class: 'mutation',
      description: 'Append a message (agent reply or internal note) to an existing Gorgias ticket.',
      parameters: {
        type: 'object',
        properties: {
          ticketId: { type: 'integer' },
          channel: { type: 'string' },
          via: { type: 'string' },
          sender: { type: 'object' },
          receiver: { type: 'object' },
          body_text: { type: 'string' },
          body_html: { type: 'string' },
          public: { type: 'boolean' },
          source: { type: 'object' },
        },
        required: ['ticketId', 'channel', 'via', 'sender'],
      },
      request: { method: 'POST', path: '/api/tickets/{ticketId}/messages', body: 'args' },
      cas: 'native-idempotency',
      requiredScopes: ['messages:write'],
    },
    {
      name: 'customers.search',
      class: 'read',
      description: 'List customers, optionally filtered by email or external_id. Pass any Gorgias customer-list query parameter.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          external_id: { type: 'string' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          cursor: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/api/customers',
        query: {
          email: '{email}',
          external_id: '{external_id}',
          limit: '{limit}',
          cursor: '{cursor}',
        },
      },
      requiredScopes: ['customers:read'],
    },
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a Gorgias customer. Pass the customer payload (name, email, channels, etc.).',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          email: { type: 'string' },
          firstname: { type: 'string' },
          lastname: { type: 'string' },
          language: { type: 'string' },
          channels: { type: 'array', items: { type: 'object' } },
          external_id: { type: 'string' },
          data: { type: 'object' },
          meta: { type: 'object' },
        },
        required: ['email'],
      },
      request: { method: 'POST', path: '/api/customers', body: 'args' },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['customers:write'],
    },
    {
      name: 'tickets.close',
      class: 'mutation',
      description:
        'Close a Gorgias ticket. Issues PUT /api/tickets/{ticketId} with status="closed"; idempotent — already-closed tickets stay closed. Use tickets.update to set status to a different value (open, pending, resolved).',
      parameters: {
        type: 'object',
        properties: {
          ticketId: { type: 'integer', description: 'Gorgias ticket ID to close.' },
        },
        required: ['ticketId'],
      },
      request: {
        method: 'PUT',
        path: '/api/tickets/{ticketId}',
        body: { status: 'closed' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['tickets:write'],
    },
  ],
})
