import { declarativeRestConnector } from './declarative-rest.js'

// Harvest is a time-tracking + invoicing app. Its v2 REST API roots at
// `https://api.harvestapp.com/v2` and authenticates via OAuth2 issued from
// `https://id.getharvest.com`. Every call also needs a `Harvest-Account-Id`
// header naming the workspace; the per-call `accountId` parameter threads that
// through as a header so a single connection can serve multiple accounts.
export const harvestConnector = declarativeRestConnector({
  kind: 'harvest',
  displayName: 'Harvest',
  description: 'Read Harvest invoices, projects, tasks, clients, estimates, expenses, time entries, roles, users, and run the uninvoiced report.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://id.getharvest.com/oauth2/authorize',
    tokenUrl: 'https://id.getharvest.com/api/v2/oauth2/token',
    scopes: ['harvest:all'],
    clientIdEnv: 'HARVEST_OAUTH_CLIENT_ID',
    clientSecretEnv: 'HARVEST_OAUTH_CLIENT_SECRET',
  },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.harvestapp.com/v2',
  test: {
    method: 'GET',
    path: '/users/me',
    headers: { 'Harvest-Account-Id': '{accountId}' },
  },
  capabilities: [
    {
      name: 'invoices.get',
      class: 'read',
      description: 'List invoices in a Harvest account, optionally filtered by client/project/state/date window.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string', description: 'Harvest Account ID (sent as the Harvest-Account-Id header).' },
          client_id: { type: 'string' },
          project_id: { type: 'string' },
          state: { type: 'string', enum: ['draft', 'open', 'paid', 'closed'] },
          updated_since: { type: 'string', description: 'ISO-8601 timestamp.' },
          from: { type: 'string', description: 'ISO-8601 date.' },
          to: { type: 'string', description: 'ISO-8601 date.' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/invoices',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          client_id: '{client_id}',
          project_id: '{project_id}',
          state: '{state}',
          updated_since: '{updated_since}',
          from: '{from}',
          to: '{to}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'projects.get',
      class: 'read',
      description: 'List projects, optionally filtered by client or active state.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          is_active: { type: 'boolean' },
          client_id: { type: 'string' },
          updated_since: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/projects',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          is_active: '{is_active}',
          client_id: '{client_id}',
          updated_since: '{updated_since}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'tasks.get',
      class: 'read',
      description: 'List billable/non-billable tasks defined on the Harvest account.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          is_active: { type: 'boolean' },
          updated_since: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/tasks',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          is_active: '{is_active}',
          updated_since: '{updated_since}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'clients.get',
      class: 'read',
      description: 'List clients in the Harvest account.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          is_active: { type: 'boolean' },
          updated_since: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/clients',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          is_active: '{is_active}',
          updated_since: '{updated_since}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'estimates.get',
      class: 'read',
      description: 'List estimates, optionally filtered by client/state/updated_since.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          client_id: { type: 'string' },
          state: { type: 'string', enum: ['draft', 'sent', 'accepted', 'declined'] },
          updated_since: { type: 'string' },
          from: { type: 'string' },
          to: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/estimates',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          client_id: '{client_id}',
          state: '{state}',
          updated_since: '{updated_since}',
          from: '{from}',
          to: '{to}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'expenses.get',
      class: 'read',
      description: 'List expenses in the account, with optional user/client/project/billed/date filters.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          user_id: { type: 'string' },
          client_id: { type: 'string' },
          project_id: { type: 'string' },
          is_billed: { type: 'boolean' },
          updated_since: { type: 'string' },
          from: { type: 'string' },
          to: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/expenses',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          user_id: '{user_id}',
          client_id: '{client_id}',
          project_id: '{project_id}',
          is_billed: '{is_billed}',
          updated_since: '{updated_since}',
          from: '{from}',
          to: '{to}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'time.entries.get',
      class: 'read',
      description: 'List time entries with optional user/client/project/task/billed/running/date filters.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          user_id: { type: 'string' },
          client_id: { type: 'string' },
          project_id: { type: 'string' },
          task_id: { type: 'string' },
          is_billed: { type: 'boolean' },
          is_running: { type: 'boolean' },
          updated_since: { type: 'string' },
          from: { type: 'string' },
          to: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/time_entries',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          user_id: '{user_id}',
          client_id: '{client_id}',
          project_id: '{project_id}',
          task_id: '{task_id}',
          is_billed: '{is_billed}',
          is_running: '{is_running}',
          updated_since: '{updated_since}',
          from: '{from}',
          to: '{to}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'roles.get',
      class: 'read',
      description: 'List user roles defined in the Harvest account.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/roles',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: { page: '{page}', per_page: '{per_page}' },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'users.get',
      class: 'read',
      description: 'List Harvest users in the account.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          is_active: { type: 'boolean' },
          updated_since: { type: 'string' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/users',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          is_active: '{is_active}',
          updated_since: '{updated_since}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
    {
      name: 'reports.uninvoiced',
      class: 'read',
      description: 'Pull the uninvoiced report for a date window — totals of uninvoiced hours/expenses per project.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          from: { type: 'string', description: 'Window start date (YYYY-MM-DD).' },
          to: { type: 'string', description: 'Window end date (YYYY-MM-DD).' },
          page: { type: 'integer', minimum: 1 },
          per_page: { type: 'integer', minimum: 1, maximum: 2000 },
        },
        required: ['accountId', 'from', 'to'],
      },
      request: {
        method: 'GET',
        path: '/reports/uninvoiced',
        headers: { 'Harvest-Account-Id': '{accountId}' },
        query: {
          from: '{from}',
          to: '{to}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
      requiredScopes: ['harvest:all'],
    },
  ],
})
