/**
 * Concrete first-party adapter implementations.
 *
 * Every export here is either:
 *   - A factory `function fooConnector(opts) → ConnectorAdapter` for OAuth-shaped
 *     integrations (Google Calendar, Sheets, Microsoft Calendar, HubSpot, Slack,
 *     Notion). Caller resolves clientId / clientSecret from env, DB, or vault and
 *     passes them at construction.
 *   - A const `barConnector: ConnectorAdapter` for integrations that don't need
 *     hub-side OAuth client config — credentials per-connection (Twilio,
 *     Stripe-pack), HMAC-only (Webhook), or signing-secret-only inbound
 *     receivers (stripe-webhook-receiver, slack-events).
 *
 * All adapters are stateless — no module-level state, no env reads, no DB
 * coupling. Persistence + secret resolution + audit logging are the consumer's
 * concern (see the `IntegrationActionGuard` hook on the hub for cross-cutting
 * discipline).
 */

export { googleCalendar, type GoogleCalendarOptions } from './google-calendar.js'
export { googleDrive, type GoogleDriveOptions } from './google-drive.js'
export { googleSheets, type GoogleSheetsOptions } from './google-sheets.js'
export { googleSlidesConnector } from './google-slides.js'
export { gmail, type GmailOptions } from './gmail.js'
export {
  classifyGoogleError,
  classifyGoogleReason,
  googleApiError,
  googleErrorReason,
  googleTestFailureReason,
  type GoogleErrorClass,
} from './google-errors.js'
export { microsoftCalendar, type MicrosoftCalendarOptions } from './microsoft-calendar.js'
export { hubspot, type HubSpotOptions } from './hubspot.js'
export { slack, type SlackOptions } from './slack.js'
export { docuseal, type DocuSealOptions } from './docuseal.js'
export {
  declarativeRestConnector,
  type RestConnectorSpec,
  type RestOperationSpec,
  type RestRequestSpec,
  type RestCredentialPlacement,
} from './declarative-rest.js'

export { twilioSmsConnector } from './twilio-sms.js'
export { phonyConnector } from './phony.js'
export { whatsappBusiness, type WhatsappBusinessOptions } from './whatsapp-business.js'
export { stripePackConnector } from './stripe-pack.js'
export { webhookConnector } from './webhook.js'
export { stripeWebhookReceiverConnector } from './stripe-webhook-receiver.js'
export { slackEventsConnector } from './slack-events.js'
export { githubConnector } from './github.js'
export { giteaConnector } from './gitea.js'
export { gitlabConnector } from './gitlab.js'
export { airtableConnector } from './airtable.js'
export { asanaConnector } from './asana.js'
export { salesforceConnector } from './salesforce.js'
export { firebaseConnector } from './firebase.js'
export { twentyConnector } from './twenty.js'
export { supabaseConnector } from './supabase.js'
export { discordConnector } from './discord.js'
export { facebookPagesConnector } from './facebook-pages.js'
export { telegramConnector, TELEGRAM_FILE_DOWNLOAD_ROOT } from './telegram.js'

// === Mega fan-out (2026-05-31): native adapter expansion ===
// 24 declarative-REST OAuth2 connectors (use declarativeRestConnector internally)
// CRM family
export { pipedriveConnector } from './pipedrive.js'
export { closeConnector } from './close.js'
export { zohoCrmConnector } from './zoho-crm.js'
export { zohoDeskConnector } from './zoho-desk.js'
export { attioConnector } from './attio.js'
// Finance / accounting
export { quickbooksConnector } from './quickbooks.js'
export { xeroConnector } from './xero.js'
// HR / payroll
export { gustoConnector } from './gusto.js'
// Commerce
export { bigcommerceConnector } from './bigcommerce.js'
export { shopifyConnector } from './shopify.js'
export { ebayConnector } from './ebay.js'
export { etsyConnector, type EtsyOptions } from './etsy.js'
export { quickzuConnector } from './quickzu.js'
// Support desks
export { zagomailConnector } from './zagomail.js'
export { zendeskConnector } from './zendesk.js'
export { zendeskSellConnector } from './zendesk-sell.js'
export { intercomConnector } from './intercom.js'
export { helpscoutConnector } from './helpscout.js'
export { frontConnector } from './front.js'
export { gorgiasConnector } from './gorgias.js'
// Email / marketing
export { mailchimpConnector } from './mailchimp.js'
export { klaviyoConnector } from './klaviyo.js'
export { sendgridConnector } from './sendgrid.js'
export { sendpulseConnector } from './sendpulse.js'
export { postmarkConnector } from './postmark.js'
export { marketoConnector } from './marketo.js'
export { brazeConnector } from './braze.js'
export { customerIoConnector } from './customer-io.js'
// Scheduling
export { calComConnector } from './cal-com.js'
export { calendlyConnector } from './calendly.js'
export { zohoBookingsConnector } from './zoho-bookings.js'
// Content
export { contentfulConnector } from './contentful.js'
export { sanityConnector } from './sanity.js'
export { codaConnector } from './coda.js'
export { webflowConnector } from './webflow.js'
export { wordpressConnector } from './wordpress.js'
// Atlassian
export { confluenceConnector } from './confluence.js'
// E-signature
export { docusignConnector } from './docusign.js'
// Design
export { figmaConnector } from './figma.js'
export { figjamConnector } from './figjam.js'
export { miroConnector } from './miro.js'
export { canvaConnector } from './canva.js'
// Storage
export { boxConnector } from './box.js'
export { dropboxConnector } from './dropbox.js'
export { adobeCreativeCloudConnector } from './adobe-creative-cloud.js'
// Project management
export { linearConnector } from './linear.js'
export { trelloConnector } from './trello.js'
export { mondayConnector } from './monday.js'
export { clickupConnector } from './clickup.js'
export { basecampConnector } from './basecamp.js'
// Legal practice management
export { clioConnector } from './clio.js'
// Observability / errors
export { sentryConnector } from './sentry.js'
export { datadogConnector } from './datadog.js'
// Incident response / on-call
export { pagerdutyConnector } from './pagerduty.js'
export { opsgenieConnector } from './opsgenie.js'
// Identity / auth
export { auth0Connector } from './auth0.js'
// AI / LLM providers
export { openaiConnector } from './openai.js'
export { anthropicConnector } from './anthropic.js'
export { googleGeminiConnector } from './google-gemini.js'
export { geminiConnector } from './gemini.js'
export { huggingfaceConnector } from './huggingface.js'
// Vector databases
export { weaviateConnector } from './weaviate.js'
export { pineconeConnector } from './pinecone.js'
export { qdrantConnector } from './qdrant.js'
// HRIS
export { bamboohrConnector } from './bamboohr.js'
export { ripplingConnector } from './rippling.js'
export { workdayConnector } from './workday.js'
// ATS / recruiting
export { leverConnector } from './lever.js'
export { greenhouseConnector } from './greenhouse.js'
// Deployment platforms
export { vercelConnector } from './vercel.js'
export { netlifyConnector } from './netlify.js'
// Forms
export { typeformConnector } from './typeform.js'
export { smooveConnector } from './smoove.js'

// 8 factory-style adapters (need client credentials at construction)
export { hellosign, type HelloSignOptions } from './hellosign.js'
export { pandadoc, type PandaDocOptions } from './pandadoc.js'
export { googleDocs, type GoogleDocsOptions } from './google-docs.js'
export { googleForms, type GoogleFormsOptions } from './google-forms.js'
export { microsoftGraph, type MicrosoftGraphOptions } from './microsoft-graph.js'
export { outlookMail, type OutlookMailOptions } from './outlook-mail.js'
export { microsoftTeams, type MicrosoftTeamsOptions } from './microsoft-teams.js'
export { oneDrive, type OneDriveOptions } from './onedrive.js'
export { sharepoint, type SharePointOptions } from './sharepoint.js'

export { activecampaignConnector } from './activecampaign.js'
export { kustomerConnector } from './kustomer.js'
export { savvycalConnector } from './savvycal.js'

export {
  tangleIdentity,
  createTangleIdentityClient,
  DEFAULT_TANGLE_PLATFORM_URL,
  TANGLE_API_KEY_PREFIX,
  TANGLE_SERVICE_TOKEN_PREFIX,
  TangleIdentityUnreachableError,
  type TangleIdentityClient,
  type TangleIdentityOptions,
  type TangleTokenVerifyFailure,
  type TangleTokenVerifyResult,
  type TangleUserSummary,
  type TangleWorkspaceSummary,
} from './tangle-id.js'
export { airOpsConnector } from './air-ops.js'
export { agentxConnector } from './agentx.js'
export { afforaiConnector } from './afforai.js'
export { aidbaseConnector } from './aidbase.js'
export { acumbamailConnector } from './acumbamail.js'
export { aipriseConnector } from './aiprise.js'
export { aircallConnector } from './aircall.js'
export { amazonBedrockConnector } from './amazon-bedrock.js'
export { amazonSecretsManagerConnector } from './amazon-secrets-manager.js'
export { airtopConnector } from './airtop.js'
export { alaiConnector } from './alai.js'
export { altTextAiConnector } from './alt-text-ai.js'
export { alttextifyConnector } from './alttextify.js'
export { amazonSesConnector } from './amazon-ses.js'
export { amazonSnsConnector } from './amazon-sns.js'
export { amazonSqsConnector } from './amazon-sqs.js'
export { amazonTextractConnector } from './amazon-textract.js'
export { apitemplateIoConnector } from './apitemplate-io.js'
export { ampecoConnector } from './ampeco.js'
export { appfollowConnector } from './appfollow.js'
export { apitableConnector } from './apitable.js'
export { aminosConnector } from './aminos.js'
export { apolloConnector } from './apollo.js'
export { similarwebConnector } from './similarweb.js'
export { semrushConnector } from './semrush.js'
export { cognismConnector } from './cognism.js'
export { clayConnector } from './clay.js'
export { zoominfoConnector } from './zoominfo.js'
export { paychexConnector } from './paychex.js'
// ADP ships manifest + isolation tests only: ADP mandates mutual-TLS client
// certs the shared declarative-REST runtime cannot present, so live execution
// is gated on follow-up cert plumbing. See ./adp.ts header.
export { adpConnector } from './adp.js'
export { ashbyConnector } from './ashby.js'
export { assemblyaiConnector } from './assemblyai.js'
export { avianConnector } from './avian.js'
export { asknewsConnector } from './asknews.js'
export { avomaConnector } from './avoma.js'
export { azureCommunicationServicesConnector } from './azure-communication-services.js'
export { autocallsConnector } from './autocalls.js'
export { azureAdConnector } from './azure-ad.js'
export { barcodeLookupConnector } from './barcode-lookup.js'
export { azureOpenaiConnector } from './azure-openai.js'
export { backblazeConnector } from './backblaze.js'
export { baremetricsConnector } from './baremetrics.js'
export { beamerConnector } from './beamer.js'
export { bettermodeConnector } from './bettermode.js'
export { blandAiConnector } from './bland-ai.js'
export { bitlyConnector } from './bitly.js'
export { biginByZohoConnector } from './bigin-by-zoho.js'
export { billplzConnector } from './billplz.js'
export { bonjoroConnector } from './bonjoro.js'
export { blueskyConnector } from './bluesky.js'
export { bolnaConnector } from './bolna.js'
export { bexioConnector } from './bexio.js'
export { bookedinConnector } from './bookedin.js'
export { browseAiConnector } from './browse-ai.js'
export { brilliantDirectoriesConnector } from './brilliant-directories.js'
export { campaignMonitorConnector } from './campaign-monitor.js'
export { braveSearchConnector } from './brave-search.js'
export { captainDataConnector } from './captain-data.js'
export { certopusConnector } from './certopus.js'
export { chainalysisApiConnector } from './chainalysis-api.js'
export { cannyConnector } from './canny.js'
export { capsuleCrmConnector } from './capsule-crm.js'
export { cashfreePaymentsConnector } from './cashfree-payments.js'
export { chargebeeConnector } from './chargebee.js'
export { chargekeepConnector } from './chargekeep.js'
export { chatlingConnector } from './chatling.js'
export { chatbaseConnector } from './chatbase.js'
export { chartlyConnector } from './chartly.js'

export { chatwootConnector } from './chatwoot.js'
export { chatDataConnector } from './chat-data.js'
export { circleConnector } from './circle.js'
export { checkoutConnector } from './checkout.js'
export { chatnodeConnector } from './chatnode.js'
export { cloudinaryConnector } from './cloudinary.js'
export { clockodoConnector } from './clockodo.js'
export { clockifyConnector } from './clockify.js'
export { cloutlyConnector } from './cloutly.js'
export { clearoutConnector } from './clearout.js'
export { clicdataConnector } from './clicdata.js'
export { cognitoFormsConnector } from './cognito-forms.js'
export { cohereConnector } from './cohere.js'
export { cloudconvertConnector } from './cloudconvert.js'
export { cometapiConnector } from './cometapi.js'
export { comfyicuConnector } from './comfyicu.js'
export { constantContactConnector } from './constant-contact.js'
export { crispConnector } from './crisp.js'
export { convertkitConnector } from './convertkit.js'
export { dashworksConnector } from './dashworks.js'
export { copyAiConnector } from './copy-ai.js'
export { datafuelConnector } from './datafuel.js'
export { cryptolensConnector } from './cryptolens.js'
export { copperConnector } from './copper.js'
export { customgptConnector } from './customgpt.js'
export { deepseekConnector } from './deepseek.js'
export { denserAiConnector } from './denser-ai.js'
export { devinConnector } from './devin.js'
export { descriptConnector } from './descript.js'
export { datocmsConnector } from './datocms.js'
export { dittofeedConnector } from './dittofeed.js'
export { documergeConnector } from './documerge.js'
export { doctlyConnector } from './doctly.js'
export { dumplingAiConnector } from './dumpling-ai.js'
export { dubConnector } from './dub.js'
export { documentproConnector } from './documentpro.js'
export { elasticEmailConnector } from './elastic-email.js'
export { edenAiConnector } from './eden-ai.js'
export { easyPeasyAiConnector } from './easy-peasy-ai.js'
export { dustConnector } from './dust.js'
export { emailoctopusConnector } from './emailoctopus.js'
export { emailitConnector } from './emailit.js'

export { esignaturesConnector } from './esignatures.js'
export { firefliesAiConnector } from './fireflies-ai.js'
export { firecrawlConnector } from './firecrawl.js'
export { fathomAnalyticsConnector } from './fathom-analytics.js'
export { enrichlayerConnector } from './enrichlayer.js'
export { fathomConnector } from './fathom.js'
export { filloutFormsConnector } from './fillout-forms.js'
export { facebookLeadsConnector } from './facebook-leads.js'
export { fireberryConnector } from './fireberry.js'
export { flowluConnector } from './flowlu.js'
export { flowiseConnector } from './flowise.js'
export { flipandoConnector } from './flipando.js'
export { folkConnector } from './folk.js'
export { formbricksConnector } from './formbricks.js'
export { formstackConnector } from './formstack.js'
export { foreplayCoConnector } from './foreplay-co.js'
export { fountainConnector } from './fountain.js'
export { mailercheckConnector } from './mailercheck.js'
export { freshsalesConnector } from './freshsales.js'
export { frameConnector } from './frame.js'
export { fragmentConnector } from './fragment.js'
export { gameballConnector } from './gameball.js'
export { freeAgentConnector } from './free-agent.js'
export { freshserviceConnector } from './freshservice.js'
export { ghostcmsConnector } from './ghostcms.js'
export { gistlyConnector } from './gistly.js'
export { googleSearchConsoleConnector } from './google-search-console.js'
export { googleAnalyticsConnector } from './google-analytics.js'
export { googleMeetConnector } from './google-meet.js'
export { youtubeDataConnector } from './youtube-data.js'
export { googleCloudStorageConnector } from './google-cloud-storage.js'
export { googleBigqueryConnector } from './google-bigquery.js'
export { googleSearchConnector } from './google-search.js'
export { googleContactsConnector } from './google-contacts.js'
export { googlechatConnector } from './googlechat.js'
export { googleMyBusinessConnector } from './google-my-business.js'
export { googleTasksConnector } from './google-tasks.js'
export { greenptConnector } from './greenpt.js'
export { greipConnector } from './greip.js'
export { guideliteConnector } from './guidelite.js'
export { hastewireConnector } from './hastewire.js'
export { heygenConnector } from './heygen.js'
export { hashiCorpVaultConnector } from './hashi-corp-vault.js'
export { harvestConnector } from './harvest.js'
export { heymarketSmsConnector } from './heymarket-sms.js'
export { housecallProConnector } from './housecall-pro.js'
export { influencersClubConnector } from './influencers-club.js'
export { hunterConnector } from './hunter.js'
export { huggingFaceConnector } from './hugging-face.js'
export { insightlyConnector } from './insightly.js'
export { instantlyAiConnector } from './instantly-ai.js'
export { imageRouterConnector } from './image-router.js'
export { jinaAiConnector } from './jina-ai.js'
export { invoiceninjaConnector } from './invoiceninja.js'
export { jiraDataCenterConnector } from './jira-data-center.js'
export { justInvoiceConnector } from './just-invoice.js'
export { jiraCloudConnector } from './jira-cloud.js'
export { joggAiConnector } from './jogg-ai.js'
export { jotformConnector } from './jotform.js'
export { kizeoFormsConnector } from './kizeo-forms.js'
export { kapsoConnector } from './kapso.js'
export { kimaiConnector } from './kimai.js'
export { kissflowConnector } from './kissflow.js'
export { klentyConnector } from './klenty.js'
export { knackConnector } from './knack.js'
export { koFiConnector } from './ko-fi.js'
export { kudosityConnector } from './kudosity.js'
export { leapAiConnector } from './leap-ai.js'
export { kommoConnector } from './kommo.js'
export { lemonSqueezyConnector } from './lemon-squeezy.js'
export { leexiConnector } from './leexi.js'
export { lettaConnector } from './letta.js'
export { leadConnectorConnector } from './lead-connector.js'
export { linkupConnector } from './linkup.js'
export { lightfunnelsConnector } from './lightfunnels.js'
export { lemlistConnector } from './lemlist.js'
export { letsCalendarConnector } from './lets-calendar.js'
export { linkaConnector } from './linka.js'
export { localaiConnector } from './localai.js'
export { lobstermailConnector } from './lobstermail.js'
export { llmrailsConnector } from './llmrails.js'
export { magicalApiConnector } from './magical-api.js'
export { lokaliseConnector } from './lokalise.js'
export { logrocketConnector } from './logrocket.js'
export { logsnagConnector } from './logsnag.js'
export { loftyConnector } from './lofty.js'
export { lushaConnector } from './lusha.js'
export { mailerLiteConnector } from './mailer-lite.js'
export { luxuryPresenceConnector } from './luxury-presence.js'
export { lucidyaConnector } from './lucidya.js'
export { mastodonConnector } from './mastodon.js'
export { matomoConnector } from './matomo.js'
export { manychatConnector } from './manychat.js'
export { mailgunConnector } from './mailgun.js'
export { matrixConnector } from './matrix.js'
export { mattermostConnector } from './mattermost.js'
export { mailerooConnector } from './maileroo.js'
export { meetgeekAiConnector } from './meetgeek-ai.js'
export { messagebirdConnector } from './messagebird.js'
export { mauticConnector } from './mautic.js'
export { microsoft365PeopleConnector } from './microsoft-365-people.js'
export { memConnector } from './mem.js'
export { microsoftDynamicsCrmConnector } from './microsoft-dynamics-crm.js'
export { microsoftDynamics365BusinessCentralConnector } from './microsoft-dynamics-365-business-central.js'
export { microsoft365PlannerConnector } from './microsoft-365-planner.js'
export { microsoftPowerBiConnector } from './microsoft-power-bi.js'
export { microsoftOnenoteConnector } from './microsoft-onenote.js'
export { microsoftExcel365Connector } from './microsoft-excel-365.js'
export { microsoftTodoConnector } from './microsoft-todo.js'
export { millionverifierConnector } from './millionverifier.js'
export { mindeeConnector } from './mindee.js'
export { mixmaxConnector } from './mixmax.js'
export { mixpanelConnector } from './mixpanel.js'
export { missiveConnector } from './missive.js'
export { exaConnector } from './exa.js'
export { googleVertexaiConnector } from './google-vertexai.js'
export { glideConnector } from './glide.js'
export { gotifyConnector } from './gotify.js'
export { gptzeroDetectAiConnector } from './gptzero-detect-ai.js'
export { gristConnector } from './grist.js'
export { granolaConnector } from './granola.js'
export { griptapeConnector } from './griptape.js'
export { heartbeatConnector } from './heartbeat.js'
export { hedyConnector } from './hedy.js'
export { humeAiConnector } from './hume-ai.js'
export { hystructConnector } from './hystruct.js'
export { ibmCognoseConnector } from './ibm-cognose.js'
export { imapConnector } from './imap.js'
export { instaChartsConnector } from './insta-charts.js'
export { insightoAiConnector } from './insighto-ai.js'
export { instasentConnector } from './instasent.js'
export { kallabotAiConnector } from './kallabot-ai.js'
export { knockConnector } from './knock.js'
export { loopsConnector } from './loops.js'
export { mailchainConnector } from './mailchain.js'
export { medullarConnector } from './medullar.js'
export { mollieConnector } from './mollie.js'
export { metabaseConnector } from './metabase.js'
export { mindStudioConnector } from './mind-studio.js'
export { mongodbConnector } from './mongodb.js'
export { niftyConnector } from './nifty.js'
export { ninjapipeConnector } from './ninjapipe.js'
export { nocodbConnector } from './nocodb.js'
export { notionConnector, notion, type NotionOptions } from './notion.js'
export { ntfyConnector } from './ntfy.js'
export { odooConnector } from './odoo.js'
export { omniCoConnector } from './omni-co.js'
export { omnihrConnector } from './omnihr.js'
export { openRouterConnector } from './open-router.js'
export { openPhoneConnector } from './open-phone.js'
export { opportifyConnector } from './opportify.js'
export { openmicAiConnector } from './openmic-ai.js'
export { opnformConnector } from './opnform.js'
export { orimonConnector } from './orimon.js'
export { oracleDatabaseConnector } from './oracle-database.js'
export { paddleConnector } from './paddle.js'
export { paperformConnector } from './paperform.js'
export { pastefyConnector } from './pastefy.js'
export { pinchPaymentsConnector } from './pinch-payments.js'
export { paywhirlConnector } from './paywhirl.js'
export { parseurConnector } from './parseur.js'
export { pdfmonkeyConnector } from './pdfmonkey.js'
export { peekshotConnector } from './peekshot.js'
export { perplexityAiConnector } from './perplexity-ai.js'
export { personalAiConnector } from './personal-ai.js'
export { placidConnector } from './placid.js'
export { plausibleConnector } from './plausible.js'
export { pocketbaseConnector } from './pocketbase.js'
export { pollybotAiConnector } from './pollybot-ai.js'
export { postgresConnector } from './postgres.js'
export { postizConnector } from './postiz.js'
export { posthogConnector } from './posthog.js'
export { predictLeadsConnector } from './predict-leads.js'
export { productboardConnector } from './productboard.js'
export { proxycurlConnector } from './proxycurl.js'
export { pushbulletConnector } from './pushbullet.js'
export { pushoverConnector } from './pushover.js'
export { qawafelConnector } from './qawafel.js'
export { quadernoConnector } from './quaderno.js'
export { raiaAiConnector } from './raia-ai.js'
export { rapidtextAiConnector } from './rapidtext-ai.js'
export { recallAiConnector } from './recall-ai.js'
export { reachinboxConnector } from './reachinbox.js'
export { redditConnector } from './reddit.js'
export { reoonVerifierConnector } from './reoon-verifier.js'
export { replyIoConnector } from './reply-io.js'
export { retableConnector } from './retable.js'
export { retellAiConnector } from './retell-ai.js'
export { robollyConnector } from './robolly.js'
export { runwareConnector } from './runware.js'
export { saasticConnector } from './saastic.js'
export { saleorConnector } from './saleor.js'
export { sardisConnector } from './sardis.js'
export { scrapegraphaiConnector } from './scrapegraphai.js'
export { scrapelessConnector } from './scrapeless.js'
export { seekTableConnector } from './seek-table.js'
export { skyprepConnector } from './skyprep.js'
export { sendinblueConnector } from './sendinblue.js'
export { senjaConnector } from './senja.js'
export { serpstatConnector } from './serpstat.js'
export { serviceNowConnector } from './service-now.js'
export { signNowConnector } from './sign-now.js'
export { signrequestConnector } from './signrequest.js'
export { shortIoConnector } from './short-io.js'
export { shippoConnector } from './shippo.js'
export { simplirouteConnector } from './simpliroute.js'
export { simplybookmeConnector } from './simplybookme.js'
export { smartleadConnector } from './smartlead.js'
export { smartsheetConnector } from './smartsheet.js'
export { smartsuiteConnector } from './smartsuite.js'
export { smsmodeConnector } from './smsmode.js'
export { snowflakeConnector } from './snowflake.js'
export { socialkitConnector } from './socialkit.js'
export { squareConnector } from './square.js'
export { supadataConnector } from './supadata.js'
export { swarmnodeConnector } from './swarmnode.js'
export { stripeConnector } from './stripe.js'
export { systemeIoConnector } from './systeme-io.js'
export { tableauConnector } from './tableau.js'
export { talkableConnector } from './talkable.js'
export { tallyConnector } from './tally.js'
export { ticktickConnector } from './ticktick.js'
export { teableConnector } from './teable.js'
export { telnyxConnector } from './telnyx.js'
export { tenzoConnector } from './tenzo.js'
export { textcortexAiConnector } from './textcortex-ai.js'
export { timeOpsConnector } from './time-ops.js'
export { timelinesAiConnector } from './timelines-ai.js'
export { tlDvConnector } from './tl-dv.js'
export { todoistConnector } from './todoist.js'
export { togglTrackConnector } from './toggl-track.js'
export { totalcmsConnector } from './totalcms.js'
export { typefullyConnector } from './typefully.js'
export { twinLabsConnector } from './twin-labs.js'
export { twitter, twitterConnector, type TwitterOptions } from './twitter.js'
export { twilioConnector } from './twilio.js'
export { upgradechatConnector } from './upgradechat.js'
export { vapiConnector } from './vapi.js'
export { validatedmailsConnector } from './validatedmails.js'
export { umamiConnector } from './umami.js'
export { uscreenConnector } from './uscreen.js'
export { vboutConnector } from './vbout.js'
export { vidlab7Connector } from './vidlab7.js'
export { videoaskConnector } from './videoask.js'
export { vlmRunConnector } from './vlm-run.js'
export { voucheryIoConnector } from './vouchery-io.js'
export { vtexConnector } from './vtex.js'
export { vtigerConnector } from './vtiger.js'
export { wafeqConnector } from './wafeq.js'
export { whatConvertsConnector } from './what-converts.js'
export { webscrapingAiConnector } from './webscraping-ai.js'
export { whatsappConnector } from './whatsapp.js'
export { whatsscaleConnector } from './whatsscale.js'
export { wonderchatConnector } from './wonderchat.js'
export { woodpeckerConnector } from './woodpecker.js'
export { wootricConnector } from './wootric.js'
export { woocommerceConnector } from './woocommerce.js'
export { workableConnector } from './workable.js'
export { writesonicBulkConnector } from './writesonic-bulk.js'
export { wufooConnector } from './wufoo.js'
export { wrikeConnector } from './wrike.js'
export { youcanbookmeConnector } from './youcanbookme.js'
export { zerobounceConnector } from './zerobounce.js'
export { zeplinConnector } from './zeplin.js'
export { zuoraConnector } from './zuora.js'

// Workflow-orchestrator meta-tools — first-class REST/webhook surfaces, not
// proxies for the platforms' long-tail integration catalogs.
export { zapierConnector } from './zapier.js'
export { n8nConnector } from './n8n.js'
export { makeConnector } from './make.js'
export { pipedreamConnector } from './pipedream.js'

// --- Toolverse api-key GTM connectors (tangle-network/agent-dev-container#2330) ---
export { amplemarketConnector } from './amplemarket.js'
export { heyreachConnector } from './heyreach.js'
export { lagrowthmachineConnector } from './lagrowthmachine.js'
export { saleshandyConnector } from './saleshandy.js'
export { bettercontactConnector } from './bettercontact.js'
export { contactoutConnector } from './contactout.js'
export { findymailConnector } from './findymail.js'
export { snovIoConnector } from './snov-io.js'
export { wizaConnector } from './wiza.js'
export { builtwithConnector } from './builtwith.js'
export { commonRoomConnector } from './common-room.js'
export { leadfeederConnector } from './leadfeeder.js'
export { serperConnector } from './serper.js'
export { warmlyConnector } from './warmly.js'
export { autoboundConnector } from './autobound.js'
export { crustdataConnector } from './crustdata.js'
export { fullenrichConnector } from './fullenrich.js'
export { leadmagicConnector } from './leadmagic.js'
export { brightdataConnector } from './brightdata.js'
export { phantombusterConnector } from './phantombuster.js'
export { zenrowsConnector } from './zenrows.js'
export { oceanIoConnector } from './ocean-io.js'
export { seamlessAiConnector } from './seamless-ai.js'
export { theirstackConnector } from './theirstack.js'
export { usergemsConnector } from './usergems.js'
export { hightouchConnector } from './hightouch.js'
export { polytomicConnector } from './polytomic.js'
export { signwellConnector } from './signwell.js'
export { justcallConnector } from './justcall.js'
export { nooksConnector } from './nooks.js'
export { modjoConnector } from './modjo.js'
export { factorsAiConnector } from './factors-ai.js'
export { getresponseConnector } from './getresponse.js'
// --- end Toolverse api-key GTM connectors ---

// --- Toolverse OAuth2 GTM connectors (tangle-network/agent-dev-container#2330) ---
export { outreachConnector } from './outreach.js'
export { salesloftConnector } from './salesloft.js'
export { gongConnector } from './gong.js'
export { ringcentralConnector } from './ringcentral.js'
export { dialpadConnector } from './dialpad.js'
export { demandbaseConnector } from './demandbase.js'
// --- end Toolverse OAuth2 GTM connectors ---
