/**
 * Concrete first-party adapter implementations.
 *
 * Every export here is either:
 *   - A factory `function fooConnector(opts) → ConnectorAdapter` for OAuth-shaped
 *     integrations (Google Calendar, Sheets, Microsoft Calendar, HubSpot, Slack,
 *     Notion). Caller resolves clientId / clientSecret from env, DB, or vault and
 *     passes them at construction.
 *   - A const `barConnector: ConnectorAdapter` for integrations that don't need
 *     hub-side OAuth client config — credentials per-connection (Twilio,
 *     Stripe-pack), HMAC-only (Webhook), or signing-secret-only inbound
 *     receivers (stripe-webhook-receiver, slack-events).
 *
 * All adapters are stateless — no module-level state, no env reads, no DB
 * coupling. Persistence + secret resolution + audit logging are the consumer's
 * concern (see the `IntegrationActionGuard` hook on the hub for cross-cutting
 * discipline).
 */

export { googleCalendar, type GoogleCalendarOptions } from './google-calendar.js'
export { googleDrive, type GoogleDriveOptions } from './google-drive.js'
export { googleSheets, type GoogleSheetsOptions } from './google-sheets.js'
export { gmail, type GmailOptions } from './gmail.js'
export { microsoftCalendar, type MicrosoftCalendarOptions } from './microsoft-calendar.js'
export { hubspot, type HubSpotOptions } from './hubspot.js'
export { slack, type SlackOptions } from './slack.js'
export { notionDatabase, type NotionDatabaseOptions } from './notion-database.js'
export { docuseal, type DocuSealOptions } from './docuseal.js'
export {
  declarativeRestConnector,
  type RestConnectorSpec,
  type RestOperationSpec,
  type RestRequestSpec,
  type RestCredentialPlacement,
} from './declarative-rest.js'

export { twilioSmsConnector } from './twilio-sms.js'
export { whatsappBusiness, type WhatsappBusinessOptions } from './whatsapp-business.js'
export { stripePackConnector } from './stripe-pack.js'
export { webhookConnector } from './webhook.js'
export { stripeWebhookReceiverConnector } from './stripe-webhook-receiver.js'
export { slackEventsConnector } from './slack-events.js'
export { githubConnector } from './github.js'
export { gitlabConnector } from './gitlab.js'
export { airtableConnector } from './airtable.js'
export { asanaConnector } from './asana.js'
export { salesforceConnector } from './salesforce.js'
export { firebaseConnector } from './firebase.js'
export { supabaseConnector } from './supabase.js'
export { discordConnector } from './discord.js'
export { facebookPagesConnector } from './facebook-pages.js'
export { telegramConnector, TELEGRAM_FILE_DOWNLOAD_ROOT } from './telegram.js'

// === Mega fan-out (2026-05-31): native adapter expansion ===
// 24 declarative-REST OAuth2 connectors (use declarativeRestConnector internally)
// CRM family
export { pipedriveConnector } from './pipedrive.js'
export { closeConnector } from './close.js'
export { zohoCrmConnector } from './zoho-crm.js'
export { attioConnector } from './attio.js'
// Finance / accounting
export { quickbooksConnector } from './quickbooks.js'
export { xeroConnector } from './xero.js'
// HR / payroll
export { gustoConnector } from './gusto.js'
// Commerce
export { bigcommerceConnector } from './bigcommerce.js'
export { shopifyConnector } from './shopify.js'
export { ebayConnector } from './ebay.js'
export { etsyConnector, type EtsyOptions } from './etsy.js'
// Support desks
export { zendeskConnector } from './zendesk.js'
export { intercomConnector } from './intercom.js'
export { helpscoutConnector } from './helpscout.js'
export { frontConnector } from './front.js'
export { gorgiasConnector } from './gorgias.js'
// Email / marketing
export { mailchimpConnector } from './mailchimp.js'
export { klaviyoConnector } from './klaviyo.js'
export { sendgridConnector } from './sendgrid.js'
export { postmarkConnector } from './postmark.js'
export { marketoConnector } from './marketo.js'
export { brazeConnector } from './braze.js'
export { customerIoConnector } from './customer-io.js'
// Scheduling
export { calComConnector } from './cal-com.js'
export { calendlyConnector } from './calendly.js'
// Content
export { contentfulConnector } from './contentful.js'
export { sanityConnector } from './sanity.js'
export { codaConnector } from './coda.js'
export { webflowConnector } from './webflow.js'
export { wordpressConnector } from './wordpress.js'
// Atlassian
export { confluenceConnector } from './confluence.js'
// E-signature
export { docusignConnector } from './docusign.js'
// Design
export { figmaConnector } from './figma.js'
export { figjamConnector } from './figjam.js'
export { miroConnector } from './miro.js'
export { canvaConnector } from './canva.js'
// Storage
export { boxConnector } from './box.js'
export { dropboxConnector } from './dropbox.js'
export { adobeCreativeCloudConnector } from './adobe-creative-cloud.js'
// Project management
export { linearConnector } from './linear.js'
export { trelloConnector } from './trello.js'
export { mondayConnector } from './monday.js'
export { clickupConnector } from './clickup.js'
export { basecampConnector } from './basecamp.js'
// Legal practice management
export { clioConnector } from './clio.js'
// Observability / errors
export { sentryConnector } from './sentry.js'
export { datadogConnector } from './datadog.js'
// Incident response / on-call
export { pagerdutyConnector } from './pagerduty.js'
export { opsgenieConnector } from './opsgenie.js'
// Identity / auth
export { auth0Connector } from './auth0.js'
// AI / LLM providers
export { openaiConnector } from './openai.js'
export { anthropicConnector } from './anthropic.js'
export { geminiConnector } from './gemini.js'
export { huggingfaceConnector } from './huggingface.js'
// Vector databases
export { weaviateConnector } from './weaviate.js'
export { pineconeConnector } from './pinecone.js'
export { qdrantConnector } from './qdrant.js'
// HRIS
export { bamboohrConnector } from './bamboohr.js'
export { ripplingConnector } from './rippling.js'
export { workdayConnector } from './workday.js'
// ATS / recruiting
export { leverConnector } from './lever.js'
export { greenhouseConnector } from './greenhouse.js'
// Deployment platforms
export { vercelConnector } from './vercel.js'
export { netlifyConnector } from './netlify.js'
// Forms
export { typeformConnector } from './typeform.js'

// 8 factory-style adapters (need client credentials at construction)
export { hellosign, type HelloSignOptions } from './hellosign.js'
export { pandadoc, type PandaDocOptions } from './pandadoc.js'
export { googleDocs, type GoogleDocsOptions } from './google-docs.js'
export { googleForms, type GoogleFormsOptions } from './google-forms.js'
export { microsoftGraph, type MicrosoftGraphOptions } from './microsoft-graph.js'
export { outlookMail, type OutlookMailOptions } from './outlook-mail.js'
export { microsoftTeams, type MicrosoftTeamsOptions } from './microsoft-teams.js'
export { oneDrive, type OneDriveOptions } from './onedrive.js'
export { sharepoint, type SharePointOptions } from './sharepoint.js'

export { activecampaignConnector } from './activecampaign.js'

export {
  tangleIdentity,
  createTangleIdentityClient,
  DEFAULT_TANGLE_PLATFORM_URL,
  TANGLE_API_KEY_PREFIX,
  TANGLE_SERVICE_TOKEN_PREFIX,
  TangleIdentityUnreachableError,
  type TangleIdentityClient,
  type TangleIdentityOptions,
  type TangleTokenVerifyFailure,
  type TangleTokenVerifyResult,
  type TangleUserSummary,
  type TangleWorkspaceSummary,
} from './tangle-id.js'
export { airOpsConnector } from './air-ops.js'
export { agentxConnector } from './agentx.js'
export { afforaiConnector } from './afforai.js'
export { aidbaseConnector } from './aidbase.js'
export { acumbamailConnector } from './acumbamail.js'
export { aipriseConnector } from './aiprise.js'
export { aircallConnector } from './aircall.js'
export { amazonBedrockConnector } from './amazon-bedrock.js'
export { amazonSecretsManagerConnector } from './amazon-secrets-manager.js'
export { airtopConnector } from './airtop.js'
export { alaiConnector } from './alai.js'
export { altTextAiConnector } from './alt-text-ai.js'
export { alttextifyConnector } from './alttextify.js'
export { amazonSesConnector } from './amazon-ses.js'
export { amazonSnsConnector } from './amazon-sns.js'
export { amazonSqsConnector } from './amazon-sqs.js'
export { amazonTextractConnector } from './amazon-textract.js'
export { apitemplateIoConnector } from './apitemplate-io.js'
export { ampecoConnector } from './ampeco.js'
export { appfollowConnector } from './appfollow.js'
export { apitableConnector } from './apitable.js'
export { aminosConnector } from './aminos.js'
export { apolloConnector } from './apollo.js'
export { ashbyConnector } from './ashby.js'
export { assemblyaiConnector } from './assemblyai.js'
export { avianConnector } from './avian.js'
export { asknewsConnector } from './asknews.js'
export { avomaConnector } from './avoma.js'
export { azureCommunicationServicesConnector } from './azure-communication-services.js'
export { autocallsConnector } from './autocalls.js'
export { azureAdConnector } from './azure-ad.js'
export { barcodeLookupConnector } from './barcode-lookup.js'
export { azureOpenaiConnector } from './azure-openai.js'
export { backblazeConnector } from './backblaze.js'
export { baremetricsConnector } from './baremetrics.js'
export { beamerConnector } from './beamer.js'
export { bettermodeConnector } from './bettermode.js'
export { blandAiConnector } from './bland-ai.js'
export { bitlyConnector } from './bitly.js'
export { biginByZohoConnector } from './bigin-by-zoho.js'
export { billplzConnector } from './billplz.js'
export { bonjoroConnector } from './bonjoro.js'
export { blueskyConnector } from './bluesky.js'
export { bolnaConnector } from './bolna.js'
export { bexioConnector } from './bexio.js'
export { bookedinConnector } from './bookedin.js'
export { browseAiConnector } from './browse-ai.js'
export { brilliantDirectoriesConnector } from './brilliant-directories.js'
export { campaignMonitorConnector } from './campaign-monitor.js'
export { braveSearchConnector } from './brave-search.js'
export { captainDataConnector } from './captain-data.js'
export { certopusConnector } from './certopus.js'
export { chainalysisApiConnector } from './chainalysis-api.js'
export { cannyConnector } from './canny.js'
export { capsuleCrmConnector } from './capsule-crm.js'
export { cashfreePaymentsConnector } from './cashfree-payments.js'
export { chargebeeConnector } from './chargebee.js'
export { chargekeepConnector } from './chargekeep.js'
export { chatlingConnector } from './chatling.js'
export { chatbaseConnector } from './chatbase.js'
export { chartlyConnector } from './chartly.js'

export { chatwootConnector } from './chatwoot.js'
export { chatDataConnector } from './chat-data.js'
export { circleConnector } from './circle.js'
export { checkoutConnector } from './checkout.js'
export { chatnodeConnector } from './chatnode.js'
export { cloudinaryConnector } from './cloudinary.js'
export { clockodoConnector } from './clockodo.js'
export { clockifyConnector } from './clockify.js'
export { cloutlyConnector } from './cloutly.js'
export { clearoutConnector } from './clearout.js'
export { clicdataConnector } from './clicdata.js'
export { cognitoFormsConnector } from './cognito-forms.js'
export { cohereConnector } from './cohere.js'
export { cloudconvertConnector } from './cloudconvert.js'
export { cometapiConnector } from './cometapi.js'
export { comfyicuConnector } from './comfyicu.js'
export { constantContactConnector } from './constant-contact.js'
export { crispConnector } from './crisp.js'
export { convertkitConnector } from './convertkit.js'
export { dashworksConnector } from './dashworks.js'
export { copyAiConnector } from './copy-ai.js'
export { datafuelConnector } from './datafuel.js'
export { cryptolensConnector } from './cryptolens.js'
export { copperConnector } from './copper.js'
export { customgptConnector } from './customgpt.js'
export { deepseekConnector } from './deepseek.js'
export { denserAiConnector } from './denser-ai.js'
export { devinConnector } from './devin.js'
export { descriptConnector } from './descript.js'
export { datocmsConnector } from './datocms.js'
export { dittofeedConnector } from './dittofeed.js'
export { documergeConnector } from './documerge.js'
export { doctlyConnector } from './doctly.js'
export { dumplingAiConnector } from './dumpling-ai.js'
export { dubConnector } from './dub.js'
export { documentproConnector } from './documentpro.js'
export { elasticEmailConnector } from './elastic-email.js'
export { edenAiConnector } from './eden-ai.js'
export { easyPeasyAiConnector } from './easy-peasy-ai.js'
export { dustConnector } from './dust.js'
export { emailoctopusConnector } from './emailoctopus.js'
export { emailitConnector } from './emailit.js'

export { esignaturesConnector } from './esignatures.js'
export { firefliesAiConnector } from './fireflies-ai.js'
export { firecrawlConnector } from './firecrawl.js'
export { fathomAnalyticsConnector } from './fathom-analytics.js'
export { enrichlayerConnector } from './enrichlayer.js'
export { fathomConnector } from './fathom.js'
export { filloutFormsConnector } from './fillout-forms.js'
export { facebookLeadsConnector } from './facebook-leads.js'
export { fireberryConnector } from './fireberry.js'
export { flowluConnector } from './flowlu.js'
export { flowiseConnector } from './flowise.js'
export { flipandoConnector } from './flipando.js'
export { folkConnector } from './folk.js'
export { formbricksConnector } from './formbricks.js'
export { formstackConnector } from './formstack.js'
export { foreplayCoConnector } from './foreplay-co.js'
export { fountainConnector } from './fountain.js'
export { mailercheckConnector } from './mailercheck.js'
export { freshsalesConnector } from './freshsales.js'
export { frameConnector } from './frame.js'
export { fragmentConnector } from './fragment.js'
export { gameballConnector } from './gameball.js'
export { freeAgentConnector } from './free-agent.js'
export { freshserviceConnector } from './freshservice.js'
export { ghostcmsConnector } from './ghostcms.js'
export { gistlyConnector } from './gistly.js'
export { googleSearchConsoleConnector } from './google-search-console.js'
export { googleCloudStorageConnector } from './google-cloud-storage.js'
export { googleBigqueryConnector } from './google-bigquery.js'
export { googleSearchConnector } from './google-search.js'
export { googleContactsConnector } from './google-contacts.js'
export { googlechatConnector } from './googlechat.js'
export { googleMyBusinessConnector } from './google-my-business.js'
export { greenptConnector } from './greenpt.js'
export { greipConnector } from './greip.js'
export { guideliteConnector } from './guidelite.js'
export { hastewireConnector } from './hastewire.js'
export { heygenConnector } from './heygen.js'
export { hashiCorpVaultConnector } from './hashi-corp-vault.js'
export { harvestConnector } from './harvest.js'
export { heymarketSmsConnector } from './heymarket-sms.js'
export { housecallProConnector } from './housecall-pro.js'
export { influencersClubConnector } from './influencers-club.js'
export { hunterConnector } from './hunter.js'
export { huggingFaceConnector } from './hugging-face.js'
export { insightlyConnector } from './insightly.js'
export { instantlyAiConnector } from './instantly-ai.js'
export { imageRouterConnector } from './image-router.js'
export { jinaAiConnector } from './jina-ai.js'
export { invoiceninjaConnector } from './invoiceninja.js'
export { jiraDataCenterConnector } from './jira-data-center.js'
export { justInvoiceConnector } from './just-invoice.js'
export { jiraCloudConnector } from './jira-cloud.js'
export { joggAiConnector } from './jogg-ai.js'
export { jotformConnector } from './jotform.js'
export { kizeoFormsConnector } from './kizeo-forms.js'
export { kapsoConnector } from './kapso.js'
export { kimaiConnector } from './kimai.js'
export { kissflowConnector } from './kissflow.js'
export { klentyConnector } from './klenty.js'
export { knackConnector } from './knack.js'
export { koFiConnector } from './ko-fi.js'
export { kudosityConnector } from './kudosity.js'
export { leapAiConnector } from './leap-ai.js'
export { kommoConnector } from './kommo.js'
export { lemonSqueezyConnector } from './lemon-squeezy.js'
export { leexiConnector } from './leexi.js'
export { leadConnectorConnector } from './lead-connector.js'
export { linkupConnector } from './linkup.js'
export { lightfunnelsConnector } from './lightfunnels.js'
export { lemlistConnector } from './lemlist.js'
export { letsCalendarConnector } from './lets-calendar.js'
export { linkaConnector } from './linka.js'
export { localaiConnector } from './localai.js'
export { lobstermailConnector } from './lobstermail.js'
export { llmrailsConnector } from './llmrails.js'
export { magicalApiConnector } from './magical-api.js'
export { lokaliseConnector } from './lokalise.js'
export { logrocketConnector } from './logrocket.js'
export { logsnagConnector } from './logsnag.js'
export { lushaConnector } from './lusha.js'
export { mailerLiteConnector } from './mailer-lite.js'
export { luxuryPresenceConnector } from './luxury-presence.js'
export { lucidyaConnector } from './lucidya.js'
export { mastodonConnector } from './mastodon.js'
export { matomoConnector } from './matomo.js'
export { manychatConnector } from './manychat.js'
export { mailgunConnector } from './mailgun.js'
export { matrixConnector } from './matrix.js'
export { mattermostConnector } from './mattermost.js'
export { mailerooConnector } from './maileroo.js'
export { meetgeekAiConnector } from './meetgeek-ai.js'
export { messagebirdConnector } from './messagebird.js'
export { mauticConnector } from './mautic.js'
export { microsoft365PeopleConnector } from './microsoft-365-people.js'
export { memConnector } from './mem.js'
export { microsoftDynamicsCrmConnector } from './microsoft-dynamics-crm.js'
export { microsoftDynamics365BusinessCentralConnector } from './microsoft-dynamics-365-business-central.js'
export { microsoft365PlannerConnector } from './microsoft-365-planner.js'
export { microsoftPowerBiConnector } from './microsoft-power-bi.js'
export { microsoftOutlookCalendarConnector } from './microsoft-outlook-calendar.js'
export { microsoftOnenoteConnector } from './microsoft-onenote.js'
export { microsoftOutlookConnector } from './microsoft-outlook.js'
export { microsoftExcel365Connector } from './microsoft-excel-365.js'
export { microsoftTodoConnector } from './microsoft-todo.js'
export { microsoftSharepointConnector } from './microsoft-sharepoint.js'
export { millionverifierConnector } from './millionverifier.js'
export { mindeeConnector } from './mindee.js'
export { mixmaxConnector } from './mixmax.js'
export { mixpanelConnector } from './mixpanel.js'
export { missiveConnector } from './missive.js'
