import { declarativeRestConnector } from './declarative-rest.js'

export const kapsoConnector = declarativeRestConnector({
  kind: 'kapso',
  displayName: 'Kapso',
  description: 'Send and receive WhatsApp messages, media, templates, and reactions through the Kapso WhatsApp API.',
  auth: { kind: 'api-key', hint: 'Kapso API key (X-API-Key header).' },
  category: 'comms',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://app.kapso.ai/api/v1',
  credentialPlacement: { kind: 'header', header: 'X-API-Key' },
  test: { method: 'GET', path: '/whatsapp/health' },
  capabilities: [
    {
      name: 'messages.send_text',
      class: 'mutation',
      description: 'Send a WhatsApp text message to a recipient phone number.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          body: { type: 'string' },
          previewUrl: { type: 'boolean' },
        },
        required: ['to', 'body'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/text',
        body: { to: '{to}', body: '{body}', preview_url: '{previewUrl}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_buttons',
      class: 'mutation',
      description: 'Send an interactive WhatsApp message with reply buttons.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          bodyText: { type: 'string' },
          buttons: { type: 'array' },
          footerText: { type: 'string' },
          headerText: { type: 'string' },
        },
        required: ['to', 'bodyText', 'buttons'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/buttons',
        body: {
          to: '{to}',
          body_text: '{bodyText}',
          buttons: '{buttons}',
          footer_text: '{footerText}',
          header_text: '{headerText}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_list',
      class: 'mutation',
      description: 'Send an interactive WhatsApp list message with selectable rows grouped in sections.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          bodyText: { type: 'string' },
          buttonText: { type: 'string' },
          sections: { type: 'array' },
          headerText: { type: 'string' },
          footerText: { type: 'string' },
        },
        required: ['to', 'bodyText', 'buttonText', 'sections'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/list',
        body: {
          to: '{to}',
          body_text: '{bodyText}',
          button_text: '{buttonText}',
          sections: '{sections}',
          header_text: '{headerText}',
          footer_text: '{footerText}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_image',
      class: 'mutation',
      description: 'Send an image to a WhatsApp recipient by public URL or previously uploaded media id.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          imageUrl: { type: 'string' },
          imageId: { type: 'string' },
          caption: { type: 'string' },
        },
        required: ['to'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/image',
        body: { to: '{to}', image_url: '{imageUrl}', image_id: '{imageId}', caption: '{caption}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_video',
      class: 'mutation',
      description: 'Send a video to a WhatsApp recipient by public URL or previously uploaded media id.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          videoUrl: { type: 'string' },
          videoId: { type: 'string' },
          caption: { type: 'string' },
        },
        required: ['to'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/video',
        body: { to: '{to}', video_url: '{videoUrl}', video_id: '{videoId}', caption: '{caption}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_audio',
      class: 'mutation',
      description: 'Send an audio message to a WhatsApp recipient by public URL or media id.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          audioUrl: { type: 'string' },
          audioId: { type: 'string' },
        },
        required: ['to'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/audio',
        body: { to: '{to}', audio_url: '{audioUrl}', audio_id: '{audioId}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_document',
      class: 'mutation',
      description: 'Send a document to a WhatsApp recipient by public URL or media id.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          documentUrl: { type: 'string' },
          documentId: { type: 'string' },
          filename: { type: 'string' },
          caption: { type: 'string' },
        },
        required: ['to'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/document',
        body: {
          to: '{to}',
          document_url: '{documentUrl}',
          document_id: '{documentId}',
          filename: '{filename}',
          caption: '{caption}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_sticker',
      class: 'mutation',
      description: 'Send a WebP sticker to a WhatsApp recipient.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          stickerUrl: { type: 'string' },
          stickerId: { type: 'string' },
        },
        required: ['to'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/sticker',
        body: { to: '{to}', sticker_url: '{stickerUrl}', sticker_id: '{stickerId}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_location',
      class: 'mutation',
      description: 'Share a location (latitude/longitude) with a WhatsApp recipient.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          latitude: { type: 'number' },
          longitude: { type: 'number' },
          name: { type: 'string' },
          address: { type: 'string' },
        },
        required: ['to', 'latitude', 'longitude'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/location',
        body: {
          to: '{to}',
          latitude: '{latitude}',
          longitude: '{longitude}',
          name: '{name}',
          address: '{address}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.request_location',
      class: 'mutation',
      description: 'Send an interactive message that prompts the recipient to share their location.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          bodyText: { type: 'string' },
        },
        required: ['to', 'bodyText'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/location-request',
        body: { to: '{to}', body_text: '{bodyText}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_contact',
      class: 'mutation',
      description: 'Share a contact card with a WhatsApp recipient.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          formattedName: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          phone: { type: 'string' },
          email: { type: 'string' },
          company: { type: 'string' },
        },
        required: ['to', 'formattedName'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/contact',
        body: {
          to: '{to}',
          formatted_name: '{formattedName}',
          first_name: '{firstName}',
          last_name: '{lastName}',
          phone: '{phone}',
          email: '{email}',
          company: '{company}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_reaction',
      class: 'mutation',
      description: 'React (or remove a reaction) to a WhatsApp message by message id.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          messageId: { type: 'string' },
          emoji: { type: 'string' },
        },
        required: ['to', 'messageId'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/reaction',
        body: { to: '{to}', message_id: '{messageId}', emoji: '{emoji}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.mark_as_read',
      class: 'mutation',
      description: 'Mark an inbound WhatsApp message as read by message id.',
      parameters: {
        type: 'object',
        properties: { messageId: { type: 'string' } },
        required: ['messageId'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/{messageId}/read',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'messages.send_template',
      class: 'mutation',
      description: 'Send a pre-approved WhatsApp template message with header, body, and button parameters.',
      parameters: {
        type: 'object',
        properties: {
          to: { type: 'string' },
          templateName: { type: 'string' },
          languageCode: { type: 'string' },
          headerType: { type: 'string' },
          headerTextParameters: { type: 'array' },
          headerMediaUrl: { type: 'string' },
          headerMediaFilename: { type: 'string' },
          headerLocationLatitude: { type: 'number' },
          headerLocationLongitude: { type: 'number' },
          headerLocationName: { type: 'string' },
          headerLocationAddress: { type: 'string' },
          bodyParameters: { type: 'array' },
          buttonParameters: { type: 'array' },
        },
        required: ['to', 'templateName', 'languageCode'],
      },
      request: {
        method: 'POST',
        path: '/whatsapp/messages/template',
        body: {
          to: '{to}',
          template_name: '{templateName}',
          language_code: '{languageCode}',
          header_type: '{headerType}',
          header_text_parameters: '{headerTextParameters}',
          header_media_url: '{headerMediaUrl}',
          header_media_filename: '{headerMediaFilename}',
          header_location_latitude: '{headerLocationLatitude}',
          header_location_longitude: '{headerLocationLongitude}',
          header_location_name: '{headerLocationName}',
          header_location_address: '{headerLocationAddress}',
          body_parameters: '{bodyParameters}',
          button_parameters: '{buttonParameters}',
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
