import { declarativeRestConnector } from './declarative-rest.js'

// LeadConnector (a.k.a. Go High Level / HighLevel) is a multi-tenant CRM and
// marketing-automation platform. The public REST surface lives at
// `services.leadconnectorhq.com` and is locationId-scoped: contacts, tasks,
// notes, opportunities, campaigns, and workflows all hang off a sub-account
// (location). OAuth tokens carry a `locationId` claim, so most write paths
// require it in either the path, query, or body.
export const leadConnectorConnector = declarativeRestConnector({
  kind: 'lead-connector',
  displayName: 'LeadConnector',
  description: 'Manage HighLevel (LeadConnector) contacts, opportunities, tasks, notes, campaigns, and workflows.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://marketplace.gohighlevel.com/oauth/chooselocation',
    tokenUrl: 'https://services.leadconnectorhq.com/oauth/token',
    scopes: [
      'contacts.readonly',
      'contacts.write',
      'opportunities.readonly',
      'opportunities.write',
      'campaigns.readonly',
      'workflows.readonly',
      'locations.readonly',
    ],
    clientIdEnv: 'LEAD_CONNECTOR_OAUTH_CLIENT_ID',
    clientSecretEnv: 'LEAD_CONNECTOR_OAUTH_CLIENT_SECRET',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://services.leadconnectorhq.com',
  defaultHeaders: { Version: '2021-07-28' },
  test: { method: 'GET', path: '/locations/' },
  capabilities: [
    {
      name: 'contacts.create',
      class: 'mutation',
      description: 'Create a contact in a HighLevel sub-account (location).',
      parameters: {
        type: 'object',
        properties: {
          locationId: { type: 'string', description: 'HighLevel sub-account id the contact belongs to.' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          name: { type: 'string', description: 'Full display name; used when first/last are not supplied.' },
          email: { type: 'string', format: 'email' },
          phone: { type: 'string' },
          address1: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          country: { type: 'string' },
          postalCode: { type: 'string' },
          website: { type: 'string' },
          timezone: { type: 'string' },
          companyName: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          customFields: { type: 'array', items: { type: 'object' }, description: 'Array of { id|key, field_value } entries.' },
          source: { type: 'string' },
        },
        required: ['locationId'],
      },
      request: {
        method: 'POST',
        path: '/contacts/',
        body: {
          locationId: '{locationId}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          name: '{name}',
          email: '{email}',
          phone: '{phone}',
          address1: '{address1}',
          city: '{city}',
          state: '{state}',
          country: '{country}',
          postalCode: '{postalCode}',
          website: '{website}',
          timezone: '{timezone}',
          companyName: '{companyName}',
          tags: '{tags}',
          customFields: '{customFields}',
          source: '{source}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contacts.write'],
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description: 'Patch attributes of an existing HighLevel contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          name: { type: 'string' },
          email: { type: 'string', format: 'email' },
          phone: { type: 'string' },
          address1: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          country: { type: 'string' },
          postalCode: { type: 'string' },
          website: { type: 'string' },
          timezone: { type: 'string' },
          companyName: { type: 'string' },
          tags: { type: 'array', items: { type: 'string' } },
          customFields: { type: 'array', items: { type: 'object' } },
          source: { type: 'string' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'PUT',
        path: '/contacts/{contactId}',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          name: '{name}',
          email: '{email}',
          phone: '{phone}',
          address1: '{address1}',
          city: '{city}',
          state: '{state}',
          country: '{country}',
          postalCode: '{postalCode}',
          website: '{website}',
          timezone: '{timezone}',
          companyName: '{companyName}',
          tags: '{tags}',
          customFields: '{customFields}',
          source: '{source}',
        },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['contacts.write'],
    },
    {
      name: 'contacts.search',
      class: 'read',
      description: 'Search contacts in a sub-account by email, phone, or free-text query.',
      parameters: {
        type: 'object',
        properties: {
          locationId: { type: 'string' },
          query: { type: 'string', description: 'Free-text search across name/email/phone.' },
          email: { type: 'string' },
          phone: { type: 'string' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          startAfter: { type: 'number', description: 'Page cursor (ms since epoch of the prior page boundary).' },
          startAfterId: { type: 'string', description: 'Page cursor id from the prior response.' },
        },
        required: ['locationId'],
      },
      request: {
        method: 'GET',
        path: '/contacts/',
        query: {
          locationId: '{locationId}',
          query: '{query}',
          email: '{email}',
          phone: '{phone}',
          limit: '{limit}',
          startAfter: '{startAfter}',
          startAfterId: '{startAfterId}',
        },
      },
      requiredScopes: ['contacts.readonly'],
    },
    {
      name: 'contacts.notes.add',
      class: 'mutation',
      description: 'Attach a note to a HighLevel contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          userId: { type: 'string', description: 'Authoring user id; defaults to the token owner when omitted.' },
          body: { type: 'string', description: 'Note body (plain text or HTML).' },
        },
        required: ['contactId', 'body'],
      },
      request: {
        method: 'POST',
        path: '/contacts/{contactId}/notes',
        body: { userId: '{userId}', body: '{body}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contacts.write'],
    },
    {
      name: 'contacts.campaigns.add',
      class: 'mutation',
      description: 'Add a contact to a marketing campaign.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          campaignId: { type: 'string' },
        },
        required: ['contactId', 'campaignId'],
      },
      request: {
        method: 'POST',
        path: '/contacts/{contactId}/campaigns/{campaignId}',
      },
      cas: 'native-idempotency',
      requiredScopes: ['contacts.write'],
      externalEffect: true,
    },
    {
      name: 'contacts.workflows.add',
      class: 'mutation',
      description: 'Enroll a contact in an automation workflow.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          workflowId: { type: 'string' },
          eventStartTime: { type: 'string', description: 'ISO-8601 timestamp to start workflow execution.' },
        },
        required: ['contactId', 'workflowId'],
      },
      request: {
        method: 'POST',
        path: '/contacts/{contactId}/workflow/{workflowId}',
        body: { eventStartTime: '{eventStartTime}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contacts.write'],
      externalEffect: true,
    },
    {
      name: 'opportunities.create',
      class: 'mutation',
      description: 'Create an opportunity within a pipeline stage.',
      parameters: {
        type: 'object',
        properties: {
          locationId: { type: 'string' },
          pipelineId: { type: 'string' },
          pipelineStageId: { type: 'string' },
          name: { type: 'string' },
          status: { type: 'string', enum: ['open', 'won', 'lost', 'abandoned'] },
          contactId: { type: 'string' },
          monetaryValue: { type: 'number' },
          assignedTo: { type: 'string', description: 'Assignee user id.' },
          source: { type: 'string' },
          customFields: { type: 'array', items: { type: 'object' } },
        },
        required: ['locationId', 'pipelineId', 'pipelineStageId', 'name'],
      },
      request: {
        method: 'POST',
        path: '/opportunities/',
        body: {
          locationId: '{locationId}',
          pipelineId: '{pipelineId}',
          pipelineStageId: '{pipelineStageId}',
          name: '{name}',
          status: '{status}',
          contactId: '{contactId}',
          monetaryValue: '{monetaryValue}',
          assignedTo: '{assignedTo}',
          source: '{source}',
          customFields: '{customFields}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['opportunities.write'],
    },
    {
      name: 'opportunities.update',
      class: 'mutation',
      description: 'Update an opportunity status, value, stage, or assignment.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          pipelineId: { type: 'string' },
          pipelineStageId: { type: 'string' },
          name: { type: 'string' },
          status: { type: 'string', enum: ['open', 'won', 'lost', 'abandoned'] },
          monetaryValue: { type: 'number' },
          assignedTo: { type: 'string' },
          customFields: { type: 'array', items: { type: 'object' } },
        },
        required: ['opportunityId'],
      },
      request: {
        method: 'PUT',
        path: '/opportunities/{opportunityId}',
        body: {
          pipelineId: '{pipelineId}',
          pipelineStageId: '{pipelineStageId}',
          name: '{name}',
          status: '{status}',
          monetaryValue: '{monetaryValue}',
          assignedTo: '{assignedTo}',
          customFields: '{customFields}',
        },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['opportunities.write'],
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a task on a HighLevel contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          title: { type: 'string' },
          body: { type: 'string', description: 'Task description.' },
          dueDate: { type: 'string', description: 'ISO-8601 due date.' },
          completed: { type: 'boolean' },
          assignedTo: { type: 'string', description: 'Assignee user id.' },
        },
        required: ['contactId', 'title', 'dueDate'],
      },
      request: {
        method: 'POST',
        path: '/contacts/{contactId}/tasks/',
        body: {
          title: '{title}',
          body: '{body}',
          dueDate: '{dueDate}',
          completed: '{completed}',
          assignedTo: '{assignedTo}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['contacts.write'],
    },
    {
      name: 'tasks.update',
      class: 'mutation',
      description: 'Update a task on a HighLevel contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          taskId: { type: 'string' },
          title: { type: 'string' },
          body: { type: 'string' },
          dueDate: { type: 'string' },
          completed: { type: 'boolean' },
          assignedTo: { type: 'string' },
        },
        required: ['contactId', 'taskId'],
      },
      request: {
        method: 'PUT',
        path: '/contacts/{contactId}/tasks/{taskId}',
        body: {
          title: '{title}',
          body: '{body}',
          dueDate: '{dueDate}',
          completed: '{completed}',
          assignedTo: '{assignedTo}',
        },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['contacts.write'],
    },
  ],
})
