import { declarativeRestConnector } from './declarative-rest.js'

// Lemlist REST API. Auth: Basic with empty user + API key as password, or
// query parameter `?access_token=<api_key>`. We use the query placement
// because it is the simplest declarative mapping for the shared rest engine.
export const lemlistConnector = declarativeRestConnector({
  kind: 'lemlist',
  displayName: 'Lemlist',
  description:
    'Manage Lemlist outbound campaigns: add/update/remove leads, mark leads interested or not interested, pause or resume leads, unsubscribe leads, and search leads.',
  auth: {
    kind: 'api-key',
    hint: 'Lemlist API key from Settings → Integrations → API. Sent as ?access_token=<api_key> on every request.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.lemlist.com/api',
  credentialPlacement: { kind: 'query', parameter: 'access_token' },
  test: { method: 'GET', path: '/team' },
  capabilities: [
    {
      name: 'leads.search',
      class: 'read',
      description: 'Search for a lead by email across the workspace.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string', description: 'Lead email to look up.' } },
        required: ['email'],
      },
      request: { method: 'GET', path: '/leads/{email}' },
    },
    {
      name: 'leads.add.to.campaign',
      class: 'mutation',
      description: 'Add a lead to a specific campaign.',
      parameters: {
        type: 'object',
        properties: {
          campaignId: { type: 'string', description: 'Lemlist campaign id.' },
          email: { type: 'string', description: 'Lead email (required).' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          picture: { type: 'string' },
          phone: { type: 'string' },
          linkedinUrl: { type: 'string' },
          companyName: { type: 'string' },
          companyDomain: { type: 'string' },
          icebreaker: { type: 'string' },
          jobTitle: { type: 'string' },
          deduplicate: { type: 'boolean' },
          linkedinEnrichment: { type: 'boolean' },
          findEmail: { type: 'boolean' },
          verifyEmail: { type: 'boolean' },
          findPhone: { type: 'boolean' },
        },
        required: ['campaignId', 'email'],
      },
      request: {
        method: 'POST',
        path: '/campaigns/{campaignId}/leads/{email}',
        query: {
          deduplicate: '{deduplicate}',
          linkedinEnrichment: '{linkedinEnrichment}',
          findEmail: '{findEmail}',
          verifyEmail: '{verifyEmail}',
          findPhone: '{findPhone}',
        },
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          picture: '{picture}',
          phone: '{phone}',
          linkedinUrl: '{linkedinUrl}',
          companyName: '{companyName}',
          companyDomain: '{companyDomain}',
          icebreaker: '{icebreaker}',
          jobTitle: '{jobTitle}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.update.in.campaign',
      class: 'mutation',
      description: 'Update fields on an existing lead in a campaign.',
      parameters: {
        type: 'object',
        properties: {
          campaignId: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          picture: { type: 'string' },
          phone: { type: 'string' },
          linkedinUrl: { type: 'string' },
          companyName: { type: 'string' },
          companyDomain: { type: 'string' },
          icebreaker: { type: 'string' },
          jobTitle: { type: 'string' },
        },
        required: ['campaignId', 'email'],
      },
      request: {
        method: 'PATCH',
        path: '/campaigns/{campaignId}/leads/{email}',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          picture: '{picture}',
          phone: '{phone}',
          linkedinUrl: '{linkedinUrl}',
          companyName: '{companyName}',
          companyDomain: '{companyDomain}',
          icebreaker: '{icebreaker}',
          jobTitle: '{jobTitle}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.remove.from.campaign',
      class: 'mutation',
      description: 'Remove a lead from a campaign (destructive).',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' }, email: { type: 'string' } },
        required: ['campaignId', 'email'],
      },
      request: { method: 'DELETE', path: '/campaigns/{campaignId}/leads/{email}' },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.mark.interested.in.campaign',
      class: 'mutation',
      description: 'Mark a lead in one campaign as interested.',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' }, email: { type: 'string' } },
        required: ['campaignId', 'email'],
      },
      request: { method: 'POST', path: '/campaigns/{campaignId}/leads/{email}/interested' },
    },
    {
      name: 'leads.mark.not.interested.in.campaign',
      class: 'mutation',
      description: 'Mark a lead in one campaign as not interested.',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' }, email: { type: 'string' } },
        required: ['campaignId', 'email'],
      },
      request: { method: 'POST', path: '/campaigns/{campaignId}/leads/{email}/notInterested' },
    },
    {
      name: 'leads.mark.interested.all.campaigns',
      class: 'mutation',
      description: 'Mark a lead in every campaign they appear in as interested.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'POST', path: '/leads/{email}/interested' },
    },
    {
      name: 'leads.mark.not.interested.all.campaigns',
      class: 'mutation',
      description: 'Mark a lead in every campaign they appear in as not interested.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'POST', path: '/leads/{email}/notInterested' },
    },
    {
      name: 'leads.pause.in.campaigns',
      class: 'mutation',
      description: 'Pause a lead in all campaigns, or in a specific campaign when campaignId is provided.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          campaignId: { type: 'string', description: 'Optional. Limit pause to one campaign.' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/leads/{email}/pause',
        query: { campaignId: '{campaignId}' },
      },
    },
    {
      name: 'leads.resume.in.campaigns',
      class: 'mutation',
      description: 'Resume a paused lead in all campaigns, or in a specific campaign when campaignId is provided.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          campaignId: { type: 'string', description: 'Optional. Limit resume to one campaign.' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/leads/{email}/resume',
        query: { campaignId: '{campaignId}' },
      },
    },
    {
      name: 'leads.unsubscribe',
      class: 'mutation',
      description: 'Unsubscribe a lead from the workspace.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'POST', path: '/unsubscribes/{email}' },
    },
    {
      name: 'unsubscribes.remove',
      class: 'mutation',
      description: 'Remove a lead from the workspace unsubscribe list (destructive).',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'DELETE', path: '/unsubscribes/{email}' },
      cas: 'native-idempotency',
    },
  ],
})
