import { declarativeRestConnector } from './declarative-rest.js'

/**
 * Lever ATS connector.
 *
 * - OAuth2 (authorization code) — production host `auth.lever.co`,
 *   sandbox host `sandbox-lever.auth0.com`. We default to production; callers
 *   that need sandbox set metadata.authHost / metadata.apiHost (the
 *   declarative-rest adapter only routes one baseUrl — we expose the prod API
 *   here and let callers override via {metadataKey: 'apiBase', fallback: ...}).
 * - REST API: https://api.lever.co/v1
 * - Scopes: each resource has read + write variants (e.g. `opportunities:read:admin`,
 *   `postings:write:admin`); offline_access is required for refresh tokens.
 *   See https://hire.lever.co/developer/oauth.
 */
export const leverConnector = declarativeRestConnector({
  kind: 'lever',
  displayName: 'Lever',
  description: 'Search and mutate Lever ATS opportunities (candidates), postings, requisitions, and notes.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://auth.lever.co/authorize',
    tokenUrl: 'https://auth.lever.co/oauth/token',
    scopes: [
      'offline_access',
      'opportunities:read:admin',
      'opportunities:write:admin',
      'postings:read:admin',
      'postings:write:admin',
      'requisitions:read:admin',
      'requisitions:write:admin',
      'users:read:admin',
      'stages:read:admin',
      'archive_reasons:read:admin',
      'sources:read:admin',
    ],
    clientIdEnv: 'LEVER_OAUTH_CLIENT_ID',
    clientSecretEnv: 'LEVER_OAUTH_CLIENT_SECRET',
  },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'apiBase', fallback: 'https://api.lever.co' },
  test: { method: 'GET', path: '/v1/users', query: { limit: '1' } },
  capabilities: [
    {
      name: 'opportunities.search',
      class: 'read',
      description: 'List Lever opportunities (candidates) with optional filters.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string', description: 'Filter to opportunities for a candidate email.' },
          posting_id: { type: 'string' },
          stage_id: { type: 'string' },
          archived: { type: 'boolean' },
          archived_posting_id: { type: 'string' },
          tag: { type: 'string' },
          contact_id: { type: 'string' },
          source: { type: 'string' },
          created_at_start: { type: 'integer', description: 'Epoch ms.' },
          created_at_end: { type: 'integer', description: 'Epoch ms.' },
          updated_at_start: { type: 'integer' },
          updated_at_end: { type: 'integer' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
          expand: { type: 'string', description: 'Comma-sep list e.g. "applications,stage,owner,followers".' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/opportunities',
        query: {
          email: '{email}',
          posting_id: '{posting_id}',
          stage_id: '{stage_id}',
          archived: '{archived}',
          archived_posting_id: '{archived_posting_id}',
          tag: '{tag}',
          contact_id: '{contact_id}',
          source: '{source}',
          created_at_start: '{created_at_start}',
          created_at_end: '{created_at_end}',
          updated_at_start: '{updated_at_start}',
          updated_at_end: '{updated_at_end}',
          limit: '{limit}',
          offset: '{offset}',
          expand: '{expand}',
        },
      },
      requiredScopes: ['opportunities:read:admin'],
    },
    {
      name: 'opportunities.get',
      class: 'read',
      description: 'Read a single Lever opportunity by id.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          expand: { type: 'string' },
        },
        required: ['opportunityId'],
      },
      request: {
        method: 'GET',
        path: '/v1/opportunities/{opportunityId}',
        query: { expand: '{expand}' },
      },
      requiredScopes: ['opportunities:read:admin'],
    },
    {
      name: 'opportunities.create',
      class: 'mutation',
      description: 'Create a candidate opportunity. perform_as is required (the Lever user id taking the action).',
      parameters: {
        type: 'object',
        properties: {
          perform_as: { type: 'string', description: 'Lever user id (passed as query param).' },
          name: { type: 'string' },
          headline: { type: 'string' },
          emails: { type: 'array', items: { type: 'string', format: 'email' } },
          phones: { type: 'array', items: { type: 'object' } },
          links: { type: 'array', items: { type: 'string' } },
          tags: { type: 'array', items: { type: 'string' } },
          sources: { type: 'array', items: { type: 'string' } },
          origin: { type: 'string', enum: ['applied', 'sourced', 'referred', 'university', 'agency', 'internal'] },
          owner: { type: 'string' },
          stage: { type: 'string' },
          postings: { type: 'array', items: { type: 'string' } },
          contact: { type: 'string' },
        },
        required: ['perform_as'],
      },
      request: {
        method: 'POST',
        path: '/v1/opportunities',
        query: { perform_as: '{perform_as}' },
        body: {
          name: '{name}',
          headline: '{headline}',
          emails: '{emails}',
          phones: '{phones}',
          links: '{links}',
          tags: '{tags}',
          sources: '{sources}',
          origin: '{origin}',
          owner: '{owner}',
          stage: '{stage}',
          postings: '{postings}',
          contact: '{contact}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['opportunities:write:admin'],
    },
    {
      name: 'opportunities.addNote',
      class: 'mutation',
      description: 'Add a note to a Lever opportunity.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          perform_as: { type: 'string' },
          value: { type: 'string', description: 'Note body.' },
          secret: { type: 'boolean' },
        },
        required: ['opportunityId', 'perform_as', 'value'],
      },
      request: {
        method: 'POST',
        path: '/v1/opportunities/{opportunityId}/notes',
        query: { perform_as: '{perform_as}' },
        body: { value: '{value}', secret: '{secret}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['opportunities:write:admin'],
    },
    {
      name: 'opportunities.advanceStage',
      class: 'mutation',
      description: 'Move a Lever opportunity to a different stage.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          perform_as: { type: 'string' },
          stage: { type: 'string', description: 'Target stage id.' },
        },
        required: ['opportunityId', 'perform_as', 'stage'],
      },
      request: {
        method: 'PUT',
        path: '/v1/opportunities/{opportunityId}/stage',
        query: { perform_as: '{perform_as}' },
        body: { stage: '{stage}' },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['opportunities:write:admin'],
    },
    {
      name: 'opportunities.archive',
      class: 'mutation',
      description: 'Archive a Lever opportunity with a reason.',
      parameters: {
        type: 'object',
        properties: {
          opportunityId: { type: 'string' },
          perform_as: { type: 'string' },
          reason: { type: 'string', description: 'Archive reason id.' },
          requisitionId: { type: 'string', description: 'Optional hired-against requisition id.' },
        },
        required: ['opportunityId', 'perform_as', 'reason'],
      },
      request: {
        method: 'PUT',
        path: '/v1/opportunities/{opportunityId}/archived',
        query: { perform_as: '{perform_as}' },
        body: { reason: '{reason}', requisitionId: '{requisitionId}' },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['opportunities:write:admin'],
    },
    {
      name: 'postings.search',
      class: 'read',
      description: 'List Lever job postings with optional state / team / location filters.',
      parameters: {
        type: 'object',
        properties: {
          state: { type: 'string', enum: ['published', 'internal', 'closed', 'draft', 'pending', 'rejected'] },
          team: { type: 'string' },
          department: { type: 'string' },
          location: { type: 'string' },
          commitment: { type: 'string' },
          level: { type: 'string' },
          group: { type: 'string', enum: ['team', 'department', 'location', 'commitment', 'level'] },
          tag: { type: 'string' },
          created_at_start: { type: 'integer' },
          created_at_end: { type: 'integer' },
          updated_at_start: { type: 'integer' },
          updated_at_end: { type: 'integer' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/postings',
        query: {
          state: '{state}',
          team: '{team}',
          department: '{department}',
          location: '{location}',
          commitment: '{commitment}',
          level: '{level}',
          group: '{group}',
          tag: '{tag}',
          created_at_start: '{created_at_start}',
          created_at_end: '{created_at_end}',
          updated_at_start: '{updated_at_start}',
          updated_at_end: '{updated_at_end}',
          limit: '{limit}',
          offset: '{offset}',
        },
      },
      requiredScopes: ['postings:read:admin'],
    },
    {
      name: 'postings.get',
      class: 'read',
      description: 'Read a single Lever posting by id.',
      parameters: {
        type: 'object',
        properties: { postingId: { type: 'string' } },
        required: ['postingId'],
      },
      request: { method: 'GET', path: '/v1/postings/{postingId}' },
      requiredScopes: ['postings:read:admin'],
    },
    {
      name: 'postings.create',
      class: 'mutation',
      description: 'Create a Lever posting.',
      parameters: {
        type: 'object',
        properties: {
          perform_as: { type: 'string' },
          text: { type: 'string', description: 'Posting title.' },
          state: { type: 'string', enum: ['published', 'internal', 'closed', 'draft', 'pending', 'rejected'] },
          distributionChannels: { type: 'array', items: { type: 'string' } },
          user: { type: 'string', description: 'Hiring manager Lever user id.' },
          owner: { type: 'string', description: 'Posting owner Lever user id.' },
          hiringManager: { type: 'string' },
          categories: { type: 'object' },
          tags: { type: 'array', items: { type: 'string' } },
          content: { type: 'object', description: 'Posting body sections.' },
          country: { type: 'string' },
          followers: { type: 'array', items: { type: 'string' } },
          reqCode: { type: 'string' },
          requisitionCodes: { type: 'array', items: { type: 'string' } },
        },
        required: ['perform_as', 'text'],
      },
      request: {
        method: 'POST',
        path: '/v1/postings',
        query: { perform_as: '{perform_as}' },
        body: {
          text: '{text}',
          state: '{state}',
          distributionChannels: '{distributionChannels}',
          user: '{user}',
          owner: '{owner}',
          hiringManager: '{hiringManager}',
          categories: '{categories}',
          tags: '{tags}',
          content: '{content}',
          country: '{country}',
          followers: '{followers}',
          reqCode: '{reqCode}',
          requisitionCodes: '{requisitionCodes}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['postings:write:admin'],
    },
    {
      name: 'requisitions.search',
      class: 'read',
      description: 'List Lever requisitions.',
      parameters: {
        type: 'object',
        properties: {
          requisition_code: { type: 'string' },
          status: { type: 'string', enum: ['open', 'onHold', 'closed', 'draft'] },
          created_at_start: { type: 'integer' },
          created_at_end: { type: 'integer' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/requisitions',
        query: {
          requisition_code: '{requisition_code}',
          status: '{status}',
          created_at_start: '{created_at_start}',
          created_at_end: '{created_at_end}',
          limit: '{limit}',
          offset: '{offset}',
        },
      },
      requiredScopes: ['requisitions:read:admin'],
    },
    {
      name: 'requisitions.get',
      class: 'read',
      description: 'Read a single Lever requisition by id.',
      parameters: {
        type: 'object',
        properties: { requisitionId: { type: 'string' } },
        required: ['requisitionId'],
      },
      request: { method: 'GET', path: '/v1/requisitions/{requisitionId}' },
      requiredScopes: ['requisitions:read:admin'],
    },
    {
      name: 'users.search',
      class: 'read',
      description: 'List Lever users (recruiters, hiring managers).',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          access_role: { type: 'string', enum: ['super_admin', 'admin', 'team_member', 'limited_team_member', 'interviewer'] },
          deactivated: { type: 'boolean' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/users',
        query: {
          email: '{email}',
          access_role: '{access_role}',
          deactivated: '{deactivated}',
          limit: '{limit}',
          offset: '{offset}',
        },
      },
      requiredScopes: ['users:read:admin'],
    },
    {
      name: 'stages.list',
      class: 'read',
      description: 'List configured Lever pipeline stages.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/stages',
        query: { limit: '{limit}', offset: '{offset}' },
      },
      requiredScopes: ['stages:read:admin'],
    },
    {
      name: 'archive_reasons.list',
      class: 'read',
      description: 'List configured Lever archive reasons (required for archiving opportunities).',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/archive_reasons',
        query: { limit: '{limit}', offset: '{offset}' },
      },
      requiredScopes: ['archive_reasons:read:admin'],
    },
    {
      name: 'sources.list',
      class: 'read',
      description: 'List configured Lever opportunity sources.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          offset: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/v1/sources',
        query: { limit: '{limit}', offset: '{offset}' },
      },
      requiredScopes: ['sources:read:admin'],
    },
  ],
})
