import { declarativeRestConnector } from './declarative-rest.js'

// Linka is a white-label B2B marketplace built on the Sperse CRM API.
// All upstream endpoints live under the Sperse REST surface; the activepieces
// piece reuses the Sperse contact/subscription/invoice/product model.
export const linkaConnector = declarativeRestConnector({
  kind: 'linka',
  displayName: 'Linka',
  description:
    'Manage Linka (Sperse-powered) marketplace contacts, subscriptions, invoices, and products.',
  auth: {
    kind: 'api-key',
    hint: 'Linka / Sperse API key (sent as X-API-Key on every request).',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.sperse.com',
  test: { method: 'GET', path: '/api/v1/contacts/me' },
  capabilities: [
    {
      name: 'contacts.get',
      class: 'read',
      description: 'Get a Linka contact by Sperse contact ID.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'GET',
        path: '/api/v1/contacts/{contactId}',
      },
    },
    {
      name: 'contacts.upsert',
      class: 'mutation',
      description:
        'Add or update a Linka contact (mirrors activepieces addOrUpdateContact).',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'number' },
          contactXref: { type: 'string' },
          matchExisting: { type: 'boolean' },
          overrideLists: { type: 'boolean' },
          ignoreInvalidValues: { type: 'boolean' },
          importType: { type: 'string' },
          createUser: { type: 'boolean' },
          sendWelcomeEmail: { type: 'boolean' },
          fields: { type: 'object' },
        },
        required: ['importType'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/contacts',
        body: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
          matchExisting: '{matchExisting}',
          overrideLists: '{overrideLists}',
          ignoreInvalidValues: '{ignoreInvalidValues}',
          importType: '{importType}',
          createUser: '{createUser}',
          sendWelcomeEmail: '{sendWelcomeEmail}',
          fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.upsert.extended',
      class: 'mutation',
      description:
        'Add or update a Linka contact with extended profile fields (mirrors addOrUpdateContactExtended).',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'number' },
          contactXref: { type: 'string' },
          matchExisting: { type: 'boolean' },
          overrideLists: { type: 'boolean' },
          ignoreInvalidValues: { type: 'boolean' },
          importType: { type: 'string' },
          createUser: { type: 'boolean' },
          sendWelcomeEmail: { type: 'boolean' },
          userPassword: { type: 'string' },
          fields: { type: 'object' },
          social: { type: 'object' },
          company: { type: 'object' },
          tracking: { type: 'object' },
        },
        required: ['importType'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/contacts/extended',
        body: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
          matchExisting: '{matchExisting}',
          overrideLists: '{overrideLists}',
          ignoreInvalidValues: '{ignoreInvalidValues}',
          importType: '{importType}',
          createUser: '{createUser}',
          sendWelcomeEmail: '{sendWelcomeEmail}',
          userPassword: '{userPassword}',
          fields: '{fields}',
          social: '{social}',
          company: '{company}',
          tracking: '{tracking}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.upsert',
      class: 'mutation',
      description: 'Add or update a Linka subscription for a contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'number' },
          contactXref: { type: 'string' },
          subscriptionXref: { type: 'string' },
          productCode: { type: 'string' },
          status: { type: 'string' },
          startDate: { type: 'string' },
          endDate: { type: 'string' },
          fields: { type: 'object' },
        },
        required: ['productCode'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/subscriptions',
        body: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
          subscriptionXref: '{subscriptionXref}',
          productCode: '{productCode}',
          status: '{status}',
          startDate: '{startDate}',
          endDate: '{endDate}',
          fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create a Linka invoice for a contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'number' },
          contactXref: { type: 'string' },
          invoiceXref: { type: 'string' },
          currency: { type: 'string' },
          dueDate: { type: 'string' },
          lineItems: { type: 'array' },
          notes: { type: 'string' },
        },
        required: ['lineItems'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/invoices',
        body: {
          contactId: '{contactId}',
          contactXref: '{contactXref}',
          invoiceXref: '{invoiceXref}',
          currency: '{currency}',
          dueDate: '{dueDate}',
          lineItems: '{lineItems}',
          notes: '{notes}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a Linka product / catalog entry.',
      parameters: {
        type: 'object',
        properties: {
          productCode: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          price: { type: 'number' },
          currency: { type: 'string' },
          category: { type: 'string' },
          active: { type: 'boolean' },
          fields: { type: 'object' },
        },
        required: ['productCode', 'name'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/products',
        body: {
          productCode: '{productCode}',
          name: '{name}',
          description: '{description}',
          price: '{price}',
          currency: '{currency}',
          category: '{category}',
          active: '{active}',
          fields: '{fields}',
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
