import { declarativeRestConnector } from './declarative-rest.js'

export const loftyConnector = declarativeRestConnector({
  kind: 'lofty',
  displayName: 'Lofty',
  description: 'Create and update leads and transactions in Lofty for real estate agents.',
  auth: { kind: 'api-key', hint: 'Lofty API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.lofty.ai/v1',
  test: { method: 'GET', path: '/leads' },
  capabilities: [
    {
      name: 'leads.create',
      class: 'mutation',
      description: 'Create a lead in Lofty.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          source: { type: 'string' },
          leadType: { type: 'string' },
          minPrice: { type: 'number' },
          maxPrice: { type: 'number' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          beds: { type: 'number' },
          baths: { type: 'number' },
          tags: { type: 'array', items: { type: 'string' } },
          note: { type: 'string' },
          sendWelcomeEmail: { type: 'boolean' },
          emailOptIn: { type: 'boolean' },
        },
        required: ['firstName', 'email'],
      },
      request: { method: 'POST', path: '/leads', body: '{properties}' },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.update',
      class: 'mutation',
      description: 'Update a lead in Lofty.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          source: { type: 'string' },
          leadType: { type: 'string' },
          minPrice: { type: 'number' },
          maxPrice: { type: 'number' },
          city: { type: 'string' },
          state: { type: 'string' },
          zipcode: { type: 'string' },
          beds: { type: 'number' },
          baths: { type: 'number' },
          tags: { type: 'array', items: { type: 'string' } },
          note: { type: 'string' },
          emailOptIn: { type: 'boolean' },
        },
        required: ['leadId'],
      },
      request: { method: 'PUT', path: '/leads/{leadId}', body: '{properties}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'transactions.create',
      class: 'mutation',
      description: 'Create a transaction in Lofty.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          transactionDate: { type: 'string' },
          transactionType: { type: 'string' },
          amount: { type: 'number' },
          propertyAddress: { type: 'string' },
          propertyCity: { type: 'string' },
          propertyState: { type: 'string' },
          propertyZipcode: { type: 'string' },
          beds: { type: 'number' },
          baths: { type: 'number' },
          sqft: { type: 'number' },
          mlsNumber: { type: 'string' },
          closingDate: { type: 'string' },
        },
        required: ['leadId', 'transactionType'],
      },
      request: { method: 'POST', path: '/transactions', body: '{properties}' },
      cas: 'native-idempotency',
    },
    {
      name: 'transactions.update',
      class: 'mutation',
      description: 'Update a transaction in Lofty.',
      parameters: {
        type: 'object',
        properties: {
          transactionId: { type: 'string' },
          transactionDate: { type: 'string' },
          transactionType: { type: 'string' },
          amount: { type: 'number' },
          propertyAddress: { type: 'string' },
          propertyCity: { type: 'string' },
          propertyState: { type: 'string' },
          propertyZipcode: { type: 'string' },
          beds: { type: 'number' },
          baths: { type: 'number' },
          sqft: { type: 'number' },
          mlsNumber: { type: 'string' },
          closingDate: { type: 'string' },
        },
        required: ['transactionId'],
      },
      request: { method: 'PUT', path: '/transactions/{transactionId}', body: '{properties}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.delete',
      class: 'mutation',
      description: 'Delete a lead by id.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
        },
        required: ['leadId'],
      },
      request: { method: 'DELETE', path: '/leads/{leadId}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a task on a lead.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          dueDate: { type: 'string' },
          priority: { type: 'string' },
          assigneeId: { type: 'string' },
          status: { type: 'string' },
        },
        required: ['leadId', 'title'],
      },
      request: { method: 'POST', path: '/leads/{leadId}/tasks', body: '{properties}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
