import { declarativeRestConnector } from './declarative-rest.js'

export const lokaliseConnector = declarativeRestConnector({
  kind: 'lokalise',
  displayName: 'Lokalise',
  description:
    'Manage Lokalise translation projects: read projects, keys, translations, and comments; create or update keys, translations, tasks, projects, and comments.',
  auth: {
    kind: 'api-key',
    hint: 'Lokalise API token, sent as the X-Api-Token header.',
  },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.lokalise.com/api2',
  test: { method: 'GET', path: '/projects' },
  capabilities: [
    {
      name: 'projects.create',
      class: 'mutation',
      description: 'Create a new Lokalise project.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          team_id: { type: 'string' },
          description: { type: 'string' },
          base_lang_iso: { type: 'string' },
          languages: { type: 'array', items: { type: 'object' } },
          project_type: { type: 'string' },
          is_segmentation_enabled: { type: 'boolean' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/projects',
        body: {
          name: '{name}',
          team_id: '{team_id}',
          description: '{description}',
          base_lang_iso: '{base_lang_iso}',
          languages: '{languages}',
          project_type: '{project_type}',
          is_segmentation_enabled: '{is_segmentation_enabled}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'projects.get',
      class: 'read',
      description: 'Retrieve a single Lokalise project.',
      parameters: {
        type: 'object',
        properties: { project_id: { type: 'string' } },
        required: ['project_id'],
      },
      request: { method: 'GET', path: '/projects/{project_id}' },
    },
    {
      name: 'keys.create',
      class: 'mutation',
      description: 'Create one or more translation keys in a project.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          keys: { type: 'array', items: { type: 'object' } },
          use_automations: { type: 'boolean' },
        },
        required: ['project_id', 'keys'],
      },
      request: {
        method: 'POST',
        path: '/projects/{project_id}/keys',
        body: {
          keys: '{keys}',
          use_automations: '{use_automations}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'keys.get',
      class: 'read',
      description: 'Retrieve a single key from a project.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          key_id: { type: 'string' },
          disable_references: { type: 'boolean' },
        },
        required: ['project_id', 'key_id'],
      },
      request: {
        method: 'GET',
        path: '/projects/{project_id}/keys/{key_id}',
        query: { disable_references: '{disable_references}' },
      },
    },
    {
      name: 'keys.update',
      class: 'mutation',
      description: 'Update an existing translation key.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          key_id: { type: 'string' },
          key_name: { type: 'string' },
          description: { type: 'string' },
          platforms: { type: 'array', items: { type: 'string' } },
          tags: { type: 'array', items: { type: 'string' } },
          merge_tags: { type: 'boolean' },
          is_plural: { type: 'boolean' },
          plural_name: { type: 'string' },
          is_hidden: { type: 'boolean' },
          is_archived: { type: 'boolean' },
          context: { type: 'string' },
          char_limit: { type: 'integer' },
        },
        required: ['project_id', 'key_id'],
      },
      request: {
        method: 'PUT',
        path: '/projects/{project_id}/keys/{key_id}',
        body: {
          key_name: '{key_name}',
          description: '{description}',
          platforms: '{platforms}',
          tags: '{tags}',
          merge_tags: '{merge_tags}',
          is_plural: '{is_plural}',
          plural_name: '{plural_name}',
          is_hidden: '{is_hidden}',
          is_archived: '{is_archived}',
          context: '{context}',
          char_limit: '{char_limit}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'keys.delete',
      class: 'mutation',
      description: 'Delete a translation key from a project.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          key_id: { type: 'string' },
        },
        required: ['project_id', 'key_id'],
      },
      request: { method: 'DELETE', path: '/projects/{project_id}/keys/{key_id}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'translations.get',
      class: 'read',
      description: 'Retrieve a single translation by id.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          translation_id: { type: 'string' },
          disable_references: { type: 'boolean' },
        },
        required: ['project_id', 'translation_id'],
      },
      request: {
        method: 'GET',
        path: '/projects/{project_id}/translations/{translation_id}',
        query: { disable_references: '{disable_references}' },
      },
    },
    {
      name: 'translations.update',
      class: 'mutation',
      description: 'Update a translation by id.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          translation_id: { type: 'string' },
          translation: { type: 'string' },
          is_unverified: { type: 'boolean' },
          is_reviewed: { type: 'boolean' },
          custom_translation_status_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['project_id', 'translation_id', 'translation'],
      },
      request: {
        method: 'PUT',
        path: '/projects/{project_id}/translations/{translation_id}',
        body: {
          translation: '{translation}',
          is_unverified: '{is_unverified}',
          is_reviewed: '{is_reviewed}',
          custom_translation_status_ids: '{custom_translation_status_ids}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a translation or review task within a project.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          title: { type: 'string' },
          task_type: { type: 'string' },
          keys: { type: 'array', items: { type: 'integer' } },
          languages: { type: 'array', items: { type: 'object' } },
          source_language_iso: { type: 'string' },
          due_date: { type: 'string' },
          auto_close_languages: { type: 'boolean' },
          auto_close_task: { type: 'boolean' },
          closing_tags: { type: 'array', items: { type: 'string' } },
          do_lock_translations: { type: 'boolean' },
          mark_verified: { type: 'boolean' },
          save_ai_translation_to_tm: { type: 'boolean' },
          apply_ai_tm_100_matches: { type: 'boolean' },
        },
        required: ['project_id', 'title'],
      },
      request: {
        method: 'POST',
        path: '/projects/{project_id}/tasks',
        body: {
          title: '{title}',
          task_type: '{task_type}',
          keys: '{keys}',
          languages: '{languages}',
          source_language_iso: '{source_language_iso}',
          due_date: '{due_date}',
          auto_close_languages: '{auto_close_languages}',
          auto_close_task: '{auto_close_task}',
          closing_tags: '{closing_tags}',
          do_lock_translations: '{do_lock_translations}',
          mark_verified: '{mark_verified}',
          save_ai_translation_to_tm: '{save_ai_translation_to_tm}',
          apply_ai_tm_100_matches: '{apply_ai_tm_100_matches}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'comments.create',
      class: 'mutation',
      description: 'Add a comment to a key in a project.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          key_id: { type: 'string' },
          comment: { type: 'string' },
        },
        required: ['project_id', 'key_id', 'comment'],
      },
      request: {
        method: 'POST',
        path: '/projects/{project_id}/keys/{key_id}/comments',
        body: { comments: [{ comment: '{comment}' }] },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'comments.get',
      class: 'read',
      description: 'Retrieve a single comment on a key.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string' },
          key_id: { type: 'string' },
          comment_id: { type: 'string' },
        },
        required: ['project_id', 'key_id', 'comment_id'],
      },
      request: {
        method: 'GET',
        path: '/projects/{project_id}/keys/{key_id}/comments/{comment_id}',
      },
    },
  ],
})
