import { declarativeRestConnector } from './declarative-rest.js'

export const missiveConnector = declarativeRestConnector({
  kind: 'missive',
  displayName: 'Missive',
  description:
    'Manage Missive contacts, draft posts, and tasks, and look up contacts in shared contact books.',
  auth: { kind: 'api-key', hint: 'Missive API token, sent as `Authorization: Bearer <token>`.' },
  category: 'comms',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://public.missiveapp.com/v1',
  test: { method: 'GET', path: '/users' },
  capabilities: [
    {
      name: 'contacts.find',
      class: 'read',
      description:
        'Search contacts in a Missive contact book, optionally filtered by free-text search, modification time, or deletion state.',
      parameters: {
        type: 'object',
        properties: {
          contact_book: { type: 'string' },
          search: { type: 'string' },
          order: { type: 'string' },
          limit: { type: 'integer' },
          offset: { type: 'integer' },
          modified_since: { type: 'integer' },
          include_deleted: { type: 'boolean' },
        },
        required: ['contact_book'],
      },
      request: {
        method: 'GET',
        path: '/contacts',
        query: {
          contact_book: '{contact_book}',
          search: '{search}',
          order: '{order}',
          limit: '{limit}',
          offset: '{offset}',
          modified_since: '{modified_since}',
          include_deleted: '{include_deleted}',
        },
      },
    },
    {
      name: 'contacts.create',
      class: 'mutation',
      description:
        'Create a contact in a Missive contact book. `infos` carries the emails/phones/addresses and `memberships` carries the organization or group links.',
      parameters: {
        type: 'object',
        properties: {
          contact_book: { type: 'string' },
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          middle_name: { type: 'string' },
          phonetic_first_name: { type: 'string' },
          phonetic_last_name: { type: 'string' },
          phonetic_middle_name: { type: 'string' },
          prefix: { type: 'string' },
          suffix: { type: 'string' },
          nickname: { type: 'string' },
          file_as: { type: 'string' },
          notes: { type: 'string' },
          starred: { type: 'boolean' },
          gender: { type: 'string' },
          infos: { type: 'array', items: { type: 'object' } },
          memberships: { type: 'array', items: { type: 'object' } },
        },
        required: ['contact_book'],
      },
      request: {
        method: 'POST',
        path: '/contacts',
        body: {
          contacts: {
            contact_book: '{contact_book}',
            first_name: '{first_name}',
            last_name: '{last_name}',
            middle_name: '{middle_name}',
            phonetic_first_name: '{phonetic_first_name}',
            phonetic_last_name: '{phonetic_last_name}',
            phonetic_middle_name: '{phonetic_middle_name}',
            prefix: '{prefix}',
            suffix: '{suffix}',
            nickname: '{nickname}',
            file_as: '{file_as}',
            notes: '{notes}',
            starred: '{starred}',
            gender: '{gender}',
            infos: '{infos}',
            memberships: '{memberships}',
          },
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description:
        'Update an existing Missive contact by id. Optionally move the contact to a different contact book.',
      parameters: {
        type: 'object',
        properties: {
          contact_id: { type: 'string' },
          move_to_contact_book: { type: 'string' },
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          middle_name: { type: 'string' },
          nickname: { type: 'string' },
          notes: { type: 'string' },
          starred: { type: 'boolean' },
          gender: { type: 'string' },
          infos: { type: 'array', items: { type: 'object' } },
          memberships: { type: 'array', items: { type: 'object' } },
        },
        required: ['contact_id'],
      },
      request: {
        method: 'PATCH',
        path: '/contacts/{contact_id}',
        body: {
          contacts: {
            move_to_contact_book: '{move_to_contact_book}',
            first_name: '{first_name}',
            last_name: '{last_name}',
            middle_name: '{middle_name}',
            nickname: '{nickname}',
            notes: '{notes}',
            starred: '{starred}',
            gender: '{gender}',
            infos: '{infos}',
            memberships: '{memberships}',
          },
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'drafts.create',
      class: 'mutation',
      description:
        'Create a draft post in Missive. Set `send` to deliver immediately, or pass `send_at` to schedule. Supports attachments and conversation/team metadata.',
      parameters: {
        type: 'object',
        properties: {
          account: { type: 'string' },
          subject: { type: 'string' },
          body: { type: 'string' },
          from_field: { type: 'object' },
          to_fields: { type: 'array', items: { type: 'object' } },
          cc_fields: { type: 'array', items: { type: 'object' } },
          bcc_fields: { type: 'array', items: { type: 'object' } },
          attachments: { type: 'array', items: { type: 'object' } },
          references: { type: 'array', items: { type: 'string' } },
          conversation: { type: 'string' },
          conversation_subject: { type: 'string' },
          conversation_color: { type: 'string' },
          team: { type: 'string' },
          force_team: { type: 'boolean' },
          add_to_inbox: { type: 'boolean' },
          add_to_team_inbox: { type: 'boolean' },
          close: { type: 'boolean' },
          add_shared_labels: { type: 'array', items: { type: 'string' } },
          remove_shared_labels: { type: 'array', items: { type: 'string' } },
          send: { type: 'boolean' },
          send_at: { type: 'integer' },
          auto_followup: { type: 'boolean' },
        },
        required: ['body'],
      },
      request: {
        method: 'POST',
        path: '/drafts',
        body: {
          drafts: {
            account: '{account}',
            subject: '{subject}',
            body: '{body}',
            from_field: '{from_field}',
            to_fields: '{to_fields}',
            cc_fields: '{cc_fields}',
            bcc_fields: '{bcc_fields}',
            attachments: '{attachments}',
            references: '{references}',
            conversation: '{conversation}',
            conversation_subject: '{conversation_subject}',
            conversation_color: '{conversation_color}',
            team: '{team}',
            force_team: '{force_team}',
            add_to_inbox: '{add_to_inbox}',
            add_to_team_inbox: '{add_to_team_inbox}',
            close: '{close}',
            add_shared_labels: '{add_shared_labels}',
            remove_shared_labels: '{remove_shared_labels}',
            send: '{send}',
            send_at: '{send_at}',
            auto_followup: '{auto_followup}',
          },
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description:
        'Create a task in Missive. Standalone tasks need `team`; conversation tasks need `conversation`; subtasks need `parent_task`.',
      parameters: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          description: { type: 'string' },
          team: { type: 'string' },
          conversation: { type: 'string' },
          parent_task: { type: 'string' },
          assignees: { type: 'array', items: { type: 'string' } },
          state: { type: 'string' },
          due_at: { type: 'integer' },
        },
        required: ['title'],
      },
      request: {
        method: 'POST',
        path: '/tasks',
        body: {
          tasks: {
            title: '{title}',
            description: '{description}',
            team: '{team}',
            conversation: '{conversation}',
            parent_task: '{parent_task}',
            assignees: '{assignees}',
            state: '{state}',
            due_at: '{due_at}',
          },
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
