import { declarativeRestConnector } from './declarative-rest.js'

export const mollieConnector = declarativeRestConnector({
  kind: 'mollie',
  displayName: 'Mollie',
  description:
    'Manage Mollie payments, orders, refunds, customers, and invoices. Automate payment processing and track payment statuses.',
  auth: { kind: 'api-key', hint: 'Mollie API key (found in your Mollie dashboard under Developers → API keys).' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.mollie.com/v2',
  test: { method: 'GET', path: '/customers', query: { limit: '1' } },
  capabilities: [
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a Mollie customer with optional name, email, and metadata.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          email: { type: 'string' },
          locale: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/customers',
        body: {
          name: '{name}',
          email: '{email}',
          locale: '{locale}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'customers.search',
      class: 'read',
      description: 'List or search Mollie customers with pagination.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer' },
          from: { type: 'string' },
          sort: { type: 'string', enum: ['name', '-name', 'createdAt', '-createdAt'] },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/customers',
        query: {
          limit: '{limit}',
          from: '{from}',
          sort: '{sort}',
        },
      },
    },
    {
      name: 'orders.create',
      class: 'mutation',
      description:
        'Create a Mollie order with order lines, billing address, and optional shipping address. Supports multiple payment methods and custom metadata.',
      parameters: {
        type: 'object',
        properties: {
          amount: { type: 'string' },
          currency: { type: 'string' },
          orderNumber: { type: 'string' },
          description: { type: 'string' },
          customerId: { type: 'string' },
          lines: { type: 'array', items: { type: 'object' } },
          redirectUrl: { type: 'string' },
          webhookUrl: { type: 'string' },
          locale: { type: 'string' },
          expiresAt: { type: 'string' },
          testmode: { type: 'boolean' },
        },
        required: ['amount', 'currency', 'orderNumber'],
      },
      request: {
        method: 'POST',
        path: '/orders',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          orderNumber: '{orderNumber}',
          description: '{description}',
          customerId: '{customerId}',
          lines: '{lines}',
          redirectUrl: '{redirectUrl}',
          webhookUrl: '{webhookUrl}',
          locale: '{locale}',
          expiresAt: '{expiresAt}',
          testmode: '{testmode}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'orders.search',
      class: 'read',
      description: 'Search Mollie orders with optional filtering by status and profile.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer' },
          status: {
            type: 'string',
            enum: ['created', 'paid', 'authorized', 'canceled', 'shipping', 'completed', 'expired'],
          },
          profileId: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/orders',
        query: {
          limit: '{limit}',
          status: '{status}',
          profileId: '{profileId}',
        },
      },
    },
    {
      name: 'payments.create',
      class: 'mutation',
      description:
        'Create a Mollie payment with optional customer, mandate, and method restrictions. Supports description, metadata, and webhook configuration.',
      parameters: {
        type: 'object',
        properties: {
          amount: { type: 'string' },
          currency: { type: 'string' },
          description: { type: 'string' },
          customerId: { type: 'string' },
          mandateId: { type: 'string' },
          method: {
            type: 'string',
            enum: [
              'creditcard',
              'ideal',
              'paypal',
              'banktransfer',
              'directdebit',
              'kbc',
              'belfius',
              'girocard',
              'eps',
              'giropay',
              'przelewy24',
              'payip',
              'klarnasliceit',
              'klarnapaylater',
              'klarnapaynow',
              'klarnasliceithome',
              'satispay',
              'applepay',
              'googlepay',
              'twint',
              'blik',
              'voucher',
            ],
          },
          redirectUrl: { type: 'string' },
          webhookUrl: { type: 'string' },
          locale: { type: 'string' },
          testmode: { type: 'boolean' },
        },
        required: ['amount', 'currency', 'description'],
      },
      request: {
        method: 'POST',
        path: '/payments',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          description: '{description}',
          customerId: '{customerId}',
          mandateId: '{mandateId}',
          method: '{method}',
          redirectUrl: '{redirectUrl}',
          webhookUrl: '{webhookUrl}',
          locale: '{locale}',
          testmode: '{testmode}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'payments.search',
      class: 'read',
      description: 'Search Mollie payments with optional status and profile filtering.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer' },
          status: {
            type: 'string',
            enum: ['open', 'pending', 'authorized', 'canceled', 'failed', 'expired', 'paid'],
          },
          profileId: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/payments',
        query: {
          limit: '{limit}',
          status: '{status}',
          profileId: '{profileId}',
        },
      },
    },
    {
      name: 'refunds.create',
      class: 'mutation',
      description: 'Create a refund for a Mollie payment with optional amount and description.',
      parameters: {
        type: 'object',
        properties: {
          paymentId: { type: 'string' },
          amount: { type: 'string' },
          currency: { type: 'string' },
          description: { type: 'string' },
        },
        required: ['paymentId'],
      },
      request: {
        method: 'POST',
        path: '/payments/{paymentId}/refunds',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          description: '{description}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'paymentlinks.create',
      class: 'mutation',
      description:
        'Create a Mollie payment link with optional fixed amount, billing address, and payment method restrictions.',
      parameters: {
        type: 'object',
        properties: {
          amount: { type: 'string' },
          currency: { type: 'string' },
          description: { type: 'string' },
          redirectUrl: { type: 'string' },
          webhookUrl: { type: 'string' },
          customerId: { type: 'string' },
          locale: { type: 'string' },
          method: { type: 'string' },
          testmode: { type: 'boolean' },
          reusable: { type: 'boolean' },
          expiresAt: { type: 'string' },
        },
        required: ['amount', 'currency', 'description'],
      },
      request: {
        method: 'POST',
        path: '/payment_links',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          description: '{description}',
          redirectUrl: '{redirectUrl}',
          webhookUrl: '{webhookUrl}',
          customerId: '{customerId}',
          locale: '{locale}',
          method: '{method}',
          testmode: '{testmode}',
          reusable: '{reusable}',
          expiresAt: '{expiresAt}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
