import { declarativeRestConnector } from './declarative-rest.js'

export const ninjapipeConnector = declarativeRestConnector({
  kind: 'ninjapipe',
  displayName: 'NinjaPipe',
  description: 'Connect to NinjaPipe and manage contacts, companies, deals, tasks, projects, products, and orders.',
  auth: { kind: 'api-key', hint: 'NinjaPipe API key from Workspace Settings > API.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'base_url', fallback: 'https://www.ninjapipe.app/api' },
  credentialPlacement: { kind: 'header', header: 'Authorization', prefix: 'Bearer' },
  test: { method: 'GET', path: '/contacts' },
  capabilities: [
    {
      name: 'contacts.list',
      class: 'read',
      description: 'List contacts in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/contacts' },
    },
    {
      name: 'contacts.get',
      class: 'read',
      description: 'Get a contact by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/contacts/{id}' },
    },
    {
      name: 'contacts.create',
      class: 'mutation',
      description: 'Create a new contact.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          company: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          status: { type: 'string' },
          owner: { type: 'string' },
          notes: { type: 'string' },
          customFields: { type: 'object' },
        },
        required: ['firstName', 'lastName', 'email'],
      },
      request: { method: 'POST', path: '/contacts', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description: 'Update a contact.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          company: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          status: { type: 'string' },
          owner: { type: 'string' },
          notes: { type: 'string' },
          customFields: { type: 'object' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/contacts/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'contacts.delete',
      class: 'mutation',
      description: 'Delete a contact.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/contacts/{id}' },
      externalEffect: true,
    },
    {
      name: 'contacts.upsert',
      class: 'mutation',
      description: 'Upsert a contact by email.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          company: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          status: { type: 'string' },
          owner: { type: 'string' },
          notes: { type: 'string' },
          customFields: { type: 'object' },
        },
        required: ['email'],
      },
      request: { method: 'POST', path: '/contacts/upsert', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'companies.list',
      class: 'read',
      description: 'List companies in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/companies' },
    },
    {
      name: 'companies.get',
      class: 'read',
      description: 'Get a company by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/companies/{id}' },
    },
    {
      name: 'companies.create',
      class: 'mutation',
      description: 'Create a new company.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          industry: { type: 'string' },
          website: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          owner: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['name'],
      },
      request: { method: 'POST', path: '/companies', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'companies.update',
      class: 'mutation',
      description: 'Update a company.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          name: { type: 'string' },
          industry: { type: 'string' },
          website: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          owner: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/companies/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'companies.delete',
      class: 'mutation',
      description: 'Delete a company.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/companies/{id}' },
      externalEffect: true,
    },
    {
      name: 'deals.list',
      class: 'read',
      description: 'List deals in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/deals' },
    },
    {
      name: 'deals.get',
      class: 'read',
      description: 'Get a deal by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/deals/{id}' },
    },
    {
      name: 'deals.create',
      class: 'mutation',
      description: 'Create a new deal.',
      parameters: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          value: { type: 'number' },
          company: { type: 'string' },
          owner: { type: 'string' },
          status: { type: 'string' },
        },
        required: ['title', 'value'],
      },
      request: { method: 'POST', path: '/deals', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'deals.update',
      class: 'mutation',
      description: 'Update a deal.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          value: { type: 'number' },
          company: { type: 'string' },
          owner: { type: 'string' },
          status: { type: 'string' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/deals/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'deals.delete',
      class: 'mutation',
      description: 'Delete a deal.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/deals/{id}' },
      externalEffect: true,
    },
    {
      name: 'tasks.list',
      class: 'read',
      description: 'List tasks in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/tasks' },
    },
    {
      name: 'tasks.get',
      class: 'read',
      description: 'Get a task by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/tasks/{id}' },
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a new task.',
      parameters: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          description: { type: 'string' },
          assigneeId: { type: 'string' },
          dueDate: { type: 'string' },
          parentId: { type: 'string' },
          priority: { type: 'string' },
        },
        required: ['title'],
      },
      request: { method: 'POST', path: '/tasks', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'tasks.update',
      class: 'mutation',
      description: 'Update a task.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          assigneeId: { type: 'string' },
          dueDate: { type: 'string' },
          parentId: { type: 'string' },
          priority: { type: 'string' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/tasks/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'tasks.delete',
      class: 'mutation',
      description: 'Delete a task.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/tasks/{id}' },
      externalEffect: true,
    },
    {
      name: 'projects.list',
      class: 'read',
      description: 'List projects in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/projects' },
    },
    {
      name: 'projects.get',
      class: 'read',
      description: 'Get a project by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/projects/{id}' },
    },
    {
      name: 'projects.create',
      class: 'mutation',
      description: 'Create a new project.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          owner: { type: 'string' },
        },
        required: ['name'],
      },
      request: { method: 'POST', path: '/projects', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'projects.update',
      class: 'mutation',
      description: 'Update a project.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          owner: { type: 'string' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/projects/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'projects.delete',
      class: 'mutation',
      description: 'Delete a project.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/projects/{id}' },
      externalEffect: true,
    },
    {
      name: 'products.list',
      class: 'read',
      description: 'List products in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/products' },
    },
    {
      name: 'products.get',
      class: 'read',
      description: 'Get a product by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/products/{id}' },
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a new product.',
      parameters: {
        type: 'object',
        properties: {
          sku: { type: 'string' },
          name: { type: 'string' },
          price: { type: 'number' },
          description: { type: 'string' },
        },
        required: ['sku', 'name', 'price'],
      },
      request: { method: 'POST', path: '/products', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'products.update',
      class: 'mutation',
      description: 'Update a product.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          sku: { type: 'string' },
          name: { type: 'string' },
          price: { type: 'number' },
          description: { type: 'string' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/products/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'products.delete',
      class: 'mutation',
      description: 'Delete a product.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/products/{id}' },
      externalEffect: true,
    },
    {
      name: 'orders.list',
      class: 'read',
      description: 'List orders in NinjaPipe.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/orders' },
    },
    {
      name: 'orders.get',
      class: 'read',
      description: 'Get an order by ID.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'GET', path: '/orders/{id}' },
    },
    {
      name: 'orders.create',
      class: 'mutation',
      description: 'Create a new order.',
      parameters: {
        type: 'object',
        properties: {
          customerName: { type: 'string' },
          customerEmail: { type: 'string' },
          totalAmount: { type: 'number' },
        },
        required: ['customerName'],
      },
      request: { method: 'POST', path: '/orders', body: 'args' },
      cas: 'native-idempotency',
    },
    {
      name: 'orders.update',
      class: 'mutation',
      description: 'Update an order.',
      parameters: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          customerName: { type: 'string' },
          customerEmail: { type: 'string' },
          totalAmount: { type: 'number' },
        },
        required: ['id'],
      },
      request: { method: 'PATCH', path: '/orders/{id}', body: 'args' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'orders.delete',
      class: 'mutation',
      description: 'Delete an order.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/orders/{id}' },
      externalEffect: true,
    },
  ],
})
