import { declarativeRestConnector } from './declarative-rest.js'

export const omniCoConnector = declarativeRestConnector({
  kind: 'omni-co',
  displayName: 'Omni',
  description: 'Query Omni dashboards and documents, create schedules, and generate queries with natural language.',
  auth: { kind: 'api-key', hint: 'Omni API key.' },
  category: 'database',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.omniapp.co/api',
  test: { method: 'GET', path: '/v1/documents' },
  capabilities: [
    {
      name: 'documents.create',
      class: 'mutation',
      description: 'Create a document in Omni.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'The name of the document' },
          folderPath: { type: 'string', description: 'The destination folder path' },
          scope: { type: 'string', description: 'Optional sharing scope for the document' },
        },
        required: ['name', 'folderPath'],
      },
      request: { method: 'POST', path: '/v1/documents', body: { name: '{name}', folderPath: '{folderPath}', scope: '{scope}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'documents.delete',
      class: 'mutation',
      description: 'Delete a document from Omni.',
      parameters: {
        type: 'object',
        properties: { documentId: { type: 'string', description: 'The ID of the document to delete' } },
        required: ['documentId'],
      },
      request: { method: 'DELETE', path: '/v1/documents/{documentId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'documents.move',
      class: 'mutation',
      description: 'Move a document to a different folder.',
      parameters: {
        type: 'object',
        properties: {
          documentId: { type: 'string', description: 'The ID of the document' },
          folderPath: { type: 'string', description: 'The destination folder path' },
        },
        required: ['documentId', 'folderPath'],
      },
      request: { method: 'PATCH', path: '/v1/documents/{documentId}', body: { folderPath: '{folderPath}' } },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'queries.run',
      class: 'read',
      description: 'Run a query against a dashboard.',
      parameters: {
        type: 'object',
        properties: {
          identifier: { type: 'string', description: 'The dashboard identifier' },
          query: { type: 'object', description: 'The query object to run' },
          limit: { type: 'integer', description: 'Number of rows to return (defaults to 1000)' },
          cache: { type: 'string', description: 'Optional cache policy' },
          formatResults: { type: 'boolean', description: 'Apply formatting to numeric and currency values' },
          resultType: { type: 'string', description: 'Format of query results' },
          planOnly: { type: 'boolean', description: 'Return query execution plan without running' },
          userId: { type: 'string', description: 'Optional UUID to run query as specific user' },
        },
        required: ['identifier', 'query'],
      },
      request: {
        method: 'POST',
        path: '/v1/dashboards/{identifier}/query',
        body: { query: '{query}', limit: '{limit}', cache: '{cache}', formatResults: '{formatResults}', resultType: '{resultType}', planOnly: '{planOnly}', userId: '{userId}' },
      },
    },
    {
      name: 'queries.generate',
      class: 'read',
      description: 'Generate a query from natural language description.',
      parameters: {
        type: 'object',
        properties: {
          identifier: { type: 'string', description: 'The dashboard identifier' },
          prompt: { type: 'string', description: 'Natural language description of the query' },
          currentTopicName: { type: 'string', description: 'Name of the topic for context' },
          branchId: { type: 'string', description: 'Optional model branch ID' },
          contextQuery: { type: 'object', description: 'Optional context query object' },
          structured: { type: 'boolean', description: 'Return strictly structured query format' },
        },
        required: ['identifier', 'prompt'],
      },
      request: {
        method: 'POST',
        path: '/v1/dashboards/{identifier}/generate-query',
        body: { prompt: '{prompt}', currentTopicName: '{currentTopicName}', branchId: '{branchId}', contextQuery: '{contextQuery}', structured: '{structured}' },
      },
    },
    {
      name: 'schedules.create',
      class: 'mutation',
      description: 'Create a schedule for dashboard delivery.',
      parameters: {
        type: 'object',
        properties: {
          identifier: { type: 'string', description: 'The dashboard identifier' },
          schedule: { type: 'string', description: 'Cron expression for the schedule' },
          timezone: { type: 'string', description: 'Timezone for the schedule' },
          format: { type: 'string', description: 'Output format (pdf, csv, etc)' },
          destinationType: { type: 'string', description: 'Destination type (webhook, email, etc)' },
          url: { type: 'string', description: 'Webhook URL for delivery' },
          recipients: { type: 'object', description: 'Email recipients' },
          subject: { type: 'string', description: 'Email subject line' },
          paperFormat: { type: 'string', description: 'Paper format for PDF output' },
          paperOrientation: { type: 'string', description: 'Paper orientation for PDF output' },
        },
        required: ['identifier', 'schedule', 'timezone', 'format', 'destinationType'],
      },
      request: {
        method: 'POST',
        path: '/v1/dashboards/{identifier}/schedules',
        body: {
          schedule: '{schedule}',
          timezone: '{timezone}',
          format: '{format}',
          destinationType: '{destinationType}',
          url: '{url}',
          recipients: '{recipients}',
          subject: '{subject}',
          paperFormat: '{paperFormat}',
          paperOrientation: '{paperOrientation}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'schedules.edit',
      class: 'mutation',
      description: 'Edit an existing schedule.',
      parameters: {
        type: 'object',
        properties: {
          identifier: { type: 'string', description: 'The dashboard identifier' },
          scheduleId: { type: 'string', description: 'The schedule ID to edit' },
          schedule: { type: 'string', description: 'Cron expression' },
          timezone: { type: 'string', description: 'Timezone' },
          format: { type: 'string', description: 'Output format' },
          destinationType: { type: 'string', description: 'Destination type' },
          url: { type: 'string', description: 'Webhook URL' },
          recipients: { type: 'object', description: 'Email recipients' },
          subject: { type: 'string', description: 'Email subject' },
        },
        required: ['identifier', 'scheduleId'],
      },
      request: {
        method: 'PATCH',
        path: '/v1/dashboards/{identifier}/schedules/{scheduleId}',
        body: { schedule: '{schedule}', timezone: '{timezone}', format: '{format}', destinationType: '{destinationType}', url: '{url}', recipients: '{recipients}', subject: '{subject}' },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'schedules.delete',
      class: 'mutation',
      description: 'Delete a schedule.',
      parameters: {
        type: 'object',
        properties: {
          identifier: { type: 'string', description: 'The dashboard identifier' },
          scheduleId: { type: 'string', description: 'The schedule ID to delete' },
        },
        required: ['identifier', 'scheduleId'],
      },
      request: { method: 'DELETE', path: '/v1/dashboards/{identifier}/schedules/{scheduleId}' },
      cas: 'optimistic-read-verify',
    },
  ],
})
