import { declarativeRestConnector } from './declarative-rest.js'

export const openPhoneConnector = declarativeRestConnector({
  kind: 'open-phone',
  displayName: 'OpenPhone',
  description: 'Send messages, manage contacts, and retrieve call summaries via OpenPhone.',
  auth: { kind: 'api-key', hint: 'OpenPhone API key.' },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.openphone.com/v1',
  test: { method: 'GET', path: '/users' },
  capabilities: [
    {
      name: 'messages.send',
      class: 'mutation',
      description: 'Send an SMS message to one or more recipients.',
      parameters: {
        type: 'object',
        properties: {
          content: { type: 'string' },
          from: { type: 'string' },
          to: { type: 'array', items: { type: 'string' } },
          userId: { type: 'string' },
        },
        required: ['content', 'from', 'to'],
      },
      request: { method: 'POST', path: '/messages', body: { content: '{content}', from: '{from}', to: '{to}', userId: '{userId}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.create',
      class: 'mutation',
      description: 'Create a new contact in OpenPhone.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          company: { type: 'string' },
          role: { type: 'string' },
          emails: { type: 'array', items: { type: 'object' } },
          phoneNumbers: { type: 'array', items: { type: 'object' } },
          customFields: { type: 'object' },
          source: { type: 'string' },
          sourceUrl: { type: 'string' },
          externalId: { type: 'string' },
        },
        required: ['firstName'],
      },
      request: {
        method: 'POST',
        path: '/contacts',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          company: '{company}',
          role: '{role}',
          emails: '{emails}',
          phoneNumbers: '{phoneNumbers}',
          customFields: '{customFields}',
          source: '{source}',
          sourceUrl: '{sourceUrl}',
          externalId: '{externalId}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description: 'Update an existing contact in OpenPhone.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          company: { type: 'string' },
          role: { type: 'string' },
          emails: { type: 'array', items: { type: 'object' } },
          phoneNumbers: { type: 'array', items: { type: 'object' } },
          customFields: { type: 'object' },
          source: { type: 'string' },
          sourceUrl: { type: 'string' },
          externalId: { type: 'string' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'PUT',
        path: '/contacts/{contactId}',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          company: '{company}',
          role: '{role}',
          emails: '{emails}',
          phoneNumbers: '{phoneNumbers}',
          customFields: '{customFields}',
          source: '{source}',
          sourceUrl: '{sourceUrl}',
          externalId: '{externalId}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'calls.summary',
      class: 'read',
      description: 'Retrieve a summary of a call.',
      parameters: {
        type: 'object',
        properties: {
          callId: { type: 'string' },
        },
        required: ['callId'],
      },
      request: { method: 'GET', path: '/calls/{callId}/summary' },
    },
  ],
})
