import { declarativeRestConnector } from './declarative-rest.js'

export const paywhirlConnector = declarativeRestConnector({
  kind: 'paywhirl',
  displayName: 'Paywhirl',
  description: 'Paywhirl integration for managing customers, subscriptions, and recurring billing.',
  auth: {
    kind: 'api-key',
    hint: 'Paywhirl API key. Set source.metadata.apiSecret to the matching API secret.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.paywhirl.com/api',
  credentialPlacement: { kind: 'query', parameter: 'api_key' },
  defaultHeaders: {
    'Content-Type': 'application/json',
  },
  test: { method: 'GET', path: '/v1/customers?api_key={credential}&api_secret={metadata.apiSecret}' },
  capabilities: [
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a new customer in Paywhirl.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          currency: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          zip: { type: 'string' },
          country: { type: 'string' },
          password: { type: 'string' },
          gatewayId: { type: 'string' },
          utmSource: { type: 'string' },
          utmMedium: { type: 'string' },
          utmTerm: { type: 'string' },
          utmContent: { type: 'string' },
          utmCampaign: { type: 'string' },
          utmGroup: { type: 'string' },
        },
        required: ['firstName', 'lastName', 'email', 'currency'],
      },
      request: {
        method: 'POST',
        path: '/v1/customers',
        query: { api_secret: '{metadata.apiSecret}' },
        body: {
          first_name: '{firstName}',
          last_name: '{lastName}',
          email: '{email}',
          currency: '{currency}',
          phone: '{phone}',
          address: '{address}',
          city: '{city}',
          state: '{state}',
          zip: '{zip}',
          country: '{country}',
          password: '{password}',
          gateway_id: '{gatewayId}',
          utm_source: '{utmSource}',
          utm_medium: '{utmMedium}',
          utm_term: '{utmTerm}',
          utm_content: '{utmContent}',
          utm_campaign: '{utmCampaign}',
          utm_group: '{utmGroup}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'customers.get',
      class: 'read',
      description: 'Retrieve a customer by ID.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' } },
        required: ['customerId'],
      },
      request: {
        method: 'GET',
        path: '/v1/customers/{customerId}',
        query: { api_secret: '{metadata.apiSecret}' },
      },
    },
    {
      name: 'customers.search',
      class: 'read',
      description: 'Search for customers with pagination and filtering.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer' },
          orderKey: { type: 'string' },
          orderDirection: { type: 'string' },
          beforeId: { type: 'integer' },
          afterId: { type: 'integer' },
          keyword: { type: 'string' },
          status: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/v1/customers',
        query: {
          api_secret: '{metadata.apiSecret}',
          limit: '{limit}',
          order_key: '{orderKey}',
          order_direction: '{orderDirection}',
          before_id: '{beforeId}',
          after_id: '{afterId}',
          keyword: '{keyword}',
          status: '{status}',
        },
      },
    },
    {
      name: 'subscriptions.create',
      class: 'mutation',
      description: 'Subscribe a customer to a plan.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          planId: { type: 'integer' },
          trialEnd: { type: 'integer' },
          promoId: { type: 'integer' },
          quantity: { type: 'integer' },
        },
        required: ['customerId', 'planId'],
      },
      request: {
        method: 'POST',
        path: '/v1/customers/{customerId}/subscribe',
        query: { api_secret: '{metadata.apiSecret}' },
        body: {
          plan_id: '{planId}',
          trial_end: '{trialEnd}',
          promo_id: '{promoId}',
          quantity: '{quantity}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.cancel',
      class: 'mutation',
      description: 'Cancel a customer subscription.',
      parameters: {
        type: 'object',
        properties: { subscriptionId: { type: 'integer' } },
        required: ['subscriptionId'],
      },
      request: {
        method: 'POST',
        path: '/v1/subscriptions/{subscriptionId}/cancel',
        query: { api_secret: '{metadata.apiSecret}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.search',
      class: 'read',
      description: 'Search customer subscriptions.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer' },
          orderKey: { type: 'string' },
          orderDirection: { type: 'string' },
          beforeId: { type: 'integer' },
          afterId: { type: 'integer' },
          keyword: { type: 'string' },
          status: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/v1/subscriptions',
        query: {
          api_secret: '{metadata.apiSecret}',
          limit: '{limit}',
          order_key: '{orderKey}',
          order_direction: '{orderDirection}',
          before_id: '{beforeId}',
          after_id: '{afterId}',
          keyword: '{keyword}',
          status: '{status}',
        },
      },
    },
  ],
})
