import { declarativeRestConnector } from './declarative-rest.js'

export const pinchPaymentsConnector = declarativeRestConnector({
  kind: 'pinch-payments',
  displayName: 'Pinch Payments',
  description: 'Australian payment processing platform for direct debits, credit cards, and recurring payments. Create payers, process payments, manage subscriptions, and handle payment sources.',
  auth: {
    kind: 'api-key',
    hint: 'Pinch Payments API credentials (Application ID and Secret Key).',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.pinchpayments.com/v1',
  test: { method: 'GET', path: '/payers' },
  capabilities: [
    {
      name: 'payers.create-or-update',
      class: 'mutation',
      description: 'Create or update a payer with contact information and metadata.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          emailAddress: { type: 'string' },
          mobileNumber: { type: 'string' },
          companyName: { type: 'string' },
          streetAddress: { type: 'string' },
          suburb: { type: 'string' },
          state: { type: 'string' },
          postcode: { type: 'string' },
          country: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['firstName', 'emailAddress'],
      },
      request: {
        method: 'POST',
        path: '/payers',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          emailAddress: '{emailAddress}',
          mobileNumber: '{mobileNumber}',
          companyName: '{companyName}',
          streetAddress: '{streetAddress}',
          suburb: '{suburb}',
          state: '{state}',
          postcode: '{postcode}',
          country: '{country}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payers.find',
      class: 'read',
      description: 'Find a payer by ID or email.',
      parameters: {
        type: 'object',
        properties: {
          payerId: { type: 'string' },
        },
        required: ['payerId'],
      },
      request: {
        method: 'GET',
        path: '/payers/{payerId}',
      },
    },
    {
      name: 'sources.add-to-payer',
      class: 'mutation',
      description: 'Add a payment source (bank account or credit card) to a payer.',
      parameters: {
        type: 'object',
        properties: {
          payerId: { type: 'string' },
          sourceType: { type: 'string' },
          token: { type: 'string' },
          bankAccountNumber: { type: 'string' },
          bankAccountBsb: { type: 'string' },
          bankAccountName: { type: 'string' },
        },
        required: ['payerId', 'sourceType'],
      },
      request: {
        method: 'POST',
        path: '/payers/{payerId}/sources',
        body: {
          sourceType: '{sourceType}',
          token: '{token}',
          bankAccountNumber: '{bankAccountNumber}',
          bankAccountBsb: '{bankAccountBsb}',
          bankAccountName: '{bankAccountName}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payments.create-realtime',
      class: 'mutation',
      description: 'Create and process a real-time payment (immediate debit).',
      parameters: {
        type: 'object',
        properties: {
          payerId: { type: 'string' },
          amount: { type: 'number' },
          description: { type: 'string' },
          sourceId: { type: 'string' },
          nonce: { type: 'string' },
        },
        required: ['payerId', 'amount'],
      },
      request: {
        method: 'POST',
        path: '/payments',
        body: {
          payerId: '{payerId}',
          amount: '{amount}',
          description: '{description}',
          sourceId: '{sourceId}',
          nonce: '{nonce}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payments.create-or-update-scheduled',
      class: 'mutation',
      description: 'Create or update a scheduled payment for a future transaction date.',
      parameters: {
        type: 'object',
        properties: {
          paymentId: { type: 'string' },
          payerId: { type: 'string' },
          amount: { type: 'number' },
          transactionDate: { type: 'string' },
          description: { type: 'string' },
          sourceId: { type: 'string' },
          applicationFee: { type: 'number' },
        },
        required: ['payerId', 'amount', 'transactionDate'],
      },
      request: {
        method: 'POST',
        path: '/scheduled-payments',
        body: {
          paymentId: '{paymentId}',
          payerId: '{payerId}',
          amount: '{amount}',
          transactionDate: '{transactionDate}',
          description: '{description}',
          sourceId: '{sourceId}',
          applicationFee: '{applicationFee}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'subscriptions.create-or-update',
      class: 'mutation',
      description: 'Create or update a subscription for recurring payments.',
      parameters: {
        type: 'object',
        properties: {
          payerId: { type: 'string' },
          planId: { type: 'string' },
          sourceId: { type: 'string' },
          startDate: { type: 'string' },
          totalAmount: { type: 'number' },
          surcharge: { type: 'string' },
        },
        required: ['payerId', 'planId'],
      },
      request: {
        method: 'POST',
        path: '/subscriptions',
        body: {
          payerId: '{payerId}',
          planId: '{planId}',
          sourceId: '{sourceId}',
          startDate: '{startDate}',
          totalAmount: '{totalAmount}',
          surcharge: '{surcharge}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.find',
      class: 'read',
      description: 'Find a subscription by ID.',
      parameters: {
        type: 'object',
        properties: {
          subscriptionId: { type: 'string' },
        },
        required: ['subscriptionId'],
      },
      request: {
        method: 'GET',
        path: '/subscriptions/{subscriptionId}',
      },
    },
    {
      name: 'events.find',
      class: 'read',
      description: 'Find an event by ID.',
      parameters: {
        type: 'object',
        properties: {
          eventId: { type: 'string' },
        },
        required: ['eventId'],
      },
      request: {
        method: 'GET',
        path: '/events/{eventId}',
      },
    },
  ],
})
