import { declarativeRestConnector } from './declarative-rest.js'

export const qawafelConnector = declarativeRestConnector({
  kind: 'qawafel',
  displayName: 'Qawafel',
  description: 'B2B marketplace and ZATCA-compliant document platform — sync products, orders, merchants and invoices with Saudi Arabia.',
  auth: { kind: 'api-key', hint: 'Qawafel API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.qawafel.sa/v1',
  test: { method: 'GET', path: '/me' },
  capabilities: [
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a product in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          sku: { type: 'string' },
          unit_price: { type: 'string' },
          description_en: { type: 'string' },
          description_ar: { type: 'string' },
          barcode: { type: 'string' },
          is_active: { type: 'boolean' },
        },
        required: ['sku', 'unit_price'],
      },
      request: { method: 'POST', path: '/products', body: '{}' },
      cas: 'native-idempotency',
    },
    {
      name: 'products.update',
      class: 'mutation',
      description: 'Update a product in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          product_id: { type: 'string' },
          sku: { type: 'string' },
          unit_price: { type: 'string' },
          description_en: { type: 'string' },
          description_ar: { type: 'string' },
          barcode: { type: 'string' },
          is_active: { type: 'boolean' },
        },
        required: ['product_id'],
      },
      request: { method: 'PATCH', path: '/products/{product_id}', body: '{}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'products.get',
      class: 'read',
      description: 'Get a single product from Qawafel.',
      parameters: {
        type: 'object',
        properties: { product_id: { type: 'string' } },
        required: ['product_id'],
      },
      request: { method: 'GET', path: '/products/{product_id}' },
    },
    {
      name: 'products.list',
      class: 'read',
      description: 'List products in Qawafel.',
      parameters: {
        type: 'object',
        properties: { supplier_id: { type: 'string' }, limit: { type: 'integer' } },
      },
      request: { method: 'GET', path: '/products', query: { supplier_id: '{supplier_id}', limit: '{limit}' } },
    },
    {
      name: 'orders.create',
      class: 'mutation',
      description: 'Create an order in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          items: { type: 'array' },
          shipping_fees: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['items'],
      },
      request: { method: 'POST', path: '/orders', body: '{}' },
      cas: 'native-idempotency',
    },
    {
      name: 'orders.updateStatus',
      class: 'mutation',
      description: 'Update order status in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          order_id: { type: 'string' },
          transition: { type: 'string' },
        },
        required: ['order_id', 'transition'],
      },
      request: { method: 'PATCH', path: '/orders/{order_id}/status', body: { transition: '{transition}' } },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'orders.cancel',
      class: 'mutation',
      description: 'Cancel an order in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          order_id: { type: 'string' },
          reason: { type: 'string' },
        },
        required: ['order_id'],
      },
      request: { method: 'POST', path: '/orders/{order_id}/cancel', body: { reason: '{reason}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'orders.get',
      class: 'read',
      description: 'Get a single order from Qawafel.',
      parameters: {
        type: 'object',
        properties: { order_id: { type: 'string' } },
        required: ['order_id'],
      },
      request: { method: 'GET', path: '/orders/{order_id}' },
    },
    {
      name: 'orders.list',
      class: 'read',
      description: 'List orders in Qawafel.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' } },
      },
      request: { method: 'GET', path: '/orders', query: { limit: '{limit}' } },
    },
    {
      name: 'merchants.create',
      class: 'mutation',
      description: 'Create a merchant in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          legal_name: { type: 'string' },
          name_en: { type: 'string' },
          name_ar: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          cr_number: { type: 'string' },
          vat_number: { type: 'string' },
          unified_national_number: { type: 'string' },
          is_taxable: { type: 'boolean' },
          address_line: { type: 'string' },
          city: { type: 'string' },
          postal_code: { type: 'string' },
          country: { type: 'string' },
          district: { type: 'string' },
          region: { type: 'string' },
          short_address: { type: 'string' },
        },
        required: ['legal_name', 'name_en', 'name_ar', 'email', 'phone', 'cr_number', 'address_line', 'city', 'postal_code', 'country'],
      },
      request: { method: 'POST', path: '/merchants', body: '{}' },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create an invoice in Qawafel.',
      parameters: {
        type: 'object',
        properties: {
          issue_date: { type: 'string' },
          due_date: { type: 'string' },
          shipping_fees: { type: 'string' },
          payment_start_date: { type: 'string' },
          payment_due_date: { type: 'string' },
          notes: { type: 'string' },
          items: { type: 'array' },
        },
        required: ['issue_date', 'due_date', 'items'],
      },
      request: { method: 'POST', path: '/invoices', body: '{}' },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.get',
      class: 'read',
      description: 'Get a single invoice from Qawafel.',
      parameters: {
        type: 'object',
        properties: { invoice_id: { type: 'string' } },
        required: ['invoice_id'],
      },
      request: { method: 'GET', path: '/invoices/{invoice_id}' },
    },
    {
      name: 'invoices.list',
      class: 'read',
      description: 'List invoices in Qawafel.',
      parameters: {
        type: 'object',
        properties: { created_after: { type: 'string' }, limit: { type: 'integer' } },
      },
      request: { method: 'GET', path: '/invoices', query: { created_after: '{created_after}', limit: '{limit}' } },
    },
  ],
})
