import { declarativeRestConnector } from './declarative-rest.js'

export const quadernoConnector = declarativeRestConnector({
  kind: 'quaderno',
  displayName: 'Quaderno',
  description: 'Manage contacts, invoices, and expenses in Quaderno for tax compliance and financial tracking.',
  auth: { kind: 'api-key', hint: 'Quaderno API Key (account_name and api_key credentials).' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://{account_name}.quadernoapp.com/api/v1',
  test: { method: 'GET', path: '/contacts' },
  capabilities: [
    {
      name: 'contacts.find',
      class: 'read',
      description: 'Search for contacts by name, email, or tax ID.',
      parameters: {
        type: 'object',
        properties: {
          searchQuery: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/contacts',
        query: {
          q: '{searchQuery}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'contacts.create',
      class: 'mutation',
      description: 'Create a new contact (customer or vendor).',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          fullName: { type: 'string' },
          kind: { type: 'string' },
          country: { type: 'string' },
          city: { type: 'string' },
          postalCode: { type: 'string' },
          region: { type: 'string' },
          streetLine1: { type: 'string' },
          streetLine2: { type: 'string' },
          taxId: { type: 'string' },
          taxStatus: { type: 'string' },
          language: { type: 'string' },
          phone: { type: 'string' },
          website: { type: 'string' },
          discount: { type: 'number' },
          notes: { type: 'string' },
          processorId: { type: 'string' },
          processor: { type: 'string' },
        },
        required: ['firstName', 'country'],
      },
      request: {
        method: 'POST',
        path: '/contacts',
        body: {
          first_name: '{firstName}',
          last_name: '{lastName}',
          email: '{email}',
          full_name: '{fullName}',
          kind: '{kind}',
          country: '{country}',
          city: '{city}',
          postal_code: '{postalCode}',
          region: '{region}',
          street_line_1: '{streetLine1}',
          street_line_2: '{streetLine2}',
          tax_id: '{taxId}',
          tax_status: '{taxStatus}',
          language: '{language}',
          phone: '{phone}',
          website: '{website}',
          discount: '{discount}',
          notes: '{notes}',
          processor_id: '{processorId}',
          processor: '{processor}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create a new invoice.',
      parameters: {
        type: 'object',
        properties: {
          invoiceNumber: { type: 'string' },
          dueDate: { type: 'string' },
          customerFirstName: { type: 'string' },
          customerLastName: { type: 'string' },
          customerEmail: { type: 'string' },
          customerCountry: { type: 'string' },
          issueDate: { type: 'string' },
          currency: { type: 'string' },
          itemDescription: { type: 'string' },
          itemQuantity: { type: 'number' },
          itemUnitCost: { type: 'string' },
        },
        required: ['customerFirstName', 'issueDate', 'currency', 'itemDescription', 'itemQuantity', 'itemUnitCost'],
      },
      request: {
        method: 'POST',
        path: '/invoices',
        body: {
          number: '{invoiceNumber}',
          due_date: '{dueDate}',
          contact: {
            first_name: '{customerFirstName}',
            last_name: '{customerLastName}',
            email: '{customerEmail}',
            country: '{customerCountry}',
          },
          issued_at: '{issueDate}',
          currency: '{currency}',
          line_items: [
            {
              description: '{itemDescription}',
              quantity: '{itemQuantity}',
              unit_cost: '{itemUnitCost}',
            },
          ],
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description: "Update a contact's tax or billing fields.",
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          fullName: { type: 'string' },
          kind: { type: 'string' },
          country: { type: 'string' },
          city: { type: 'string' },
          postalCode: { type: 'string' },
          region: { type: 'string' },
          streetLine1: { type: 'string' },
          streetLine2: { type: 'string' },
          taxId: { type: 'string' },
          taxStatus: { type: 'string' },
          language: { type: 'string' },
          phone: { type: 'string' },
          website: { type: 'string' },
          discount: { type: 'number' },
          notes: { type: 'string' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'PUT',
        path: '/contacts/{contactId}',
        body: {
          first_name: '{firstName}',
          last_name: '{lastName}',
          email: '{email}',
          full_name: '{fullName}',
          kind: '{kind}',
          country: '{country}',
          city: '{city}',
          postal_code: '{postalCode}',
          region: '{region}',
          street_line_1: '{streetLine1}',
          street_line_2: '{streetLine2}',
          tax_id: '{taxId}',
          tax_status: '{taxStatus}',
          language: '{language}',
          phone: '{phone}',
          website: '{website}',
          discount: '{discount}',
          notes: '{notes}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'contacts.delete',
      class: 'mutation',
      description: 'Delete a contact.',
      parameters: {
        type: 'object',
        properties: { contactId: { type: 'string' } },
        required: ['contactId'],
      },
      request: { method: 'DELETE', path: '/contacts/{contactId}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'invoices.update',
      class: 'mutation',
      description: 'Update an invoice.',
      parameters: {
        type: 'object',
        properties: {
          invoiceId: { type: 'string' },
          invoiceNumber: { type: 'string' },
          dueDate: { type: 'string' },
          issueDate: { type: 'string' },
          currency: { type: 'string' },
          poNumber: { type: 'string' },
          notes: { type: 'string' },
          tagList: { type: 'string' },
        },
        required: ['invoiceId'],
      },
      request: {
        method: 'PUT',
        path: '/invoices/{invoiceId}',
        body: {
          number: '{invoiceNumber}',
          due_date: '{dueDate}',
          issued_at: '{issueDate}',
          currency: '{currency}',
          po_number: '{poNumber}',
          notes: '{notes}',
          tag_list: '{tagList}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'invoices.deliver',
      class: 'mutation',
      description: 'Email an invoice to the customer.',
      parameters: {
        type: 'object',
        properties: {
          invoiceId: { type: 'string' },
          emails: { type: 'string' },
        },
        required: ['invoiceId'],
      },
      request: {
        method: 'GET',
        path: '/invoices/{invoiceId}/deliver',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'credits.create',
      class: 'mutation',
      description: 'Create a credit note.',
      parameters: {
        type: 'object',
        properties: {
          customerFirstName: { type: 'string' },
          customerLastName: { type: 'string' },
          customerEmail: { type: 'string' },
          customerCountry: { type: 'string' },
          issueDate: { type: 'string' },
          currency: { type: 'string' },
          creditNumber: { type: 'string' },
          poNumber: { type: 'string' },
          notes: { type: 'string' },
          itemDescription: { type: 'string' },
          itemQuantity: { type: 'number' },
          itemUnitCost: { type: 'string' },
        },
        required: ['customerFirstName', 'issueDate', 'currency', 'itemDescription', 'itemQuantity', 'itemUnitCost'],
      },
      request: {
        method: 'POST',
        path: '/credits',
        body: {
          number: '{creditNumber}',
          issued_at: '{issueDate}',
          currency: '{currency}',
          po_number: '{poNumber}',
          notes: '{notes}',
          contact: {
            first_name: '{customerFirstName}',
            last_name: '{customerLastName}',
            email: '{customerEmail}',
            country: '{customerCountry}',
          },
          line_items: [
            {
              description: '{itemDescription}',
              quantity: '{itemQuantity}',
              unit_cost: '{itemUnitCost}',
            },
          ],
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'expenses.create',
      class: 'mutation',
      description: 'Create a new expense.',
      parameters: {
        type: 'object',
        properties: {
          issueDate: { type: 'string' },
          currency: { type: 'string' },
          contactFirstName: { type: 'string' },
          contactLastName: { type: 'string' },
          contactEmail: { type: 'string' },
          contactCountry: { type: 'string' },
          itemDescription: { type: 'string' },
          itemQuantity: { type: 'number' },
          itemUnitCost: { type: 'string' },
          paymentMethod: { type: 'string' },
          poNumber: { type: 'string' },
          tagList: { type: 'string' },
        },
        required: ['issueDate', 'currency', 'contactFirstName', 'contactCountry', 'itemDescription', 'itemQuantity', 'itemUnitCost', 'paymentMethod'],
      },
      request: {
        method: 'POST',
        path: '/expenses',
        body: {
          issued_at: '{issueDate}',
          currency: '{currency}',
          contact: {
            first_name: '{contactFirstName}',
            last_name: '{contactLastName}',
            email: '{contactEmail}',
            country: '{contactCountry}',
          },
          line_items: [
            {
              description: '{itemDescription}',
              quantity: '{itemQuantity}',
              unit_cost: '{itemUnitCost}',
            },
          ],
          payment_method: '{paymentMethod}',
          po_number: '{poNumber}',
          tag_list: '{tagList}',
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
