import { declarativeRestConnector } from './declarative-rest.js'

// QuickBooks Online API. The per-tenant API base
// `https://quickbooks.api.intuit.com/v3/company/{realmId}` is resolved from
// `metadata.apiBaseUrl`, which the consumer composes from the realmId returned
// alongside the OAuth code (Intuit ships realmId as a query param on the
// redirect, not inside the token response).
export const quickbooksConnector = declarativeRestConnector({
  kind: 'quickbooks',
  displayName: 'QuickBooks',
  description: 'Query QuickBooks Online entities with SQL-like queries and create or update customers, invoices, and items.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://appcenter.intuit.com/connect/oauth2',
    tokenUrl: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
    scopes: ['com.intuit.quickbooks.accounting'],
    clientIdEnv: 'QUICKBOOKS_OAUTH_CLIENT_ID',
    clientSecretEnv: 'QUICKBOOKS_OAUTH_CLIENT_SECRET',
  },
  category: 'commerce',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'apiBaseUrl' },
  defaultHeaders: {
    accept: 'application/json',
  },
  test: { method: 'GET', path: 'companyinfo/{realmId}', query: { minorversion: '70' } },
  capabilities: [
    {
      name: 'entities.query',
      class: 'read',
      description: 'Run a QuickBooks Online query (e.g. "SELECT * FROM Customer WHERE Active = true MAXRESULTS 50").',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          minorversion: { type: 'string' },
        },
        required: ['query'],
      },
      request: {
        method: 'GET',
        path: 'query',
        query: { query: '{query}', minorversion: '{minorversion}' },
      },
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'customers.get',
      class: 'read',
      description: 'Read a QuickBooks customer by id.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          minorversion: { type: 'string' },
        },
        required: ['customerId'],
      },
      request: {
        method: 'GET',
        path: 'customer/{customerId}',
        query: { minorversion: '{minorversion}' },
      },
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a QuickBooks customer.',
      parameters: {
        type: 'object',
        properties: {
          DisplayName: { type: 'string' },
          GivenName: { type: 'string' },
          FamilyName: { type: 'string' },
          CompanyName: { type: 'string' },
          PrimaryEmailAddr: { type: 'object' },
          PrimaryPhone: { type: 'object' },
          BillAddr: { type: 'object' },
          Notes: { type: 'string' },
        },
        required: ['DisplayName'],
      },
      request: {
        method: 'POST',
        path: 'customer',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'customers.update',
      class: 'mutation',
      description: 'Sparse-update a QuickBooks customer. Caller must include Id and SyncToken from the prior read.',
      parameters: {
        type: 'object',
        properties: {
          Id: { type: 'string' },
          SyncToken: { type: 'string' },
          sparse: { type: 'boolean', default: true },
          DisplayName: { type: 'string' },
          GivenName: { type: 'string' },
          FamilyName: { type: 'string' },
          CompanyName: { type: 'string' },
          PrimaryEmailAddr: { type: 'object' },
          PrimaryPhone: { type: 'object' },
          BillAddr: { type: 'object' },
          Notes: { type: 'string' },
          Active: { type: 'boolean' },
        },
        required: ['Id', 'SyncToken'],
      },
      request: {
        method: 'POST',
        path: 'customer',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'invoices.get',
      class: 'read',
      description: 'Read a QuickBooks invoice by id.',
      parameters: {
        type: 'object',
        properties: {
          invoiceId: { type: 'string' },
          minorversion: { type: 'string' },
        },
        required: ['invoiceId'],
      },
      request: {
        method: 'GET',
        path: 'invoice/{invoiceId}',
        query: { minorversion: '{minorversion}' },
      },
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create a QuickBooks invoice. `Line` and `CustomerRef` are required by the API.',
      parameters: {
        type: 'object',
        properties: {
          CustomerRef: { type: 'object' },
          Line: { type: 'array', items: { type: 'object' } },
          TxnDate: { type: 'string' },
          DueDate: { type: 'string' },
          CurrencyRef: { type: 'object' },
          BillEmail: { type: 'object' },
          PrivateNote: { type: 'string' },
          CustomerMemo: { type: 'object' },
        },
        required: ['CustomerRef', 'Line'],
      },
      request: {
        method: 'POST',
        path: 'invoice',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'invoices.update',
      class: 'mutation',
      description: 'Sparse-update a QuickBooks invoice. Caller must include Id and SyncToken from the prior read.',
      parameters: {
        type: 'object',
        properties: {
          Id: { type: 'string' },
          SyncToken: { type: 'string' },
          sparse: { type: 'boolean', default: true },
          CustomerRef: { type: 'object' },
          Line: { type: 'array', items: { type: 'object' } },
          DueDate: { type: 'string' },
          CustomerMemo: { type: 'object' },
          PrivateNote: { type: 'string' },
        },
        required: ['Id', 'SyncToken'],
      },
      request: {
        method: 'POST',
        path: 'invoice',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'items.create',
      class: 'mutation',
      description: 'Create a QuickBooks item (product or service).',
      parameters: {
        type: 'object',
        properties: {
          Name: { type: 'string' },
          Type: { type: 'string', enum: ['Service', 'Inventory', 'NonInventory'] },
          IncomeAccountRef: { type: 'object' },
          ExpenseAccountRef: { type: 'object' },
          UnitPrice: { type: 'number' },
          Description: { type: 'string' },
          Taxable: { type: 'boolean' },
        },
        required: ['Name', 'Type', 'IncomeAccountRef'],
      },
      request: {
        method: 'POST',
        path: 'item',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'customers.delete',
      class: 'mutation',
      description: 'Mark a QuickBooks customer inactive. QBO does not support hard deletes — caller must supply Id and SyncToken from the prior read.',
      parameters: {
        type: 'object',
        properties: {
          Id: { type: 'string' },
          SyncToken: { type: 'string' },
          sparse: { type: 'boolean', default: true },
          Active: { type: 'boolean', default: false },
        },
        required: ['Id', 'SyncToken'],
      },
      request: {
        method: 'POST',
        path: 'customer',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'invoices.delete',
      class: 'mutation',
      description: 'Void a QuickBooks invoice (QBO does not hard-delete invoices). Caller must supply Id and SyncToken.',
      parameters: {
        type: 'object',
        properties: {
          Id: { type: 'string' },
          SyncToken: { type: 'string' },
        },
        required: ['Id', 'SyncToken'],
      },
      request: {
        method: 'POST',
        path: 'invoice',
        query: { operation: 'void', minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'invoices.send',
      class: 'mutation',
      description: 'Email a QuickBooks invoice to the customer (optionally override the recipient with `sendTo`).',
      parameters: {
        type: 'object',
        properties: {
          invoiceId: { type: 'string' },
          sendTo: { type: 'string' },
        },
        required: ['invoiceId'],
      },
      request: {
        method: 'POST',
        path: 'invoice/{invoiceId}/send',
        query: { sendTo: '{sendTo}', minorversion: '70' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'bills.create',
      class: 'mutation',
      description: 'Create a QuickBooks vendor bill. `VendorRef` and `Line` are required by the API.',
      parameters: {
        type: 'object',
        properties: {
          VendorRef: { type: 'object' },
          Line: { type: 'array', items: { type: 'object' } },
          TxnDate: { type: 'string' },
          DueDate: { type: 'string' },
          CurrencyRef: { type: 'object' },
          PrivateNote: { type: 'string' },
          APAccountRef: { type: 'object' },
        },
        required: ['VendorRef', 'Line'],
      },
      request: {
        method: 'POST',
        path: 'bill',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'vendors.create',
      class: 'mutation',
      description: 'Create a QuickBooks vendor.',
      parameters: {
        type: 'object',
        properties: {
          DisplayName: { type: 'string' },
          GivenName: { type: 'string' },
          FamilyName: { type: 'string' },
          CompanyName: { type: 'string' },
          PrimaryEmailAddr: { type: 'object' },
          PrimaryPhone: { type: 'object' },
          BillAddr: { type: 'object' },
          TaxIdentifier: { type: 'string' },
          AcctNum: { type: 'string' },
        },
        required: ['DisplayName'],
      },
      request: {
        method: 'POST',
        path: 'vendor',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
    {
      name: 'payments.create',
      class: 'mutation',
      description: 'Record a QuickBooks payment against a customer (and optionally apply to invoices via `Line[].LinkedTxn`).',
      parameters: {
        type: 'object',
        properties: {
          CustomerRef: { type: 'object' },
          TotalAmt: { type: 'number' },
          TxnDate: { type: 'string' },
          PaymentMethodRef: { type: 'object' },
          DepositToAccountRef: { type: 'object' },
          Line: { type: 'array', items: { type: 'object' } },
          PrivateNote: { type: 'string' },
        },
        required: ['CustomerRef', 'TotalAmt'],
      },
      request: {
        method: 'POST',
        path: 'payment',
        query: { minorversion: '70' },
        body: 'args',
      },
      cas: 'native-idempotency',
      requiredScopes: ['com.intuit.quickbooks.accounting'],
    },
  ],
})
