import { declarativeRestConnector } from './declarative-rest.js'

export const reachinboxConnector = declarativeRestConnector({
  kind: 'reachinbox',
  displayName: 'ReachInbox',
  description: 'Manage campaigns, leads, email accounts, and warmup schedules in ReachInbox.',
  auth: { kind: 'api-key', hint: 'ReachInbox API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.reachinbox.xyz',
  test: { method: 'GET', path: '/api/v1/campaigns' },
  capabilities: [
    {
      name: 'campaigns.list',
      class: 'read',
      description: 'Get campaign analytics and summary information.',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' } },
        required: ['campaignId'],
      },
      request: { method: 'GET', path: '/api/v1/campaigns/{campaignId}/analytics' },
    },
    {
      name: 'campaigns.summary',
      class: 'read',
      description: 'Get overall account summary.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/api/v1/summary' },
    },
    {
      name: 'leads.add',
      class: 'mutation',
      description: 'Add leads to a campaign.',
      parameters: {
        type: 'object',
        properties: {
          campaignId: { type: 'string' },
          email: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          customVariables: { type: 'object' },
        },
        required: ['campaignId', 'email', 'firstName'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/campaigns/{campaignId}/leads',
        body: {
          email: '{email}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          customVariables: '{customVariables}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.update',
      class: 'mutation',
      description: 'Update a lead with custom variables or details.',
      parameters: {
        type: 'object',
        properties: {
          leadId: { type: 'string' },
          customVariables: { type: 'object' },
        },
        required: ['leadId'],
      },
      request: {
        method: 'PATCH',
        path: '/api/v1/leads/{leadId}',
        body: {
          customVariables: '{customVariables}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.remove',
      class: 'mutation',
      description: 'Remove an email from a campaign.',
      parameters: {
        type: 'object',
        properties: {
          campaignId: { type: 'string' },
          email: { type: 'string' },
        },
        required: ['campaignId', 'email'],
      },
      request: {
        method: 'DELETE',
        path: '/api/v1/campaigns/{campaignId}/leads/{email}',
      },
    },
    {
      name: 'blocklist.add',
      class: 'mutation',
      description: 'Add emails or domains to the blocklist.',
      parameters: {
        type: 'object',
        properties: {
          emails: { type: 'array' },
          domains: { type: 'array' },
          keywords: { type: 'array' },
        },
        required: [],
      },
      request: {
        method: 'POST',
        path: '/api/v1/blocklist',
        body: {
          emails: '{emails}',
          domains: '{domains}',
          keywords: '{keywords}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'campaigns.start',
      class: 'mutation',
      description: 'Start a campaign.',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' } },
        required: ['campaignId'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/campaigns/{campaignId}/start',
      },
      cas: 'native-idempotency',
    },
    {
      name: 'campaigns.pause',
      class: 'mutation',
      description: 'Pause a campaign.',
      parameters: {
        type: 'object',
        properties: { campaignId: { type: 'string' } },
        required: ['campaignId'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/campaigns/{campaignId}/pause',
        body: {},
      },
      cas: 'native-idempotency',
    },
    {
      name: 'warmup.enable',
      class: 'mutation',
      description: 'Enable email warmup for account(s).',
      parameters: {
        type: 'object',
        properties: { accountId: { type: 'string' } },
        required: ['accountId'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/accounts/{accountId}/warmup/enable',
        body: {},
      },
      cas: 'native-idempotency',
    },
    {
      name: 'warmup.pause',
      class: 'mutation',
      description: 'Pause email warmup for account(s).',
      parameters: {
        type: 'object',
        properties: { accountId: { type: 'string' } },
        required: ['accountId'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/accounts/{accountId}/warmup/pause',
        body: {},
      },
      cas: 'native-idempotency',
    },
    {
      name: 'schedule.set',
      class: 'mutation',
      description: 'Set a warmup or campaign schedule.',
      parameters: {
        type: 'object',
        properties: {
          accountId: { type: 'string' },
          scheduleName: { type: 'string' },
          startDate: { type: 'string' },
          endDate: { type: 'string' },
          startTime: { type: 'string' },
          endTime: { type: 'string' },
          timezone: { type: 'string' },
          sunday: { type: 'boolean' },
          monday: { type: 'boolean' },
          tuesday: { type: 'boolean' },
          wednesday: { type: 'boolean' },
          thursday: { type: 'boolean' },
          friday: { type: 'boolean' },
          saturday: { type: 'boolean' },
        },
        required: [
          'accountId',
          'scheduleName',
          'startDate',
          'endDate',
          'startTime',
          'endTime',
          'timezone',
          'sunday',
          'monday',
          'tuesday',
          'wednesday',
          'thursday',
          'friday',
          'saturday',
        ],
      },
      request: {
        method: 'POST',
        path: '/api/v1/accounts/{accountId}/schedule',
        body: {
          name: '{scheduleName}',
          startDate: '{startDate}',
          endDate: '{endDate}',
          startTime: '{startTime}',
          endTime: '{endTime}',
          timezone: '{timezone}',
          daysOfWeek: {
            sunday: '{sunday}',
            monday: '{monday}',
            tuesday: '{tuesday}',
            wednesday: '{wednesday}',
            thursday: '{thursday}',
            friday: '{friday}',
            saturday: '{saturday}',
          },
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'email.add',
      class: 'mutation',
      description: 'Add a new email account.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/accounts',
        body: { email: '{email}' },
      },
      cas: 'native-idempotency',
    },
  ],
})
