import { declarativeRestConnector } from './declarative-rest.js'

export const retellAiConnector = declarativeRestConnector({
  kind: 'retell-ai',
  displayName: 'Retell AI',
  description: 'Make phone calls, manage phone numbers, and retrieve call/agent/voice information.',
  auth: { kind: 'api-key', hint: 'Retell AI API key.' },
  category: 'comms',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.retellai.com/v2',
  test: { method: 'GET', path: '/voices' },
  capabilities: [
    {
      name: 'calls.make',
      class: 'mutation',
      description: 'Make an outbound phone call.',
      parameters: {
        type: 'object',
        properties: {
          fromNumber: { type: 'string', description: 'Phone number to call from in E.164 format.' },
          toNumber: { type: 'string', description: 'Phone number to call in E.164 format.' },
          agentId: { type: 'string', description: 'ID of the agent to use for the call.' },
          overrideAgentVersion: { type: 'integer', description: 'Optional agent version to override.' },
          metadata: { type: 'object', description: 'Optional metadata to attach to the call.' },
          dynamicVariables: { type: 'object', description: 'Optional dynamic variables for the agent.' },
          customSipHeaders: { type: 'object', description: 'Optional custom SIP headers.' },
        },
        required: ['fromNumber', 'toNumber', 'agentId'],
      },
      request: {
        method: 'POST',
        path: '/calls',
        body: {
          from_number: '{fromNumber}',
          to_number: '{toNumber}',
          agent_id: '{agentId}',
          override_agent_version: '{overrideAgentVersion}',
          metadata: '{metadata}',
          dynamic_variables: '{dynamicVariables}',
          custom_sip_headers: '{customSipHeaders}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'calls.get',
      class: 'read',
      description: 'Retrieve details of a phone call.',
      parameters: {
        type: 'object',
        properties: { callId: { type: 'string', description: 'ID of the call to retrieve.' } },
        required: ['callId'],
      },
      request: { method: 'GET', path: '/calls/{callId}' },
    },
    {
      name: 'phonenumbers.create',
      class: 'mutation',
      description: 'Create a new phone number.',
      parameters: {
        type: 'object',
        properties: {
          nickname: { type: 'string', description: 'Nickname for the phone number.' },
          inboundAgentVersion: { type: 'integer', description: 'Version of inbound agent.' },
          outboundAgentVersion: { type: 'integer', description: 'Version of outbound agent.' },
          areaCode: { type: 'integer', description: '3-digit US area code.' },
          countryCode: { type: 'string', description: 'Country code for the phone number.' },
          tollFree: { type: 'boolean', description: 'Whether to purchase a toll-free number.' },
          phoneNumber: { type: 'string', description: 'Phone number to purchase in E.164 format.' },
          inboundWebhookUrl: { type: 'string', description: 'Webhook URL for inbound calls.' },
        },
        required: ['nickname'],
      },
      request: {
        method: 'POST',
        path: '/phone-numbers',
        body: {
          nickname: '{nickname}',
          inbound_agent_version: '{inboundAgentVersion}',
          outbound_agent_version: '{outboundAgentVersion}',
          area_code: '{areaCode}',
          country_code: '{countryCode}',
          toll_free: '{tollFree}',
          phone_number: '{phoneNumber}',
          inbound_webhook_url: '{inboundWebhookUrl}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'phonenumbers.get',
      class: 'read',
      description: 'Retrieve details of a phone number.',
      parameters: {
        type: 'object',
        properties: { phoneNumberId: { type: 'string', description: 'ID of the phone number.' } },
        required: ['phoneNumberId'],
      },
      request: { method: 'GET', path: '/phone-numbers/{phoneNumberId}' },
    },
    {
      name: 'agents.get',
      class: 'read',
      description: 'Retrieve details of an agent.',
      parameters: {
        type: 'object',
        properties: { agentId: { type: 'string', description: 'ID of the agent to retrieve.' } },
        required: ['agentId'],
      },
      request: { method: 'GET', path: '/agents/{agentId}' },
    },
    {
      name: 'voices.get',
      class: 'read',
      description: 'Retrieve details of a voice.',
      parameters: {
        type: 'object',
        properties: { voiceId: { type: 'string', description: 'ID of the voice to retrieve.' } },
        required: ['voiceId'],
      },
      request: { method: 'GET', path: '/voices/{voiceId}' },
    },
    {
      name: 'voices.list',
      class: 'read',
      description: 'List all available voices.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/voices' },
    },
  ],
})
