import { declarativeRestConnector } from './declarative-rest.js'

export const savvycalConnector = declarativeRestConnector({
  kind: 'savvycal',
  displayName: 'SavvyCal',
  description: 'Manage SavvyCal scheduling links, bookings, availability, and workflows.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://savvycal.com/oauth/authorize',
    tokenUrl: 'https://savvycal.com/oauth/token',
    scopes: [],
    sendScopeParam: false,
    clientIdEnv: 'SAVVYCAL_OAUTH_CLIENT_ID',
    clientSecretEnv: 'SAVVYCAL_OAUTH_CLIENT_SECRET',
  },
  category: 'calendar',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.savvycal.com/v1',
  test: { method: 'GET', path: '/me' },
  capabilities: [
    {
      name: 'user.current',
      class: 'read',
      description: 'Read the authenticated SavvyCal user.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/me' },
    },
    {
      name: 'events.list',
      class: 'read',
      description: 'List scheduled events with cursor, state, period, date, and attendance filters.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          after: { type: 'string' },
          before: { type: 'string' },
          state: {
            type: 'string',
            enum: ['all', 'confirmed', 'canceled', 'awaiting_reschedule', 'awaiting_checkout', 'checkout_expired', 'awaiting_approval', 'declined', 'tentative'],
          },
          period: { type: 'string', enum: ['past', 'upcoming', 'fixed', 'all'] },
          from: { type: 'string' },
          until: { type: 'string' },
          direction: { type: 'string', enum: ['asc', 'desc'] },
          attendance: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/events',
        query: {
          limit: '{limit}',
          after: '{after}',
          before: '{before}',
          state: '{state}',
          period: '{period}',
          from: '{from}',
          until: '{until}',
          direction: '{direction}',
          attendance: '{attendance}',
        },
      },
    },
    {
      name: 'events.get',
      class: 'read',
      description: 'Read one scheduled event by ID or UUID.',
      parameters: {
        type: 'object',
        properties: { eventId: { type: 'string' } },
        required: ['eventId'],
      },
      request: { method: 'GET', path: '/events/{eventId}' },
    },
    {
      name: 'events.create',
      class: 'mutation',
      description: 'Book an available slot through a scheduling link.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          display_name: { type: 'string' },
          email: { type: 'string' },
          start_at: { type: 'string' },
          end_at: { type: 'string' },
          time_zone: { type: 'string' },
          phone_number: { type: 'string' },
          fields: { type: 'array', items: { type: 'object' } },
          metadata: { type: 'object' },
        },
        required: ['linkId', 'display_name', 'email', 'start_at', 'end_at', 'time_zone'],
      },
      request: {
        method: 'POST',
        path: '/links/{linkId}/events',
        body: {
          display_name: '{display_name}',
          email: '{email}',
          start_at: '{start_at}',
          end_at: '{end_at}',
          time_zone: '{time_zone}',
          phone_number: '{phone_number}',
          fields: '{fields}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'events.cancel',
      class: 'mutation',
      description: 'Cancel an event with an optional reason.',
      parameters: {
        type: 'object',
        properties: { eventId: { type: 'string' }, cancel_reason: { type: 'string' } },
        required: ['eventId'],
      },
      request: {
        method: 'POST',
        path: '/events/{eventId}/cancel',
        body: { cancel_reason: '{cancel_reason}' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'links.list',
      class: 'read',
      description: 'List scheduling links with cursor and state filters.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          after: { type: 'string' },
          before: { type: 'string' },
          state: { type: 'string', enum: ['active', 'disabled'] },
        },
      },
      request: {
        method: 'GET',
        path: '/links',
        query: { limit: '{limit}', after: '{after}', before: '{before}', state: '{state}' },
      },
    },
    {
      name: 'links.get',
      class: 'read',
      description: 'Read one scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'GET', path: '/links/{linkId}' },
    },
    {
      name: 'links.slots',
      class: 'read',
      description: 'Read available slots for a scheduling link over at most 31 days.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          from: { type: 'string' },
          until: { type: 'string' },
        },
        required: ['linkId'],
      },
      request: {
        method: 'GET',
        path: '/links/{linkId}/slots',
        query: { from: '{from}', until: '{until}' },
      },
    },
    {
      name: 'workflows.list',
      class: 'read',
      description: 'List workflows with cursor pagination.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          after: { type: 'string' },
          before: { type: 'string' },
        },
      },
      request: {
        method: 'GET',
        path: '/workflows',
        query: { limit: '{limit}', after: '{after}', before: '{before}' },
      },
    },
    {
      name: 'workflows.rules',
      class: 'read',
      description: 'List rules for one workflow.',
      parameters: {
        type: 'object',
        properties: { workflowId: { type: 'string' } },
        required: ['workflowId'],
      },
      request: { method: 'GET', path: '/workflows/{workflowId}/rules' },
    },
    {
      name: 'links.create',
      class: 'mutation',
      description: 'Create a personal recurring or single-use scheduling link.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          private_name: { type: 'string' },
          type: { type: 'string', enum: ['recurring', 'single'] },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/links',
        body: {
          name: '{name}',
          description: '{description}',
          private_name: '{private_name}',
          type: '{type}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'links.update',
      class: 'mutation',
      description: 'Update a scheduling link name, description, private name, or type.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          private_name: { type: 'string' },
          type: { type: 'string', enum: ['recurring', 'single'] },
        },
        required: ['linkId'],
      },
      request: {
        method: 'PATCH',
        path: '/links/{linkId}',
        body: {
          name: '{name}',
          description: '{description}',
          private_name: '{private_name}',
          type: '{type}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'links.delete',
      class: 'mutation',
      description: 'Delete a scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'DELETE', path: '/links/{linkId}' },
      cas: 'optimistic-read-verify',
      externalEffect: true,
    },
    {
      name: 'links.duplicate',
      class: 'mutation',
      description: 'Create a copy of a scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'POST', path: '/links/{linkId}/duplicate', body: {} },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'links.toggle',
      class: 'mutation',
      description: 'Toggle a scheduling link between active and disabled.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'POST', path: '/links/{linkId}/toggle', body: {} },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
