import { declarativeRestConnector } from './declarative-rest.js'

export const savvycalConnector = declarativeRestConnector({
  kind: 'savvycal',
  displayName: 'SavvyCal',
  description: 'Manage scheduling links, events, and workflows in SavvyCal.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://api.savvycal.com/oauth/authorize',
    tokenUrl: 'https://api.savvycal.com/oauth/token',
    scopes: ['read', 'write'],
    clientIdEnv: 'SAVVYCAL_OAUTH_CLIENT_ID',
    clientSecretEnv: 'SAVVYCAL_OAUTH_CLIENT_SECRET',
  },
  category: 'doc',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.savvycal.com/v1',
  test: { method: 'GET', path: '/user' },
  capabilities: [
    {
      name: 'user.current',
      class: 'read',
      description: 'Get the current authenticated user.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/user' },
      requiredScopes: ['read'],
    },
    {
      name: 'events.list',
      class: 'read',
      description: 'List all events.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, offset: { type: 'integer' } },
        required: [],
      },
      request: { method: 'GET', path: '/events', query: { limit: '{limit}', offset: '{offset}' } },
      requiredScopes: ['read'],
    },
    {
      name: 'events.get',
      class: 'read',
      description: 'Get a specific event by ID.',
      parameters: {
        type: 'object',
        properties: { eventId: { type: 'string' } },
        required: ['eventId'],
      },
      request: { method: 'GET', path: '/events/{eventId}' },
      requiredScopes: ['read'],
    },
    {
      name: 'events.create',
      class: 'mutation',
      description: 'Create a new event.',
      parameters: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          description: { type: 'string' },
          startTime: { type: 'string' },
          endTime: { type: 'string' },
          guests: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'startTime', 'endTime'],
      },
      request: {
        method: 'POST',
        path: '/events',
        body: {
          title: '{title}',
          description: '{description}',
          startTime: '{startTime}',
          endTime: '{endTime}',
          guests: '{guests}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['write'],
    },
    {
      name: 'events.cancel',
      class: 'mutation',
      description: 'Cancel an event.',
      parameters: {
        type: 'object',
        properties: { eventId: { type: 'string' } },
        required: ['eventId'],
      },
      request: { method: 'DELETE', path: '/events/{eventId}' },
      requiredScopes: ['write'],
    },
    {
      name: 'events.findByEmail',
      class: 'read',
      description: 'Find events by attendee email.',
      parameters: {
        type: 'object',
        properties: { email: { type: 'string' } },
        required: ['email'],
      },
      request: { method: 'GET', path: '/events', query: { email: '{email}' } },
      requiredScopes: ['read'],
    },
    {
      name: 'links.list',
      class: 'read',
      description: 'List all scheduling links.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, offset: { type: 'integer' } },
        required: [],
      },
      request: { method: 'GET', path: '/scheduling_links', query: { limit: '{limit}', offset: '{offset}' } },
      requiredScopes: ['read'],
    },
    {
      name: 'links.get',
      class: 'read',
      description: 'Get a specific scheduling link by ID.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'GET', path: '/scheduling_links/{linkId}' },
      requiredScopes: ['read'],
    },
    {
      name: 'links.delete',
      class: 'mutation',
      description: 'Delete a scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'DELETE', path: '/scheduling_links/{linkId}' },
      requiredScopes: ['write'],
    },
    {
      name: 'links.duplicate',
      class: 'mutation',
      description: 'Duplicate an existing scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' } },
        required: ['linkId'],
      },
      request: { method: 'POST', path: '/scheduling_links/{linkId}/duplicate', body: {} },
      cas: 'native-idempotency',
      requiredScopes: ['write'],
    },
    {
      name: 'links.toggle',
      class: 'mutation',
      description: 'Toggle a scheduling link active/inactive status.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' }, active: { type: 'boolean' } },
        required: ['linkId', 'active'],
      },
      request: {
        method: 'PATCH',
        path: '/scheduling_links/{linkId}',
        body: { active: '{active}' },
      },
      requiredScopes: ['write'],
    },
    {
      name: 'links.slots',
      class: 'read',
      description: 'Get available time slots for a scheduling link.',
      parameters: {
        type: 'object',
        properties: { linkId: { type: 'string' }, startDate: { type: 'string' }, endDate: { type: 'string' } },
        required: ['linkId'],
      },
      request: {
        method: 'GET',
        path: '/scheduling_links/{linkId}/slots',
        query: { startDate: '{startDate}', endDate: '{endDate}' },
      },
      requiredScopes: ['read'],
    },
    {
      name: 'workflows.list',
      class: 'read',
      description: 'List all workflows.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, offset: { type: 'integer' } },
        required: [],
      },
      request: { method: 'GET', path: '/workflows', query: { limit: '{limit}', offset: '{offset}' } },
      requiredScopes: ['read'],
    },
    {
      name: 'workflows.rules',
      class: 'read',
      description: 'Get workflow rules for a specific workflow.',
      parameters: {
        type: 'object',
        properties: { workflowId: { type: 'string' } },
        required: ['workflowId'],
      },
      request: { method: 'GET', path: '/workflows/{workflowId}/rules' },
      requiredScopes: ['read'],
    },
    {
      name: 'links.create',
      class: 'mutation',
      description: 'Create a new scheduling link.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          slug: { type: 'string', description: 'URL-safe slug for the booking URL.' },
          durations: {
            type: 'array',
            items: { type: 'integer' },
            description: 'List of allowed meeting durations in minutes.',
          },
          description: { type: 'string' },
          locations: {
            type: 'array',
            description: 'List of meeting locations (Zoom, in-person, custom URL, etc.).',
          },
          active: { type: 'boolean' },
        },
        required: ['name', 'slug', 'durations'],
      },
      request: {
        method: 'POST',
        path: '/scheduling_links',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['write'],
    },
    {
      name: 'links.update',
      class: 'mutation',
      description: 'Update an existing scheduling link.',
      parameters: {
        type: 'object',
        properties: {
          linkId: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          durations: { type: 'array', items: { type: 'integer' } },
          locations: { type: 'array' },
          active: { type: 'boolean' },
        },
        required: ['linkId'],
      },
      request: {
        method: 'PATCH',
        path: '/scheduling_links/{linkId}',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['write'],
    },
    {
      name: 'events.update',
      class: 'mutation',
      description: 'Update a scheduled event (reschedule, change title/description/guests).',
      parameters: {
        type: 'object',
        properties: {
          eventId: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          startTime: { type: 'string' },
          endTime: { type: 'string' },
          guests: { type: 'array', items: { type: 'string' } },
        },
        required: ['eventId'],
      },
      request: {
        method: 'PATCH',
        path: '/events/{eventId}',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['write'],
    },
    {
      name: 'workflows.create',
      class: 'mutation',
      description: 'Create a scheduling workflow rule (e.g. confirmation email, reminder, follow-up).',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          trigger: {
            type: 'string',
            description: 'Trigger event for the workflow (e.g. event_scheduled, event_cancelled, before_event).',
          },
          action: {
            type: 'object',
            description: 'Workflow action definition (email, SMS, webhook, etc.).',
          },
          active: { type: 'boolean' },
        },
        required: ['name', 'trigger', 'action'],
      },
      request: {
        method: 'POST',
        path: '/workflows',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['write'],
    },
  ],
})
