import { declarativeRestConnector } from './declarative-rest.js'

export const simplirouteConnector = declarativeRestConnector({
  kind: 'simpliroute',
  displayName: 'SimpliRoute',
  description: 'Manage delivery operations: clients, vehicles, visits, routes, and optimization planning.',
  auth: { kind: 'api-key', hint: 'SimpliRoute API key.' },
  category: 'commerce',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.simpliroute.com/v2',
  test: { method: 'GET', path: '/me' },
  capabilities: [
    {
      name: 'account.getMe',
      class: 'read',
      description: 'Get current account information.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/me' },
    },
    {
      name: 'clients.list',
      class: 'read',
      description: 'List all clients.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/clients' },
    },
    {
      name: 'clients.create',
      class: 'mutation',
      description: 'Create one or more clients.',
      parameters: {
        type: 'object',
        properties: { clients: { type: 'array', items: { type: 'object' } } },
        required: ['clients'],
      },
      request: { method: 'POST', path: '/clients', body: { clients: '{clients}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'clients.bulkDelete',
      class: 'mutation',
      description: 'Bulk delete multiple clients.',
      parameters: {
        type: 'object',
        properties: { ids: { type: 'array', items: { type: 'integer' } } },
        required: ['ids'],
      },
      request: { method: 'DELETE', path: '/clients', body: { ids: '{ids}' } },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'clientProperties.create',
      class: 'mutation',
      description: 'Create a custom client property.',
      parameters: {
        type: 'object',
        properties: {
          label: { type: 'string' },
          type: { type: 'string', enum: ['str', 'int', 'float', 'bool'] },
        },
        required: ['label', 'type'],
      },
      request: { method: 'POST', path: '/client-properties', body: { label: '{label}', type: '{type}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'vehicles.list',
      class: 'read',
      description: 'List all vehicles.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/vehicles' },
    },
    {
      name: 'vehicles.get',
      class: 'read',
      description: 'Get a vehicle by ID.',
      parameters: {
        type: 'object',
        properties: { vehicleId: { type: 'integer' } },
        required: ['vehicleId'],
      },
      request: { method: 'GET', path: '/vehicles/{vehicleId}' },
    },
    {
      name: 'vehicles.create',
      class: 'mutation',
      description: 'Create a vehicle.',
      parameters: {
        type: 'object',
        properties: {
          capacity: { type: 'number' },
          defaultDriver: { type: ['string', 'null'] },
          skills: { type: ['array', 'null'], items: { type: 'integer' } },
        },
        required: ['capacity'],
      },
      request: { method: 'POST', path: '/vehicles', body: { capacity: '{capacity}', default_driver: '{defaultDriver}', skills: '{skills}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'vehicles.delete',
      class: 'mutation',
      description: 'Delete a vehicle.',
      parameters: {
        type: 'object',
        properties: { vehicleId: { type: 'integer' } },
        required: ['vehicleId'],
      },
      request: { method: 'DELETE', path: '/vehicles/{vehicleId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'visits.list',
      class: 'read',
      description: 'List all visits.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/visits' },
    },
    {
      name: 'visits.get',
      class: 'read',
      description: 'Get a visit by ID.',
      parameters: {
        type: 'object',
        properties: { visitId: { type: 'integer' } },
        required: ['visitId'],
      },
      request: { method: 'GET', path: '/visits/{visitId}' },
    },
    {
      name: 'visits.getDetail',
      class: 'read',
      description: 'Get detailed visit information.',
      parameters: {
        type: 'object',
        properties: { visitId: { type: 'integer' } },
        required: ['visitId'],
      },
      request: { method: 'GET', path: '/visits/{visitId}/detail' },
    },
    {
      name: 'visits.create',
      class: 'mutation',
      description: 'Create one or more visits.',
      parameters: {
        type: 'object',
        properties: { visits: { type: 'array', items: { type: 'object' } } },
        required: ['visits'],
      },
      request: { method: 'POST', path: '/visits', body: { visits: '{visits}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'visits.update',
      class: 'mutation',
      description: 'Update a visit.',
      parameters: {
        type: 'object',
        properties: { visitId: { type: 'integer' }, fields: { type: 'object' } },
        required: ['visitId', 'fields'],
      },
      request: { method: 'PUT', path: '/visits/{visitId}', body: '{fields}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'visits.updatePartial',
      class: 'mutation',
      description: 'Partially update a visit.',
      parameters: {
        type: 'object',
        properties: { visitId: { type: 'integer' }, fields: { type: 'object' } },
        required: ['visitId', 'fields'],
      },
      request: { method: 'PATCH', path: '/visits/{visitId}', body: '{fields}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'visits.delete',
      class: 'mutation',
      description: 'Delete a visit.',
      parameters: {
        type: 'object',
        properties: { visitId: { type: 'integer' } },
        required: ['visitId'],
      },
      request: { method: 'DELETE', path: '/visits/{visitId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'visits.addItems',
      class: 'mutation',
      description: 'Add items to a visit.',
      parameters: {
        type: 'object',
        properties: {
          visitId: { type: 'integer' },
          items: { type: 'array', items: { type: 'object' } },
        },
        required: ['visitId', 'items'],
      },
      request: { method: 'POST', path: '/visits/{visitId}/items', body: { items: '{items}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'routes.list',
      class: 'read',
      description: 'List all routes.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/routes' },
    },
    {
      name: 'routes.get',
      class: 'read',
      description: 'Get a route by ID.',
      parameters: {
        type: 'object',
        properties: { routeId: { type: 'string' } },
        required: ['routeId'],
      },
      request: { method: 'GET', path: '/routes/{routeId}' },
    },
    {
      name: 'routes.create',
      class: 'mutation',
      description: 'Create a delivery route.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          plannedDate: { type: 'string' },
          vehicle: { type: 'integer' },
          driver: { type: 'integer' },
          plan: { type: 'string' },
        },
        required: ['name', 'plannedDate', 'vehicle', 'driver', 'plan'],
      },
      request: {
        method: 'POST',
        path: '/routes',
        body: { name: '{name}', planned_date: '{plannedDate}', vehicle: '{vehicle}', driver: '{driver}', plan: '{plan}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'routes.delete',
      class: 'mutation',
      description: 'Delete a route.',
      parameters: {
        type: 'object',
        properties: { routeId: { type: 'string' } },
        required: ['routeId'],
      },
      request: { method: 'DELETE', path: '/routes/{routeId}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'plans.list',
      class: 'read',
      description: 'List all delivery plans.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/plans' },
    },
    {
      name: 'plans.create',
      class: 'mutation',
      description: 'Create a delivery plan.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          startDate: { type: 'string' },
          endDate: { type: 'string' },
        },
        required: ['name', 'startDate', 'endDate'],
      },
      request: {
        method: 'POST',
        path: '/plans',
        body: { name: '{name}', start_date: '{startDate}', end_date: '{endDate}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'plans.getVehicles',
      class: 'read',
      description: 'Get vehicles assigned to a plan.',
      parameters: {
        type: 'object',
        properties: { planId: { type: 'string' } },
        required: ['planId'],
      },
      request: { method: 'GET', path: '/plans/{planId}/vehicles' },
    },
    {
      name: 'users.list',
      class: 'read',
      description: 'List all users.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/users' },
    },
    {
      name: 'users.get',
      class: 'read',
      description: 'Get a user by ID.',
      parameters: {
        type: 'object',
        properties: { userId: { type: 'integer' } },
        required: ['userId'],
      },
      request: { method: 'GET', path: '/users/{userId}' },
    },
    {
      name: 'users.create',
      class: 'mutation',
      description: 'Create one or more users.',
      parameters: {
        type: 'object',
        properties: { users: { type: 'array', items: { type: 'object' } } },
        required: ['users'],
      },
      request: { method: 'POST', path: '/users', body: { users: '{users}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'users.update',
      class: 'mutation',
      description: 'Update a user.',
      parameters: {
        type: 'object',
        properties: { userId: { type: 'integer' }, fields: { type: 'object' } },
        required: ['userId', 'fields'],
      },
      request: { method: 'PUT', path: '/users/{userId}', body: '{fields}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'drivers.list',
      class: 'read',
      description: 'List all drivers.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/drivers' },
    },
    {
      name: 'fleets.list',
      class: 'read',
      description: 'List all fleets.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/fleets' },
    },
    {
      name: 'skills.list',
      class: 'read',
      description: 'List all available skills.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/skills' },
    },
    {
      name: 'tags.list',
      class: 'read',
      description: 'List all available tags.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/tags' },
    },
    {
      name: 'zones.list',
      class: 'read',
      description: 'List all zones.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/zones' },
    },
    {
      name: 'observations.list',
      class: 'read',
      description: 'List observations.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/observations' },
    },
    {
      name: 'sellers.list',
      class: 'read',
      description: 'List all sellers.',
      parameters: { type: 'object', properties: {}, required: [] },
      request: { method: 'GET', path: '/sellers' },
    },
  ],
})
