import { declarativeRestConnector } from './declarative-rest.js'

export const snowflakeConnector = declarativeRestConnector({
  kind: 'snowflake',
  displayName: 'Snowflake',
  description: 'Data warehouse built for the cloud. Query, insert, update, delete, and upsert rows.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://app.snowflake.com/oauth/authorize',
    tokenUrl: 'https://app.snowflake.com/oauth/token',
    scopes: ['session:role:manage'],
    clientIdEnv: 'SNOWFLAKE_OAUTH_CLIENT_ID',
    clientSecretEnv: 'SNOWFLAKE_OAUTH_CLIENT_SECRET',
  },
  category: 'database',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.snowflakecomputing.com/api/v2',
  test: { method: 'GET', path: '/accounts/whoami' },
  capabilities: [
    {
      name: 'queries.run',
      class: 'read',
      description: 'Run a SQL query.',
      parameters: {
        type: 'object',
        properties: { statement: { type: 'string' } },
        required: ['statement'],
      },
      request: { method: 'POST', path: '/statements', body: { statement: '{statement}' } },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'queries.runMultiple',
      class: 'read',
      description: 'Run multiple SQL queries.',
      parameters: {
        type: 'object',
        properties: { statements: { type: 'array', items: { type: 'string' } } },
        required: ['statements'],
      },
      request: { method: 'POST', path: '/statements', body: { statements: '{statements}' } },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.insert',
      class: 'mutation',
      description: 'Insert a row into a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          values: { type: 'object' },
        },
        required: ['database', 'schema', 'table', 'values'],
      },
      request: {
        method: 'POST',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows',
        body: { values: '{values}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.insertMultiple',
      class: 'mutation',
      description: 'Insert multiple rows into a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          rows: { type: 'array', items: { type: 'object' } },
        },
        required: ['database', 'schema', 'table', 'rows'],
      },
      request: {
        method: 'POST',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows/bulk',
        body: { rows: '{rows}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.update',
      class: 'mutation',
      description: 'Update a row in a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          rowId: { type: 'string' },
          values: { type: 'object' },
        },
        required: ['database', 'schema', 'table', 'rowId', 'values'],
      },
      request: {
        method: 'PATCH',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows/{rowId}',
        body: { values: '{values}' },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.upsert',
      class: 'mutation',
      description: 'Insert or update a row in a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          values: { type: 'object' },
          keyColumns: { type: 'array', items: { type: 'string' } },
        },
        required: ['database', 'schema', 'table', 'values', 'keyColumns'],
      },
      request: {
        method: 'PUT',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows/upsert',
        body: { values: '{values}', keyColumns: '{keyColumns}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.delete',
      class: 'mutation',
      description: 'Delete a row from a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          rowId: { type: 'string' },
        },
        required: ['database', 'schema', 'table', 'rowId'],
      },
      request: {
        method: 'DELETE',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows/{rowId}',
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.getById',
      class: 'read',
      description: 'Get a row by ID from a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          rowId: { type: 'string' },
        },
        required: ['database', 'schema', 'table', 'rowId'],
      },
      request: {
        method: 'GET',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows/{rowId}',
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'rows.search',
      class: 'read',
      description: 'Search rows in a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          filter: { type: 'object' },
          limit: { type: 'integer' },
        },
        required: ['database', 'schema', 'table'],
      },
      request: {
        method: 'GET',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/rows',
        query: { filter: '{filter}', limit: '{limit}' },
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'tables.list',
      class: 'read',
      description: 'List tables in a schema.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
        },
        required: ['database', 'schema'],
      },
      request: {
        method: 'GET',
        path: '/databases/{database}/schemas/{schema}/tables',
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'tables.getSchema',
      class: 'read',
      description: 'Get the schema of a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
        },
        required: ['database', 'schema', 'table'],
      },
      request: {
        method: 'GET',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/schema',
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'procedures.execute',
      class: 'mutation',
      description: 'Execute a stored procedure.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          procedureName: { type: 'string' },
          arguments: { type: 'array', items: { type: 'string' } },
        },
        required: ['database', 'schema', 'procedureName'],
      },
      request: {
        method: 'POST',
        path: '/databases/{database}/schemas/{schema}/procedures/{procedureName}/execute',
        body: { arguments: '{arguments}' },
      },
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'stages.loadData',
      class: 'mutation',
      description: 'Load data from a stage into a table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          table: { type: 'string' },
          stage: { type: 'string' },
          files: { type: 'array', items: { type: 'string' } },
        },
        required: ['database', 'schema', 'table', 'stage'],
      },
      request: {
        method: 'POST',
        path: '/databases/{database}/schemas/{schema}/tables/{table}/load',
        body: { stage: '{stage}', files: '{files}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['session:role:manage'],
    },
    {
      name: 'dynamicTables.create',
      class: 'mutation',
      description: 'Create a dynamic table.',
      parameters: {
        type: 'object',
        properties: {
          database: { type: 'string' },
          schema: { type: 'string' },
          name: { type: 'string' },
          query: { type: 'string' },
        },
        required: ['database', 'schema', 'name', 'query'],
      },
      request: {
        method: 'POST',
        path: '/databases/{database}/schemas/{schema}/dynamic-tables',
        body: { name: '{name}', query: '{query}' },
      },
      cas: 'native-idempotency',
      requiredScopes: ['session:role:manage'],
    },
  ],
})
