import { declarativeRestConnector } from './declarative-rest.js'

export const squareConnector = declarativeRestConnector({
  kind: 'square',
  displayName: 'Square',
  description: 'Query customers, payments, and invoices. Create or update Square objects.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://connect.squareup.com/oauth2/authorize',
    tokenUrl: 'https://connect.squareup.com/oauth2/token',
    scopes: ['CUSTOMERS_READ', 'CUSTOMERS_WRITE', 'PAYMENTS_READ', 'PAYMENTS_WRITE', 'INVOICES_READ', 'INVOICES_WRITE'],
    clientIdEnv: 'SQUARE_OAUTH_CLIENT_ID',
    clientSecretEnv: 'SQUARE_OAUTH_CLIENT_SECRET',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://connect.squareup.com/v2',
  test: { method: 'GET', path: '/locations' },
  capabilities: [
    {
      name: 'customers.list',
      class: 'read',
      description: 'List customers.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, cursor: { type: 'string' } },
        required: [],
      },
      request: { method: 'GET', path: '/customers', query: { limit: '{limit}', cursor: '{cursor}' } },
      requiredScopes: ['CUSTOMERS_READ'],
    },
    {
      name: 'customers.get',
      class: 'read',
      description: 'Retrieve a customer by ID.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' } },
        required: ['customerId'],
      },
      request: { method: 'GET', path: '/customers/{customerId}' },
      requiredScopes: ['CUSTOMERS_READ'],
    },
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a new customer.',
      parameters: {
        type: 'object',
        properties: { givenName: { type: 'string' }, familyName: { type: 'string' }, emailAddress: { type: 'string' }, phoneNumber: { type: 'string' } },
        required: ['givenName'],
      },
      request: { method: 'POST', path: '/customers', body: { givenName: '{givenName}', familyName: '{familyName}', emailAddress: '{emailAddress}', phoneNumber: '{phoneNumber}' } },
      cas: 'native-idempotency',
      requiredScopes: ['CUSTOMERS_WRITE'],
    },
    {
      name: 'customers.update',
      class: 'mutation',
      description: 'Update a customer.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' }, givenName: { type: 'string' }, familyName: { type: 'string' }, emailAddress: { type: 'string' } },
        required: ['customerId'],
      },
      request: { method: 'PUT', path: '/customers/{customerId}', body: { givenName: '{givenName}', familyName: '{familyName}', emailAddress: '{emailAddress}' } },
      cas: 'optimistic-read-verify',
      requiredScopes: ['CUSTOMERS_WRITE'],
    },
    {
      name: 'payments.list',
      class: 'read',
      description: 'List payments.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, cursor: { type: 'string' }, beginTime: { type: 'string' }, endTime: { type: 'string' } },
        required: [],
      },
      request: { method: 'GET', path: '/payments', query: { limit: '{limit}', cursor: '{cursor}', beginTime: '{beginTime}', endTime: '{endTime}' } },
      requiredScopes: ['PAYMENTS_READ'],
    },
    {
      name: 'payments.get',
      class: 'read',
      description: 'Retrieve a payment by ID.',
      parameters: {
        type: 'object',
        properties: { paymentId: { type: 'string' } },
        required: ['paymentId'],
      },
      request: { method: 'GET', path: '/payments/{paymentId}' },
      requiredScopes: ['PAYMENTS_READ'],
    },
    {
      name: 'invoices.list',
      class: 'read',
      description: 'List invoices.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer' }, cursor: { type: 'string' } },
        required: [],
      },
      request: { method: 'GET', path: '/invoices', query: { limit: '{limit}', cursor: '{cursor}' } },
      requiredScopes: ['INVOICES_READ'],
    },
    {
      name: 'invoices.get',
      class: 'read',
      description: 'Retrieve an invoice by ID.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' } },
        required: ['invoiceId'],
      },
      request: { method: 'GET', path: '/invoices/{invoiceId}' },
      requiredScopes: ['INVOICES_READ'],
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create an invoice.',
      parameters: {
        type: 'object',
        properties: { invoice: { type: 'object' } },
        required: ['invoice'],
      },
      request: { method: 'POST', path: '/invoices', body: { invoice: '{invoice}' } },
      cas: 'native-idempotency',
      requiredScopes: ['INVOICES_WRITE'],
    },
    {
      name: 'invoices.update',
      class: 'mutation',
      description: 'Update an invoice.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' }, invoice: { type: 'object' } },
        required: ['invoiceId', 'invoice'],
      },
      request: { method: 'PUT', path: '/invoices/{invoiceId}', body: { invoice: '{invoice}' } },
      cas: 'optimistic-read-verify',
      requiredScopes: ['INVOICES_WRITE'],
    },
  ],
})
