import { declarativeRestConnector } from './declarative-rest.js'

export const stripeConnector = declarativeRestConnector({
  kind: 'stripe',
  displayName: 'Stripe',
  description: 'Manage Stripe customers, invoices, subscriptions, and payments.',
  auth: { kind: 'api-key', hint: 'Stripe Secret API Key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.stripe.com/v1',
  test: { method: 'GET', path: '/account' },
  capabilities: [
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a new Stripe customer.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          phone: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/customers',
        body: {
          email: '{email}',
          name: '{name}',
          description: '{description}',
          phone: '{phone}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'customers.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe customer by ID.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' } },
        required: ['customerId'],
      },
      request: { method: 'GET', path: '/customers/{customerId}' },
    },
    {
      name: 'customers.search',
      class: 'read',
      description: 'Search Stripe customers.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: { method: 'GET', path: '/customers', query: { limit: '{limit}' } },
    },
    {
      name: 'customers.update',
      class: 'mutation',
      description: 'Update a Stripe customer.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          email: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          phone: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId'],
      },
      request: {
        method: 'POST',
        path: '/customers/{customerId}',
        body: {
          email: '{email}',
          name: '{name}',
          description: '{description}',
          phone: '{phone}',
          metadata: '{metadata}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create a Stripe invoice.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          description: { type: 'string' },
          currency: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId'],
      },
      request: {
        method: 'POST',
        path: '/invoices',
        body: {
          customer: '{customerId}',
          description: '{description}',
          currency: '{currency}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe invoice by ID.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' } },
        required: ['invoiceId'],
      },
      request: { method: 'GET', path: '/invoices/{invoiceId}' },
    },
    {
      name: 'invoices.find',
      class: 'read',
      description: 'Find Stripe invoices.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/invoices',
        query: {
          customer: '{customerId}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'subscriptions.create',
      class: 'mutation',
      description: 'Create a Stripe subscription.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          items: { type: 'object' },
          trialPeriodDays: { type: 'integer' },
          defaultPaymentMethod: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId', 'items'],
      },
      request: {
        method: 'POST',
        path: '/subscriptions',
        body: {
          customer: '{customerId}',
          items: '{items}',
          trial_period_days: '{trialPeriodDays}',
          default_payment_method: '{defaultPaymentMethod}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe subscription by ID.',
      parameters: {
        type: 'object',
        properties: { subscriptionId: { type: 'string' } },
        required: ['subscriptionId'],
      },
      request: { method: 'GET', path: '/subscriptions/{subscriptionId}' },
    },
    {
      name: 'subscriptions.search',
      class: 'read',
      description: 'Search Stripe subscriptions.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          status: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/subscriptions',
        query: {
          customer: '{customerId}',
          status: '{status}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'subscriptions.cancel',
      class: 'mutation',
      description: 'Cancel a Stripe subscription.',
      parameters: {
        type: 'object',
        properties: {
          subscriptionId: { type: 'string' },
          cancelAtPeriodEnd: { type: 'boolean' },
        },
        required: ['subscriptionId'],
      },
      request: {
        method: 'DELETE',
        path: '/subscriptions/{subscriptionId}',
        body: {
          cancel_at_period_end: '{cancelAtPeriodEnd}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'payment-intents.create',
      class: 'mutation',
      description: 'Create a Stripe payment intent.',
      parameters: {
        type: 'object',
        properties: {
          amount: { type: 'integer' },
          currency: { type: 'string' },
          customerId: { type: 'string' },
          paymentMethod: { type: 'string' },
          confirm: { type: 'boolean' },
          returnUrl: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['amount', 'currency'],
      },
      request: {
        method: 'POST',
        path: '/payment_intents',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          customer: '{customerId}',
          payment_method: '{paymentMethod}',
          confirm: '{confirm}',
          return_url: '{returnUrl}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-intents.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe payment intent by ID.',
      parameters: {
        type: 'object',
        properties: { paymentIntentId: { type: 'string' } },
        required: ['paymentIntentId'],
      },
      request: { method: 'GET', path: '/payment_intents/{paymentIntentId}' },
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a Stripe product.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'boolean' },
          metadata: { type: 'object' },
          url: { type: 'string' },
          images: { type: 'array' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/products',
        body: {
          name: '{name}',
          description: '{description}',
          active: '{active}',
          metadata: '{metadata}',
          url: '{url}',
          images: '{images}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'prices.create',
      class: 'mutation',
      description: 'Create a Stripe price.',
      parameters: {
        type: 'object',
        properties: {
          productId: { type: 'string' },
          unitAmount: { type: 'integer' },
          currency: { type: 'string' },
          recurring: { type: 'object' },
          metadata: { type: 'object' },
        },
        required: ['productId', 'currency'],
      },
      request: {
        method: 'POST',
        path: '/prices',
        body: {
          product: '{productId}',
          unit_amount: '{unitAmount}',
          currency: '{currency}',
          recurring: '{recurring}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'refunds.create',
      class: 'mutation',
      description: 'Create a Stripe refund.',
      parameters: {
        type: 'object',
        properties: {
          chargeId: { type: 'string' },
          amount: { type: 'integer' },
          reason: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['chargeId'],
      },
      request: {
        method: 'POST',
        path: '/refunds',
        body: {
          charge: '{chargeId}',
          amount: '{amount}',
          reason: '{reason}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-links.create',
      class: 'mutation',
      description: 'Create a Stripe payment link.',
      parameters: {
        type: 'object',
        properties: {
          lineItems: { type: 'array' },
          afterCompletionType: { type: 'string' },
          afterCompletionRedirectUrl: { type: 'string' },
          allowPromotionCodes: { type: 'boolean' },
          billingAddressCollection: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['lineItems'],
      },
      request: {
        method: 'POST',
        path: '/payment_links',
        body: {
          line_items: '{lineItems}',
          after_completion: '{afterCompletionType}',
          after_completion_redirect_url: '{afterCompletionRedirectUrl}',
          allow_promotion_codes: '{allowPromotionCodes}',
          billing_address_collection: '{billingAddressCollection}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-links.deactivate',
      class: 'mutation',
      description: 'Deactivate a Stripe payment link.',
      parameters: {
        type: 'object',
        properties: { paymentLinkId: { type: 'string' } },
        required: ['paymentLinkId'],
      },
      request: {
        method: 'POST',
        path: '/payment_links/{paymentLinkId}/line_items',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'customers.delete',
      class: 'mutation',
      description: 'Delete a Stripe customer.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' } },
        required: ['customerId'],
      },
      request: { method: 'DELETE', path: '/customers/{customerId}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'invoices.send',
      class: 'mutation',
      description: 'Finalize and send a Stripe invoice to the customer.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' } },
        required: ['invoiceId'],
      },
      request: { method: 'POST', path: '/invoices/{invoiceId}/send' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'invoices.void',
      class: 'mutation',
      description: 'Void a finalized Stripe invoice.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' } },
        required: ['invoiceId'],
      },
      request: { method: 'POST', path: '/invoices/{invoiceId}/void' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'products.update',
      class: 'mutation',
      description: 'Update a Stripe product.',
      parameters: {
        type: 'object',
        properties: {
          productId: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'boolean' },
          metadata: { type: 'object' },
          url: { type: 'string' },
          images: { type: 'array' },
        },
        required: ['productId'],
      },
      request: {
        method: 'POST',
        path: '/products/{productId}',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'charges.capture',
      class: 'mutation',
      description: 'Capture a previously-authorized Stripe charge.',
      parameters: {
        type: 'object',
        properties: {
          chargeId: { type: 'string' },
          amount: { type: 'integer' },
          receiptEmail: { type: 'string' },
          statementDescriptor: { type: 'string' },
        },
        required: ['chargeId'],
      },
      request: {
        method: 'POST',
        path: '/charges/{chargeId}/capture',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'webhooks.subscribe',
      class: 'mutation',
      description:
        'Create a Stripe webhook endpoint subscribed to one or more event types. Stripe pushes signed events at the supplied url; the returned secret is what the receiver verifies signatures against.',
      parameters: {
        type: 'object',
        properties: {
          url: { type: 'string', description: 'Destination URL Stripe should POST events to.' },
          enabled_events: {
            type: 'array',
            items: { type: 'string' },
            description: 'List of Stripe event types (or ["*"]) to subscribe to.',
          },
          description: { type: 'string' },
          api_version: { type: 'string' },
          connect: { type: 'boolean' },
          metadata: { type: 'object' },
        },
        required: ['url', 'enabled_events'],
      },
      request: {
        method: 'POST',
        path: '/webhook_endpoints',
        // Optional fields (description/api_version/connect/metadata) can't be
        // bare {placeholder} body entries because readRequiredPath throws on
        // undefined; pass args through directly so callers may omit them.
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'events.list',
      class: 'read',
      description:
        'List recently delivered Stripe events. Supports filtering by event type, created timestamp range, and cursor pagination via starting_after / ending_before.',
      parameters: {
        type: 'object',
        properties: {
          type: { type: 'string', description: 'Stripe event type to filter by (e.g. "invoice.payment_failed").' },
          deliverySuccess: { type: 'boolean' },
          createdGte: { type: 'integer', description: 'Unix timestamp lower bound (inclusive).' },
          createdLte: { type: 'integer', description: 'Unix timestamp upper bound (inclusive).' },
          startingAfter: { type: 'string' },
          endingBefore: { type: 'string' },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/events',
        query: {
          type: '{type}',
          delivery_success: '{deliverySuccess}',
          'created[gte]': '{createdGte}',
          'created[lte]': '{createdLte}',
          starting_after: '{startingAfter}',
          ending_before: '{endingBefore}',
          limit: '{limit}',
        },
      },
    },
  ],
})
