import { declarativeRestConnector } from './declarative-rest.js'

export const stripeConnector = declarativeRestConnector({
  kind: 'stripe',
  displayName: 'Stripe',
  description: 'Manage Stripe customers, invoices, subscriptions, and payments.',
  auth: { kind: 'api-key', hint: 'Stripe Secret API Key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.stripe.com/v1',
  test: { method: 'GET', path: '/account' },
  capabilities: [
    {
      name: 'customers.create',
      class: 'mutation',
      description: 'Create a new Stripe customer.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          phone: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/customers',
        body: {
          email: '{email}',
          name: '{name}',
          description: '{description}',
          phone: '{phone}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'customers.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe customer by ID.',
      parameters: {
        type: 'object',
        properties: { customerId: { type: 'string' } },
        required: ['customerId'],
      },
      request: { method: 'GET', path: '/customers/{customerId}' },
    },
    {
      name: 'customers.search',
      class: 'read',
      description: 'Search Stripe customers.',
      parameters: {
        type: 'object',
        properties: {
          query: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: { method: 'GET', path: '/customers', query: { limit: '{limit}' } },
    },
    {
      name: 'customers.update',
      class: 'mutation',
      description: 'Update a Stripe customer.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          email: { type: 'string' },
          name: { type: 'string' },
          description: { type: 'string' },
          phone: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId'],
      },
      request: {
        method: 'POST',
        path: '/customers/{customerId}',
        body: {
          email: '{email}',
          name: '{name}',
          description: '{description}',
          phone: '{phone}',
          metadata: '{metadata}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'invoices.create',
      class: 'mutation',
      description: 'Create a Stripe invoice.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          description: { type: 'string' },
          currency: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId'],
      },
      request: {
        method: 'POST',
        path: '/invoices',
        body: {
          customer: '{customerId}',
          description: '{description}',
          currency: '{currency}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'invoices.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe invoice by ID.',
      parameters: {
        type: 'object',
        properties: { invoiceId: { type: 'string' } },
        required: ['invoiceId'],
      },
      request: { method: 'GET', path: '/invoices/{invoiceId}' },
    },
    {
      name: 'invoices.find',
      class: 'read',
      description: 'Find Stripe invoices.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/invoices',
        query: {
          customer: '{customerId}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'subscriptions.create',
      class: 'mutation',
      description: 'Create a Stripe subscription.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          items: { type: 'object' },
          trialPeriodDays: { type: 'integer' },
          defaultPaymentMethod: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['customerId', 'items'],
      },
      request: {
        method: 'POST',
        path: '/subscriptions',
        body: {
          customer: '{customerId}',
          items: '{items}',
          trial_period_days: '{trialPeriodDays}',
          default_payment_method: '{defaultPaymentMethod}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'subscriptions.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe subscription by ID.',
      parameters: {
        type: 'object',
        properties: { subscriptionId: { type: 'string' } },
        required: ['subscriptionId'],
      },
      request: { method: 'GET', path: '/subscriptions/{subscriptionId}' },
    },
    {
      name: 'subscriptions.search',
      class: 'read',
      description: 'Search Stripe subscriptions.',
      parameters: {
        type: 'object',
        properties: {
          customerId: { type: 'string' },
          status: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/subscriptions',
        query: {
          customer: '{customerId}',
          status: '{status}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'subscriptions.cancel',
      class: 'mutation',
      description: 'Cancel a Stripe subscription.',
      parameters: {
        type: 'object',
        properties: {
          subscriptionId: { type: 'string' },
          cancelAtPeriodEnd: { type: 'boolean' },
        },
        required: ['subscriptionId'],
      },
      request: {
        method: 'DELETE',
        path: '/subscriptions/{subscriptionId}',
        body: {
          cancel_at_period_end: '{cancelAtPeriodEnd}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'payment-intents.create',
      class: 'mutation',
      description: 'Create a Stripe payment intent.',
      parameters: {
        type: 'object',
        properties: {
          amount: { type: 'integer' },
          currency: { type: 'string' },
          customerId: { type: 'string' },
          paymentMethod: { type: 'string' },
          confirm: { type: 'boolean' },
          returnUrl: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['amount', 'currency'],
      },
      request: {
        method: 'POST',
        path: '/payment_intents',
        body: {
          amount: '{amount}',
          currency: '{currency}',
          customer: '{customerId}',
          payment_method: '{paymentMethod}',
          confirm: '{confirm}',
          return_url: '{returnUrl}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-intents.retrieve',
      class: 'read',
      description: 'Retrieve a Stripe payment intent by ID.',
      parameters: {
        type: 'object',
        properties: { paymentIntentId: { type: 'string' } },
        required: ['paymentIntentId'],
      },
      request: { method: 'GET', path: '/payment_intents/{paymentIntentId}' },
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a Stripe product.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          description: { type: 'string' },
          active: { type: 'boolean' },
          metadata: { type: 'object' },
          url: { type: 'string' },
          images: { type: 'array' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/products',
        body: {
          name: '{name}',
          description: '{description}',
          active: '{active}',
          metadata: '{metadata}',
          url: '{url}',
          images: '{images}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'prices.create',
      class: 'mutation',
      description: 'Create a Stripe price.',
      parameters: {
        type: 'object',
        properties: {
          productId: { type: 'string' },
          unitAmount: { type: 'integer' },
          currency: { type: 'string' },
          recurring: { type: 'object' },
          metadata: { type: 'object' },
        },
        required: ['productId', 'currency'],
      },
      request: {
        method: 'POST',
        path: '/prices',
        body: {
          product: '{productId}',
          unit_amount: '{unitAmount}',
          currency: '{currency}',
          recurring: '{recurring}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'refunds.create',
      class: 'mutation',
      description: 'Create a Stripe refund.',
      parameters: {
        type: 'object',
        properties: {
          chargeId: { type: 'string' },
          amount: { type: 'integer' },
          reason: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['chargeId'],
      },
      request: {
        method: 'POST',
        path: '/refunds',
        body: {
          charge: '{chargeId}',
          amount: '{amount}',
          reason: '{reason}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-links.create',
      class: 'mutation',
      description: 'Create a Stripe payment link.',
      parameters: {
        type: 'object',
        properties: {
          lineItems: { type: 'array' },
          afterCompletionType: { type: 'string' },
          afterCompletionRedirectUrl: { type: 'string' },
          allowPromotionCodes: { type: 'boolean' },
          billingAddressCollection: { type: 'string' },
          metadata: { type: 'object' },
        },
        required: ['lineItems'],
      },
      request: {
        method: 'POST',
        path: '/payment_links',
        body: {
          line_items: '{lineItems}',
          after_completion: '{afterCompletionType}',
          after_completion_redirect_url: '{afterCompletionRedirectUrl}',
          allow_promotion_codes: '{allowPromotionCodes}',
          billing_address_collection: '{billingAddressCollection}',
          metadata: '{metadata}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'payment-links.deactivate',
      class: 'mutation',
      description: 'Deactivate a Stripe payment link.',
      parameters: {
        type: 'object',
        properties: { paymentLinkId: { type: 'string' } },
        required: ['paymentLinkId'],
      },
      request: {
        method: 'POST',
        path: '/payment_links/{paymentLinkId}/line_items',
      },
      cas: 'optimistic-read-verify',
    },
  ],
})
