import { declarativeRestConnector } from './declarative-rest.js'

export const todoistConnector = declarativeRestConnector({
  kind: 'todoist',
  displayName: 'Todoist',
  description: 'Create, update, and search tasks in Todoist.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://todoist.com/oauth/authorize',
    tokenUrl: 'https://todoist.com/oauth/access_token',
    scopes: ['task:add', 'task:read', 'task:update', 'data:read'],
    clientIdEnv: 'TODOIST_OAUTH_CLIENT_ID',
    clientSecretEnv: 'TODOIST_OAUTH_CLIENT_SECRET',
  },
  category: 'doc',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.todoist.com/rest/v2',
  test: { method: 'GET', path: '/projects' },
  capabilities: [
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a task in Todoist.',
      parameters: {
        type: 'object',
        properties: {
          content: { type: 'string', description: 'Task content/title' },
          description: { type: 'string', description: 'Task description' },
          project_id: { type: 'string', description: 'Project ID where the task will be created' },
          due_string: { type: 'string', description: 'Due date (e.g., "tomorrow", "next Monday")' },
          priority: { type: 'integer', description: 'Priority (1-4, where 4 is urgent)' },
          labels: { type: 'array', description: 'Label names' },
          assignee_id: { type: 'string', description: 'Assignee user ID' },
        },
        required: ['content'],
      },
      request: {
        method: 'POST',
        path: '/tasks',
        body: {
          content: '{content}',
          description: '{description}',
          project_id: '{project_id}',
          due_string: '{due_string}',
          priority: '{priority}',
          labels: '{labels}',
          assignee_id: '{assignee_id}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['task:add'],
    },
    {
      name: 'tasks.update',
      class: 'mutation',
      description: 'Update a Todoist task.',
      parameters: {
        type: 'object',
        properties: {
          task_id: { type: 'string', description: 'Task ID' },
          content: { type: 'string', description: 'Task content/title' },
          description: { type: 'string', description: 'Task description' },
          due_string: { type: 'string', description: 'Due date (e.g., "tomorrow", "next Monday")' },
          priority: { type: 'integer', description: 'Priority (1-4, where 4 is urgent)' },
          labels: { type: 'array', description: 'Label names' },
          assignee_id: { type: 'string', description: 'Assignee user ID' },
        },
        required: ['task_id'],
      },
      request: {
        method: 'POST',
        path: '/tasks/{task_id}',
        body: {
          content: '{content}',
          description: '{description}',
          due_string: '{due_string}',
          priority: '{priority}',
          labels: '{labels}',
          assignee_id: '{assignee_id}',
        },
      },
      cas: 'optimistic-read-verify',
      requiredScopes: ['task:update'],
    },
    {
      name: 'tasks.get',
      class: 'read',
      description: 'Retrieve a single task from Todoist.',
      parameters: {
        type: 'object',
        properties: { task_id: { type: 'string', description: 'Task ID' } },
        required: ['task_id'],
      },
      request: { method: 'GET', path: '/tasks/{task_id}' },
      requiredScopes: ['task:read'],
    },
    {
      name: 'tasks.list',
      class: 'read',
      description: 'List tasks from a project or filter.',
      parameters: {
        type: 'object',
        properties: {
          project_id: { type: 'string', description: 'Filter by project ID' },
          filter: { type: 'string', description: 'Todoist filter query' },
          limit: { type: 'integer', description: 'Maximum number of tasks to return' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/tasks',
        query: {
          project_id: '{project_id}',
          filter: '{filter}',
          limit: '{limit}',
        },
      },
      requiredScopes: ['task:read'],
    },
    {
      name: 'tasks.complete',
      class: 'mutation',
      description: 'Mark a task as completed.',
      parameters: {
        type: 'object',
        properties: { task_id: { type: 'string', description: 'Task ID' } },
        required: ['task_id'],
      },
      request: { method: 'POST', path: '/tasks/{task_id}/close' },
      cas: 'optimistic-read-verify',
      requiredScopes: ['task:update'],
    },
    {
      name: 'tasks.delete',
      class: 'mutation',
      description: 'Delete a task.',
      parameters: {
        type: 'object',
        properties: { task_id: { type: 'string', description: 'Task ID' } },
        required: ['task_id'],
      },
      request: { method: 'DELETE', path: '/tasks/{task_id}' },
      cas: 'optimistic-read-verify',
      requiredScopes: ['task:update'],
    },
    {
      name: 'projects.list',
      class: 'read',
      description: 'List all projects.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/projects' },
      requiredScopes: ['data:read'],
    },
    {
      name: 'projects.create',
      class: 'mutation',
      description: 'Create a new project.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Project name' },
          parent_id: { type: 'string', description: 'Parent project ID' },
          color: { type: 'string', description: 'Project color' },
          is_favorite: { type: 'boolean', description: 'Whether the project is marked as favorite' },
          view_style: { type: 'string', description: 'Project view style (list or board)' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/projects',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['data:read'],
    },
    {
      name: 'projects.delete',
      class: 'mutation',
      description: 'Delete a project.',
      parameters: {
        type: 'object',
        properties: { project_id: { type: 'string', description: 'Project ID' } },
        required: ['project_id'],
      },
      request: { method: 'DELETE', path: '/projects/{project_id}' },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['data:read'],
    },
    {
      name: 'comments.create',
      class: 'mutation',
      description: 'Add a comment to a task or project.',
      parameters: {
        type: 'object',
        properties: {
          content: { type: 'string', description: 'Comment content' },
          task_id: { type: 'string', description: 'Task ID to attach the comment to' },
          project_id: { type: 'string', description: 'Project ID to attach the comment to' },
        },
        required: ['content'],
      },
      request: {
        method: 'POST',
        path: '/comments',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['task:add'],
    },
    {
      name: 'labels.create',
      class: 'mutation',
      description: 'Create a new label.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Label name' },
          color: { type: 'string', description: 'Label color' },
          order: { type: 'integer', description: 'Label order' },
          is_favorite: { type: 'boolean', description: 'Whether the label is marked as favorite' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/labels',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['data:read'],
    },
  ],
})
