import { declarativeRestConnector } from './declarative-rest.js'

export const togglTrackConnector = declarativeRestConnector({
  kind: 'toggl-track',
  displayName: 'Toggl Track',
  description: 'Manage time entries, projects, clients, tasks, and tags in Toggl Track.',
  auth: { kind: 'api-key', hint: 'Toggl Track API token.' },
  category: 'other',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.track.toggl.com/api/v9',
  test: { method: 'GET', path: '/me' },
  capabilities: [
    {
      name: 'clients.create',
      class: 'mutation',
      description: 'Create a new client.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          name: { type: 'string' },
          external_reference: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['workspace_id', 'name'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/clients',
        body: { name: '{name}', external_reference: '{external_reference}', notes: '{notes}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'clients.find',
      class: 'read',
      description: 'Find clients in a workspace.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          status: { type: 'string' },
          page: { type: 'integer' },
          per_page: { type: 'integer' },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/clients',
        query: { status: '{status}', page: '{page}', per_page: '{per_page}' },
      },
    },
    {
      name: 'projects.create',
      class: 'mutation',
      description: 'Create a new project.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          name: { type: 'string' },
          client_id: { type: 'integer' },
          is_private: { type: 'boolean' },
          active: { type: 'boolean' },
          color: { type: 'string' },
          rate: { type: 'number' },
          fixed_fee: { type: 'number' },
          start_date: { type: 'string' },
          end_date: { type: 'string' },
        },
        required: ['workspace_id', 'name'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/projects',
        body: {
          name: '{name}',
          client_id: '{client_id}',
          is_private: '{is_private}',
          active: '{active}',
          color: '{color}',
          rate: '{rate}',
          fixed_fee: '{fixed_fee}',
          start_date: '{start_date}',
          end_date: '{end_date}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'projects.find',
      class: 'read',
      description: 'Find projects in a workspace.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          only_me: { type: 'boolean' },
          only_templates: { type: 'boolean' },
          page: { type: 'integer' },
          per_page: { type: 'integer' },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/projects',
        query: {
          only_me: '{only_me}',
          only_templates: '{only_templates}',
          page: '{page}',
          per_page: '{per_page}',
        },
      },
    },
    {
      name: 'tasks.create',
      class: 'mutation',
      description: 'Create a new task.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          project_id: { type: 'integer' },
          name: { type: 'string' },
          description: { type: 'string' },
          estimated_seconds: { type: 'integer' },
          user_id: { type: 'integer' },
        },
        required: ['workspace_id', 'project_id', 'name'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/tasks',
        body: {
          project_id: '{project_id}',
          name: '{name}',
          description: '{description}',
          estimated_seconds: '{estimated_seconds}',
          user_id: '{user_id}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'tasks.find',
      class: 'read',
      description: 'Find tasks in a workspace.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          project_id: { type: 'integer' },
          page: { type: 'integer' },
          per_page: { type: 'integer' },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/tasks',
        query: { project_id: '{project_id}', page: '{page}', per_page: '{per_page}' },
      },
    },
    {
      name: 'tags.create',
      class: 'mutation',
      description: 'Create a new tag.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          name: { type: 'string' },
        },
        required: ['workspace_id', 'name'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/tags',
        body: { name: '{name}' },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'tags.find',
      class: 'read',
      description: 'Find tags in a workspace.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          search_term: { type: 'string' },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/tags',
        query: { search: '{search_term}' },
      },
    },
    {
      name: 'time-entries.create',
      class: 'mutation',
      description: 'Create a new time entry.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          description: { type: 'string' },
          duration: { type: 'integer' },
          start: { type: 'string' },
          stop: { type: 'string' },
          project_id: { type: 'integer' },
          task_id: { type: 'integer' },
          billable: { type: 'boolean' },
          tag_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['workspace_id', 'start', 'duration'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/time_entries',
        body: {
          description: '{description}',
          duration: '{duration}',
          start: '{start}',
          stop: '{stop}',
          project_id: '{project_id}',
          task_id: '{task_id}',
          billable: '{billable}',
          tag_ids: '{tag_ids}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'time-entries.start',
      class: 'mutation',
      description: 'Start a new time entry.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          description: { type: 'string' },
          project_id: { type: 'integer' },
          task_id: { type: 'integer' },
          billable: { type: 'boolean' },
          tag_ids: { type: 'array', items: { type: 'integer' } },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'POST',
        path: '/workspaces/{workspace_id}/time_entries/start',
        body: {
          description: '{description}',
          project_id: '{project_id}',
          task_id: '{task_id}',
          billable: '{billable}',
          tag_ids: '{tag_ids}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'time-entries.stop',
      class: 'mutation',
      description: 'Stop a running time entry.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          time_entry_id: { type: 'integer' },
        },
        required: ['workspace_id', 'time_entry_id'],
      },
      request: {
        method: 'PUT',
        path: '/workspaces/{workspace_id}/time_entries/{time_entry_id}/stop',
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'time-entries.find',
      class: 'read',
      description: 'Find time entries in a workspace.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          before: { type: 'string' },
          since: { type: 'integer' },
          meta: { type: 'boolean' },
        },
        required: ['workspace_id'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/time_entries',
        query: { before: '{before}', since: '{since}', meta: '{meta}' },
      },
    },
    {
      name: 'user.find',
      class: 'read',
      description: 'Find a user by name or email.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          search_term: { type: 'string' },
        },
        required: ['workspace_id', 'search_term'],
      },
      request: {
        method: 'GET',
        path: '/workspaces/{workspace_id}/users',
        query: { search: '{search_term}' },
      },
    },
    {
      name: 'clients.update',
      class: 'mutation',
      description: 'Update an existing client.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          client_id: { type: 'integer' },
          name: { type: 'string' },
          external_reference: { type: 'string' },
          notes: { type: 'string' },
        },
        required: ['workspace_id', 'client_id'],
      },
      request: {
        method: 'PUT',
        path: '/workspaces/{workspace_id}/clients/{client_id}',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'clients.delete',
      class: 'mutation',
      description: 'Delete a client.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          client_id: { type: 'integer' },
        },
        required: ['workspace_id', 'client_id'],
      },
      request: {
        method: 'DELETE',
        path: '/workspaces/{workspace_id}/clients/{client_id}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'projects.update',
      class: 'mutation',
      description: 'Update an existing project.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          project_id: { type: 'integer' },
          name: { type: 'string' },
          client_id: { type: 'integer' },
          is_private: { type: 'boolean' },
          active: { type: 'boolean' },
          color: { type: 'string' },
          rate: { type: 'number' },
          fixed_fee: { type: 'number' },
          start_date: { type: 'string' },
          end_date: { type: 'string' },
        },
        required: ['workspace_id', 'project_id'],
      },
      request: {
        method: 'PUT',
        path: '/workspaces/{workspace_id}/projects/{project_id}',
        body: 'args',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'projects.delete',
      class: 'mutation',
      description: 'Delete a project.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          project_id: { type: 'integer' },
        },
        required: ['workspace_id', 'project_id'],
      },
      request: {
        method: 'DELETE',
        path: '/workspaces/{workspace_id}/projects/{project_id}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'time-entries.delete',
      class: 'mutation',
      description: 'Delete a time entry.',
      parameters: {
        type: 'object',
        properties: {
          workspace_id: { type: 'integer' },
          time_entry_id: { type: 'integer' },
        },
        required: ['workspace_id', 'time_entry_id'],
      },
      request: {
        method: 'DELETE',
        path: '/workspaces/{workspace_id}/time_entries/{time_entry_id}',
      },
      cas: 'native-idempotency',
      externalEffect: true,
    },
  ],
})
