import { declarativeRestConnector } from './declarative-rest.js'

export const totalcmsConnector = declarativeRestConnector({
  kind: 'totalcms',
  displayName: 'Total CMS',
  description: 'Content management system for modern websites',
  auth: { kind: 'api-key', hint: 'Total CMS API key.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.totalcms.com/v1',
  test: { method: 'GET', path: '/status' },
  capabilities: [
    {
      name: 'posts.get_blog_post',
      class: 'read',
      description: 'Get a blog post by slug.',
      parameters: {
        type: 'object',
        properties: { slug: { type: 'string' } },
        required: ['slug'],
      },
      request: { method: 'GET', path: '/posts/{slug}' },
    },
    {
      name: 'content.get_content',
      class: 'read',
      description: 'Get content by permalink.',
      parameters: {
        type: 'object',
        properties: { permalink: { type: 'string' } },
        required: ['permalink'],
      },
      request: { method: 'GET', path: '/content/{permalink}' },
    },
    {
      name: 'posts.save_blog_post',
      class: 'mutation',
      description: 'Create or update a blog post.',
      parameters: {
        type: 'object',
        properties: { slug: { type: 'string' }, data: { type: 'object' } },
        required: ['slug', 'data'],
      },
      request: { method: 'POST', path: '/posts/{slug}', body: '{data}' },
      cas: 'native-idempotency',
    },
    {
      name: 'content.save_content',
      class: 'mutation',
      description: 'Create or update content.',
      parameters: {
        type: 'object',
        properties: { permalink: { type: 'string' }, data: { type: 'object' } },
        required: ['permalink', 'data'],
      },
      request: { method: 'POST', path: '/content/{permalink}', body: '{data}' },
      cas: 'native-idempotency',
    },
    {
      name: 'media.save_image',
      class: 'mutation',
      description: 'Upload and save an image.',
      parameters: {
        type: 'object',
        properties: { image: { type: 'string' }, alt: { type: 'string' } },
        required: ['image', 'alt'],
      },
      request: { method: 'POST', path: '/media/images', body: { image: '{image}', alt: '{alt}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'media.save_blog_image',
      class: 'mutation',
      description: 'Upload and save a blog post image.',
      parameters: {
        type: 'object',
        properties: { image: { type: 'string' }, alt: { type: 'string' } },
        required: ['image', 'alt'],
      },
      request: { method: 'POST', path: '/media/blog/images', body: { image: '{image}', alt: '{alt}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'media.save_video',
      class: 'mutation',
      description: 'Upload and save a video.',
      parameters: {
        type: 'object',
        properties: { video: { type: 'string' }, title: { type: 'string' } },
        required: ['video'],
      },
      request: { method: 'POST', path: '/media/videos', body: { video: '{video}', title: '{title}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'media.save_gallery',
      class: 'mutation',
      description: 'Create or update a media gallery.',
      parameters: {
        type: 'object',
        properties: { name: { type: 'string' }, items: { type: 'array' } },
        required: ['name'],
      },
      request: { method: 'POST', path: '/media/galleries', body: { name: '{name}', items: '{items}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'media.save_blog_gallery',
      class: 'mutation',
      description: 'Create or update a blog post gallery.',
      parameters: {
        type: 'object',
        properties: { name: { type: 'string' }, items: { type: 'array' } },
        required: ['name'],
      },
      request: { method: 'POST', path: '/media/blog/galleries', body: { name: '{name}', items: '{items}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'data.save_file',
      class: 'mutation',
      description: 'Upload and save a file.',
      parameters: {
        type: 'object',
        properties: { filename: { type: 'string' }, file: { type: 'string' } },
        required: ['filename', 'file'],
      },
      request: { method: 'POST', path: '/data/files', body: { filename: '{filename}', file: '{file}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'data.save_text',
      class: 'mutation',
      description: 'Save text data.',
      parameters: {
        type: 'object',
        properties: { key: { type: 'string' }, value: { type: 'string' } },
        required: ['key', 'value'],
      },
      request: { method: 'POST', path: '/data/text', body: { key: '{key}', value: '{value}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'data.save_toggle',
      class: 'mutation',
      description: 'Save a toggle/boolean value.',
      parameters: {
        type: 'object',
        properties: { key: { type: 'string' }, enabled: { type: 'boolean' } },
        required: ['key', 'enabled'],
      },
      request: { method: 'POST', path: '/data/toggles', body: { key: '{key}', enabled: '{enabled}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'data.save_date',
      class: 'mutation',
      description: 'Save a date value.',
      parameters: {
        type: 'object',
        properties: { key: { type: 'string' }, date: { type: 'string' } },
        required: ['key', 'date'],
      },
      request: { method: 'POST', path: '/data/dates', body: { key: '{key}', date: '{date}' } },
      cas: 'native-idempotency',
    },
    {
      name: 'depot.save_depot',
      class: 'mutation',
      description: 'Save to depot storage.',
      parameters: {
        type: 'object',
        properties: { key: { type: 'string' }, data: { type: 'object' } },
        required: ['key', 'data'],
      },
      request: { method: 'POST', path: '/depot/{key}', body: '{data}' },
      cas: 'native-idempotency',
    },
    {
      name: 'posts.delete',
      class: 'mutation',
      description: 'Delete a blog post by slug. Re-deleting an absent slug is treated as a no-op.',
      parameters: {
        type: 'object',
        properties: { slug: { type: 'string' } },
        required: ['slug'],
      },
      request: { method: 'DELETE', path: '/posts/{slug}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'content.delete',
      class: 'mutation',
      description: 'Delete a content block by permalink. Re-deleting an absent permalink is a no-op.',
      parameters: {
        type: 'object',
        properties: { permalink: { type: 'string' } },
        required: ['permalink'],
      },
      request: { method: 'DELETE', path: '/content/{permalink}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'media.delete',
      class: 'mutation',
      description: 'Delete a media asset by id. Re-deleting an absent id is a no-op.',
      parameters: {
        type: 'object',
        properties: { id: { type: 'string' } },
        required: ['id'],
      },
      request: { method: 'DELETE', path: '/media/{id}' },
      cas: 'native-idempotency',
      externalEffect: true,
    },
    {
      name: 'media.list',
      class: 'read',
      description: 'List uploaded media assets. Optional type filter (images, videos, galleries, files).',
      parameters: {
        type: 'object',
        properties: {
          type: { type: 'string', description: 'Optional filter: images | videos | galleries | files.' },
          limit: { type: 'integer', minimum: 1, maximum: 200 },
          offset: { type: 'integer', minimum: 0 },
        },
      },
      request: {
        method: 'GET',
        path: '/media',
        query: { type: '{type}', limit: '{limit}', offset: '{offset}' },
      },
    },
  ],
})
