import { declarativeRestConnector } from './declarative-rest.js'

export const vtexConnector = declarativeRestConnector({
  kind: 'vtex',
  displayName: 'VTEX',
  description: 'Manage VTEX catalog including brands, products, SKUs, categories, clients, and orders.',
  auth: {
    kind: 'api-key',
    hint: 'VTEX App Key and App Token with Host URL.',
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'hostUrl' },
  test: { method: 'GET', path: '/api/catalog_system/pub/brand' },
  capabilities: [
    {
      name: 'brands.list',
      class: 'read',
      description: 'Get a list of all brands.',
      parameters: {
        type: 'object',
        properties: {},
        required: [],
      },
      request: { method: 'GET', path: '/api/catalog_system/pub/brand' },
    },
    {
      name: 'brands.get',
      class: 'read',
      description: 'Get a brand by ID.',
      parameters: {
        type: 'object',
        properties: { brandId: { type: 'integer', description: 'The Brand ID' } },
        required: ['brandId'],
      },
      request: { method: 'GET', path: '/api/catalog_system/pub/brand/{brandId}' },
    },
    {
      name: 'brands.create',
      class: 'mutation',
      description: 'Create a new brand.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Brand name' },
          text: { type: 'string', description: 'Brand text/description' },
          keywords: { type: 'string', description: 'Keywords for the brand' },
          active: { type: 'boolean', description: 'Is the brand active' },
          score: { type: 'integer', description: 'Score value' },
        },
        required: ['name'],
      },
      request: { method: 'POST', path: '/api/catalog_system/pub/brand', body: '{*}' },
      cas: 'native-idempotency',
    },
    {
      name: 'brands.update',
      class: 'mutation',
      description: 'Update a brand.',
      parameters: {
        type: 'object',
        properties: {
          brandId: { type: 'integer', description: 'The Brand ID' },
          name: { type: 'string', description: 'Brand name' },
          text: { type: 'string', description: 'Brand text/description' },
          keywords: { type: 'string', description: 'Keywords for the brand' },
          active: { type: 'boolean', description: 'Is the brand active' },
          score: { type: 'integer', description: 'Score value' },
        },
        required: ['brandId'],
      },
      request: { method: 'PUT', path: '/api/catalog_system/pub/brand/{brandId}', body: '{*}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'brands.delete',
      class: 'mutation',
      description: 'Delete a brand.',
      parameters: {
        type: 'object',
        properties: { brandId: { type: 'integer', description: 'The Brand ID' } },
        required: ['brandId'],
      },
      request: { method: 'DELETE', path: '/api/catalog_system/pub/brand/{brandId}' },
      cas: 'native-idempotency',
    },
    {
      name: 'products.get',
      class: 'read',
      description: 'Get a product by ID.',
      parameters: {
        type: 'object',
        properties: { productId: { type: 'integer', description: 'The Product ID' } },
        required: ['productId'],
      },
      request: { method: 'GET', path: '/api/catalog_system/pub/products/search?fq=productId:{productId}' },
    },
    {
      name: 'products.create',
      class: 'mutation',
      description: 'Create a new product.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Product name' },
          categoryId: { type: 'integer', description: 'Category ID' },
          brandId: { type: 'integer', description: 'Brand ID' },
          description: { type: 'string', description: 'Product description' },
          refId: { type: 'string', description: 'Reference ID' },
          isVisible: { type: 'boolean', description: 'Is the product visible' },
          descriptionShort: { type: 'string', description: 'Short description' },
          releaseDate: { type: 'string', description: 'Release date' },
          keyWords: { type: 'string', description: 'Keywords' },
          isActive: { type: 'boolean', description: 'Is the product active' },
          taxCode: { type: 'string', description: 'Tax code' },
          metaTagDescription: { type: 'string', description: 'Meta tag description' },
          showWithoutStock: { type: 'boolean', description: 'Show without stock' },
        },
        required: ['name', 'categoryId', 'brandId'],
      },
      request: { method: 'POST', path: '/api/catalog_system/v2.0/products', body: '{*}' },
      cas: 'native-idempotency',
    },
    {
      name: 'products.update',
      class: 'mutation',
      description: 'Update a product.',
      parameters: {
        type: 'object',
        properties: {
          productId: { type: 'integer', description: 'The Product ID' },
          name: { type: 'string', description: 'Product name' },
          categoryId: { type: 'integer', description: 'Category ID' },
          brandId: { type: 'integer', description: 'Brand ID' },
          description: { type: 'string', description: 'Product description' },
          refId: { type: 'string', description: 'Reference ID' },
          isVisible: { type: 'boolean', description: 'Is the product visible' },
          descriptionShort: { type: 'string', description: 'Short description' },
          releaseDate: { type: 'string', description: 'Release date' },
          keyWords: { type: 'string', description: 'Keywords' },
          isActive: { type: 'boolean', description: 'Is the product active' },
          taxCode: { type: 'string', description: 'Tax code' },
          metaTagDescription: { type: 'string', description: 'Meta tag description' },
          showWithoutStock: { type: 'boolean', description: 'Show without stock' },
        },
        required: ['productId'],
      },
      request: { method: 'PUT', path: '/api/catalog_system/v2.0/products/{productId}', body: '{*}' },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'categories.get',
      class: 'read',
      description: 'Get a category by ID.',
      parameters: {
        type: 'object',
        properties: { categoryId: { type: 'integer', description: 'The Category ID' } },
        required: ['categoryId'],
      },
      request: { method: 'GET', path: '/api/catalog_system/v1.0/category/{categoryId}' },
    },
    {
      name: 'skus.list',
      class: 'read',
      description: 'Get SKUs for a product.',
      parameters: {
        type: 'object',
        properties: { productId: { type: 'integer', description: 'The Product ID' } },
        required: ['productId'],
      },
      request: { method: 'GET', path: '/api/catalog_system/pub/products/search?fq=productId:{productId}' },
    },
    {
      name: 'skus.create',
      class: 'mutation',
      description: 'Create a new SKU.',
      parameters: {
        type: 'object',
        properties: {
          productId: { type: 'integer', description: 'Product ID' },
          name: { type: 'string', description: 'SKU name' },
          packaging: {
            type: 'object',
            description: 'Packaging dimensions',
            properties: {
              height: { type: 'number', description: 'Package Height' },
              length: { type: 'number', description: 'Package Length' },
              width: { type: 'number', description: 'Package Width' },
              weightKg: { type: 'number', description: 'Package Weight (Kg)' },
            },
          },
          isKit: { type: 'boolean', description: 'Is Kit' },
        },
        required: ['productId', 'name', 'packaging'],
      },
      request: { method: 'POST', path: '/api/catalog_system/v2.0/skus', body: '{*}' },
      cas: 'native-idempotency',
    },
    {
      name: 'orders.get',
      class: 'read',
      description: 'Get an order by ID.',
      parameters: {
        type: 'object',
        properties: { orderId: { type: 'integer', description: 'The Order ID' } },
        required: ['orderId'],
      },
      request: { method: 'GET', path: '/api/oms/pvt/orders/{orderId}' },
    },
    {
      name: 'orders.list',
      class: 'read',
      description: 'Get a list of orders.',
      parameters: {
        type: 'object',
        properties: {
          fromYear: { type: 'integer', description: 'From year' },
          toYear: { type: 'string', description: 'To year' },
          fromMonth: { type: 'string', description: 'From month' },
          toMonth: { type: 'string', description: 'To month' },
          fromDay: { type: 'string', description: 'From day' },
          toDay: { type: 'string', description: 'To day' },
          limit: { type: 'integer', description: 'Result limit' },
        },
        required: ['fromYear', 'toYear'],
      },
      request: {
        method: 'GET',
        path: '/api/oms/pvt/orders?from={fromYear}-{fromMonth}-{fromDay}&to={toYear}-{toMonth}-{toDay}&limit={limit}',
        query: {
          from: '{fromYear}-{fromMonth}-{fromDay}',
          to: '{toYear}-{toMonth}-{toDay}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'clients.get',
      class: 'read',
      description: 'Get a client by ID.',
      parameters: {
        type: 'object',
        properties: { clientId: { type: 'integer', description: 'The Client ID' } },
        required: ['clientId'],
      },
      request: { method: 'GET', path: '/api/crm/pub/customers/{clientId}' },
    },
    {
      name: 'clients.list',
      class: 'read',
      description: 'Get a list of clients.',
      parameters: {
        type: 'object',
        properties: { limit: { type: 'integer', description: 'Result limit' } },
        required: [],
      },
      request: { method: 'GET', path: '/api/crm/pub/customers?limit={limit}', query: { limit: '{limit}' } },
    },
  ],
})
