import { declarativeRestConnector } from './declarative-rest.js'

export const woodpeckerConnector = declarativeRestConnector({
  kind: 'woodpecker',
  displayName: 'Woodpecker',
  description: 'Manage prospects and campaigns with Woodpecker API.',
  auth: { kind: 'api-key', hint: 'Woodpecker API key from Marketplace → Integrations → API keys.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.woodpecker.co',
  test: { method: 'GET', path: '/prospect' },
  capabilities: [
    {
      name: 'prospect.find-by-email',
      class: 'read',
      description: 'Find a prospect by email address.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          campaignId: { type: 'string' },
          includeCampaignDetails: { type: 'boolean' },
        },
        required: ['email'],
      },
      request: {
        method: 'GET',
        path: '/prospect',
        query: {
          email: '{email}',
          campaignId: '{campaignId}',
          includeCampaignDetails: '{includeCampaignDetails}',
        },
      },
    },
    {
      name: 'prospect.get-responses',
      class: 'read',
      description: 'Get prospect responses.',
      parameters: {
        type: 'object',
        properties: {
          prospectId: { type: 'number' },
          campaignId: { type: 'string' },
        },
        required: ['prospectId'],
      },
      request: {
        method: 'GET',
        path: '/prospect/{prospectId}/responses',
        query: { campaignId: '{campaignId}' },
      },
    },
    {
      name: 'prospect.add-to-campaign',
      class: 'mutation',
      description: 'Add a prospect to a campaign.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          company: { type: 'string' },
          website: { type: 'string' },
          linkedinUrl: { type: 'string' },
          title: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          country: { type: 'string' },
          industry: { type: 'string' },
          tags: { type: 'string' },
          status: { type: 'string' },
          force: { type: 'boolean' },
          update: { type: 'boolean' },
          setTags: { type: 'string' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/prospect',
        body: {
          email: '{email}',
          first_name: '{firstName}',
          last_name: '{lastName}',
          company: '{company}',
          website: '{website}',
          linkedin_url: '{linkedinUrl}',
          title: '{title}',
          phone: '{phone}',
          address: '{address}',
          city: '{city}',
          state: '{state}',
          country: '{country}',
          industry: '{industry}',
          tags: '{tags}',
          status: '{status}',
          force: '{force}',
          update: '{update}',
          set_tags: '{setTags}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'prospect.add-to-list',
      class: 'mutation',
      description: 'Add a prospect to a list.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          company: { type: 'string' },
          website: { type: 'string' },
          linkedinUrl: { type: 'string' },
          title: { type: 'string' },
          phone: { type: 'string' },
          address: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          country: { type: 'string' },
          industry: { type: 'string' },
          tags: { type: 'string' },
          status: { type: 'string' },
          force: { type: 'boolean' },
          fileName: { type: 'string' },
        },
        required: ['email'],
      },
      request: {
        method: 'POST',
        path: '/prospect/list',
        body: {
          email: '{email}',
          first_name: '{firstName}',
          last_name: '{lastName}',
          company: '{company}',
          website: '{website}',
          linkedin_url: '{linkedinUrl}',
          title: '{title}',
          phone: '{phone}',
          address: '{address}',
          city: '{city}',
          state: '{state}',
          country: '{country}',
          industry: '{industry}',
          tags: '{tags}',
          status: '{status}',
          force: '{force}',
          file_name: '{fileName}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'domain.blacklist',
      class: 'mutation',
      description: 'Blacklist a domain.',
      parameters: {
        type: 'object',
        properties: {
          domain: { type: 'string' },
        },
        required: ['domain'],
      },
      request: {
        method: 'POST',
        path: '/domain/blacklist',
        body: { domain: '{domain}' },
      },
      cas: 'native-idempotency',
    },
  ],
})
