import { declarativeRestConnector } from './declarative-rest.js'

export const zendeskSellConnector = declarativeRestConnector({
  kind: 'zendesk-sell',
  displayName: 'Zendesk Sell',
  description: 'Manage CRM data with Zendesk Sell for pipeline management, lead tracking, and contact organization.',
  auth: { kind: 'api-key', hint: 'Zendesk Sell API Token.' },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: 'https://api.sellsy.com/v2',
  test: { method: 'GET', path: '/contact' },
  capabilities: [
    {
      name: 'contacts.create',
      class: 'mutation',
      description: 'Create a new contact in Zendesk Sell.',
      parameters: {
        type: 'object',
        properties: {
          isOrganization: { type: 'boolean' },
          name: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          mobile: { type: 'string' },
          address: { type: 'object' },
          customFields: { type: 'object' },
        },
        required: [],
      },
      request: {
        method: 'POST',
        path: '/contact',
        body: {
          isOrganization: '{isOrganization}',
          name: '{name}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          mobile: '{mobile}',
          address: '{address}',
          customFields: '{customFields}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'contacts.find',
      class: 'read',
      description: 'Find contacts by criteria.',
      parameters: {
        type: 'object',
        properties: {
          email: { type: 'string' },
          name: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/contact',
        query: {
          email: '{email}',
          name: '{name}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'contacts.update',
      class: 'mutation',
      description: 'Update an existing contact.',
      parameters: {
        type: 'object',
        properties: {
          contactId: { type: 'string' },
          name: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          mobile: { type: 'string' },
          address: { type: 'object' },
          customFields: { type: 'object' },
        },
        required: ['contactId'],
      },
      request: {
        method: 'PUT',
        path: '/contact/{contactId}',
        body: {
          name: '{name}',
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          mobile: '{mobile}',
          address: '{address}',
          customFields: '{customFields}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'leads.create',
      class: 'mutation',
      description: 'Create a new lead.',
      parameters: {
        type: 'object',
        properties: {
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          organizationName: { type: 'string' },
          status: { type: 'string' },
          title: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'POST',
        path: '/lead',
        body: {
          firstName: '{firstName}',
          lastName: '{lastName}',
          email: '{email}',
          phone: '{phone}',
          organizationName: '{organizationName}',
          status: '{status}',
          title: '{title}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'leads.find',
      class: 'read',
      description: 'Find leads by criteria.',
      parameters: {
        type: 'object',
        properties: {
          status: { type: 'string' },
          email: { type: 'string' },
          limit: { type: 'integer' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/lead',
        query: {
          status: '{status}',
          email: '{email}',
          limit: '{limit}',
        },
      },
    },
    {
      name: 'deals.create',
      class: 'mutation',
      description: 'Create a new deal.',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          value: { type: 'number' },
          currency: { type: 'string' },
          estimatedCloseDate: { type: 'string' },
          hot: { type: 'boolean' },
        },
        required: ['name'],
      },
      request: {
        method: 'POST',
        path: '/deal',
        body: {
          name: '{name}',
          value: '{value}',
          currency: '{currency}',
          estimatedCloseDate: '{estimatedCloseDate}',
          hot: '{hot}',
        },
      },
      cas: 'native-idempotency',
    },
    {
      name: 'deals.find',
      class: 'read',
      description: 'Find a deal by ID or name.',
      parameters: {
        type: 'object',
        properties: {
          dealId: { type: 'number' },
          dealName: { type: 'string' },
        },
        required: [],
      },
      request: {
        method: 'GET',
        path: '/deal',
        query: {
          id: '{dealId}',
          name: '{dealName}',
        },
      },
    },
    {
      name: 'deals.update',
      class: 'mutation',
      description: 'Update an existing deal.',
      parameters: {
        type: 'object',
        properties: {
          dealId: { type: 'string' },
          name: { type: 'string' },
          value: { type: 'number' },
          currency: { type: 'string' },
          estimatedCloseDate: { type: 'string' },
          hot: { type: 'boolean' },
        },
        required: ['dealId'],
      },
      request: {
        method: 'PUT',
        path: '/deal/{dealId}',
        body: {
          name: '{name}',
          value: '{value}',
          currency: '{currency}',
          estimatedCloseDate: '{estimatedCloseDate}',
          hot: '{hot}',
        },
      },
      cas: 'optimistic-read-verify',
    },
    {
      name: 'notes.create',
      class: 'mutation',
      description: 'Create a note attached to a resource.',
      parameters: {
        type: 'object',
        properties: {
          resourceType: { type: 'string' },
          resourceId: { type: 'string' },
          content: { type: 'string' },
          isImportant: { type: 'boolean' },
        },
        required: ['resourceType', 'resourceId', 'content'],
      },
      request: {
        method: 'POST',
        path: '/note',
        body: {
          resourceType: '{resourceType}',
          resourceId: '{resourceId}',
          content: '{content}',
          isImportant: '{isImportant}',
        },
      },
      cas: 'native-idempotency',
    },
  ],
})
