import { declarativeRestConnector } from './declarative-rest.js'

const orgId = {
  type: 'string',
  description: 'Zoho Desk organization id. Discover it with organizations.list.',
} as const

const data = {
  type: 'object',
  description: 'Provider-native Zoho Desk request body.',
} as const

const orgHeader = { orgId: '{orgId}' } as const

export const zohoDeskConnector = declarativeRestConnector({
  kind: 'zoho-desk',
  displayName: 'Zoho Desk',
  description: 'Discover organizations, manage support tickets, and find contacts in Zoho Desk.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
    tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
    scopes: [
      'Desk.tickets.ALL',
      'Desk.contacts.READ',
      'Desk.search.READ',
      'Desk.basic.READ',
    ],
    scopeSeparator: ',',
    clientIdEnv: 'ZOHO_OAUTH_CLIENT_ID',
    clientSecretEnv: 'ZOHO_OAUTH_CLIENT_SECRET',
    extraAuthParams: { access_type: 'offline', prompt: 'consent' },
  },
  category: 'crm',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'deskApiDomain', fallback: 'https://desk.zoho.com' },
  allowedBaseUrls: [
    'https://desk.zoho.com',
    'https://desk.zoho.eu',
    'https://desk.zoho.in',
    'https://desk.zoho.com.au',
    'https://desk.zoho.jp',
    'https://desk.zohocloud.ca',
    'https://desk.zoho.com.cn',
  ],
  credentialPlacement: { kind: 'header', header: 'Authorization', prefix: 'Zoho-oauthtoken ' },
  test: { method: 'GET', path: '/api/v1/organizations' },
  capabilities: [
    {
      name: 'organizations.list',
      class: 'read',
      description: 'List Zoho Desk organizations available to the connected user.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/api/v1/organizations' },
      requiredScopes: ['Desk.basic.READ'],
    },
    {
      name: 'tickets.list',
      class: 'read',
      description: 'List tickets within one Zoho Desk organization.',
      parameters: {
        type: 'object',
        properties: {
          orgId,
          include: { type: 'string', description: 'Comma-separated related objects to include.' },
          from: { type: 'integer', minimum: 0 },
          limit: { type: 'integer', minimum: 1, maximum: 100 },
          status: { type: 'string' },
          departmentId: { type: 'string' },
        },
        required: ['orgId'],
      },
      request: {
        method: 'GET',
        path: '/api/v1/tickets',
        headers: orgHeader,
        query: {
          include: '{include}',
          from: '{from}',
          limit: '{limit}',
          status: '{status}',
          departmentId: '{departmentId}',
        },
      },
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.get',
      class: 'read',
      description: 'Read one ticket by id.',
      parameters: {
        type: 'object',
        properties: { orgId, ticketId: { type: 'string' } },
        required: ['orgId', 'ticketId'],
      },
      request: { method: 'GET', path: '/api/v1/tickets/{ticketId}', headers: orgHeader },
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.create',
      class: 'mutation',
      description: 'Create a ticket in one Zoho Desk organization.',
      parameters: {
        type: 'object',
        properties: { orgId, data },
        required: ['orgId', 'data'],
      },
      request: { method: 'POST', path: '/api/v1/tickets', headers: orgHeader, body: '{data}' },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.update',
      class: 'mutation',
      description: 'Update an existing ticket.',
      parameters: {
        type: 'object',
        properties: { orgId, ticketId: { type: 'string' }, data },
        required: ['orgId', 'ticketId', 'data'],
      },
      request: { method: 'PATCH', path: '/api/v1/tickets/{ticketId}', headers: orgHeader, body: '{data}' },
      cas: 'optimistic-read-verify',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.close',
      class: 'mutation',
      description: 'Close a ticket.',
      parameters: {
        type: 'object',
        properties: { orgId, ticketId: { type: 'string' } },
        required: ['orgId', 'ticketId'],
      },
      request: {
        method: 'PATCH',
        path: '/api/v1/tickets/{ticketId}',
        headers: orgHeader,
        body: { status: 'Closed' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.assign',
      class: 'mutation',
      description: 'Assign a ticket to an agent.',
      parameters: {
        type: 'object',
        properties: { orgId, ticketId: { type: 'string' }, assigneeId: { type: 'string' } },
        required: ['orgId', 'ticketId', 'assigneeId'],
      },
      request: {
        method: 'PATCH',
        path: '/api/v1/tickets/{ticketId}',
        headers: orgHeader,
        body: { assigneeId: '{assigneeId}' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.add-comment',
      class: 'mutation',
      description: 'Add a public or internal comment to a ticket.',
      parameters: {
        type: 'object',
        properties: {
          orgId,
          ticketId: { type: 'string' },
          content: { type: 'string' },
          isPublic: { type: 'boolean' },
          contentType: { type: 'string', enum: ['html', 'plainText'] },
        },
        required: ['orgId', 'ticketId', 'content', 'isPublic'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/tickets/{ticketId}/comments',
        headers: orgHeader,
        body: {
          content: '{content}',
          isPublic: '{isPublic}',
          contentType: '{contentType}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'tickets.merge',
      class: 'mutation',
      description: 'Merge duplicate tickets into a primary ticket.',
      parameters: {
        type: 'object',
        properties: {
          orgId,
          ticketId: { type: 'string', description: 'Primary ticket id.' },
          ids: { type: 'array', items: { type: 'string' }, minItems: 1 },
        },
        required: ['orgId', 'ticketId', 'ids'],
      },
      request: {
        method: 'POST',
        path: '/api/v1/tickets/{ticketId}/mergeTickets',
        headers: orgHeader,
        body: { ids: '{ids}' },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['Desk.tickets.ALL'],
    },
    {
      name: 'contacts.find',
      class: 'read',
      description: 'Find contacts by exact email address.',
      parameters: {
        type: 'object',
        properties: { orgId, email: { type: 'string' } },
        required: ['orgId', 'email'],
      },
      request: {
        method: 'GET',
        path: '/api/v1/contacts/search',
        headers: orgHeader,
        query: { email: '{email}' },
      },
      requiredScopes: ['Desk.contacts.READ', 'Desk.search.READ'],
    },
  ],
})
