import { declarativeRestConnector } from './declarative-rest.js'

const accountId = { type: 'string', description: 'Zoho Mail account id.' } as const
const messageId = { type: 'string', description: 'Zoho Mail message id.' } as const

export const zohoMailConnector = declarativeRestConnector({
  kind: 'zoho-mail',
  displayName: 'Zoho Mail',
  description: 'Read, organize, and send mail through Zoho Mail.',
  auth: {
    kind: 'oauth2',
    authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
    tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
    scopes: [
      'ZohoMail.accounts.READ',
      'ZohoMail.messages.ALL',
      'ZohoMail.folders.ALL',
      'ZohoMail.organization.accounts.READ',
    ],
    scopeSeparator: ',',
    clientIdEnv: 'ZOHO_OAUTH_CLIENT_ID',
    clientSecretEnv: 'ZOHO_OAUTH_CLIENT_SECRET',
    extraAuthParams: { access_type: 'offline', prompt: 'consent' },
  },
  category: 'comms',
  defaultConsistencyModel: 'authoritative',
  baseUrl: { metadataKey: 'mailApiDomain', fallback: 'https://mail.zoho.com' },
  allowedBaseUrls: [
    'https://mail.zoho.com',
    'https://mail.zoho.eu',
    'https://mail.zoho.in',
    'https://mail.zoho.com.au',
    'https://mail.zoho.jp',
    'https://mail.zohocloud.ca',
    'https://mail.zoho.com.cn',
  ],
  credentialPlacement: { kind: 'header', header: 'Authorization', prefix: 'Zoho-oauthtoken ' },
  test: { method: 'GET', path: '/api/accounts' },
  capabilities: [
    {
      name: 'accounts.list',
      class: 'read',
      description: 'List Zoho Mail accounts available to the connected user.',
      parameters: { type: 'object', properties: {} },
      request: { method: 'GET', path: '/api/accounts' },
      requiredScopes: ['ZohoMail.accounts.READ'],
    },
    {
      name: 'folders.list',
      class: 'read',
      description: 'List folders for one Zoho Mail account.',
      parameters: {
        type: 'object',
        properties: { accountId },
        required: ['accountId'],
      },
      request: { method: 'GET', path: '/api/accounts/{accountId}/folders' },
      requiredScopes: ['ZohoMail.folders.ALL'],
    },
    {
      name: 'messages.list',
      class: 'read',
      description: 'List messages for a folder with offset pagination.',
      parameters: {
        type: 'object',
        properties: {
          accountId,
          folderId: { type: 'string' },
          start: { type: 'integer', minimum: 0 },
          limit: { type: 'integer', minimum: 1, maximum: 200 },
        },
        required: ['accountId'],
      },
      request: {
        method: 'GET',
        path: '/api/accounts/{accountId}/messages/view',
        query: { folderId: '{folderId}', start: '{start}', limit: '{limit}' },
      },
      requiredScopes: ['ZohoMail.messages.ALL'],
    },
    {
      name: 'messages.get-original',
      class: 'read',
      description: 'Fetch the original RFC 822 content for a message.',
      parameters: {
        type: 'object',
        properties: { accountId, messageId },
        required: ['accountId', 'messageId'],
      },
      request: { method: 'GET', path: '/api/accounts/{accountId}/messages/{messageId}/originalmessage' },
      requiredScopes: ['ZohoMail.messages.ALL'],
    },
    ...[
      ['messages.mark-read', 'markAsRead'] as const,
      ['messages.mark-unread', 'markAsUnread'] as const,
      ['messages.archive', 'archiveMails'] as const,
      ['messages.unarchive', 'unArchiveMails'] as const,
    ].map(([name, mode]) => ({
      name,
      class: 'mutation' as const,
      description: `${name.split('.')[1]} one Zoho Mail message.`,
      parameters: {
        type: 'object',
        properties: { accountId, messageId },
        required: ['accountId', 'messageId'],
      },
      request: {
        method: 'PUT' as const,
        path: '/api/accounts/{accountId}/updatemessage',
        body: { mode, messageId: ['{messageId}'] },
      },
      cas: 'native-idempotency' as const,
      requiredScopes: ['ZohoMail.messages.ALL'],
    })),
    {
      name: 'messages.move',
      class: 'mutation',
      description: 'Move one message to another folder.',
      parameters: {
        type: 'object',
        properties: {
          accountId,
          messageId,
          folderId: { type: 'string', description: 'Current folder id.' },
          destinationFolderId: { type: 'string', description: 'Destination folder id.' },
        },
        required: ['accountId', 'messageId', 'folderId', 'destinationFolderId'],
      },
      request: {
        method: 'PUT',
        path: '/api/accounts/{accountId}/updatemessage',
        body: {
          mode: 'moveMessage',
          destfolderId: '{destinationFolderId}',
          messageId: ['{messageId}'],
          isFolderSpecific: true,
          folderId: '{folderId}',
        },
      },
      cas: 'native-idempotency',
      requiredScopes: ['ZohoMail.messages.ALL'],
    },
    {
      name: 'messages.send',
      class: 'mutation',
      description: 'Send a new Zoho Mail message.',
      parameters: {
        type: 'object',
        properties: {
          accountId,
          fromAddress: { type: 'string' },
          toAddress: { type: 'string' },
          ccAddress: { type: 'string' },
          bccAddress: { type: 'string' },
          subject: { type: 'string' },
          content: { type: 'string' },
          mailFormat: { type: 'string', enum: ['html', 'plaintext'] },
          askReceipt: { type: 'string', enum: ['yes', 'no'] },
        },
        required: ['accountId', 'fromAddress', 'toAddress', 'subject', 'content'],
      },
      request: {
        method: 'POST',
        path: '/api/accounts/{accountId}/messages',
        body: {
          fromAddress: '{fromAddress}',
          toAddress: '{toAddress}',
          ccAddress: '{ccAddress}',
          bccAddress: '{bccAddress}',
          subject: '{subject}',
          content: '{content}',
          mailFormat: '{mailFormat}',
          askReceipt: '{askReceipt}',
        },
      },
      cas: 'native-idempotency',
      externalEffect: true,
      requiredScopes: ['ZohoMail.messages.ALL'],
    },
  ],
})
